- cli/tests/services.bats
- flake.lock
- flake.nix
Bump process-compose from version 1.6.1 to 1.9.0
Contrary to appearances, 1.9.0 is the release immediately after 1.6.1
1.9.0 contains a fix for a race condition we've encountered.
> chore: bump process-compose

- cli/flox-rust-sdk/src/providers/services.rs
Current code assumes that once process-compose closes stdout, it will have exited. When this is not the case, we kill process-compose rather than reporting any error process-compose has printed to stderr.
It is possible that stdout gets closed before process-compose exits. So kill process-compose just to be sure it's exiting, and then use wait instead of try_wait. After waiting, we can always report any error printed to stderr.
> fix: race between closing stdout and exit

- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/commands/upgrade.rs
- cli/tests/environment-remote.bats
Currently a `ConcreteEnvironment` is created with a `Flox` object that may not specify auth credential to Floxhub.
While detect a missing or expired token and update the `floxhub_token` field in `Flox`, this happens after the instantiation of the `ConcreteEnvironment`, which remains configured with the old/absent token. The result was that flox commands would prompt for login but fail to finish anyway. Any subsequent run would instantiate the environment with the now correct token.
```
$ flox rm -r limeytexan/default nodejs
You are not logged in to FloxHub. Logging in...
Go to https://auth.flox.dev/activate?user_code=ZSDT-GNMF in your browser
Your one-time activation code is: ZSDT-GNMF
✅ Authentication complete
✅ Logged in as limeytexan
❌ ERROR: Access denied to the remote environment. …
```
> fix: check if user is logged in before instantiating environment

- assets/activation-scripts/activate
- pkgs/flox-activation-scripts/default.nix
Avoid process-compose accidentally handling signals sent in the shell,
such as terminating upon `^C`.
Using the `setsid` from the `util-linux` package, which contrary to its name
does provide several utilities on macos as well, including the setsid binary.
> fix: detach `process-compose` from activation using `setsid`

- cli/tests/services.bats
We currently close fd3 and kill any sleep processes left behind by process-compose in the test
`blocking: error message when startup times out`
Since bumping to process-compose 1.9, this appears to no longer be necessary.
With 1.6.1, the following would fail within a few runs on aarch64-linux. With 1.9, I've run it through all 10k runs.
```
i=0; while ! ps | grep sleep && [ $i -le 10000 ]; do process-compose up --config service-config.yaml --unix-socket /no-perms; (( i++ )); done; echo "$i"
```
(sidenote for the diligent reader of git log: the pgrep_sleep invocation had a bug anyways because it didn't sort by PID, so comm wouldn't work correctly)
> test: drop workaround for process-compose bug

- cli/tests/test_support.bash
Klaus runs asynchronously, which means that if the last command a test
runs is `flox activate`, there is a chance it will move on to teardown
before klaus has finished its work. Specifically, klaus might try to
read and then write the env-registry.json file in the data dir, which
can fail in at least two ways:
1) Klaus itself might fail because that file has been deleted
2) The deletion of the data dir might fail because klaus has recreated
the file after it was deleted, before the directory was removed
We now provide a standard teardown step that waits for any klaus
processes associated with this test run to exit. Associated processes
are identified by the presence of the test-specific data dir in their
command line, as klaus is invoked with a reference to the env-registry
file in the …
> fix: Wait for klaus processes to finish between tests

- cli/tests/test_support.bash
Use `ps` and `grep` separately rather than relying on `pgrep`
N/A
> fix: pgrep not in devshell on macOS

- cli/Cargo.toml
- cli/catalog-api-v1/Cargo.toml
- cli/catalog-api-v1/build.rs
- cli/flox/Cargo.toml
- flake.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-klaus/default.nix
- pkgs/flox-src/default.nix
- pkgs/flox/default.nix
- pkgs/rust-external-deps/default.nix
- pkgs/rust-internal-deps/default.nix
- shells/default/default.nix
This PR splits up the `flox-cli`/`rust-pkg` nix expression into **6** individual expressions, that aim to improve incrementality and factorisation of build steps.
- **`rust-external-deps`** is essentially the `cargoDepsArtifacts` value split into its own separate package and provides all crates from the `Cargo.toml` pulled in by our rust workspace.
- **`rust-internal-deps`** provides the dependencies of our binary crates `flox` and `klaus`, i.e. `flox-rust-sdk` and `catalog-api-v1`.
Note the following commentary:
https://github.com/flox/flox/blob/ec6ae903654981ac612d45ae5e2f073bc56c1b31/pkgs/rust-internal-deps/default.nix#L48-L59
This package also defines (and `passthru`s) all env variables to build `flox-rust-sdk`, including referencing `pkgdb` through `PKGDB_BIN`.
The internal deps are …
> build: separate incremental builds of rust binaries

- pkgs/flox-cli/default.nix
- pkgs/flox/default.nix
Expose the original package set in passthru. Used to help make installers without messing around with overlays.
N/A
> fix: re-add pkgsFor to allow extracting the full package set used

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/status.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
**feat(services): impl Display for ProcessStates**
Using the output format described in:
- https://www.notion.so/floxdev/Services-status-output-53ee184e2b5b4b7d8d565041b5b555bf
I've resisted bringing in a third-party table library for the moment
because they all seem to have massive feature sets or quirks:
- https://github.com/BurntSushi/tabwriter
- https://github.com/phsym/prettytable-rs
- https://github.com/zhiburt/tabled
Some notes about the current implementation:
- NAME column is padded to 20 chars and will no longer align if it
overflow but it will still be space delimited
- NAME is already sorted for us and the test uses header/footer entries
to prevent any future regressions.
- PID column is right align to account variable length values
This was quick and easy to unit test with …
> feat(commands): Add flox services status

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/pull.rs
- cli/tests/activate.bats
- cli/tests/install.bats
- cli/tests/list.bats
- cli/tests/upgrade.bats
We use both content and contents throughout the codebase to refer to
what's contained in the manifest. Use contents throughout as it's
consistent with file contents, which sounds more natural to most people.
Change:
manifest_content -> manifest_contents
MANIFEST_CONTENTS -> MANIFEST_CONTENT
> refactor: grammar - use contents instead of content

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/status.rs
- cli/tests/services.bats
**refactor(services): ProcessStateDisplay SDK->CLI**
Move it to the command as it's concerned with user facing display. We
have to make `ProcessState` public as a result. Added some `IntoIter`
and `From` to make `ProcessStates` easier to use from the outside.
**test(services): ProcessStateDisplay as JSON lines**
Add a test that will double check whether we expose more from the struct
than we intend to. This duplicates the iteration and `json::to_string`
in the command but it seems simple enough not to worry or warrant making
it a method on the struct right now.
**feat(commands): Indicate running PID in status out**
Wrap the PID in square brackets if the process is no longer running, to
make it clear that you'll no longer be able to see the process but the
value may still be useful for …
> feat(commands): Indicate running PID in status out

- assets/activation-scripts/etc/profile.d/0800_cuda.sh
I noticed some double slashes in the `flox activate -v` output:
++ activate_cuda /
++ local fhs_root_prefix=/
++ [[ 1 != 1 ]]
++ /nix/store/zr6klxfjzpdr2674ly1f4fix7ig57mjr-findutils-4.9.0/bin/find //dev -maxdepth 1 -iname 'nvidia*' -o -iname dxg
Fix it by not attempting to combine it with unset substitution. We always pass a value, so we don't actually need it. Examples of the behaviour before and after:
(2) ~
% activate_cuda() {
echo "arg: $1"
echo "before: ${1%/:-}/dev/nvidia"
echo "after: ${1%/}/dev/nvidia"
}
(2) ~
% activate_cuda
arg:
before: /dev/nvidia
after: /dev/nvidia
(2) ~
% activate_cuda "/"
arg: /
before: //dev/nvidia
after: /dev/nvidia
(2) ~
% activate_cuda "/foo/bar"
arg: /foo/bar
before: /foo/bar/dev/nvidia
after: /foo/bar/dev/nvidia
(2) ~
% activate_cuda "/foo/bar/"
arg: …
> fix(cuda): Strip fhs_root_prefix slash correctly

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/utils/message.rs
- cli/tests/services.bats
* implement common process name selection in cli based on `ProcessStates` to use by all process subcommands
* update messaging for `stop` command
+ fail if any named process does not exist
+ stop processes individually
+ warn if a process is not running -- do not attempt to stop
* add test for parsing process states from a running process-compose instance
> refactor: update process selection errors and `stop` messages

- cli/flox/src/commands/activate.rs
- cli/tests/cuda.bats
The test for "libcuda present but manifest opts-out" was failing for me locally. I wasn't using a Flox environment as my default shell when I originally wrote the test. Now that I am, the environment variable gets inherited by the test from my default shell and doesn't get reset when a nested activation opts-out. Fix this by always setting the value based on the manifest of the target activation.
Honour `options.cuda-detection = false` for nested activations.
> fix(cuda): Adjust behaviour for nested opt-out

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/mod.rs
Fix unnecessary indentation and lack of headers in `flox activate --help` by using a bpaf `header()`
Before
```
Enter the environment, type 'exit' to leave
Usage: flox activate [-d=<path> | -r=<owner>/<name>] [-t] -- [<cmd>]...
When called with no arguments 'flox activate' will look for a '.flox' directory
in the current directory. Calling 'flox activate' in your home directory will
activate a default environment. Environments in other directories and remote
environments are activated with the '-d' and '-r' flags respectively.
-d, --dir=<path>  Path containing a .flox/ directory
-r, --remote=<owner>/<name>  A remote environment on FloxHub
-t, --trust       Trust a remote environment temporarily for this activation
<cmd>             Command to run interactively in the context of the …
```
> fix: activate --help formatting

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/tests/activate.bats
- cli/tests/containerize.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/lang-node.bats
- cli/tests/lang-python.bats
- cli/tests/ld-floxlib.bats
- cli/tests/list.bats
- cli/tests/pull.bats
- cli/tests/upgrade.bats
- test_data/manually_generated/hello_and_htop_for_no_system_v0/manifest.lock
- test_data/manually_generated/hello_and_htop_for_no_system_v0/manifest.toml
- test_data/manually_generated/hello_as_greeting_v0/manifest.lock
- test_data/manually_generated/hello_as_greeting_v0/manifest.toml
- test_data/manually_generated/hello_for_activate_v0/manifest.lock
- test_data/manually_generated/hello_for_activate_v0/manifest.toml
- test_data/manually_generated/hello_for_catalog_v0/manifest.lock
- test_data/manually_generated/hello_for_catalog_v0/manifest.toml
- test_data/manually_generated/hello_for_containerize_v0/manifest.lock
- test_data/manually_generated/hello_for_containerize_v0/manifest.toml
- test_data/manually_generated/hello_v0/manifest.lock
- test_data/manually_generated/hello_v0/manifest.toml
- test_data/manually_generated/influxdb2_v0/manifest.lock
- test_data/manually_generated/influxdb2_v0/manifest.toml
- test_data/manually_generated/ld_floxlib_test_deps_v0/manifest.lock
- test_data/manually_generated/ld_floxlib_test_deps_v0/manifest.toml
- test_data/manually_generated/python_v0/manifest.lock
- test_data/manually_generated/python_v0/manifest.toml
* Convert bats tests that were previously depending on `FLOX_FEATURES_USE_CATALOG=false` in their setup to using prepared/bundled manifests and locks.
* Convert bats tests to use catalog based v1 environments that were depending on `FLOX_FEATURES_USE_CATALOG=false` but test behaviour unrelated to the kind of environment where there was no catalog variant yet.
* Delete bats tests that were depending on `FLOX_FEATURES_USE_CATALOG=false` but test behaviour unrelated to the kind of environment.
* Delete bats tests that were depending on `FLOX_FEATURES_USE_CATALOG=false` and testing deprecated functionality (e.g. `edit` and `upgrade`)
* change the behaviour of `push_new` to conditionally lock.
> test: remove/port tests that lock with pkgdb

- assets/activation-scripts/activate
- cli/flox/src/commands/activate.rs
- pkgs/flox-activation-scripts/default.nix
When `flox services start name` is implemented, when `process-compose` is not running, we will need to call `process-compose up name` in order to start an instance of `process-compose` without starting more services than just `name`. In this case, we'll additionally want to skip starting the watchdog, because the activation `flox services start` is running inside will already have a watchdog.
To support this, split the bulk of `Activate::handle` out into an `Activate::activate` function that accepts additional arguments:
- `start_watchdog`: this will allow start and restart to skip starting a watchdog for ephemeral activations
- `services_to_start`: `flox services start` may be called with a list of service names, and these must be passed to the activation script
Pass `services_to_start` …
> feat: activation script changes needed for start

- cli/flox/src/utils/metrics.rs
This works for bounding the reqwest getaddrinfo call to the desired timeout
@ysndr suggested this in https://github.com/flox/flox/pull/1769#issuecomment-2260675622
issue: #1766
> fix: wrap metrics blocking reqwest in thread with timeout

- cli/tests/services.bats
This is failing for me locally. It's fixed by specifying the SHELL for the activation, because I use `zsh` which doesn't support exporting functions.
However I'm a bit perplexed about why it's using `zsh` at all. I thought that BATS, and the way that we've configured the test setup, isolated us from this.
✗ watchdog: lives as long as the activation [271]
tags: services
(from function `assert_success' in file /nix/store/dhghqmkjk7fqpdbz71clvbh5zxp6p3lf-bats-with-libraries-1.10.0/share/bats/bats-assert/src/assert_success.bash, line 42,
in test file services.bats, line 507)
`assert_success' failed
✨ Created environment 'test' (aarch64-darwin)
Next:
$ flox search <package>    <- Search for a package
$ flox install <package>   <- Install a package into an environment
$ flox activate …
> test(services): Set SHELL for watchdog test

- cli/tests/services.bats
The retained test is a superset of the deleted test because it ensures that no services are stopped when the invalid name is given _after_ valid names.
If we test this then we already know that it works the other way round and it wasn't easy to tell the tell the difference between the intent of the two tests at a glance. So we can save ourselves a bit of runtime.
N/A
> test(services): Remove dupe test

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/start.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/utils/message.rs
- cli/tests/services.bats
- cli/tests/services/start_does_not_pick_up_modifications.sh
- cli/tests/services/start_picks_up_modifications.sh
- cli/tests/services/start_shuts_down_process_compose.sh
Add `flox services start` subcommand.
- Check if the specified environment is active. Error if not
- If no process-compose is running or all processes are stopped, start the specified services with Activate::activate which is roughly equivalent to `flox activate -s -- true`. Differences are not starting a watchdog and forking rather than execing.
- If process-compose is running, use the existing process-compose to start the specified services. Warn if any processes are already running. Error if any services fail to start, but only after attempting to start all processes.
For testing:
All of the tests for creating a new process compose were added using
bats. This was because `services-start`:
- relies on the watchdog started by activate to cleanup
- relies on the state of an already …
> feat: services start

- pkgs/flox-cli/default.nix
- pkgs/flox-klaus/default.nix
- pkgs/rust-internal-deps/default.nix
Use `propagatedBuildInputs` to ensure all referenced packages are available in the closure. In the past we had issues with rust optimizing away some constants referencing 3rd party crates causing runtime failures.
See: <https://github.com/flox/flox/issues/1820>
> fix: define references to 3rd party packages

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/tests/services.bats
**feat(services): Prevent restart outside activation**
We don't support this for `start` or `restart` because it may start a
new `process-compose` instance which needs to be shutdown by the
watchdog of an existing activation.
**refactor(services): Move start_with_new_p_c**
Move the function and move the printing of names to the caller so that
the same functionality can be used by `start` and `restart`.
**feat(services): Allow restart to load new configs**
Stop the existing and start a new `process-compose` when:
- there are no services currently running
- all services are going to be restarted
This allows two behaviours:
- restarting in an activation that didn't previously start services
- reloading the services config when changes are made to the manifest
**fix(services): Allow status …
> feat(services): Allow restart to load new configs

- cli/flox/src/commands/edit.rs
Do we need to do something when the user tries to use single or double quotes?
@ysndr suggested using shlex.
If so -- that can be added in another commit
(kubectl handles this case by just looking for quotes and passing an escaped string to whatever the SHELL is)
I considered splitting the path search logic into a different function, so I could test it separately.
Do we think that would be better?
Fallback behavior is slightly weird/non-uniform when VISUAL is whitespace only -- do we care? If so, it will just require an additional whitespace parser for that case.
#1744 #1746
`VISUAL` and `EDITOR` now support passing editor arguments split on whitespace
> Improve VISUAL and EDITOR arg splitting and fallback

- assets/activation-scripts/activate
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/start.rs
- pkgs/rust-internal-deps/default.nix
To prevent `process-compose` from exiting when all services are stopped,
we run a dummy service that sleeps indefinitely.
However, not all systems have a `sleep` command that supports `sleep infinity`,
so we use a nix provided `sleep` binary instead.
> fix: use nix provided sleep command

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
A handful of improvements to error messaging for `flox services start` and `flox services restart` that came out of https://github.com/flox/flox/pull/1923#discussion_r1713945833
This is best reviewed commit-by-commit.
N/A until services release.
> feat(services): Improve error messaging for start and restart

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/logs.rs
- cli/tests/services.bats
- cli/tests/services/logging_services.toml
Empirically, process-compose will
* log the last _up to_ `<n>` lines logged by a process
* exit with `0` exit code
* not wait for more logs of running processes, even if they logged less than `<n>` lines yet
* print a particular error message to `stderr`:
```
$ process-compose process logs -u test.sock -n 2 foo 2>/dev/null
2
3
write close: write unix ->test.sock: write: broken pipe
```
Currently we use this as another cue that the reading completed,
however we cannot know whether this was printed by process compose or a running service.
A PR to banish these logs to stderr was opened upstream at
<https://github.com/F1bonacc1/process-compose/pull/216>
This adds a new `ProcessComposeLogTail` that calls `process-compose process logs` with `--tail`
and directly reads its output, storing all …
> feat: oneshot logs/tail for flox services

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/edit.rs
- cli/tests/services.bats
- test_data/config.toml
- test_data/generated/resolve/overmind.json
By default `process-compose` shuts down services by sending the service a signal (SIGTERM by default). If a service spawns a background process then the process that `process-compose` delivers the signal to may not be the process that we need to stop. Other service managers, like supervisord, get around this by having some kind of proxy process that forwards signals to the background process. `process-compose` lets you specify a shutdown command instead.
This change adds `is-daemon` and `shutdown.command` fields to a service descriptor so that a user can properly configure a service that will background itself or another process (`pg_ctl`, etc). When a user lists an `is-daemon` service, they also need to provide a `shutdown.command`, otherwise we have no way of shutting the process down. …
> feat: support services that spawn daemons

- cli/flox/src/commands/services/restart.rs
- cli/tests/services.bats
- cli/tests/services/wait_for_service_status.sh
Improvement suggested in https://github.com/flox/flox/pull/1923#discussion_r1714382987
Indicate whether `flox services restart` did a start or restart based on whether the service was running previously.
This removes an unnecessary `ProcessStates::read` when we're using an existing `process-compose` instance.
I considered checking the names against a HashSet of running processes so that `ProcessStates.process()` doesn't have to filter by name each time but passing it around made it harder to read so I've contained it all in one private function.
N/A until services release.
> feat(services): Indicate whether restart or start

- .github/workflows/ci.yml
- shells/default/default.nix
**ci: Limit integ-tests step to 30mins**
This step takes <10 mins in normal execution but sometimes hangs
indefinitely. Setting a stricter timeout on the step, but leaving the
more relaxed timeout on the job, will give us faster feedback whilst
also allowing us to capture information in an additional
step (subsequent commit).
**ci: Run pstree when Runner integ-tests fail**
To help us figure out what's still running when the integration tests
hang. I'm only doing this on the Runner jobs, not the Nix remote builder
jobs, because it will be hard to tell on those shared instance which
processes belong to this CI run.
There's an example of this working here:
- https://github.com/flox/flox/actions/runs/10388611281/job/28764639190#step:8:1
N/A
> ci: Limit and debug failing integ-tests

- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/klaus/src/main.rs
For a short-lived activation, e.g. `flox activate -s -- true`, the
parent of the watchdog may exit quickly. Currently we error when we
detect that case, but that means we may leave behind a running
process-compose. Instead, perform cleanup.
> fix: cleanup when parent exits before watchdog

- assets/activation-scripts/activate
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
- cli/tests/services/start_picks_up_modifications.sh
When `services start` and `services restart` restart `process-compose`,
they need to do so in an up-to-date activation. To support this, they
have to run the activate script. Currently the activate script skips
running hooks and setting vars if it has already been run.
Add a `_FLOX_ACTIVATE_FORCE_REACTIVATE` variable and use it to control
whether the hooks should be re-run and vars set.
This has some limitations:
- Hooks that aren't idempotent might have unexpected behavior
- Variables aren't yet unset, so if a variable is removed from an
environment, it won't be unset
We'll address those issues later on.
Add a note to the man page saying hooks should be able to be run
multiple times non-interactively.
> fix: re-run activation for start and restart

- cli/flox/src/commands/edit.rs
`buildenv` will fail with status 122 when realising an environment which contains multiple packages that provide the same file.
A package can specify a `priority` to be used instead of the other to resolve the conflict.
In interactive edits, build failures of any kind were treated as unrecoverable. However since conflict can be recovered we are returning that error as recoverable.
Thus now installing e.g. `vim` and `vim-full` to an environment with `flox edit`:
```
version = 1
[install]
vim.pkg-path = "vim"
vim-full.pkg-path = "vim-full"
```
Will prompt to continue editing:
```
❌ ERROR: 'vim' conflicts with 'vim-full'. Both packages provide the file '/bin/rview'
Resolve by uninstalling one of the conflicting packages or setting the priority of the preferred package to a value lower than …
```
> fix: recover from build errors due to conflicting packages

- assets/activation-scripts/activate
- cli/tests/services.bats
- fix: print process-compose logs on start failure
Currently we print the path to the logfile, but since `process-compose`
has failed to start, the logfile should be relatively short.
It will help us in debugging failures to just print the log.
- fix: services logs test timing out
The test `logs: follow shows logs for all services if no names provided`
currently has a timeout of .5 seconds. We've seen that fail in CI:
https://github.com/flox/flox/actions/runs/10390132193/job/28770507812?pr=1920#step:6:480
There's likely an underlying issue, but for now, increase the timeout to
1 second. While doing so, restructure the test to background the logs
command with redirection to a file, and poll for the logs we want to
appear. That way, faster runs of the test won't wait for the full
timeout to …
> Some work on flakey tests

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/services/start.rs
- cli/tests/services.bats
When `activate -s` is called, if process-compose is running and all services are stopped, call `process-compose down` and then start `process-compose` again as part of activation.
This is consistent with how `start` and `restart` handle when to restart `process-compose`, and it allows re-starting `process-compose` in the context of an updated environment.
The logic for starting `process-compose` in activate was refactored with a few behavioral changes:
- We always error for remote environments if `--start-services` is passed. That makes it more clear services aren't ever started for remote environments.
- _FLOX_SERVICES_TO_START is only set when services should actually be started. Previously, it was dependent on the socket being present. Since it is only needed when services are actually …
> fix: stop process-compose in activate

- cli/tests/services.bats
Remove the stricter assertions that were added in 130ad75e because we appear to sometimes race `process-compose` creating the log file on our x86-64_linux instance:
- https://github.com/flox/flox/actions/runs/10451722456/job/28938781344#step:6:403
- https://github.com/flox/flox/actions/runs/10451722456/job/28938781344#step:6:403
We already have a separate test for reading the log file from the correct location.
N/A
> test(services): Flakey test process-compose log

- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/commands/upgrade.rs
- cli/tests/edit.bats
- cli/tests/install.bats
- cli/tests/services.bats
- cli/tests/upgrade.bats
Warn the user, if they have services running for an environment, that
they will likely need to restart the services in order to pick up
manifest changes to that environment.
We originally planned to not warn about changes to the `profile` section
because those changes would only affect interactive activations. But
I've opted for a simplification for now where we treat all changes as
affecting because it would have required fragmenting the logic in
`EditResult`.
The behaviour of `install` is harder to reason about than the others.
You could have a service that depends on a binary that either isn't
available or accidentally comes from your host system which you then
want to come from the environment.
I've opted for integration tests because they were the easiest to setup
and reason about. …
> feat(services): Warn on most manifest changes

- cli/tests/services/logging_services.toml
It currently appears process-compose has a race in which it doesn't always collect log output emitted right before a service exits. A reproducer is included below. When running on an x86_64-linux machine under resource load, the log line containing `2` is dropped at least once every 20 runs.
If a `sleep .1` is added after the `echo 2`, I haven't seen the log line dropped in 200 runs.
Add the same workaround for our tests.
```
set -euo pipefail
cat << EOF > process-compose.yml
version: "0.5"
log_level: debug
processes:
sleep:
command: "sleep 100"
echo:
command: |
echo 1
sleep .1
echo 2
EOF
process-compose up -u pc.sock -L pc.log --tui=false >/dev/null 2>&1 &
for i in {1..5}; do
if process-compose process list -u pc.sock 2>/dev/null | grep sleep >/dev/null; then
break;
fi
sleep .1
done
if [ …
```
> fix: workaround process-compose race in tests

- cli/Cargo.lock
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/start.rs
This changes the `process-compose` default log level from "info" to "debug" so that the log files are more useful. It also sets NO_COLOR=1 for all `process-compose` logs so that we no longer get tripped up by that in tests, regular expressions, etc.
N/A
> chore: set process-compose log level and no_color

- cli/flox/src/commands/pull.rs
- cli/tests/services.bats
Add the same warning to `flox pull` as we have for `install`, `uninstall`, `upgrade`, and `edit`.
This only covers the happy path where you are successfully pulling into an existing environment. In the case where a pull fails and needs to be manually resolved the warning would be emitted on one of the other commands.
We don't currently emit any context specific warnings if you forcibly pull over the top of an existing environment. I think that's OK for the moment though because:
- it's inline with not warning about existing activations and not warning on `flox delete`
- services will still be cleaned up by the watchdog when all existing activations exit
Warn when `flox pull` could affect running services.
> feat(services): Warn on flox pull changes

- assets/activation-scripts/activate.d/set-prompt.bash
- assets/activation-scripts/activate.d/set-prompt.fish
- assets/activation-scripts/activate.d/set-prompt.tcsh
- assets/activation-scripts/activate.d/set-prompt.zsh
- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-config.md
- cli/flox/src/commands/activate.rs
- cli/flox/src/config/mod.rs
Add `set_prompt` and `hide_default_prompt` config options and deprecate `shell_prompt`.
`set_prompt` defaults to true and configures whether activate modifies the prompt.
`hide_default_prompt` defaults to false and configures whether environments named default are added to both the prompt and the environment variable `FLOX_PROMPT_ENVIRONMENTS`
`shell_prompt` is marked deprecated in the man page. If it is set and `set_prompt` and `hide_default_prompt` are unset, it is used to configure the values of `set_prompt` and `hide_default_prompt`.
If `shell_prompt` is set when either `set_prompt` or `hide_default_prompt` is set, error with:
```
❌ ERROR: 'shell_prompt' has been deprecated and cannot be set when 'set_prompt' or
'hide_default_prompt' is set.
Remove 'shell_prompt' with 'flox config …
```
> feat: add `set_prompt` and `hide_default_prompt`

- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
- cli/tests/services/echo_activate_vars.sh
Always set the activate environment variables for services in order to prevent them leaking from an outer activation that has services to an inner activation that doesn't have services.
I believe that this, including the two new integration tests, will cover the bug that Leigh reported in our private Slack:
- https://flox-dev.slack.com/archives/C054SAD6NLD/p1724299932792289
I don't feel 100% good about testing the environment variables, rather than the effects, especially for the `_FLOX_SERVICES_TO_START` because it's asserting a negative result.
However the only way that I could reproduce the original error of failing to start services with normal activation commands was to run two commands within the inner activation, possibly because the first one is using the wrong socket and config …
> fix(services): Prevent activate vars leaking

- cli/flox-rust-sdk/src/flox.rs
Adds a new feature flag key `build: <bool>`,
that can be set via the usual config mechanisms:
- setting `features.build = true | false` in the config files
- modifying the config file imperatively with `flox config --set-bool features.build true`
- set the `FLOX_FEATURES_BUILD` env variable to  `true|false`
> feat: add `build` feature flag

- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/commands/show.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/utils/mod.rs
- cli/flox/src/utils/tracing.rs
Replace all uses of `instrument` and `record` to set fields with a
helper function that sets tags on the current scope. This allows us to
search them in the Sentry UI.
Tags are the only custom keys that you can search on:
- https://docs.sentry.io/concepts/search/searchable-properties/
- https://docs.sentry.io/platforms/rust/enriching-events/tags/
- https://docs.sentry.io/concepts/key-terms/enrich-data/#types-of-data
- https://sentry.zendesk.com/hc/en-us/articles/26861002545691-How-to-search-context
The other-other form of sending arbitrary data has been deprecated:
- https://docs.sentry.io/platforms/rust/enriching-events/context/#additional-data
They have no cost implications because billing is by span quantity:
- https://sentry.io/pricing/
The docstring explains more about why we have to …
> fix(tracing): Change fields to tags

- cli/flox-watchdog/src/main.rs
- cli/flox-watchdog/src/sentry.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/init/sentry.rs
Honour disabling metrics, set the version correctly, and allow logs from Sentry initialisation.
This is best reviewed commit-by-commit.
I've created some follow-up issues for the other things that I noted in demos that will require more thought or work:
- https://github.com/flox/flox/issues/1986
- https://github.com/flox/flox/issues/1987
- https://github.com/flox/flox/issues/1988
Data is no longer sent to Sentry when metrics are disabled. Apologies for the oversight!
> fix(tracing): Sentry improvements

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/errors.rs
- cli/tests/services.bats
* Add more information to connection errors when talking to the service manager.
Process-Compose commands may fail with [LoggedError::SocketDoesntExist]
if the specific socket doesn't exist,
or if the service manager has quit without cleaning up the socket,
i.e. the socket is unresponsive.
This function adds more context to the error in the latter case.
For practical purposes, we apply this to the [ProcessStates::read] call in
all services commands, as that is typically the first call that can fail.
For following commands, we can assume that the service manager is running.
* Add a `ServicesEnvironment` type that wraps a `ConcreteEnvironment`
that has been checked for compatibility with service commands.
Constructing a `ServicesEnvironment` requires a local `ConcreteEnvironment`
with a v1 …
> chore: service connection errors and command invariant guards

- cli/flox-rust-sdk/src/models/manifest.rs
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/resolver/manifest-raw.hh
- pkgdb/src/buildenv/buildenv-lockfile.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/resolver/manifest-raw.cc
- pkgdb/tests/buildenv.bats
- test_data/config.toml
- test_data/generated/envs/build-noop/manifest.lock
- test_data/generated/envs/build-noop/manifest.toml
[feat: add package build section to manifest](https://github.com/flox/flox/pull/1802/commits/1a4c901d6a31d64a8dce3fc439c92d16c3b184a9) 
Add a new `build` section with the following format to the manifest:
```
build.<name> = {
command    = <STRING>
, files      = null | [ “path1”, “path2”, … ] /* optional, build can write to $out */
, systems    = null | [ <STRING>, … ]
, sandbox    = null | "off" | "pure"
}
```
#1943 
[feat(buildenv): read build field](https://github.com/flox/flox/pull/1802/commits/8d69feb0bd0de97085a6c4ddd83446128c29a734) 
* feat(buildenv): add build scripts to environment
For every `build.<name>.command` in the manifest portion of the lockfile,
`pkgdb buildenv` should
- create an _executable_ file at `<env store-path>/package-builds.d/<build-id>`
- write the content of …
> feat: prepare manifest based builds

- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
Implement the parser for the `flox build` command. The current implementation only prints a message and quits.
The usage as defined will look like this:
```
Build packages for flox
Usage: flox build [-d=<path> | -r=<owner>/<name>] [-L] [<build>]...
Available positional items:
<build>           The package to build, corresponds to the entries in the
'build' table in the environment's manifest.toml. If not
specified, all packages are built.
Available options:
-d, --dir=<path>  Path containing a .flox/ directory
-r, --remote=<owner>/<name>  A remote environment on FloxHub
-L, --build-logs  Whether to print logs to stderr during build Logs are
always written to <TBD>
-h, --help        Prints help information
Run 'man flox-build' for more details.
```
> feat: add scaffold for `flox build` command

- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/buildenv.bats
Write the lockfile to the environment,
causing semantic changes to the lockfile to invalidate existing environment store paths.
This is useful to determine whether an environment needs to be rebuilt,
as well as reresolve the environment "linktree".
The latter is particularly important when removing package priorities,
that previously resolved package conflicts.
Since the `priority` is not part of the evaluation,
setting the `priority` for a package does not change the evaluated store path
of the environment.
Removing the `priority` will built the previous environment
and _not_ error on file conflicts,
until another change to the manifest causes a rebuild,
or the environment is built on another machine.
> feat(buildenv): include manifest lock in environment

- pkgs/flox-cli-tests/default.nix
We've seen test failures on x86_64-darwin where it appears bats files the tests depend on are being removed during the test. Since those files are in the nix store, our best guess is that those files are getting garbage collected. One such failure is https://github.com/flox/flox/actions/runs/10188862002/job/28186108948#step:6:417
The failures have always occurred on x86_64-darwin. Nix doesn't garbage collect paths store in environment variables on Linux, but on macOS it appears to only use lsof, since macOS doesn't have `/proc`. See https://github.com/NixOS/nix/blob/076b6f7bb163a95e6a6537aad21d9661b0c6c8fa/src/libstore/gc.cc#L352
Before this change, running `flox-cli-tests` and then
```
$ sudo nix-store --gc --print-roots | grep flox-cli-tests
```
doesn't show any results.
Instead of …
> fix: ensure lsof can find a flox-cli-tests gcroot

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/activate.rs
So that we can get an idea of how long we need to support activating already locked pkgdb environments.
We're recording the lockfile version, rather than the manifest version, because a v0 manifest might be automatically migrated to v1 during activation. We could later add metrics for manifest versions in order to determine whether we still need to do migrations but there are a handful of places that it would need to be added other than `activate`.
This is done in a second `subcommand_metric!`, in addition to the early call in `Activate::handle`, because we don't have all of the information required at the start, don't want to cause a premature lock/error, and our in-house metrics don't have a way to additional submit tags on existing metrics.
We can't use Sentry for this metric because …
> feat(activate): Add metric for lockfile_version

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/tests/services.bats
We currently set `_FLOX_SERVICES_SOCKET` when we activate an environment with services. We also check `_FLOX_SERVICES_SOCKET` when running an activation to allow overriding the path for the socket. This means that when an activation is performed within another activation, it uses the value of `_FLOX_SERVICES_SOCKET` set by the outer activation, which causes services for two different environments to interfere.
Instead, introduce a second variable `_FLOX_SERVICES_SOCKET_OVERRIDE` to provide the overriding behavior, and use `_FLOX_SERVICES_SOCKET` to communicate with the activate script.
We could instead drop the one test that uses the overriding behavior, but I figure it could be useful in debugging to be able to set the socket path explicitly.
> fix: socket conflict for layered activations

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/tests/edit.bats
- test_data/config.toml
- test_data/generated/resolve/vim-vim-full-conflict.json
The `priority` field is originally set when constructing in [LockedPackageCatalog::from_parts], after resolution.
Already locked packages are not re-resolved for priority changes as priority is not a constraint for resolution.
Thus removing (or setting) a priority attribute to an existing and previously locked manifest descriptor had no effect on the original priority of the locked package.
This change includes a step within the locking implementation to update the priority field of all already locked packages to the respective value in the manifest.
> fix: update `priority` of already locked packages

- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
We forgot to unhide this when releasing services. You could find it from `flox services --help` but not `flox --help`.
It may be moved to another section at a later date, possibly when we come to release `flox build`, which is currently under "additional":
- https://github.com/flox/flox/pull/1997
- https://flox-dev.slack.com/archives/C06T9RL3BQT/p1724788772613039
N/A
> chore(services): Unhide from root --help

- cli/flox/doc/flox-pull.md
- cli/flox/doc/flox-push.md
These links refer to a manpage that no longer exists.
Removes broken links from the command reference documentation.
> fix(docs): remove broken links from manpages

- .github/workflows/ci.yml
- cli/tests/install.bats
- flake.lock
- flake.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-pkgdb/default.nix
* Remove less frequently used dev tools for the C++ part of the codebase.
In the past we maintained a separate CI devshell which excluded all dev tooling.
* Reuse the single fenix provided toolchain for git hooks
Before we were missing the dependency on `tools.cargo` which pulled in nixpkgs' rust toolchain
in addition to the fenix tracked toolchain providing clippy.
Before the single devshell we use weighs >7G,
removing some tools and unifying the rust toolchains used reduced the closure size to ~5.6G
Avoid pulling more revisions of nixpkgs than necessary.
The revision corresponding to `PKGDB_NIXPKGS_REV_OLD` is entirely unused
besides this after the removal of pkgdb scraping.
While `PKGDB_NIXPKGS_REV_NEW` is still a misnomer,
the corresponding revision is pinned in additional tests
thus …
> fix: reduce dev closure

- .github/workflows/ci.yml
Reduce the parallel jobs when using the same machines to avoid excessive load.
N/A
> ci: less parallelization for remote tests

- cli/flox/src/commands/activate.rs
- cli/flox/src/utils/metrics.rs
Fixes the following since e7b0e893:
(2) ~/projects/flox/flox on HEAD (eabea829) [$]
% flox activate -r dcarley/tailscale
2024-08-30T13:45:57.839901Z TRACE flox_command: subcommand="activate#version" lockfile_version=1
✅ You are now using the environment 'dcarley/tailscale (remote)'.
To stop using this environment, type 'exit'
This would happen for any environment that requires building at the same time as activation, such as a remote environment, where the calls within or below `environment.lockfile()` generate their own tracing events.
It can also be reproduced with a much simpler:
fn test() -> &'static str {
tracing::debug!("test");
"test"
}
subcommand_metric!("activate#version", lockfile_version = test());
Moving the function outside of the macro fixes this:
(2) ~/projects/flox/flox on …
> fix(activate): Prevent stray TRACE log

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/set-prompt.tcsh
- assets/activation-scripts/activate.d/zdotdir/README.md
- cli/tests/activate.bats
- pkgs/flox-activation-scripts/default.nix
The handling of command args within the `activate` script was incomplete, and did not expose sufficient functionality to be able to invoke a bash script without employing the [previously undocumented] `FLOX_TURBO` mode. This PR addresses these issues by adding `getopt` argument parsing to the `activate` script, normalising the use of `-c` for invoking commands in each of the [3] command modes, and documents the `--turbo` and `--noprofile` command invocation modes.
This PR adds argument parsing that makes it possible to invoke any of the following:
```
% /path/to/activate bash <file>
% /path/to/activate -- bash <file>
% /path/to/activate -c "bash <file>"
```
By way of explanation, when `activate` parses the command line:
* the `--` delimiter delineates the `activate` script arguments from …
> fix: normalize `flox activate -- cmd args` handling in all cases

- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
Print a warning if you `flox activate --start-services` on an
environment that doesn't have any defined.
Previously we would continue and silently not start services, which
caught me out when manually testing something on an environment that I
thought would start services but didn't because I used the wrong
manifest.
Currently opting for warning and continuing instead of an error and
exiting because you might be iterating manifest changes and re-running
the same command knowing that it won't fully work.
Print an warning if you `flox activate --start-services` on an environment that doesn't have any defined.
> fix(activate): Warn for -s if there are none

- pkgdb/Makefile
The pkgdb Makefile was not picking up changes to the activation scripts package when inputs were changed, which of course can cause changes in the string-substituted versions of activation scripts as created by the Nix package build. This change updates the conditions for re-rendering the package to include changes in either/both of the top-level flake.{nix,lock} files.
N/A
> fix: re-render ACTIVATION_SCRIPTS_PACKAGE_DIR with flake

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/doc/flox.md
- test_data/generated/envs/hello/manifest.toml
* adds a missing SEE MORE link to manifest.toml man page to `man flox`
* adds a sentence to the default manifest template to explain the `version = 1` parameter
n/a
> docs: Add man manifest.toml to man flox SEE MORE and modify manifest template to explain version parameter

- pkgdb/tests/lock-flake-installable.cc
`test_locksUrl` failed during local development due to using a local flakeref which references the local (containing) git repository through `localTestFlake`.
`localTestFlake` is defined as `./tests/data/lock-flake-installable`, which is a subdirectory within the flox repo.
If there are any tracked changes, the repo is considered dirty. This propagates to any flake defined within the repo. Thus in development this test would fail most of the time, unless the repo is in a clean state.
To avoid this, exceptionally use an external flake for this test, that can be locked cleanly.
> test(pkgdb): use external flake to avoid failure when repo is in dirty

- cli/catalog-api-v1/README.md
The `mitmproxy` package is not available on Darwin for recent nixpkgs revisions. Update the catalog-api-v1 developer instructions to invoke it from the most recent stable nixpkgs revision on which it is known to build.
N/A
> chore: update README.md to reflect problems invoking mitmproxy on Darwin

- cli/flox/doc/flox.md
There is now a comma in the `man flox` SEE MORE section. There was great rejoicing
n/a
> docs: missing comma in man pages

- cli/Cargo.lock
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-watchdog/Cargo.toml
- cli/flox-watchdog/src/logger.rs
- cli/flox-watchdog/src/main.rs
- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
This is best reviewed commit-by-commit.
To prevent the recently added `.flox/log` directory from growing too
large whilst still keeping enough logs that users can use to inspect and
report issues. We will now keep:
**- Watchdog logs that have been updated within the last 3 days.**
A new file is created every time a watchdog is started, which happens
with every non-ephemeral activation. The file haves a PID in their name
but we don't parse it.
This relies on the preceding commit that emits a heartbeat log entry
every hour so that we can determine whether a watchdog is still using
the file without needing to look it up or check open files.
A side-effect of this is that upgrading from 1.3.0 will blow away the
watchdog logs for any activations that were started more than 3 days ago
because …
> feat(watchdog): GC watchdog and services logs

- flake.lock
- flake.nix
- pkgdb/include/flox/fetchers/wrapped-nixpkgs-input.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/eval.cc
- pkgdb/src/fetchers/wrapped-nixpkgs-input.cc
- pkgdb/src/flox-flake.cc
- pkgdb/src/lock-flake-installable.cc
- pkgdb/src/nix-state.cc
- pkgdb/tests/data/lock-flake-installable/flake.lock
- pkgdb/tests/flox-nixpkgs.cc
- pkgs/nix/default.nix
- pkgs/pre-commit-check/default.nix
- shells/default/default.nix
Update flox build to only use a single nixpkgs revision derived from one of the github:flox/nixpkgs stability branches, and switch to using the `nixVersions.stable` version of `nix`.
This is being done to reduce the closure size and assure regular upgrades of `nix` going forward.
* Upgraded version of `nix` included in Flox installation to follow the upstream "stable" version of Nix.
> chore: build flox using only one nixpkgs revision

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox/src/build/mod.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/main.rs
- flake.nix
- package-builder/Makefile
- package-builder/build-manifest.nix
- package-builder/closure.c
- package-builder/closure.h
- package-builder/flox-build.mk
- package-builder/glibc-bindings.h
- package-builder/sandbox.c
- package-builder/sandbox.h
- pkgs/flox-package-builder/default.nix
- pkgs/rust-internal-deps/default.nix
Create a package for the (manifest build) package builder,
and provide its path to the build of flok-rust-sdk,
which will implement bindings to the script in the following commit.
The source for the builder is derived from the Manifest build PoC
<https://github.com/flox/flox/pull/1809>.
Notable changes from that PR:
* build pacakges using nixpkgs fetched with `getFlake` rather than using the `<nixpkgs>` channel.
* disable sandboxing for the lack of macOS support in ld-floxlib (at this point)
Define a `ManifestBuilder` trait that provides an interface to building packages.
The signature of this trait is inspired by the requirements
of calling the `flox-build.mk` subsystem, outlined in
<https://github.com/flox/flox/issues/1998>.
Namely, builds require
* a `basedir`: the directory containing …
> feat: integrate manifest package builder

- pkgdb/src/fetchers/wrapped-nixpkgs-input.cc
This was added to the function signature and callers in 5a6c0a68 to
match Nix 2.18 but isn't used in our function body, which causes this
warning when recompiling `pkgdb`:
src/fetchers/wrapped-nixpkgs-input.cc:297:47: warning: unused parameter 'requireTree' [-Wunused-parameter]
bool requireTree ) const
^
It seems that there's a handful of different way that you can workaround
an argument not being used in C++ but I copied this pattern from
`startActivity` in our logger.
N/A
> refactor(pkgdb): inputFromURL unused arg

- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/containerize.rs
- cli/tests/containerize.bats
- removes ".gz" extension when producing a ".tar"
- remove superfluous tests that take a long time (151s -> 41s)
Fixes: https://github.com/flox/product/issues/769
> fix: remove .gz extension for containerize, trim tests

- .github/workflows/ci.yml
The `remote` job currently builds both `flox` and `flox-cli-tests`, which adds ~45 sec to every `remote` job. Most of this work is wasted, since it copies flox to the GitHub runner, even though flox is only needed on our own runner for that job.
Building `flox-cli-tests` in the `nix-build` job is much faster, because that job has already built `flox`. Building `flox-cli-tests` is relatively cheap since it only requires a `writeShellScriptBin`.
The only jobs that depend on `nix-build` are `remote`, `Build installers`, and `Report Falure`. We skip `Build installers` on PRs and in the merge queue, so adding a smaller amount of time to `nix-build` in exchange for subtracting a greater amount of time from `remote` should be an improvement.
> chore(CI): move build of flox-cli-tests to nix-build step

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/tests/containerize.bats
- pkgdb/include/flox/buildenv/command.hh
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/libexec/mkContainer.nix
- pkgdb/tests/buildenv.bats
- use environment name for image name
- `flox containerize` will now use the environment's name as the produced image's name.
> feat: container enhancements

- cli/tests/services.bats
The `kills daemon process` test flaked in
https://github.com/flox/flox/actions/runs/10742333592/job/29794735526#step:8:297
It's unclear why that run flaked. `overmind status` printed something, and it doesn't seem to have ever failed since there is no output for failure to connect.
It's odd that PID 0 was printed, but when run locally, that happens occasionally when `overmind start` and `overmind status` are racing. Locally, that still exits 0.
So it seems `overmind status` should have succeeded, but then timeout still timed out.
Add set -x to help with debugging in the future.
> test: add set -x for overmind test

- cli/tests/auth.bats
- cli/tests/containerize.bats
- cli/tests/delete.bats
- cli/tests/edit.bats
- cli/tests/environment-managed.bats
- cli/tests/floxhub-cross-systems.bats
- cli/tests/setup_suite.bash
- cli/tests/test_support.bash
- cli/tests/usage.bats
A _new_ cache directory in `/tmp/flox.tests.XXXXXX` is created with every call to `flox_vars_setup`[1]. The only call to `flox_vars_setup` is within `home_setup`[2], thus any call to `home_setup` will create a new tempdir.
Further, `home_setup` is called once during `common_suite_setup` [3], and then again for every file via `common_file_setup`[4], as well as once during `"m10: deletes existing environment"`[5].
The only place to remove `$FLOX_CACHE_DIR` is within `common_suite_teardown` [6]. Consequently, any cache dir created by [4] and [5] remain on disk:
```shell
$ ls /tmp | sort > before
$ just integ-tests
$ ls /tmp | sort > after
$ comm -3 before after
flox.tests.12lLgE
flox.tests.2fRUrE
flox.tests.6Rh9wF
flox.tests.BKzWtx
[...]
```
To address this issue
1. remove the cache dir …
> fix: cleanup cache directories

- cli/flox/doc/doc-build/flox-build.md
- cli/flox/doc/doc-build/manifest.toml.md
* Describe manifest defined builds and general build customization
such as sandbox control and files.
Add examples for simple pure builds and staged builds
by the example of a simple node built website.
* Add documentation of the `build` section in the manifest.toml
> docs: document `flox build` in manpages

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox-watchdog/src/logger.rs
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/tests/services.bats
* Add a new field to the service descriptor that restricts running a service on the specified systems.
* Add `ManifestServices::copy_for_system` to create a new ManifestServices instance
with services for systems other than provided `system` filtered out.
Clone the services rather than filter in place
to avoid accidental mutation of the original in memory manifest/lockfile.
* Where previously checking `manifest.services.is_empty()`
add an additional check whether `copy_for_system` is empty as well and warn/err
if the manifest provides no service for the current system.
The messages will be different from _not having services at all_ for clarity.
* Check service names against services for current system
When providing services as an argument, the service name
will now be checked against …
> feat: allow restricting services to specific systems

- assets/activation-scripts/activate.d/fish
- cli/tests/activate.bats
- test_data/config.toml
- test_data/generated/resolve/fish_3_2_2.json
fish 3.2.2 fails due to our usage of return outside of a function and `$(...)`
Before this commit, the test added in this commit fails with:
```
/private/var/folders/2w/r9qm37r12qs4xn3sjn4cv2ym0000gn/T/nix-shell.JcSQ0t/bats-run-MtPfNW/test/1/project-1/.flox/run/aarch64-darwin.project-1/activate.d/fish (line 17): 'return' outside of function definition
return 1
^
from sourcing file /private/var/folders/2w/r9qm37r12qs4xn3sjn4cv2ym0000gn/T/nix-shell.JcSQ0t/bats-run-MtPfNW/test/1/project-1/.flox/run/aarch64-darwin.project-1/activate.d/fish
source: Error while reading file “/private/var/folders/2w/r9qm37r12qs4xn3sjn4cv2ym0000gn/T/nix-shell.JcSQ0t/bats-run-MtPfNW/test/1/project-1/.flox/run/aarch64-darwin.project-1/activate.d/fish”
```
Fix this by using exit 1 instead of return 1.
After changing …
> fix: support fish 3.2.2

- cli/tests/services.bats
Add a set -x for the bash subshell invocation to help with debugging a flakey test.
> test: add another set -x for debugging

- cli/catalog-api-v1/src/error.rs
456cc7b07052e84571d514b395609f608a962850 made MessageType an untagged enum so that the Unknown variant would deserialize correctly, but this meant that all strings would deserialize as Unknown rather than being deserialized into the correct variant. "constraints_too_tight" for example was being deserialized as `Unknown("constraints_too_tight")`.
The Unknown variant should be untagged, but the enum as a whole should not be.
> fix: deserialize MessageType's other than Unknown

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/core/exceptions.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/buildenv.bats
Create `requisites.txt` containing a list of all packages in the closure as a file in the top directory of the rendered flox environment.
This file can be useful for a variety of reasons, but we are adding it at this stage in preparation for the upcoming flox manifest build "sandbox" features which requires a way to discern the Nix packages that are in and out of the environment closure without having to first query narinfo data from the Nix database.
N/A
> feat: render top-level requisites.txt file to flox environments

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/doc/flox-pull.md
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/commands/push.rs
- cli/tests/pull.bats
Convert a `ManagedEnvironment` and its associated metadata
into a `PathEnvironment`.
Conversion entails:
- delete the associated (local) branch for this instance of the environment
- delete the generation lock which
- rewrite `.flox/env.json` as a `PathPointer
Defer printing of the final message during result handling,
to allow conditionally displaying different headers in preparation
of adding support for `--copy`.
Copying (as implemented in the following commit) entails
1. pulling a `ManagedEnvironment`
2. handling the result of pulling the environment
(e.g. migrating v0 manifests, adding the current system as a supported system)
3. converting the environment to a path environment
When pulling an environment regularly, the header of the message is expected to read:
Pulled owner/name …
> feat: `flox pull --copy`

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
In SDK because focusing on effects rather than CLI output.
Output handling needs to be adjusted and tested in CLI.
* test(build): `flox-build.mk` honors `system` attribute
Currently ignored as the functionality is not implemented in the builder.
* test(build): `flox-build.mk` honors `files` attribute
Currently ignored as the functionality is not implemented in the builder.
* test(build): `flox-build.mk` buildCache
* test(build): test packages, hooks, and vars
* test(build): package depending on another package
* chore: Avoid depending on CC toolchain when building packages
Use `runCommandNoCC` over `runCommand`
* chore: Use flox' nixpkgs
> test(build): Test build functionality

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
Change the interpretation of "null" when reading the sandbox value from the manifest.lock to instead mean that sandbox should be set to "off" as described in #2107.
N/A
> chore: set default for manifest builds to sandbox = "off"

- cli/tests/services/start_shuts_down_process_compose.sh
I ran into this test flaking locally. `flox services start` calls `process-compose down`, but `process-compose down` is not blocking, so `flox services start` may exit before `process-compose` exits.
Add a polling loop to wait for `process-compose` to exit.
> test: process-compose shutdown race

- .github/workflows/ci.yml
- cli/flox/src/main.rs
- cli/tests/activate.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
* Run bats tests with `--jobs $(nproc)`.
* Disallow parallel runs across files
* Do not run `activate` tests in parallel
These tests break frequently, likely do to $HOME/$USER discrepancy.## Proposed Changes
Run the `set_user` function earlier to allow `config` to read from the right user.
> ci: run integ-tests in parallel

- flake.nix
To fix this warning on `nix develop` and `direnv reload`:
warning: input 'crane' has an override for a non-existent input 'nixpkgs'
It was removed upstream here:
- https://github.com/ipetkov/crane/commit/6f7504ad93304e8ddf29c0b82442f61c03900ccb
- https://github.com/ipetkov/crane/blob/master/docs/faq/custom-nixpkgs.md
We already pass an explicit pkgs to `mkLib`:
% rg crane.mkLib
pkgs/flox-cli/default.nix
27:  craneLib = (inputs.crane.mkLib pkgsFor).overrideToolchain rust-toolchain.toolchain;
pkgs/flox-watchdog/default.nix
11:  craneLib = (inputs.crane.mkLib pkgsFor).overrideToolchain rust-toolchain.toolchain;
pkgs/rust-external-deps/default.nix
13:  craneLib = (inputs.crane.mkLib pkgsFor).overrideToolchain rust-toolchain.toolchain;
pkgs/rust-internal-deps/default.nix
19:  craneLib = …
> refactor(flake): Remove crane.inputs.nixpkgs

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/commands/install.rs
- cli/tests/install.bats
- test_data/config.toml
- test_data/generated/resolve/badpkg_bpftrace.json
- test_data/generated/resolve/bpftrace.json
- test_data/generated/resolve/bpftrace_systemd.json
Currently installing packages through `Environment::install`
always installs packages for _all_ systems.
In case a package is not available on all platforms,
the package can only be installed by manually editing the manifest.
This commit adds a `system` field to the `PackageToInstall` variant
for catalog packages, to allow callers to amend the systems
that the package is installed for.
Since we do not have a formal syntax to expose this on the CLI,
the `FromStr` implementation remains unchanged and will not explicitly
restrict the systems in any way.
During `flox install`, when all resolution errors are "package unavailable on some systems",
modify the `systems` attribute in the original list of packages to install,
to match the suggested systems returned by the catalog service
and …
> feat: attempt install with reduced systems  

- pkgs/nix/default.nix
- pkgs/nix/patches/nix-7370.patch
We ran into occasional issues with the nix gc-socket in our unit test suite. <https://github.com/flox/flox/issues/2116> was logged against it to investigate. The error we are seeing is:
error: cannot connect to socket at '/nix/var/nix/gc-socket/socket': No such file or directory
Which appears to be discussed upstream in <https://github.com/NixOS/nix/issues/7370>. The upstream issue was closed via <https://github.com/NixOS/nix/commit/c5fdbdae321903740e0e735aa89fab5647992687> but only on nix >=2.20.
nix 2.18, the current stable version used by flox, still uses the existing implementation:
<https://github.com/NixOS/nix/blob/d4d300c2084b5e81ee0ea2aba8215d03133f14f8/src/libstore/gc.cc#L145-L151>.
This commit adds the upstream changes as a patch,
until nixpkgs upgrades to nix > 2.18 for good. …
> fix: backport concurrent gc issue to nix 2.18

- cli/flox/src/commands/install.rs
Follow up on <https://github.com/flox/flox/pull/2110>
* Print a warning to notify that a package is not being installed for all systems. This should avoid too much confusion when running `flox list` after an install of a package that is not available on the current system.
Before:
```
% flox install bpftrace
✅ 'bpftrace' installed to environment 'tmp'
% flox list
hello: hello (2.12.1)
```
After:
```
% flox install bpftrace
⚠️  Installing 'bpftrace' for the following systems: ["aarch64-linux", "x86_64-linux"]
✅ 'bpftrace' installed to environment 'tmp'
% flox list
hello: hello (2.12.1)
```
The installed package will still be missing from `flox list`, since it is not available on the current system.
* Remove help message from spinner. With the additional warning, the help message is less …
> style: print warning when installing with reduced systems

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
**fix(build): impure build error when no $out**
Raise a clearer error if a build script doesn't write anything to `$out`
before the contents are passed to `nix build`.
It's worth noting that `$out` should not be interpolated because it has
a special user-facing meaning that they should reference in their build
commands and there won't be anything to inspect at the interpolated path
because this error is only triggered when the path doesn't exist.
The previous error looked like this:
% FLOX_FEATURES_BUILD=true ft build
make: Entering directory '/Users/dcarley/tmp'
Rendering foo build script to /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.V2I4sp/9686f39a-foo-build.bash
Building foo-0.0.0 in local mode
MAKEFLAGS= out=/tmp/store_9686f39a3ff6d4f9d37cf289816940e7-foo-0.0.0 …
> fix(build): Consistent errors when $out is not populated

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/containerize.rs
- cli/tests/containerize.bats
- pkgdb/include/flox/buildenv/command.hh
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/libexec/mkContainer.nix
- pkgdb/tests/buildenv.bats
Closes: flox/product#771
- `flox containerize --tag ...` now sets the resulting container's tag to the value of the `tag` flag.
- `flox containerize` now sets the resulting container's tag to `latest` by default if `--tag` isn't set.
> feat(containerize): add `--tag` option

- cli/tests/setup_suite.bash
We unset a number XDG_* dirs to give our tests some level of isolation. We should also unset XDG_DATA_DIRS because we've seen it cause tests to fail.
More specifically, if a flox environment with `direnv` is activated, activation puts `$FLOX_ENV/share` in `XDG_DATA_DIRS`, and that loads direnv for fish because it contains
`$FLOX_ENV/share/fish/vnedor_conf.d/direnv.fish`.
If doing development with direnv, this can cause some fish tests to fail, e.g.:
```
flox-cli-tests -- -f "catalog: fish: interactive activate puts package in path"
```
This fails because of a `direnv: unloading`, which presumably modifies PATH and breaks the test.
> test: unset XDG_DATA_DIRS

- assets/activation-scripts/activate.d/bash
- assets/activation-scripts/activate.d/set-prompt.bash
- assets/activation-scripts/activate.d/set-prompt.zsh
- assets/activation-scripts/activate.d/zsh
- cli/tests/activate.bats
This modifies the activation scripts for bash and zsh (there's no "set -u" option for tcsh or fish) to always initialize certain variables to empty strings rather than letting them be unset. This allows a user with "set -u" in their .bashrc/.zshrc to "eval $(flox activate)" without seeing errors from our activation scripts.
N/A
> fix: don't use unset variables in activation

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/commands/build.rs
Currently run the Makefile even if no builds are defined and print
```
make: Entering directory '...'
make: Nothing to be done for 'all'.
make: Leaving directory '...'
✨ Build completed successfully
```
Print an error instead:
```
❌ ERROR: No builds found.
Add a build by modifying the '[build]' section of the manifest with 'flox edit'
```
Skip serializing the manifest tables `install`, `vars`, `services`, and
`builds` when they are empty in order to:
1. Make lockfiles smaller
2. Establish a better pattern for backwards compatibility. A newer
version of flox should try to generate a lockfile that an older
version of flox can fully understand.
I didn't skip serializing `hook`, `profile`, and `options` since doing
so would require checking if all fields are empty, and that seems more
likely …
> fix: skip serializing empty manifest tables

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/cli.rs
- cli/flox-activations/src/main.rs
- flake.nix
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-activations/default.nix
**feat: Add flox-activations crate**
This also adds a new build profile called "small" that is tuned to
produce smaller binaries. Using this profile reduces the size of the
compiled binary from 995k ("release" profile) to 471k. This application
shouldn't be doing anything performance intensive, so the difference in
speed should be negligible in practice. Of this 471k, 60% is the Rust standard
library, and 29% is the argument parser, so there's not a lot of fat left to
trim unless you want to remove the Rust standard library.
**feat: add Nix build for flox-activations**
Performs a Nix build of the `flox-activations` crate using the `small` profile.
**chore: add dep for flox-activations**
This makes `flox-activation-scripts` depend on `flox-activations` since it
will be called in the …
> feat: Add flox-activations crate

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/zdotdir/.zshrc
- cli/tests/activate.bats
- cli/tests/activate/activate.exp
- cli/tests/activate/only-once.toml
Test that in-place activation works from zsh RC files. This is a
variation of the tests above it which do something similar but not quite
the same by hooking into the RC process later on.
I was hoping to reproduce the issue in #1946 but I haven't been able to
either manually or with these tests. If the problem still exists from
Graham then we may be able to tweak these new tests to reproduce it.
Plus a bunch of test improvements that were necessary to get these working. They are best reviewed commit-by-commit.
Plus a fix when using an outer in-place activation with an inner interactive activation.
N/A
> test(activate): Test and fix zsh in-place from RC files w/nesting

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
- make the build-specific tmpdir stable across `$FLOX_ENV` updates
- don't throw away the variable-substituted build script after a build
Closes #2121 
N/A
> fix: don't throw away build files

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/src/commands/init/python.rs
No one wants stale cereal.
These were added to avoid pkgdb concurrency issues. If I remember
correctly, init hooks called search which could trigger a pkgdb scrape,
and the core_environment tests installed actual packages which could
also trigger a pkgdb scrape.
We can drop #[serial] now that we're no longer calling pkgdb.
The `serial_test` crate was not dropped since we still use it for
metrics tests.
> test: remove stale #[serial]

- pkgs/flox-activations/default.nix
Unlike the `flox` and `flox-watchdog` packages,
we cannot reuse the `flox-*-deps` packages for incremental compilation because this crate is built with the "small" profile, which among othet things applies different compiler optimizations.
Crane will still cache the dependencies of this package, through its own automation, but will experience cache misses if we add shared (internal) packages.
> build: update incremental compilation of flox-activations

- cli/flox-rust-sdk/src/providers/services.rs
I've seen the failure:
```
thread ‘providers::services::tests::test_process_states_read’ panicked at flox-rust-sdk/src/providers/services.rs:1410:9:
assertion failed: `(left == right)`
Diff < left / right > :
<Running
>Completed
```
There's a race between when we run `process-compose list` and when short-lived processes exit. Poll for processes to complete rather than assuming they have completed the first time `process-compose list` succeeds.
> test: fix race in test_process_states_read

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/build.rs
Related debugging thread: https://flox-dev.slack.com/archives/C05P6A5J6U8/p1727913617359869
To workaround the bug in the commented issue which affects a variety of tests like this:
stdout: lock released on '/nix/store/2gj49g4zw03y1mlzvs26kxyq6bxh5paq-foo-0.0.0.lock'
stdout: lock released on '/nix/store/hxvflmc8635w15bpsmjqy8ixwdgb8pqs-foo-0.0.0-buildCache.lock'
stdout: building of '/nix/store/4i5kip3jnpcchzjky78zlw41yscigvzl-foo-0.0.0.drv^*' from .drv file: done
stdout: building of '/nix/store/4i5kip3jnpcchzjky78zlw41yscigvzl-foo-0.0.0.drv^*' from .drv file: goal destroyed
stdout: performing daemon worker op: 11
stdout: sending GC root '/nix/store/hxvflmc8635w15bpsmjqy8ixwdgb8pqs-foo-0.0.0-buildCache'
stdout: closing daemon connection because of an exception
stdout: error: unexpected …
> test(build): Serial tests to workaround EOF bug

- cli/Cargo.lock
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/activations.rs
Adapt the tests for services_socket_path to cover the cases we care about for flox_runtime_dir.
> test: add tests for flox_runtime_dir

- cli/flox-rust-sdk/src/providers/build.rs
This was split out of https://github.com/flox/flox/pull/2174 to make it easier to review and not hold up the fix.
**refactor(build): Set current_dir for flox-build.mk**
When investigating the build test failures in #2185 we suspected that
one test might be cleaning up the contents of a build from another test
because `flox-build.mk` depends on the current working directory being
the Flox environment and Michael wasn't sure that the `-C` was
sufficient.
This turned out not to be the case. Based on the `Entering directory`
output and man page for the argument it is working as intended:
> Change to directory dir before reading the makefiles or doing anything else.
However if Michael was unsure, and he's most familiar with `make` and
`flox-build.mk`, then it doesn't hurt to make it more …
> refactor(build): Set current_dir and unset MAKEFLAGS for flox-build.mk

- cli/flox/src/utils/message.rs
A test spy for messages printed to stderr through the `message` module. in unit tests, the messaging functions of the `message` module will, populate a `history` in addition to printing the message to stderr. this allows the test to assert against the messages printed to stderr, without refactoring existing implementations to print to a `Write` trait and injecting a mock in tests.
The `History` is thus comparatively non-intrusive. However, it comes with a few caveats:
Messaging functions are currently effectively (process) globals, inheriting the global nature of `stderr`.
`#[test]` functions are run in parallel on separate _threads_ by both `cargo test` and `cargo nextest`.
Assuming an equally global `History`, messages from one test will be visible in another test.
There are several …
> test: add `History` to track messages in unit tests

- cli/flox-rust-sdk/src/models/manifest.rs
Previously the first `@` character found in an install argument was interpreted as the delimiter of attr_path and version.
However, nixpkgs _does_ contain several packages with attributes starting with `@`. For example, `nodePackages.@angular`.
Previously `@angular` was incorrectly interpreted as the version `angular`. This commit adds support for such leading `@` characters in attributes.
In particular we will now search for the first `@` character, but instead of eagerly splitting and returning a version, if that `@` is the first character of an attribute, (the first character, or immediately following a `.`), we continue searching for further `@` characters.
> feat: support attributes with leading `@`

- pkgs/flox/default.nix
Instead of using a version identifier that isn't really parsable by semver, use [semver build metadata] to denote the git hash or dirty working directory.
So that when I install flox with `nix profile install github:flox/flox`, it has a proper semver version string. It'll look something as follows.
```console
$ realpath "$(which flox)"
/nix/store/4cd2mak5as0br4232b6bpqfcmxa57gn9-flox-1.3.3+git.010f25e/bin/flox
$ flox --version
1.3.3+git.010f25e
```
[semver build metadata]: https://semver.org/#spec-item-10
- Flox installed with `nix profile install github:flox/flox` now gives a proper semver version when `flox --version` is run.
> fix(pkgs/flox): use semver build metadata

- .editorconfig
- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/attach.bash
- assets/activation-scripts/activate.d/set-prompt.zsh
- assets/activation-scripts/activate.d/start-services.bash
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/etc/profile.d/0501_rust.sh
- assets/activation-scripts/etc/profile.d/0800_cuda.sh
- pkgs/flox-activation-scripts/default.nix
- pkgs/pre-commit-check/default.nix
Split from https://github.com/flox/flox/pull/2209 because it turned out to be a yak-shave.
**fix(editorconfig): Add rule for activate**
`shfmt --find` identifies this file by shebang but it didn't apply the
same rules as the other files (e.g. defaulted to hard tabs) because it
only matched the `[*]` rule in `.editorconfig`.
**refactor(activate): Run shfmt --write on assets**
To consistently format all scripts that `shfmt` identifies by extension
or shebang. Lint checking will be applied in a subsequent commit.
**test(activate): Run shfmt on build**
To ensure that we don't regress formatting after applying it in a
preceding commit. This is limited to activation scripts for now, like
`shellcheck` is, because we haven't dealt with formatting of other
scripts in the repo.
This misses a small …
> refactor(activate): shfmt most scripts

- cli/flox-rust-sdk/src/providers/build.rs
- test_data/config.toml
- test_data/generated/resolve/go.json
These tests would fail on Linux systems because they were using a multi-part mock response based on `flox init` where the initial request only resolves for Darwin. This results in the environment that silently omits the package and no `$FLOX_ENV/bin` is generated:
stdout: make: Entering directory '/tmp/.tmplf5xse/temp/.tmpTH6NaM'
stdout: Rendering foo build script to /tmp/nix-shell.5Qgf1P/def85939-foo-build.bash
stdout: Building foo-0.0.0 in local mode
stdout: MAKEFLAGS= out=/tmp/store_def85939439f94b0d8842804b8c5f21a-foo-0.0.0 /tmp/.tmplf5xse/temp/.tmpTH6NaM/.flox/run/aarch64-linux.name/activate --turbo -- bash -e /tmp/nix-shell.5Qgf1P/def85939-foo-build.bash
stderr: /tmp/nix-shell.5Qgf1P/def85939-foo-build.bash: line 4: go: command not found
stderr: make: *** …
> test(build): Go mocks for non-Darwin

- pkgs/flox-activation-scripts/default.nix
Some versions of Nix don't support store paths that start with `.`, so use builtins.path to rename .editorconfig -> editorconfig so that Flox can be built with more versions of Nix.
> fix: don't use .editorconfig as name of Nix derivation

- cli/flox-rust-sdk/src/providers/build.rs
To validate the case where a package has a runtime (not buildtime) dependency from the environment:
>     [build.vhs]
>     command = "go mod tidy; go build; mv vhs $out"
>
> I get
>
>     ffmpeg is not installed. Install it from: http://ffmpeg.org
>
> when I try to invoke the result without having been activated first
From this thread:
- https://flox-dev.slack.com/archives/C074WPYRJUB/p1728321737055899
Matching the output from `exec hello` rather than `type hello` because it means that we don't have to construct the store path to `bin/hello` and doing partial matches with `assert!()` results in less useful failure messages.
N/A
> test(build): Test result that uses pkg from env

- cli/flox-rust-sdk/src/data/flox_version.rs
- cli/flox-rust-sdk/src/data/mod.rs
- cli/flox/src/commands/mod.rs
The user story that needs sorting of version between channels:
- a user installs flox and is using it
- somehow he learns (we probably tell them) that the feature that they need is being developed and is in a nightly channel
- they switch the channel (in `/etc/flox.toml`) to nightly
- happy user since he doesn't have to wait for a feature
- happy us because we are getting early feedback on the feature
- once the feature is released, they switch back to stable
Currently, switching back to stable might be problematic (depending on when they do it) since we could suggest to downgrade Flox which might leave the user in a state where they can not activate environment (we do and did some migrations).
This PR only solves the sorting portion. Possibility to change channels is coming after this …
> feat: Implement PartialOrd for comparing Flox version

- assets/activation-scripts/activate.d/attach.bash
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/mod.rs
- cli/tests/activate.bats
We currently error for an interactive `flox activate` in our Bash
activation scripts. With upcoming activation changes, Bash won't be
looking at `_FLOX_ACTIVE_ENVIRONMENTS`, it will only decide whether to
start or attach based on whether an environment is already activated
somewhere, which we shouldn't error for.
Move the error to Rust, which is also consistent with the activation
design diagram.
Also add a test as this behavior was not previously covered.
> refactor: error for nested activate in Rust

- CONTRIBUTING.md
- pkgdb/Makefile
**docs(CONTRIBUTING): Testing from Linux container**
Write up my personal notes in case they're useful to anyone else now
that I've done this a few times when working on:
- CUDA support hooks
- Watchdog PID monitoring
- Patching binaries from `flox build`
**fix(pkgdb): Clean .ACTIVATION_SCRIPTS_PACKAGE_DIR**
So that `just clean` catches everything when you need to rebuild from
the same source tree between MacOS and Linux.
N/A
> docs(CONTRIBUTING): Testing from Linux container

- cli/flox-rust-sdk/src/providers/services.rs
- cli/tests/services.bats
- flake.lock
- flake.nix
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/realisepkgs/realise.cc
- pkgdb/tests/buildenv.bats
This bumps
- Nix 2.18.5 -> 2.18.7. The interface for `maybeGetAttr` was changed in Nix commit 2c88930ef298f6804eb9c064ca918aef01fcd2e3. We currently set `forceErrors = true` in one instance, but `forceErrors` was removed. To preserve current behavior, we could catch CachedEvalError and call force()
- process-compose 1.9 -> 1.27.0. We no longer need to pull process-compose from a pinned nixpkgs because the version in nixpkgs stable is new enough.
- [fix(services-tail): stop on final line on stderr](https://github.com/flox/flox/pull/2231/commits/ea95d5c0a11247c41b2f6d3c308c3521f305051c): 
`process-compose logs --tail` immediately prints logs
and then takes about a second to eventually exit.
In order to avoid this unnecessary pause, we utilise the fact
that process compose will print a …
> chore: bump nixpkgs

- cli/Cargo.lock
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/activations.rs
- cli/flox-activations/src/main.rs
Add env_logger to allow printing debug logs from flox-activations. Set
default-features = false to keep size of flox-activations minimal.
Using `nix build .#flox-activations` and `du -ch` of the
`flox-activations` binary, this increases size from 608K to 624K.
We could write our own logging macros, but that doesn't seem worth it to
save a few KB
`tracing` is more complicated than what we need for `flox-activations`
N/A
> fix(flox-activations): use env_logger

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/attach-command.bash
- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/attach-interactive.bash
- assets/activation-scripts/activate.d/attach.bash
- assets/activation-scripts/activate.d/bash
- assets/activation-scripts/activate.d/fish
- assets/activation-scripts/activate.d/start-services.bash
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/activate.d/tcsh
- assets/activation-scripts/activate.d/zdotdir/.zshrc
- assets/activation-scripts/activate.d/zsh
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-activations/src/main.rs
- cli/flox/doc/flox-activate.md
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/activate.rs
- cli/tests/activate.bats
- cli/tests/activate/attach.exp
- cli/tests/activate/attach_runs_profile_twice.toml
- cli/tests/test_support.bash
- package-builder/build-manifest.nix
- pkgdb/Makefile
- pkgs/flox-activation-scripts/default.nix
Use `flox-activations start-or-attach` and `flox-activations set-ready`
to store environment variable diffs rather than _add_env and _del_env.
This introduces attaching; activations of an environment that are
already active don't re-run hooks.
Notes:
- _FLOX_ACTIVATE_FORCE_REACTIVATE was used to force the activation
script to re-run start because the activation script couldn't detect
when the environment store path had changed. Now that start-or-attach
is aware of the store_path for an environment, this isn't necessary.
- Previously we would run start.bash without capturing _start_env or
_end_env because we knew nobody would attach. That's no longer true.
When an environment is activated multiple times before all activations of the environment exit, the environment's hook is only run once …
> feat: use flox-activations to store env files

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
Makes the "Build command did not copy outputs to '$out'" error more visually distinct and conform to CLI style guide
N/A
> fix: more visually obvious build error

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
So that we don't need to repeat the `if panic` dance everywhere.
Currently based on https://github.com/flox/flox/pull/2268 which adds another one of these.
N/A
> refactor(catalog): Move reset mocks to test_helper

- cli/flox-rust-sdk/src/providers/build.rs
- test_data/config.toml
- test_data/generated/envs/go_gcc.json
- test_data/generated/envs/go_gcc/manifest.lock
- test_data/generated/envs/go_gcc/manifest.toml
- test_data/input_data/envs/go_gcc/manifest.toml
This supersedes https://github.com/flox/flox/pull/2234
The original hope was that we would use `autoPatchelfHook` to update the interpreter and linked libraries, from system libraries to store paths, wherever possible.
However it's _hard_ to enumerate all of the possible libraries to package names at the appropriate versions and we discovered cases where it would produce non-functioning binaries if the environment brought its own `gcc`. Possibly because of conflicting `nixpkgs` revisions. Here's an `strace` from the "hang" behaviour that's mentioned in the comment:
- https://gist.github.com/dcarley/a5a1e1c6a8cde7fd1d31ecc1f327e384
So instead we have settled on not modifying the binaries at all and adding a test to prevent regressions against the behaviours we saw.
This new test has also …
> test(build): Go with CGO against libc

- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-watchdog/src/process.rs
Our current update_watchlist logic calls 3 different functions which all check if a PID is still running:
- activation_pids() calls remove_stale_activations()
- prune_terminations()
- watch_new_pids()
The logic to determine if a PID is about to get more complicated (since we'll need to check if an attached PID has expired), so it's preferable to have to update just one thing instead of 3.
Change the algorithm in update_watchlist() such that PIDs are checked to be running just once.
NA
> refactor: simplify update_watchlist logic

- cli/Cargo.lock
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-core/src/activations.rs
- cli/flox-rust-sdk/src/models/env_registry.rs
[refactor: drop dead code](https://github.com/flox/flox/commit/49178bb2295ddd3042788516d0d29683c59e1c04)
ActivationPid::from_current_process and
ActivationPid::is_current_process_parent are unused.
[style: use i32 consistently for PIDs](https://github.com/flox/flox/commit/b624307b5aa69678a8ed9eb2d1917b77d1351427)
We currently use pid_t/i32 for ActivationPid and
PidWatcher::pid_is_running but u32 for AttachedPid. We should be
consistent, and we'll need to use PidWatcher::pid_is_running to check if
an AttachedPid is running.
Use i32 throughout since that's what's used by the libc crate.
Use i32 rather than pid_t since extra imports are annoying.
NA
> Some cleanup of our PID code

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/start.bash
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-watchdog/src/main.rs
- cli/flox-watchdog/src/process.rs
- cli/flox/src/commands/activate.rs
- cli/tests/activate.bats
- pkgs/flox-activation-scripts/default.nix
Start the watchdog from `start.bash` just before `set-ready` is called
so that it's only started once for the first "start" activation and not
the subsequent "attach" activations.
I previously wanted to do this within `flox-activations set-ready` so
that we got some type safety on the command/argument handling and it
would be atomic with the `set-ready` operation. However the need to
make this conditional for direct invocations of `${FLOX_ENV}/activate`,
where we don't currently want to start a watchdog and can't easily
compute all of the arguments (e.g. `--log-dir` when we don't have
`.flox` path), later convinced me to just implement it in Bash.
Passing the path to the watchdog binary in at runtime also ensures that
the watchdog isn't unnecessarily bundled into the closure of …
> refactor(watchdog): Move watchdog to start.bash

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
- pkgs/flox-pkgdb/default.nix
- pkgs/rust-internal-deps/default.nix
`flox build` should use a known and bundled version of nixpkgs, so that a) build issues related to the nixpkgs used do not depend
on the user's environment or change from one environment to the other.
b) builds do not require downloading and unpacking nixpkgs at runtime.
With this change, `flox build` now depends on the same **store path** of nixpkgs as the build of flox itself,
i.e. the `nixpkgs` input of the flox crate.
```
% nix eval --impure
% nix build .#flox
% nix path-info --recursive .#flox
...
/nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source
% flox build
...
nix build [..] --argstr nixpkgs-url path:/nix/store/p2hby44a0qzrnd1vxcpcgfav6160rmcv-source
```
In addition we updated the pkgdb/default.nix to use the same `path:` url, and make both implementations more similar to each …
> build: bundle `nixpkgs` used at build time

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/start.bash
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-activations/src/main.rs
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- cli/tests/activate.bats
- package-builder/build-manifest.nix
- pkgdb/src/libexec/mkContainer.nix
flox-watchdog is going to need runtime_dir. We currently compute runtime_dir in flox-activations, but per
https://github.com/flox/flox/issues/2240 we'd like to factor that out. This is because runtime_dir may be different for each of `flox activate`, `flox build`, and `flox containerize`, so each of those should be able to pass runtime_dir to the activation script.
This commit passes runtime_dir through with an environment variable from the CLI.
There are a few things I don't like about the current approach, but I left as is for the sake of time:
- runtime_dir is added to Flox but not Config. That's because it's sometimes derived from cache_dir, and it seems hard to make a config field depend on another config field. I don't really think we need it in Config, but I still don't like the …
> refactor: set FLOX_RUNTIME_DIR in CLI

- cli/flox-rust-sdk/src/providers/catalog.rs
There was at least one report of a general Catalog Connection Error that was due to a timeout waiting for a resolution response.  Ideally we would improve the performance of the resolution API call, but even then, 15s is somewhat aggressive.
Increase catalog client timeout to 60s.
Made the timeout for catalog service calls longer to address occasional timeouts
> fix: increase catalog client timeout

- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-watchdog/default.nix
- pkgs/flox/default.nix
So that it doesn't get installed to `/usr/local/bin` on MacOS and end up leaking onto `$PATH`. We don't want to expose this to users because they never need to interface with it directly.
My understanding is that `flox-installers` collects up these packages and puts them into `/usr/local`, so that moving it within these packages will have the desired outcome.
⚠️ 
I extrapolated the intent and solution from #2101 but feel free to correct if I've misinterpreted. I'm on leave from the end of today so someone else will need to respond to any feedback and merge in my absence.
N/A, don't think it's worth mentioning.
> chore(watchdog): Move from bin to libexec

- pkgs/nix/default.nix
Temporarily pinning nix at 2.18 while we work to port pkgdb to latest stable (2.24), or replace it altogether.
Confirmed this allows flox to build successfully for each of the current `github:flox/nixpkgs/{stable,staging,unstable}` branches.
N/A
> chore: pin nix at version 2.18

- pkgs/flox-cli-tests/default.nix
When running the test `kills daemon process` locally it fails. This is because flox-cli-tests sets FLOX_WATCHDOG to `flox-watchdog` instead of an absolute path. Our daemonize call in the activation scripts then fails with `The 'path' parameter must be an absolute path name.`
Use `which flox-watchdog` to set an absolute path instead.
NA
> fix: local test failure

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/mod.rs
- cli/flox-rust-sdk/src/models/user_state.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-remote.bats
**feat: prompt to create default environment**
This prompts the user to create a default environment the first time
that they attempt to install a package without an activated environment
and without an environment in the current directory. This choice is
persisted in a new file called `user_state.json`. The field for this
choice is an Option<bool> so we can represent "unprompted" as None, and
the user's choice as Some(value). If the user cancels the operation, no
choice is persisted.
**chore: address clippy lints**
The paperclip was complaining.
**refactor: rename error variant**
The previous name was unclear at the call site. The new name makes it
clear that it's simply a wrapped `EnvironmentError`.
**chore: clarify language in debug msg**
Makes it clear that the packages have not yet …
> feat: prompt to create default environment

- cli/flox-rust-sdk/src/providers/publish.rs
For a PoC, just collect the out paths present in the results location.  It will be assumed the user has done the build already.  This is working towards having a functional end-to-end publish/consume workflow on the local machine only, using storepaths only.
> collect build outputs for publish

- cli/tests/services.bats
- flake.lock
Notably this includes a newer version of nixpkgs that has https://github.com/flox/nixpkgs/commit/d0b33648223427e635df7336097f8732764d3419
• Updated input 'crane':
'github:ipetkov/crane/96fd12c7100e9e05fa1a0a5bd108525600ce282f' (2024-08-31)
→ 'github:ipetkov/crane/a4ca93905455c07cb7e3aca95d4faf7601cba458' (2024-11-03)
• Updated input 'fenix':
'github:nix-community/fenix/0774f58cf1025bbb713971deecc7f07c856be6ed' (2024-09-02)
→ 'github:nix-community/fenix/fa3610f841725c8e20fc0fab070ee60609fdd5ee' (2024-11-04)
• Updated input 'fenix/rust-analyzer-src':
'github:rust-lang/rust-analyzer/779d9eee2ea403da447278a7007c9627c8878856' (2024-09-01)
→ 'github:rust-lang/rust-analyzer/e44691a60443f1246a077df659607ca89f2ddc58' (2024-11-03)
• Updated input 'nixpkgs': …
> chore: nix flake update

- cli/flox/doc/flox-config.md
- cli/flox/src/commands/activate.rs
This more closely matches the behavior of a system package manager
- Hide default environments from shell prompts by default
> fix: hide default prompt by default

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/attach-command.bash
- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/attach-interactive.bash
- assets/activation-scripts/activate.d/bash
- assets/activation-scripts/activate.d/fish
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/activate.d/tcsh
- assets/activation-scripts/activate.d/zdotdir/.zshrc
- assets/activation-scripts/activate.d/zsh
- cli/Cargo.lock
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/tests/activate.bats
- cli/tests/test_support.bash
- package-builder/flox-build.mk
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
**feat: update activation scripts on new version**
This makes a change to how activation scripts are stored and used. Now
every flox CLI will bundle its own activation scripts that it will use
to activate environments instead of the ones stored in the rendered
environment. New environment builds will store the activation scripts
that are bundled with the CLI.
This behavior serves two purposes:
- It allows the latest activation scripts to be used without rebuilding
the environment.
- It allows you to fall back to the activation scripts that were current
at the time the environment was built.
This also introduces a naming change. The activation scripts are now
referred to as the `flox-interpreter` since they "interpret" and execute
the rendered environment.
**chore: disable set -e for now …
> feat: apply latest activation scripts without rebuild

- .github/workflows/nix-managed-lints.yml
Incorrectly formatted commit messages (i.e. commit messages
that are not complying with conventional commits' format,
will now _actually_ cause failures of the "Project Lints / Nix Git Hooks" Job.
These failures will look as the one below.
Previously we checked the commit range `<PR target branch>..HEAD`.
However, in `pull_request` events `HEAD` will point to a _detached merge commit_,
or otherwise independent history,
such that commitizen never actually got to checked the correct git history.
This commit changes the action to instead use `github.head_ref` (`pull_request` events)
or `github.events.merge_group.head_ref` (`merge_group` events).
```
TARGET_REF: refs/heads/main (abe3a55d415974cedaa014d13a588cfbadba3417)
HEAD_REF: refs/heads/ci/message-lints-2 …
```
> ci: fix git commit message checks

- pkgdb/src/libexec/mkContainer.nix
Use "now" as the timestamp.
- use a reasonable timestamp
> feat: use 'now' as the creation timestamp

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/main.rs
This prompts the user whether they would like us to add an automatic activation of the default environment to their shell's RC file. We look in the standard locations for the RC files, creating one if it doesn't exist, making a backup before writing to it, and finally append an in-place activation line to their RC file.
When users are prompted whether they'd like Flox to create a `default` environment for them, they are also asked whether they'd like Flox to append a line to their shell's RC file to automatically activate the `default` environment in every new shell.
> feat: auto add activation for default env

- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/start.bash
- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-activations/src/lib.rs
- cli/flox-activations/src/main.rs
- cli/flox-core/src/activations.rs
- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-watchdog/Cargo.toml
- cli/flox-watchdog/src/main.rs
- cli/flox-watchdog/src/process.rs
- cli/tests/activate.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/init.bats
- cli/tests/pull.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
- cli/tests/watchdog.bats
- flake.nix
- pkgs/flox-cli-tests/default.nix
Instead of using the environment registry to control when activations
are cleaned up, use activations.json
Removes the `activations` field of registered environments
in the environment registry file.
Effectively, the corresponding information is lost 
when switching back to a previous version of flox.
> feat: use activations.json in flox-watchdog

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/user_state.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
**feat: add XDG_STATE_HOME to store user data**
There is data that isn't critical, but that shouldn't be freely deleted
like data in the cache directory. This data belongs in the
XDG_STATE_HOME directory, which is `~/.local/state` on most systems.
**refactor: move user state file to state dir**
N/A
> refactor: move user state to state dir

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/publish.rs
This is an incremental update to the publish workflow, and only makes the calls into the catalog provider.  The actual calls to the service are not yet implemented, nor is there any CLI command to invoke any of this code.  There are separate PRs in progress for wiring up a new `flox publish` to this code, and to implement the calls to the catalog service (with it's own PRs and updates).
> feat: publish collected package metadata

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox/src/utils/openers.rs
- pkgs/rust-external-deps/default.nix
We're currently refreshing sysinfo for all processes instead of just one in get_parent_process_exe(). Update our sysinfo crate and get process info for just the parent process we're interested in.
Updating sysinfo required adding darwin.libobjc since a dependency on objc was added upstream in https://github.com/GuillaumeGomez/sysinfo/commit/5f78295b50c3e604d71f18fb45b5013b7b0d9f5f
Before this change, get_parent_process_exe() benchmarks were:
Duration: 9.639049208s
Duration: 64.236333ms
Duration: 8.124838292s
Duration: 676.244542ms
Duration: 6.660007916s
avg duration: 5.032875258s
min duration: 64.236333ms
max duration: 9.639049208s
I killed a bunch of processes I had running, and then benchmarks were:
Duration: 11.099875ms
Duration: 6.176417ms
Duration: 5.539125ms
Duration: 10.232542ms …
> fix: only get info for parent process

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/utils/errors.rs
- cli/tests/activate.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/install.bats
Using `DisplayCommand` can be used to print a copy-pastable shell command.
So far this only included arguments.
However some commands _also_ set or unset environment variables,
which is currently not visible in the logs.
This commit makes `DisplayCommand` print an invocation in the form of
[env (-u VAR | VAR=VALUE) ... ] CMD ARGS...
if either `Command::{env,envs}`,  or `Command::env_remove` was used on the printed command.## Proposed Changes
> Symlink extra buildenv outputs into ".flox" directory

- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/attach-command.bash
- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/attach-interactive.bash
- assets/activation-scripts/activate.d/bash
- assets/activation-scripts/activate.d/fish
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/activate.d/tcsh
- assets/activation-scripts/activate.d/zsh
- assets/activation-scripts/etc/profile.d/0100_common-paths.sh
- cli/tests/activate.bats
- cli/tests/activate/verify_PATH.bash
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-cli-tests/default.nix
Make changes needed in Bash activation scripts to support run mode. This
commit adds a `[ --mode (run|dev) ]` option. It is never used and
defaults to `dev` which is the current behavior.
Run mode only modifies PATH and MANPATH. The method for setting PATH and
MANPATH was changed to always prepend all items in FLOX_ENV_DIRS to
MANPATH and PATH rather than using add.env and del.env. This is to allow
nested activations; without this change `flox activate -d 1` in one
shell followed by `flox activate -d 2 && flox activate -d 1` in another
would blow away the changes to PATH made by the `flox activate -d 2`
command.
Run mode now supports nested activations
> feat: prep Bash changes needed for run mode

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/services/mod.rs
- cli/tests/activate.bats
- test_data/config.toml
- test_data/generated/resolve/almonds.json
This makes the `--mode` flag actually change which environment closure
is used to activate the environment.
Users can now pass the `--mode/-m (dev|run)` flag to `flox activate`, which will choose how an environment is activated. The default is `dev` and is the same as the previous behavior. The new behavior is used when `-m run` is used. This mode will only put the manifest's package in `PATH` (and not their development dependencies), and won't set certain environment variables that are necessary for development.
> feat: activate in runtime mode

- package-builder/flox-build.mk
Move the check for `FLOX_INTERPRETER` to the local build template
because we don't need an intepreter for clean and it was causing it to
fail as follows.
This wasn't caught by the unit tests and is hard to test the unhappy
path because we inherit `FLOX_INTERPRETER` set by the `devShell`.
[0] stahnma@floxbox01 ~/go/src/github.com/stahnma/vhs[main] > flox --version
1.3.3-212-gad7d08c7
[0] stahnma@floxbox01 ~/go/src/github.com/stahnma/vhs[main] > flox build
make: Entering directory '/Users/stahnma/go/src/github.com/stahnma/vhs'
Rendering vhs build script to /var/folders/sc/rddkr3kd2vg1k1qmy_cx1q900000gn/T//c807b616-vhs-build.bash
Building vhs-0.0.0 in local mode
MAKEFLAGS= out=/tmp/store_c807b616551b1981b89b913162867434-vhs-0.0.0 /nix/store/2ba0172z86znj5jp28rnl3i5gm7x7izl-flox-activation-scr …
> fix(build): Don't check FLOX_INTERPRETER for clean

- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
To suppress this message that I saw when running `flox edit` from a remote env after upgrading past bc3e3120:
[flox-rust-sdk/src/models/environment/remote_environment.rs:113:17] "removing symlink" = "removing symlink"
`dbg!` sends straight to STDERR whereas `debug!` honours the tracing level. Including the `gcroot` will make it clearer what's being removed.
N/A, if included in 1.3.4
> fix(env): Replace dbg! with debug!

- assets/activation-scripts/activate
- cli/tests/activate.bats
PR #2342 implemented code to remove duplicates in the PATH and MANPATH variables which had the effect of dropping the trailing ":" character from the MANPATH. This patch fixes that by updating the deduplication logic to ensure that a newline is appended following a trailing colon and recognised as a valid [otherwise empty] array element.
N/A - just a bugfix of a release candidate
> fix: preserve trailing colon in MANPATH when removing duplicates

- .github/workflows/ci.yml
Disable `aarch64-darwin` builds whilst we figure out how to get the machine back online.
> Temporarily disable `aarch64-darwin` builders

- buildenv/builder.pl
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
And a fix for a regression in builder.pl to default to all the outputs if outputs_to_install is missing at that level.
> fix: add missing outputs_to_install

- cli/Cargo.lock
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/delete.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
Use enum_dispatch to implement Environment for ConcreteEnvironment. It makes sense for us to use enum_dispatch rather than trait objects since:
- We have a limited number of types that implement Environment (3)
- Sometimes we want to preserve a concrete type
- There are some limitations on how trait objects can be used in combination with generics
NA
> refactor: impl Environment for ConcreteEnvironment

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
Check if the expected symlinks have been created by the manifest
builder, and if they do, print them to the user. Shorten current
directory to `.`.
Example output:
```
✨ Build completed successfully. Output created: ./result-hello
```
Example with multiple packages not in current dir:
```
✨ Builds completed successfully.
Outputs created: /private/tmp/result-hello, /private/tmp/result-hello2
```
All changes behind a feature flag
> feat(build): print paths to build outputs

- cli/tests/activate.bats
Running the tests in `Terminal.app` on Darwin caused this failure
because it loads customisations from `/etc/bashrc_Apple_Terminal` that
affect the output:
-- values do not equal --
expected : 7
actual   : 9
--
Last output:
Sourcing .profile
Setting PATH from .profile
sourcing hook.on-activate
Sourcing .bashrc
Setting PATH from .bashrc
sourcing profile.common
sourcing profile.bash
Saving session...completed.
Deleting expired sessions...none found.
Disable it by the means suggested in that file. I tried setting
`SHELL_SESSION_HISTORY=0` but that didn't change this behaviour.
I don't particularly care for `Terminal.app` but I occasionally reach
for it instead of `Kitty.app` when I want to bypass my default Flox
environment because it's causing problems like …
> test(activate): Workaround bashrc_Apple_Terminal

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
Only `CoreEnvironment::lock` and `upgrade` write lockfiles at all.
`lock` is already using `to_string_pretty`, while `upgrade` uses `json!(...).to_string()` [1] which will write the condensed format.
Change `CoreEnvironment::upgrade` to write a formatted json document instead.
[1]
https://github.com/flox/flox/blob/e54d776d24764d358e381f02d9ef80127ac99f02/cli/flox-rust-sdk/src/models/environment/core_environment.rs#L679-L681
Lockfiles are now always pretty printed for better visibility in git diffs.
> chore(upgrade): pretty print upgraded lockfile

- assets/activation-scripts/activate.d/start.bash
- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-watchdog/Cargo.toml
- cli/flox-watchdog/src/logger.rs
- cli/flox-watchdog/src/main.rs
- cli/flox-watchdog/src/process.rs
- cli/tests/activate.bats
- cli/tests/services.bats
- cli/tests/watchdog.bats
The watchdog was emitting log lines at a rate of 10Hz in some cases, which quickly generates enormous log files. This reduces the log level of the two offending lines and allows a user to override the log level of the watchdog (mostly for testing purposes).
Flox will use less disk space for log files.
> feat: reduce log output

- package-builder/flox-build.mk
It is really useful to be able to tune makefile verbosity in response to the `flox -v` verbose flag, and this commit introduces 3 new macros for this purpose, defined as in this pseudo-code:
```
_V_ = $_FLOX_PKGDB_VERBOSITY > 0 ? "" : "@"
_VV_ = $_FLOX_PKGDB_VERBOSITY > 1 ? "" : "@"
_VVV_ = $_FLOX_PKGDB_VERBOSITY > 2 ? "" : "@"
```
The end result is that we can preface any line in a makefile stanza with `$(_V_)` and make will only report that invocation if flox has been invoked with `-v`. Similarly a line starting with `$(_VVV_)` will only be reported if flox has been invoked with `-vvv` (or more).
N/A
> feat: define flox-build.mk verbosity macros based on $_FLOX_PKGDB_VERBOSITY

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
The source tarball target was employing `$(git ls-files)` to get the source manifest, but when this failed the invocation would successfully generate an empty tarball rather than failing. TIL that you need to follow a process substitution with a call to `wait $!` in order to get the desired behaviour!
Having fixed the bug, also needed to add invocations of `GitCommandProvider::init` to the rust build tests so that it doesn't crash when performing a sandbox build from a git-less directory.
N/A
> fix: propagate error from process substitution in flox-build.mk

- buildenv/buildenv.nix
- buildenv/builder.pl
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox/src/commands/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-buildenv/default.nix
Following the recent buildenv replacement we now build dedicated closures for each manifest build package. This patch updates the builder to wrap files in bin and sbin with this new closure instead of the original $FLOX_ENV closure used to perform the actual build.
N/A (manifest builds not yet a published feature)
> feat: wrap manifest build executables with build-specific env

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
since we only wrap binaries in `$out/bin` and only expose those on the PATH, the hint message used to be somewhat misleading,
asking users to copy binaries to `$out`.
This changes the hint to direct users to create and copy to `$out/bin` instead.
> chore: improve message for missing `$out`

- cli/flox-watchdog/src/logger.rs
Ensure that old-style logs, from before we introduced log rotation, are
still cleaned up. This is particularly important after the logging
regression in v1.3.4 which caused the logs to grow very large.
I realised this while writing the release notes for v1.3.5
To include this in the v1.3.5 release (https://github.com/flox/product/issues/819) we'll need to:
- add a note to the existing draft about exiting all activations if you notice previous problems with v1.3.4
- cherry-pick to the `release-1.3.5` branch and replace the `v1.3.5` tag which hasn't been "fully published" yet
> fix(watchdog): GC old watchdog.*.log pattern

- assets/activation-scripts/activate
- assets/activation-scripts/etc/profile.d/0800_cuda.sh
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-core/src/activations.rs
- cli/flox-watchdog/src/main.rs
- cli/flox-watchdog/src/process.rs
- cli/tests/activate.bats
- cli/tests/cuda.bats
- cli/tests/cuda/ldconfig-mock-error.sh
- cli/tests/services.bats
Add a mechanism for requiring users to exit existing activations when
using an incompatible version of `flox-activations`. We can bump this
version when making breaking changes to activations, such as introducing
new environment variables between the CLI and interpreter.
By implementing this in `flox-activations` it also prevents services
from being started because they use an ephemeral activation which goes
through the same code path.
It's worth noting that because the version is applied to the root of
`activations.json` that it will catch all activations of all store paths
for an environment. It will not however catch different runmodes of an
environment because they use different `activations.json`, per 2357.
We are not going to add any checks for old non-attach style activations …
> feat(activate): Warn on incompatible activations

- cli/flox/src/commands/push.rs
State that new environments are public by default and give a URL where they can navigate to settings (as well as promoting other view/edit options) whilst still giving us us the flexibility to change in FloxHub which environments can be made private, both now and again in future.
I briefly looked at converting these to use `env.floxhub_url` but then got lost in a rabbit hole of what to print when `join()` fails and whether we should promote the URL for all messages, so I've deferred that for now.
N/A
> chore(push): Generalise FloxHub editing message

- cli/Cargo.lock
- cli/Cargo.toml
- cli/tests/environment-remote.bats
**chore(cargo): Disable config crate default feats**
In preperation for downgrading the `config` crate to fix a bug. The
changes to the lock file are easier to read if we don't have these
unused dependencies, because we only parse config from TOML.
**fix(remote): Honour trust for case sensitive envs**
The `config` crate introduced a regression in 0.14.0 (which we upgraded
to in 6588ba7) whereby all keys are lowercased. This isn't configurable
And doesn't look like it will be "fixed" any time soon, so we're
downgrading to 0.13.4 which was the last release before the change.
The removal of unused features in the preceding commit makes this pretty
simple and low risk in terms of introducing CVEs from downgraded
transient dependencies.
This prevented us from honouring saved trust choices for …
> fix(remote): Honour trust for case sensitive envs

- cli/tests/floxhub-cross-systems.bats
This was using the FloxEM application and authenticating as the
superuser "floxEM", but now uses a dedicated testing app that
authenticates as "flox", a user with no special permissions.
> chore: Update client id for floxhub tests

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- pkgdb/src/main.cc
[fix: don't conflate --quiet with no verbosity flag](https://github.com/flox/flox/commit/11507c1124745166b36872dd7c493a15f4c58782)
Currently Verbosity::to_pkgdb_verbosity_level() returns 0 for both Quiet
and Verbosity(0), which correspond to `flox --quiet` and `flox` which
should actually be treated differently.
Return -1 instead for Quiet and update pkgdb accordingly.
Also to_pkgdb_verbosity_level -> to_i32 since this will be used in the
build module in Rust.
[style: review suggestions](https://github.com/flox/flox/commit/1ce2df26b142f1ea44b1599916b20284d87af686)
Thread verbosity through to build module rather than using the PKGDB env
var
> Review suggestions for 2410

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- package-builder/flox-build.mk
- pkgdb/src/main.cc
Following the addition of the makefile verbosity macros, use them to improve the signal-to-noise ratio of the text coming out of manifest builds. This is just an initial stab to get the ball rolling; I don't doubt there will be further modifications to follow.
N/A
> chore: tweak manifest build verbosity

- cli/tests/activate.bats
- cli/tests/cuda.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/lang-python.bats
- cli/tests/services.bats
- cli/tests/setup_suite.bash
- cli/tests/suite.bats
Use `bashInteractive` from `flox-cli-tests` rather than leaking `SHELL` from the user running the tests.  This surprised me when writing a `flox activate` test that made use of `export -f` because it was defaulting to my `zsh` shell. Without the change to `setup_suite.bash` the new test fails for me with:
✗ suite: should default to bashInteractive [1006]
tags: activate
(from function `assert_output' in file /nix/store/h7inz07x6739s38i02532g5pj6dlnx8k-bats-with-libraries-1.11.0/share/bats/bats-assert/src/assert_output.bash, line 178,
in test file activate.bats, line 200)
`assert_output --regexp "$EXPECTED_OUTPUT"' failed
✨ Created environment 'project-1' (aarch64-darwin)
Next:
$ flox search <package>    <- Search for a package
$ flox install <package>   <- Install a package into an …
> fix(tests): Default SHELL to bashInteractive

- buildenv/buildenv.nix
- buildenv/builder.pl
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
- cli/flox/doc/flox-install.md
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/tests/edit.bats
- cli/tests/install.bats
- pkgdb/include/flox/realisepkgs/realisepkgs-lockfile.hh
- pkgdb/src/realisepkgs/realise.cc
- pkgdb/src/realisepkgs/realisepkgs-lockfile.cc
* Add `ManifestPackageDescriptorStorePath` to the supported `ManifestPackageDescriptor` enum.
* add `LockedPackageStorePath` type and declare it as a `LockedPackage` variant
* locking: collect StorePath descriptors, and map to `LockedPackageStorePath`
Since store paths are locked by definition,
collection can directly map the descriptor to a locked package.
Establish a concrete priority when locking packages, such that `buildenv`
can expect priority to be set.
* parse and validate locked store paths
Test that manifests with a nix build store path build into an environment
* Add a `StorePath` variant to `PackageToInstall`
* implement `StorePath::parse`
Parse a path doing minimal validation that the path is in `/nix/store` or a symlinked path in `/nix/store`.
Remove extraneous path …
> feat: install by store paths

- cli/tests/activate.bats
To help debug this failing test where the existing activation hadn't exited:
- https://github.com/flox/flox/actions/runs/11956889846/job/33332714048#step:8:256
I haven't been able to reproduce this locally or with 100 runs in CI:
- https://github.com/flox/flox/actions/runs/12029821849/job/33535905317
My hunch is that the watchdog hadn't started by the time that `wait_for_watchdogs` was called, which allows it to proceed immediately, but it could also be that there was an error during cleanup. This should give us information about either case.
Unfortunately we don't currently distinguish between tests that use `wait_for_watchdogs` to guard against the suite failing vs tests that depend on the watchdog being started and/or finished.
N/A
> test(activate): Capture watchdog logs

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
[fix: don't always rebuild remote environments](https://github.com/flox/flox/commit/810421f09940686be64690927e4614a8a96f3504)
Currently every `flox activate -r` triggers a rebuild of the
environment, which is slow.
This is happening because RemoteEnvironment::new_in runs a force pull of
the underlying ManagedEnvironment.
There's currently a logic error in pull where force pulls don't check if
an environment is up to date, so a force pull returns
PullResult::Updated even when it should return PullResult::UpToDate.
Coincidentally, this leads to calling
reset_local_env_to_current_generation(), which changes the mtime of the
manifest, which causes ManagedEnvironment::rendered_env_links to call
build().
To fix this, check if the environment is up to date for force pulls in
the same way as …
> Fix remote environment flakey tests

- cli/flox-rust-sdk/src/providers/buildenv.rs
- pkgdb/include/flox/core/nix-state.hh
This allows a user to override the Nix store via the _FLOX_NIX_STORE_URL variable. This is done in both `pkgdb realise` and on the Rust side. The Rust side happens in `BuildEnvNix::base_command` by reading the environment variable, which we typically don't allow in the SDK. I'm doing it now to unblock another developer and this code will be superseded by another ticket in the very near future.
N/A
> feat: allow overriding Nix store

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
`flox publish` now accepts an optional `--cache` flag to specify a cache location for published artifacts, as well as a `--key-file` flag to specify a signing key. If `--cache` is specified, artifacts are signed with the given key and  `nix copy`'d to the cache. The cache location is also sent to catalog-server along with the rest of the build metadata, so that later installs of the package will know where to retrieve it.
This introduces a new `BinaryCache` trait to encapsulate the cache behavior and allow for easy mocking during testing.
> feat: Upload published packages to specified cache

- cli/flox/src/commands/lock_manifest.rs
- cli/flox/src/commands/mod.rs
Adds a new hidden and strictly internal command `flox lock-manifest`,
that allows locking of a manifest, separately from an environment.
With `--lockfile` allows to specify a base lockfile. This command _only_ locks
and never builds the resulting lockfile, which makes it useful for generating test data,
in particular for the use with the environment building subsystem.
> feat: add `lock-manifest` command

- .github/workflows/nix-managed-lints.yml
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- flake.lock
- pkgs/pre-commit-check/default.nix
For a while when we run the git hooks, on push and commit,
the following warning was displayed:
```
[WARNING] hook id `clang-format` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] hook id `clippy` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] hook id `nixfmt-rfc-style` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] hook id `rustfmt` uses deprecated stage names (push) which will be removed in a future version.  run: `pre-commit migrate-config` to automatically fix this.
[WARNING] …
```
> ci: update git-hooks.nix flake and migrate push hook to pre-push

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
In the Nix sandbox $HOME is usually set to `/homeless-shelter`, does not exist, and cannot be written to.
In turn, any tool attempting to write to $HOME will experience errors to do so. We set $HOME to another writable location in the sandbox, to ensure such errors do not occur.
See also: <https://github.com/flox/flox/issues/2092>
> feat(build): set `HOME` to a writable directory in the build sandbox

- cli/flox/src/commands/edit.rs
From ticket:
> If you copy a manifest from one environment to the other and it
> happens to be sizeable, building that environment could take a
> non-trivial amount of time. We're missing a spinner for this
> operation, and there's otherwise no output at all during this
> operation, so a user would reasonably expect that Flox has frozen.
Implemented by refactoring the existing spinner that used by
`interactive_edit` into a separate function and calling that for the
"non-interactive" case to make it clear that they share the same actions
and use a spinner.
Since we can't test interactive spinners (and despite asciinema stripping the rotating part)..
Before:
After:
`flox edit -f` now shows a spinner to indicate when it's building an environment.
> feat(edit): Show spinner for edit -f

- cli/flox/doc/flox-edit.md
- cli/flox/src/commands/edit.rs
- cli/flox/src/utils/errors.rs
It was easier to write the proposed changes than create and refine a ticket for this small change.
The error and the docs confuse me each time I run into them because I'm not immediately sure about which direction the sync or reset are operating and I don't have to interact with the concept of generations very often.
Attempt to clarify this by using the terms "commit" and "discard" from the perspective of local only, which is where the changes have originated from and what the user may lose. This doesn't appear to conflict with the original design in:
- https://github.com/flox/flox/issues/680
I've omitted the "after modifying manifest.toml" part because by definition the manifest has already been modified when you've reached this error and we don't have any notion of conflict resolution …
> docs(edit): Clarify docs for --sync and --reset

- cli/flox/src/commands/install.rs
On macOS every shell is started as a login shell, which is different from many Linux distributions. This means that the recommendation to put the default environment activation in `.bashrc` will not activate the default environment since Bash only loads `.profile` for login shells, not `.bashrc`. To address this we put the activation line in both scripts.
No tests were added because we already have tests for verifying that individual RC files were modified, but the new functionality and messaging was verified interactively.
On macOS when you're prompted to create a `default` environment if you're using Bash then you will be prompted to modify both `.profile` and `.bashrc`. On macOS new shells are created as login shells, and therefore Bash doesn't load `.bashrc` in that case. This fix …
> feat: recommend .profile for default env

- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
We're considering this stable after adding `--tag` and `--runtime` support, with macOS support following in #2478.
Accompanying change in https://github.com/flox/floxdocs/pull/99 but this can be merged ahead of time.
`flox containerize` is no longer marked as experimental.
> feat(containerize): Mark non-hidden/experimental

- assets/activation-scripts/activate.d/zdotdir/.zlogin
- assets/activation-scripts/activate.d/zdotdir/.zprofile
- assets/activation-scripts/activate.d/zdotdir/.zshenv
- assets/activation-scripts/activate.d/zdotdir/.zshrc
- assets/activation-scripts/activate.d/zsh
- cli/tests/activate.bats
- pkgs/flox-cli-tests/default.nix
Rather than generating a startup script as for Bash in https://github.com/flox/flox/commit/f623518b0a2b912db7cd95f8201b5ecdf941252f, extend
the approach added to .zshrc in https://github.com/flox/flox/commit/52df88e4cc2454d52b78d0aa2f183e779da57f0e that saves and restores
variables used in activation. Extend it to other zsh startup files, and
also add _FLOX_RESTORE_PATH, _FLOX_RESTORE_MANPATH, and
_FLOX_ACTIVATION_PROFILE_ONLY to the save and restore logic.
The current approach could be improved by:
improved by:
- looping over variable names
- sourcing a common file and function from all 4 scripts
Respect _FLOX_ACTIVATION_PROFILE_ONLY in the zsh startup script, similar
to what was added for Bash in https://github.com/flox/flox/commit/fa6601645c5723ce135b366695782d761f0d3795.
Fix the two …
> fix(activate): nested activations for zsh

- .github/actions/common-setup/action.yml
- .github/workflows/ci.yml
Currently, when selecting a remote builder to run tests on, or build against, we always select the one at top of the list. This isn't really taking full advantage of our infrastructure, since we offer multiple machines for all architectures currently.
This introduces a `shuf` before we select the builder.
Refs: flox/deltaops#375
> Shuffle remote builders

- cli/flox/src/commands/install.rs
Bug:
- We put the eval .. line in ~/.zshenv
- path_helper on macOS runs after that, so /usr/loca/bin isn't even in PATH yet
- flox isn't found
- Even if it was found, all of the stuff flox adds to PATH would be put at the end of PATH by path_helper
Solution:
- Put the `eval` line in both `.zshrc` and `.zprofile`
- This doesn't cover the case of a non-login non-interactive shell (which is only possible on Linux).
- We acknowledge that case and hope that a user running a command this way will already have
the default environment active in the shell running the command.
> fix: zshenv -> zshrc zprofile

- cli/flox-rust-sdk/src/data/flox_version.rs
- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- cli/tests/containerize.bats
By using the proxy container approach from:
- https://www.notion.so/floxdev/012-Containerize-cross-platform-14a744c8e3168090b508dafd1fc9f37d0
This has some rough edges which we'll polish later..
The proxy container has to fetch/build store paths on every run. We can
reduce this time by caching/persisting the proxy container in #2469. It
may also be desirable to separate the build of the Flox flake from the
build of the environment for better feedback, but it's not worth doing
that until we refactor for caching.
Testing has only been done manually so far because we don't have a
functioning Docker or Podman in CI. This will be covered in #2466.
Output from `nix run` interleaves the "Writing container" spinner but it
does give some useful feedback about why it might be slow and is
consistent …
> feat(containerize): Add support for macOS

- cli/Cargo.lock
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/utils/init/catalog_client.rs
The first commit refactors the `init_catalog_client` code to use a configuration struct.  This is passed to the catalog client new function to actually create the client, and also saves the config along side the client.  This allows a new client to be created with the config adjusted based on the original config without requiring the global `Config` object to be around.
The second commit creates a new client in the `login_flox` function with the new token.
> Ensure catalog client uses the new token after ensure_floxhub_token

- .gitignore
- Justfile
- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/start.bash
- buildenv/buildenv.bash
- flake.nix
- pkgdb/Makefile
- pkgdb/src/buildenv/realise.cc
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-activations/default.nix
- pkgs/flox-buildenv/default.nix
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-package-builder/default.nix
- pkgs/flox-watchdog/default.nix
- pkgs/rust-internal-deps/default.nix
- shells/default/default.nix
Out codebase has grown multiple subsystems that are depended on by flox or depend on other subsystems themselves.
E.g. `flox -> pkgdb -> flox-activation-scripts -> flox-activations` for one of the worse ones. On the one hand it is important to be able to build final artefacts of each individual subsystem with nix to allow for better build caching if nothing else. Nix also makes defining these dependencies relatively easy through e.g. string contexts.
However, since our devshell is derived from _the inputs of the toplevel binaries_, the naive approach results in
1. all dependencies being built upon entering the devshell
2. the devshell being in accessible while any dependency fails to build
3. the devshell being stale as soon as any dependency changes -- requiring us to reenter the …
> build: consume internal dependencies by dynamic path in devshells

- cli/flox/src/commands/install.rs
We've added a full tutorial with more information about the default environment and want to link that page in the prompt about the default environment.
Closes https://github.com/flox/flox/issues/2510
Minor: updated a link to point at a new docs page
> docs: update link to default environment tutorial

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/tests/upgrade.bats
When trying to upgrade a single installed flake and addressing it by install id, `flox` insists that the install id does not exist.
```
flox install github:nixos/nixpkgs#hello
flox upgrade hello
```
Expected:
```
ℹ️  No packages need to be upgraded in environment 'test'.
```
Expected (alternative):
```
⬆️  Upgraded 'hello' in environment 'test'.
```
Actual output:
```
❌ ERROR: no package or group named 'hello' in the manifest
```
This was caused by `pkg_or_group_found_in_manifest` returning `false` early for all descriptors but catalog descriptors (assumably due to only them supporting groups and not taking ids into account).
This commit ensures that we still check against ids for other descriptors.
`flox upgrade` can now upgrade packages installed from flakes by install id. (fixes #2463)
> fix: do not return early with `false` if iid  is not a catalog package

- Justfile
It depends on `flox` to generate and manipulate environments. So it wouldn't work on a fresh checkout or, in the case where I noticed, everything wasn't rebuilt after 083abecb:
% just gen-data -f
~/projects/flox/flox/cli ~/projects/flox/flox
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
~/projects/flox/flox
~/projects/flox/flox/test_data ~/projects/flox/flox
Error: failed while executing jobs
Caused by:
0: failed to execute job: node_yarn
1: cmd failed
2: ❌ ERROR: Failed to build environment:
Failed to constructed environment: error: getting status of '/Users/dcarley/projects/flox/flox/build/flox-buildenv/buildenv.nix': No such file or directory
N/A, development only.
> fix(Justfile): gen-data depend on build-cli

- cli/flox/src/main.rs
Currently the logger is initialized after `set_user` which means that
`warn!` in `set_user` doesn't respect `--quiet`.
This meant there was no way to silence the warning:
```
WARN flox: cannot determine effective uid - continuing as user 'floxfan'
```
Move `init_logger` before `set_user` so that `--quiet` is respected.
Warnings about determining effective uid now respect `flox --quiet`
> fix: init_logger sooner

- cli/tests/activate.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/init.bats
- cli/tests/pull.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
- cli/tests/watchdog.bats
Prevents `wait_for_watchdogs` from swallowing output and makes an offending test more reliable.
This is best reviewed commit-by-commit because each one contains more detail in the commit message.
N/A, tests only
> test(services): Fix flakey watchdog tests

- Justfile
- flake.nix
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-buildenv/default.nix
Even in dev builds building `flox-buildenv` resulted in a nix build of the `flox-activation-scripts` package, which we aim to avoid.
This commit removes the dependency on `flox-activation-scripts` in builds of the `floxDevelopmentPackages.flox-buildenv`, in which case `flox-buildenv` will depend on `$FLOX_INTERPRETER` at runtime.
This is achieved by "baking in" an absolute path to `flox-activation-scripts` into `buildenv.nix` as well as `flox-activations` into `flox-activation-scripts`.
It's no coincidence that both used to be meant to be loaded from the environment _at runtime_.
However, `flox-activation-scripts` is also a part of manifest builds, in which case the `FLOX_ACTIVATION_SCRIPTS` or respectively the `FLOX_INTERPRETER` variables would be unavailable (particularly when …
> build(buildenv): drop dependency on flox-interpreter in dev builds

- pkgs/rust-internal-deps/default.nix
The path to the `mkContainer.nix` script was compiled into the flox binary starting with https://github.com/flox/flox/pull/2473. However, upon inspection of the closure,
the corresponding store path does not seem to be part of the closure itself.
Adding `flox-mk-container` to the package closure explicitly via `propagatedBuildInputs`.
> fix: ensure `mkContainer.nix` is in the closure of flox

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
Refactor code for publish to use `nix derivation show` on the `realpath` of the output link from the build to gather all the info used to publish to the catalog.
> feat: use nix to get derivation info for publish

- assets/activation-scripts/activate.d/start.bash
- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
See commits
I didn't add tests because that would purely be checking podman and Docker behavior. Since we don't ship a version of podman or Docker there's also not an obvious version to test. But if behavior changes in either of those tools we would regress
Cleaning up the volume (and docs in the manpage) will come in a followup.
`flox containerize` is now faster on macOS as `/nix/store` is cached across `flox containerize` invocations. Flox now creates a podman or Docker volume named `flox-nix`; it can be removed.
> cache /nix/store for macOS container builder

- cli/flox/doc/flox-containerize.md
Describe `flox-nix` volume used to cache files between runs of the `flox containerize` proxy container, and document commands to delete it.
On macOS, `flox containerize` now uses a `podman` or `docker` volume named `flox-nix` to cache data. It can be deleted whenever `flox containerize` is not running.
> docs: add note about proxy container volume

- .github/actions/common-setup/action.yml
A major release including faster failing if curl fails and a newer tailscale version gets installed by default.
Refs: https://github.com/tailscale/github-action/releases/tag/v3
> Upgrade tailscale/github-action

- cli/flox/src/utils/init/logger.rs
- cli/flox/src/utils/message.rs
Dan found that for some commands the spinners would not be completely cleared before the command would print a message.
This issue appeared especially with `Span::in_scope` constructs:
```rust
let span: Span = ...;
span.in_scope(||{ ... });
```
While the "spinning status" correctly matches the scope, the spinner is not cleared, as the scope ends,
but on `Drop` of the span.
Dropping the span explicitly resolves this.
However, keeping span lifetimes in mind is easy to miss,
both in this PR as well as in future additions of spinners.
Alternatively, we can use an `IndicatifWriter`,
which will clear spinners for us to print logs or messages.
The most well integrated way to do so is by setting an `IndicatifWriter`
as the writer for the `fmt` logger, which is advisable in either way,
to avoid …
> feat: print messages via `tracing`

- buildenv/builder.pl
We didn't notice the slowness sooner since most of the closures small enough to be "good enough". But using the haskell ecosystem (with many packages in closure) you notice this right way.
But the issue that brought this up is `slack` package (the version at the time of commiting this), has some loop. Since loops are not possible within a single package output, I assume the loop happens between different package outputs.
Also a very nice side benefit is also that this fix should also speed up other Flox environments. The bigger the closure the more the speed up we'll see, which usually means bigger Flox environments will see most of the speed up.
> fix: Recursive walkReferences runs forever and eats all your CPU/RAM

- CONTRIBUTING.md
- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/attach-command.bash
- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/attach-interactive.bash
- assets/activation-scripts/activate.d/attach.bash
- assets/activation-scripts/activate.d/generate-bash-startup-commands.bash
- assets/activation-scripts/activate.d/generate-fish-startup-commands.bash
- assets/activation-scripts/activate.d/generate-tcsh-startup-commands.bash
- assets/activation-scripts/activate.d/set-prompt.bash
- assets/activation-scripts/activate.d/set-prompt.fish
- assets/activation-scripts/activate.d/set-prompt.tcsh
- assets/activation-scripts/activate.d/set-prompt.zsh
- assets/activation-scripts/activate.d/set-run-variables.bash
- assets/activation-scripts/activate.d/start-services.bash
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/activate.d/trace.bash
- assets/activation-scripts/activate.d/zdotdir/.zlogin
- assets/activation-scripts/activate.d/zdotdir/.zprofile
- assets/activation-scripts/activate.d/zdotdir/.zshenv
- assets/activation-scripts/activate.d/zdotdir/.zshrc
- assets/activation-scripts/activate.d/zsh
- pkgs/flox-activation-scripts/default.nix
With the myriad of activation scripts I was finding it challenging to track environment variable changes happening in the different files, so I added invocations of a $FLOX_ACTIVATE_TRACE script at the beginning and end of each file in order to trace their various entry/exit points. While this PR includes a default trace script, it also provides the ability for people to provide their own, making it a convenient hook for inspecting the changes that can happen to arbitrary variables.
The full instructions for using this variable have been added to the CONTRIBUTING.md document.
* added new FLOX_ACTIVATE_TRACE feature for use debugging activation scripts
> feat: add FLOX_ACTIVATE_TRACE debugging feature

- cli/tests/activate.bats
Minor changes to `cli/tests/activate.bats` to fix bugs encountered while working on #2552:
- use `tee` to display output to stdout as well as stderr so that you can see what goes wrong when the `activate:hook:tcsh` test fails
- properly quote`flox activate` output in the "tcsh: repeat activation in .tcshrc creates correct PATH ordering" test 
N/A
> fix: minor bugs in cli/tests/activate.bats

- assets/activation-scripts/activate.d/zsh
- cli/tests/activate.bats
Add a `precmd` hook for interactive zsh shells that calls `hash -r` to undo the effect of `vcs_info` and other plugins that inadvertently populate the hash table by accessing `$commands`.
This prevented newly installed packages from being picked up if they were already on PATH from outside the environment and were then installed within an activation.
Calling `vcs_info` populates the hash table despite `nohashcmds` and `nohashdirs` being set:
% zsh -o NO_GLOBAL_RCS -o NO_RCS -o nohashcmds -o nohashdirs
mba15% hash | wc -l
0
mba15% autoload -Uz vcs_info
mba15% vcs_info
mba15% hash | wc -l
1412
Narrowing it down to what a function like `VCS_INFO_detect_git` does:
% zsh -o NO_GLOBAL_RCS -o NO_RCS -o nohashcmds -o nohashdirs
mba15% hash | wc -l
0
mba15% echo "$commands[git]" …
> fix(activate): zsh interactive force rehash

- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-core/src/activations.rs
Remove an activation that's not ready and the starting process is no longer running so that another loop of `handle_inner()` can recover from the error by starting a new activation.
We introduced the first known occurrence of this happening with `_FLOX_ACTIVATION_PROFILE_ONLY` and fixed it in 2bb050e but the only way to recover existing installations is to manually edit the `activations.json`. Assuming you're able to find it from an existing activation.
We talked about the watchdog being the best place to clean these up as part of #2398, in order to limit the number of state changes to `activations.json`, but I feel differently after realising that we already had the ability to retry in `flox-activations` and a TODO for this class of problem.
Doing it here also means that we don't have to …
> fix(activations): Recover from deadlock

- cli/flox-rust-sdk/src/models/search.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/utils/search.rs
- test_data/generated/resolve/node_suggestions.json
- test_data/generated/resolve/package_suggestions.json
- test_data/generated/search/ello_all.json
- test_data/generated/search/exactly_ten.json
- test_data/generated/search/hello.json
- test_data/generated/search/java_suggestions.json
- test_data/generated/search/python.json
- test_data/generated/show/flask.json
- test_data/generated/show/hello.json
We now include the catalog name for custom catalog packages when listing
search results. Where possible, this uses the recently introduced pkg-path
field, rather than attempting to construct it from catalog name and
attr-path.
This also includes a fix for an alignment bug in the case where some package
names matched the search term and were highlighted and others were not.
It also removes the unnecessary disambiguation code that was previously
intended to handle the case where multiple catalogs could provide a package
with the same name.
Closes #2472.
> feat: Show catalog name in search results

- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
- pkgdb/Makefile
- pkgdb/src/lock-flake-installable.cc
Provide a `lockFlakeInstallable` primop through a plugin and replace the call to `pkgdb lock-flake-installable` with a respective `nix eval` that uses the primop.
> refactor: replace `pkgdb lock-flake-installable` with a plugin

- assets/activation-scripts/activate.d/generate-bash-startup-commands.bash
- assets/activation-scripts/activate.d/generate-fish-startup-commands.bash
- assets/activation-scripts/activate.d/generate-tcsh-startup-commands.bash
From @limeytexan:
We were exporting required flox internal variables when first activating an environment but not when attaching, and that caused problems for activation scripts that were expecting those variables to be defined. This patch moves those activation blocks further down where they can be defined for all activation types and makes them consistent across the bash, fish, and tcsh cases. The zsh case is handled differently on account of the way that zdotdir works, and is not a problem.
From @dcarley:
The reproduction for this is to in-place "attach" to an activation that's been "started" with a previous Flox version:
```console
% FLOX_SHELL=bash nix run github:flox/flox/v1.3.8 -- activate -d ~/tmp
warning: ignoring the client-specified setting 'trusted-public-keys', because it is …
```
> fix(activate): export internal variables required for in-place

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/providers/upgrade_checks.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/check_for_upgrades.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
Following this PR, `flox activate` will perform a dry upgrade of the activated environment, in the background.
If upgrades are available, upon the next activation `flox` will notify the user that upgrades are available.
```shell
$ flox activate 
ℹ️  Upgrades are available for packages in 'name'.
Use 'flox upgrade' to get the latest.
✅ You are now using the environment 'environmentname'.
To stop using this environment, type 'exit'
```
Add an access layer for an `UpgradeInformation` file.
An `UpgradeInformationGuard<Unlocked>` is used to access a possibly absent file.
The guard can attempt to acquire a file lock to gain exclusive access to the `UpgradeInformation` on disk.
`UpgradeInformationGuard::try_lock` will _not_ block, but instead return early
without changing state.
A simple …
> feat(activate): upgrade notifications

- .github/workflows/ci.yml
- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
- cli/tests/containerize.bats
- cli/tests/test_support.bash
- pkgs/flox-cli-tests/default.nix
Enable macOS tests in CI for `flox containerize`. This starts a `podman` VM for the `containerize.bats` file,
and reuses it for each test. This means that XDG and home dirs are shared for all tests in the file. This is necessary
because `vfkit`, which starts the VM, creates a file under the hard-coded path `$HOME/Library/Application Support/vfkit`.
N/A
> test: enable macos containerize tests

- cli/flox/doc/flox-config.md
- cli/flox/src/commands/activate.rs
- cli/flox/src/config/mod.rs
[docs: update flox-config man page with all options](https://github.com/flox/flox/pull/2591/commits/c532ab6c8ca92200984f6101d1a275a191f1de33)
[c532ab6](https://github.com/flox/flox/pull/2591/commits/c532ab6c8ca92200984f6101d1a275a191f1de33)
The options `state_dir` and `upgrade_notifications` have been added to
config but were never added to the man page.
[docs: add upgrade notification text to man page](https://github.com/flox/flox/pull/2591/commits/8d33802749741785a679cd82c7edfad922137acd)
[8d33802](https://github.com/flox/flox/pull/2591/commits/8d33802749741785a679cd82c7edfad922137acd)
Add upgrade notification text to `man flox-config` so the config setting
will appear if a user searches the text of the message. The man pages
are included on our docs site
A config option was added to …
> docs: update flox-config man page with all options

- cli/flox/src/commands/init/mod.rs
This code is a relic of when we would use either pkgdb or the catalog to search.
Should be merged after https://github.com/flox/flox/pull/2526
> refactor: drop some dead pkgdb search code

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/tests/containerize.bats
- mkContainer/mkContainer.nix
Add options from the OCI spec to a new manifest section [containerize.config]. Add all options except Entrypoint and Env since those conflict with the current implementation of activate. Deprecated and reserved keys are also left out.
> feat(containerize): add more options

- cli/tests/containerize.bats
Now that the containerize-config branch has merged (and been deleted 🙈) we should test against main.
We'll fix testing branches as part of https://github.com/flox/flox/issues/2502
NA
> chore: change containerize test ref to main

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/list.rs
When a prior check for an upgrade has been run, add `- upgrade
available` to the output of `flox list`, e.g.:
hello: hello (2.12.1 - upgrade available)
When a prior check for an upgrade has been run, add `(upgrade available)`
to the output of `flox list --all`.
Also move pname into the table instead of the header and change Path ->
Package Path.
Example output:
```
python_install_id: (upgrade available)
Description:  Python interpreter
Package Path: python3Packages.python
Package Name: python
Priority:     10
Version:      3.9.5
License:      PSF
Unfree:       false
Broken:       false
```
Prior to this change, output would be:
```
python_install_id: (python)
Description: Python interpreter
Path:     python3Packages.python
Priority: 10
Version:  3.9.5
License:  PSF
Unfree:   false
Broken: …
```
> feat: add upgrade information to list

- assets/activation-scripts/etc/profile.d/0800_cuda.sh
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-manpages/default.nix
Replace uses of `fd` with `find` in the two places where it is currently being used, and remove `fd` from the build and runtime closures.
Closes #2544 
N/A
> chore: use findutils in preference to fd

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/utils/gomap.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/tests/containerize.bats
**feat(containerize): PascalCase -> kebab-case**
Rename `containerize.config` keys from PascalCase to kebab-case in the
user-facing manifest and only convert them when passing over to the
provider. Rationale from Jenny's update to the DR:
- https://www.notion.so/floxdev/011-Containerize-image-options-14a744c8e31680f09425d84de06a3bd4?pvs=4#14a744c8e3168199a9d0e320587a089d
> We will change the capitalization of the keys to kebab-case instead of
> PascalCase. This will be consistent with the rest of the Flox manifest
> fields. Since the values for each key will have a slightly
> different (nicer) format in the manifest.toml vs the spec, we don’t
> think it’s necessary to follow the capitalization convention of the spec
> file.
We'll maintain two structs, one user facing and the other …
> feat(containerize): Change manifest format (kebab-case and arrays)

- cli/tests/containerize.bats
This reverts commit 7c35e74055511b416925e570150196bf95119fb3.
Now that the change has been merged to `main`. Which incidentally failed because the branch was automatically deleted after merge:
- https://github.com/flox/flox/actions/runs/12829247263/job/35774996409
N/A, internal only
> Revert "test(containerize): Override FLAKE_REF_OR_REV"

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/search.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/show.rs
- cli/flox/src/utils/search.rs
- test_data/generated/resolve/node_suggestions.json
- test_data/generated/resolve/package_suggestions.json
- test_data/generated/search/ello_all.json
- test_data/generated/search/exactly_ten.json
- test_data/generated/search/hello.json
- test_data/generated/search/java_suggestions.json
- test_data/generated/search/python.json
- test_data/generated/show/flask.json
- test_data/generated/show/hello.json
Previously, we only displayed the attr_path portion for custom catalog
packages (ie. mycatalog/foo would display foo). That name can't be used to
install the package, so we now properly show the full pkg path.
This includes a refactor of some of the search and show code to a) use separate types for search and show, as they correspond to different catalog service endpoints and use different fields, b) remove the intermediate `SearchResult` type and use the underlying client type directly.
This is best reviewed commitwise, in order.
> feat: Show full pkg path for custom catalog packages

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/upload.rs
- cli/flox/src/config/mod.rs
**refactor(commands): {config->flox}.features**
Use `flox.features` instead of `config.features` for all of the build
and publish commands which are feature flagged.
Unfortunately we have to carry two copies of it around per 7ba717f but
`Flox.features` is easier to access because defaults have already been
applied and we don't need to move/ref it in doing so.
**feat(publish): Rename --cache to --store-url**
To better reflect that it's copying to a store rather than actually
caching the package.
The fields have been renamed at the same time so that we don't need to
specify the argument name separately (which was easy to overlook) and
hints have been added for the argument values.
**feat(publish): Merge cache opts from config**
Allow `publish.store_url` and `publish.signing_key` to be …
> feat(publish): Allow cache options from config

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox-rust-sdk/src/utils/logging.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox-watchdog/src/main.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/upgrade.rs
- cli/flox/src/utils/init/catalog_client.rs
- cli/tests/containerize.bats
Abstract processing of lines of data from a `Read` implementation.
`WireTap::tap_lines*` will read lines from the reader
and call a provided function for every line.
`tap_lines_with_context` allows to provide a context
that can hold state across multiple calls of the tap function.
That context is used by `WireTap<String>::tap_lines`
to collect lines back into a String.
Use `WireTap` to log `ContainerSource` output with `info` verbosity.
The effect will be that by default `containerize` will not print logs
of the container builder script and conflict with the spinners.
Use `WireTap` to log `ContainerSink` output with `info` verbosity.
The effect will be that by default `containerize` will not print docker logs
and conflict with the spinners as we `<runtime> load` the container image.
`flox …
> feat(containerize): pipe subprocess output into tracing

- cli/flox-rust-sdk/src/providers/upgrade_checks.rs
We saw a few tests fail sporadically, due to ser/de of iso8601 timestamps created by `time::serde::iso8601` [1].
Deseralization of timestamps, casued the resulting native value to be off by -1 nanosecond.
The underlying issue seems to be the storage of time as a float with tricky behaviour at this granularity.
We discussed dropping `time`
(which was only first introduced to `flox-rust-sdk` for this task) in favor of using `chrono`,
but for the time being decided to fix the tests instead, done here by lowering the granularity to seconds,
which should avoid the float floor'ing.
Internal testing fixes.
> fix(tests): round timestamps down to seconds

- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/providers/flake_installable_locker.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/providers/nix.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/upload.rs
**refactor: Extract known_store_path test helper**
I plan to make `NIX_BIN` private so that we can control a default set of
feature arguments but there are a number of places where we also use it
to get a known store path for tests. Refactor these to use a test helper
rather than accessing the static or environment variable directly.
Also incldues a missing `#[cfg(test)]` because `commands::upload` was
complaining about unused imports on build after adding the helper.
**refactor: Add providers:nix::nix_base_command**
To ensure that we apply the correct set of default options to all `nix`
commands. Not doing so causes `flox publish` to fail if the system
defaults don't match:
% NIX_CONFIG='experimental-features = ""' ft publish hello2
❌ ERROR: Unable to interpret derivation info: EOF while …
> refactor/fix: Helpers for Nix commands

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/doc/flox-containerize.md
- cli/flox/doc/manifest.toml.md
Add docs marked experimental for `[containerize.config]` in `man flox-containerize`.
An experimental `[containerize.config]` section has been added to the manifest with a number of options from the OCI spec
> docs: document containerize.config as experimental

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/build.rs
Using serde is more readable in a Rust project than shelling out to jq
NA
> test: don't use duct or jq for builds test

- .github/workflows/nix-managed-lints.yml
- pkgs/pre-commit-check/default.nix
Avoid merging commits that where marked to me fixed up or squashed, by either `fixup!` or `squash! respectively.
While commitizen makes sure commit follow the conventional commit standard, some prefixes are always allowed:
Merge, Revert, Pull request, fixup! and squash
<https://commitizen-tools.github.io/commitizen/commands/check/#allowed-prefixes>
In to avoid merging `squash!`/ `fixup!`, commits we restrict these prefixes to only `Revert`, which occasionally happens for good reasons.
No user impact.
> ci: block merging of WIP commit prefixes

- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/status.rs
Currently, `flox services status` only displays the _status_ (e.g. `Running`, `Completed`, `Stopped`, ...) for managed services. However, when services are `Completed`, it doesn't tell whether they completed successfully or not, i.e. what their exit code was at completion. This PR adds an Exit code column that displays the exit code as communicated by process compose.
```
NAME       STATUS           PID
aaa        Running          123
bbb        Stopped          [456]
ccc        Completed (0)    [789]
```
`flox services status` will now include the exit codes of completed processes.
> feat(services): Add exit codes to output

- cli/flox-rust-sdk/src/models/manifest.rs
A manifest with a build edited by current HEAD produces a lockfile with:
% jq .manifest.build ~/tmp/.flox/env/manifest.lock
{
"hello2": {
"command": "exit 1",
"files": null,
"runtime-packages": null,
"systems": null,
"sandbox": null,
"version": null,
"description": null,
"license": null
}
}
Which can't be read by existing versions of Flox:
% ft list
❌ ERROR: Failed to parse lockfile as JSON: unknown field `version`, expected one of `command`, `files`, `runtime-packages`, `systems`, `sandbox` at line 26 column 17
This is likely due to a corrupt environment.
Prevent this from happening by adding `skip_serializing_none` to the
remaining child structs in the manifest and adding a test that prevents
us from regressing in the future.
Before the changes it would fail as follows:
---- …
> fix(manifest): Add+test missing skip serialize

- assets/activation-scripts/activate
- cli/flox/doc/flox-activate.md
Added support for _FLOX_SHELL_FORCE - a version of FLOX_SHELL that is useful in testing because it will not be clobbered by the activate script.
N/A
> feat: add support for _FLOX_SHELL_FORCE

- cli/tests/ld-floxlib.bats
- cli/tests/setup_suite.bash
- cli/tests/upgrade.bats
Drop unused variables from pkgdb_vars_setup. We still use TEST_NIXPKGS_REV_NEW, but that's the only one left, so export it directly and drop pkgdb_vars_setup
NA
> test: drop some unused pkgdb vars

- .github/CONTRIBUTORS.csv
- cli/flox/src/commands/general.rs
- cli/flox/src/utils/init/metrics.rs
I read the linked manpage and it wasn't helpful; `man flox-config` on the other hand was just the thing.
N/A.
> fix(flox): update manpage reference to the flox-config

- cli/tests/activate.bats
- cli/tests/activate/activate-command.exp
- cli/tests/activate/activate.exp
- cli/tests/activate/attach.exp
- cli/tests/activate/envVar.exp
- cli/tests/activate/histfile.exp
- cli/tests/activate/interactive-hello.exp
- cli/tests/activate/rc-tcsh.exp
- cli/tests/activate/rc.exp
- cli/tests/auth/loginPrompt.exp
- cli/tests/setup_suite.bash
- pkgs/flox-cli-tests/default.nix
Test that we can attach to an activation that was started by the
previously released version of Flox. This will prevent regressions like
40a77b4 and other breaking changes to activation state.
This is best reviewed commit-by-commit, where you can find more detail.
N/A, internal only.
> test(activate): Attach to previous release version

- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
Our approach to caching the store of the proxy container in a volume doesn't work across versions because it shadows new store paths needed by the base "OS" in newer container images:
% nix run github:flox/flox/v1.3.9 -- containerize -d ~/tmp
…
% nix run github:flox/flox/v1.3.10 -- containerize -d ~/tmp
⠉ Writing container
warning: the group 'nixbld' specified in 'build-users-group' does not exist
this derivation will be built:
/nix/store/aflz8nigx9lbmm8xpn58lg138a8ibysh-flox-1.3.10-g8778414.drv
⠙ Writing container
error: the group 'nixbld' specified in 'build-users-group' does not exist
open /var/lib/docker/tmp/docker-import-1278828303/repositories: no such file or directory
❌ ERROR: Writing to runtime was unsuccessful
Fix this by using one volume per Flox version, at the expense of:
- …
> fix(containerize): Proxy vol per Flox version

- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/build.rs
- package-builder/flox-build.mk
This patch updates the package builder to return the build data provided by
`nix build --json`, enhanced with `pname` and `version` as set in the manifest,
and `logs` produced by the build.
In the case of `version` specifically, this patch also adds logic to evaluate
the "file" and "command" modes at the point of performing a build.
Update the `build` provider to emit either `Success` or `Failure` events
instead of a generic `Exit` event.
When successfully running `flox-build.mk`, read the produced build results
and attach them to a new `Success` event.
> feat(package): communicate build results with cli

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/check_for_upgrades.rs
- cli/flox/src/utils/init/catalog_client.rs
Upgrade checks running in the background,
may eventually be handled differently,
e.g. given lower priority over user attended resolution requests.
One way of doing so, is by attaching a QoS class header to requests
made by  the `check-for-upgrades` command,
that describes the requested Quality of Service.
In this case we accept a low priority/quality as the request isn't user attended.
We can omit a layer of wrapping `CatalogClientConfig::extra_headers` in an `Option`,
because the field is a `BTreeMap`.
`BTreeMap` implements `Default` by returning an empty map,
which wrt the client behaves equivalently to `None`.
I.e. there is no difference between `None` and `Some(BTreeMap::default())`.
Besides, it makes modifying options more ergonomic,
as it removes the need to check whether an option …
> feat(check_for_upgrade): set QoS class header to background 

- Justfile
- cli/flox-rust-sdk/src/data/flox_version.rs
- cli/flox-rust-sdk/src/flox.rs
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-watchdog/default.nix
- pkgs/rust-internal-deps/default.nix
[build: remove FLOX_VERSION from dev shel](https://github.com/flox/flox/commit/ab6f297ee889504ff3ec5041ac197e3da418c4ca)
`FLOX_VERSION` set by the dev shell has the tendency to become stale,
especially when we depend on the current git commit rev,
which changes with every commit.
Also since activate inherits the version, activations made with an older version of flox,
affect the version printed by cargo built versions of flox.
For one, that may prevent _us_ from reliably putting correct versions into bug reports.
More importantly, missing the git rev "prevents flox containerize tests on macOS
from using the same version of Flox in the proxy container
because we don't have access to the current commit rev" [1].
[refactor: amend flox version detection and …
> refactor: amend flox version detection

- assets/activation-scripts/activate.d/flox-env-helper.awk
- assets/activation-scripts/etc/profile.d/0100_common-paths.sh
- assets/activation-scripts/etc/profile.d/0800_cuda.sh
- cli/flox/doc/doc-build/manifest.toml.md
- cli/flox/doc/manifest.toml.md
- cli/tests/cuda/cuda-disabled.sh
- cli/tests/cuda/cuda-enabled.sh
- cli/tests/ld-floxlib.bats
- cli/tests/ld-floxlib/test-load-library-last.sh
- cli/tests/setup_suite.bash
- ld-floxlib/Makefile
- ld-floxlib/ld-floxlib.c
- ld-floxlib/unit-test.c
- package-builder/closure.c
- package-builder/sandbox.c
We had been previously adding [impure] paths to the `FLOX_ENV_LIB_DIRS` variable in order for `ld-floxlib` to serve up libraries found in these directories. We then forgot this requirement as we added validation for `FLOX_ENV_LIB_DIRS` with a recent refactor, and this correspondingly broke the cuda "profile.d" init script.
This patch updates `ld-floxlib` to instead serve up libraries found in the `/lib` subdirectory of entries in the FLOX_ENV_DIRS variable, and adds support for a new pair of `LD_FLOXLIB_{FILES,DIR}_PATH` variables which can be used to direct `ld-floxlib` to serve up libraries in arbitrary locations. The order of precedence for these [three] variables is as follows:
1. `/lib` subdirectories of `FLOX_ENV_DIRS` entries
2. libraries as listed in `LD_FLOXLIB_FILES_PATH`
3. …
> feat: add LD_FLOXLIB_{FILES,DIRS}_PATH support to ld-floxlib

- cli/tests/activate.bats
We recently added a test to check activation compatability with the previous release. As the test depends on the latest flox version having been released on GitHub, the test fails when run on a commit that bumps flox version but has not yet actually been released.
We could alternatively make sure to tag the release commit and then re-run CI, but that seems like it would introduce unnecessary friction into the release process.
NA
> test: skip compatability check for relase commits

- assets/activation-scripts/activate.d/attach-command.bash
- assets/activation-scripts/activate.d/attach-inplace.bash
- assets/activation-scripts/activate.d/attach-interactive.bash
- assets/activation-scripts/activate.d/generate-bash-startup-commands.bash
- assets/activation-scripts/activate.d/generate-fish-startup-commands.bash
- assets/activation-scripts/activate.d/generate-tcsh-startup-commands.bash
- assets/activation-scripts/activate.d/zsh
- cli/tests/activate.bats
- cli/tests/activate/nested-activate.exp
When nesting environment activations the relevant `profile` hooks for all activated environments should be sourced when starting a new subshell. Prior to this patch only the profile hooks for the current / most recent environment was being sourced, but this patch adds logic to iterate over the contents of the FLOX_ENV_DIRS variable when looking for profile hook scripts to be sourced.
Closes #2574.
- Fixed sourcing of profile scripts for all active environments. Among other things this allows aliases to be set in any environment within a nested activation, but also underscores the importance of writing idempotent profile scripts. As with environment variables, profile scripts for the most recently-activated environment run last, and therefore take precedence over actions performed in …
> fix: source profile hooks for all active environments

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/errors.rs
We are running git commands to clone from a local bare repo
to a tempdir to materialize the environment files through
`Generations::<ReadWrite>::get_current_generation()` / `Generations::<Read>::writable`.
The `ReadWrite` typestate is a bit of a misnomer as it allows writiting
but is currently also required for readonly operations
where the physical files are required
(i.e. to provide a `CoreEnvironment` to build, link, etc)
-- this has been acknowledeg in comments.
What seems to trigger that materialization in activate
(despite activate generally not building, linking, etc),
are various other calls that internally call
`ManagedEnvironment::ensure_locked`[1]
-> `ManifestEnvironment::validate_checkout(_, self.get_current_generation)`[2].
-----
What I'm wondering about is the performance …
> perf(managed): avoid full checkout to validate local environment

- package-builder/flox-build.mk
- pkgs/flox-package-builder/default.nix
The `nix-daemon` can be slow to respond to `nix store delete` invocations for a variety of reasons, and users should not have to wait for these to complete, particularly as the success of this command cannot be guaranteed as users can create alternate GC roots to the packages being deleted.
This patch eliminates the slowness by invoking the deletion in the background by way of the `daemonize` wrapper.
Closes #2670.
N/A
> fix: daemonize invocations of `nix store delete`

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
Creating writable generations is slow, so we want to avoid it during activation. It's not obvious exactly what actions will lead to creating writable generations - previously validating a local checkout was doing so. Add a regression test to ensure we don't make similar mistakes in the future.
NA
> test: ensure activation doesn't create writable generations

- cli/flox-rust-sdk/src/models/manifest/composite.rs
- cli/flox-rust-sdk/src/models/manifest/mod.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
The original ticket was to mock out the implementation so I expect that the remaining TODOs will be done in subsequent tickets that we create.
**feat(manifest): Add models::manifest::composite**
Adds the following..
`ManifestMergeStrategy` trait to describe a way of merging multiple
manifests. We're starting simple and will implement more complex merging
later on, so this will allow us to experiment with other strategies
without completely replacing a current implementation in-place.
`CompositeManifest` struct to describe the composition of one or more
manifests using any given `ManifestMergeStrategy`.
`ShallowMerger` implementation of the trait which overwrites top-level
keys for each field in `manifest1` with `manifest2`. We have been
calling this "prune merge" vs "leaf merge" up until …
> feat(manifest): Initial composite merging

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/delete.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/commands/upgrade.rs
- cli/flox/src/utils/metrics.rs
[feat: add remote environment used to metrics](https://github.com/flox/flox/commit/5964cc896a721700984ab4c78c7ea33a68b328ab)
Add an environment_subcommand_metric!() macro that adds
`remote_environment = owner/name` to metrics.
Use it for all environment commands.
[feat: add --start-services metric](https://github.com/flox/flox/commit/65aac3048842317fe2b9e4c9976e817b55c00640)
Add a start_services = true/false metric for all activation commands
NA
> Activate metrics

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/src/models/manifest/raw.rs
- cli/flox-test-utils/src/lib.rs
- cli/flox-test-utils/src/manifests.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/install.rs
- cli/flox/src/utils/message.rs
- cli/tests/lang-python.bats
- test_data/config.toml
- test_data/generated/resolve/darwin_ps_all.json
This change generally makes the `flox install` output clearer and more friendly.
- All packages that were successfully installed for all requested systems are condensed onto a single line.
- All packages that were requested but already installed are condensed onto a single line.
- Packages that were only installed for _some_ of the requested systems are reported with a warning. Previously they were reported with a warning and then a subsequent line indicating that the package was installed successfully.
The output now looks like this:
```
✅ 'curl', 'jujutsu', 'fd' installed to environment 'flox-jj'
⚠  'bpftrace' installed only for the following systems: aarch64-linux, x86_64-linux
⚠  Packages with ids 'hello', 'bat' already installed to environment 'flox-jj'
```
The output of `flox …
> feat: improved install messages

- cli/tests/activate.bats
- pkgs/flox-cli-tests/default.nix
[test: partially revert background timeouts](https://github.com/flox/flox/commit/90e301d25b13074dd1961ccf33b79220b3078f2f)
Revert the addition of timeouts to `cat activate_finished` in
https://github.com/flox/flox/commit/a412f54c05b29947883c90182271b7034205ddd3 and
https://github.com/flox/flox/commit/2864016e1eb9185ed4dc3ee26cfa653dad30c0f6
The timeout was added so that the output of the activate command will be
displayed upon timeout, rather than an indefinite hang.
This has caused tests to flake:
https://github.com/flox/flox/actions/runs/13181851477/job/36794503671?pr=2701
Although better debug output would be useful, we haven't to my knowledge
ever timed out CI due to `cat activate_finished` hanging indefinitely.
For most tests that use `cat activate_finished`, any breakage that would …
> Cleanup background activation

- cli/flox/src/commands/mod.rs
When deciding which environment to perform an operation on, we already give precedence to the current directory over an activated default environment.
Add a similar exception to give precedence to an activated environment over a default environment in the current directory.
This avoids the annoyance of a prompt in the situation, where the user most likely wants to operate on the active environment
- Start shell in ~ (which contains an activated default environment)
- flox activate -r owner/name
- Run a flox environment command
Notably, this does not regress the behavior that flox environment commands default to an activated default environment when no other environment is active, which makes Flox feel more similar to a system package manager.
For flox environment commands that detect what …
> fix: don't prompt for default env in current dir

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
- package-builder/flox-build.mk
- test_data/generated/envs/publish-simple/manifest.toml
A publish operation will now create a clean clone of the rev to publish in a temp directory, invoke a clean build on that, and capture the BuildResults from that build to identify the version, pname, and outputs of the build.
- Publish will now ensure a clean repo and build, and now supports version and description metadata from the manifest.
> feat: publish from a clean build

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/upgrade_checks.rs
- cli/tests/activate.bats
Managed environments check with timestamps whether the environment needs to be rebuilt.
More precisely, flox compares the mtime of `.flox/env/manifest.toml` against the mtime of `.flox/env/name.system.dev`.
If the manifest was modified more recently,
we perform a build and link of the environment,
now requiring (local) clones again, as well as at least nix evaluation,
and store queries.
To benchmark this case, we touch `.flox/env/*` essentially forcing a rebuild in every run:
```bash
hyperfine --warmup 1 \
'touch .flox/env/* ; ./1.3.10/bin/flox activate --print-script' \
'touch .flox/env/* ; ./1.3.11/bin/flox activate --print-script' \
'touch .flox/env/* ; ./1.3.12/bin/flox activate --print-script' \
'touch .flox/env/* ; main/bin/flox activate --print-script'
Benchmark 1: touch …
```
> perf: improve environment caching and build times

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
Prevents ignoring `.flox/env` by mistake. A local or global `.gitignore` that ignores `env/` or `ENV/` breaks managed environments. See #2118 for more details.
N/A
> fix: don't allow ignoring .flox/env

- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/doc/flox-gc.md
- cli/flox/src/commands/envs.rs
- cli/flox/src/commands/gc.rs
- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
Remove environments that have been deleted from disk without using `flox
delete`. Previously these could accumulate indefinitely in the registry,
despite us filtering them from `flox envs`.
More details in the individual commits.
Follow-ups:
- https://github.com/flox/flox/issues/2685
- https://github.com/flox/flox/issues/2398
- https://github.com/flox/flox/issues/2707
- https://github.com/flox/flox/issues/2706
Added a `flox gc` command to clean up data from unused environments.
> feat(gc): Remove non-existent envs from registry

- cli/flox-core/src/activations.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox/src/commands/envs.rs
- cli/flox/src/config/mod.rs
- cli/flox/src/utils/dialog.rs
- cli/flox/src/utils/metrics.rs
- cli/tests/services.bats
- flake.lock
- flake.nix
- pkgs/t3/default.nix
Update external system dependencies by updating our flake lock.
bump: nix 2.24.9 -> 2.24.11
bump: rust 1.82 -> 1.84
bump: process-compose 1.34.0 -> 1.40.1
> chore: update flake.lock

- cli/Cargo.lock
- cli/flox-core/src/lib.rs
- cli/flox-watchdog/src/logger.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/check_for_upgrades.rs
**feat(watchdog): Loop on GCing all log types**
Rather than special casing the watchdog logs.
It's possible for `process-compose` to be stopped and started multiple
times for a long running watchdog, so long as there is at least one
attachment to the activation. And we're about to add handling for
`upgrade-check` logs.
So we should attempt to garbage collect for the life of the watchdog.
This is done every 1hr which still seems reasonable.
**fix(watchdog): GC upgrade-check logs**
Each activation backgrounds `flox check-for-upgrades` which creates a
Log file. I had 128 log files in my test environment. Ensure that these
are cleaned up in the loop whilst the watchdog is running.
Internal thread about whether we should background for every activation:
- …
> fix(watchdog): Loop on GC logs and include upgrade-check

- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox/doc/flox-containerize.md
- cli/tests/containerize.bats
- mkContainer/mkContainer.nix
- mkContainer/tests.nix
- pkgs/flox-cli-tests/default.nix
flox containerize expected to always run as root inside the container, since the
Nix store was owned by root, and the following files were basically missing.
/etc/passwd
/etc/groups
/etc/shadow
This commit changes that by extending the container with a "fakeNss" to provide
those missing files, and also abuse the fact that we can insert custom lines
during build-time. We derive most information from containerize.config.user
inside Flox's toml.
All that being said, it allows us to do the following.
$ flox containerize --file='-' | docker load
✨ 'tmp.GtqsVDTJut:latest' written to stdout
Loaded image: tmp.gtqsvdtjut:latest
$ # Works perfeclty fine when we just run it with the default user root
$ docker run --rm -it tmp.gtqsvdtjut:latest 'cowsay hello'
_______
< hello >
-------
\   ^__^
\ …
> feat(containerize): add single-user install capability

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/providers/flake_installable_locker.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
There are no behavior changes here, this just makes the names of some of our data structures less verbose. The only data structure that wasn't renamed is `ManifestPackageDescriptor` because renaming it to `PackageDescriptor` causes conflicts  with the `api_types::PackageDescriptor` type. These two types are used in very similar contexts, and the `catalog-server` type can't be easily renamed, so we'll stick with `ManifestPackageDescriptor` for now.
N/A
> refactor: remove Manifest* naming

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/main.rs
- cli/tests/containerize.bats
- cli/tests/install.bats
- cli/tests/search.bats
With `RUST_[LIB_]BACKTRACE=1` anyhow captures backtraces
to the origin of an error chain.
The backtrace can then be accessed via `anyhow::Error::backtrace`,
which returns a `Display`able type (`std::backtrace::Backtrace`
at our version of rust).
To avoid being too noisy and allow targeted enabling of backtraces,
the backtrace is logged with `debug!` under the `flox::backtrace` target.
Unfortunately, `thiserror` supports backtraces only
when compiled with rust nightly [1] [2], on account of being blocked by
the stabilization of `error_generic_member_access` [3].
[1]: <dtolnay/thiserror#390>
[2]: <dtolnay/thiserror#387>
[3]: <rust-lang/rust#99301>
> feat(debug): anyhow backtrace with `RUST_[LIB_]BACKTRACE=1`

- cli/flox-core/src/canonical_path.rs
- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/floxmeta.rs
- cli/flox/src/utils/errors.rs
Follow-up from https://github.com/flox/flox/pull/2708#discussion_r1949786418
Prune branches from floxmeta when removing managed environments from the
registry which no longer have `.flox` paths on disk.
This also removes the suffixed "remote branch" if there aren't any
suffixed "local branches" remaining and applies the same logic when
deleting a `ManagedEnvironment`.
The intersections between `ManagedEnvironment`, `FloxMeta`, and
`EnvironmentRegistry` feel kinda weird here and I made several aborted
attempts to:
- refactor pointer and git methods onto `FloxMeta`
- constructing a `ManagedEnvironment` without a path or registry entry
It's worth noting that..
Remote environments will never be GCed in practice because there's no
user interface to remove the local clone. As such, the remote …
> feat(gc): Prune branches from floxmeta

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/tests/install.bats
Resolution error messages can and often are multi-line, which look better if the first line is not appended to the `resolution error: ` line.  So we insert a newline after that for the following message(s) to start on new lines.  Similar adjustments were made for consistency, as well as some capitalization for consistency and adherence to the style guide.
> chore: adjust error message formatting

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
I had to think about what rev and local_rev mean when I was looking back at GenerationLock, so add some comments so it's more clear next time.
NA
> docs: add some comments on GenerationLock

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/floxmeta.rs
Be resilient to floxmeta branches not existing when pruning. To fix an error seen by Stahnke; we haven't debugged the particular case, but it's plausible to happen if the floxmeta repo has ever been manually deleted:
> flox gc
❌ ERROR: Failed to delete branch: Git failed with: [exit code 1]
stdout:
stderr: error: branch 'default.cf7e1b06' not found
I originally started to implement the error handling higher up in `EnvRegistry::prune_nonexistent` but changed my mind because:
1. It would still leave `flox delete` open to potential errors when deleting remote branches for managed environments.
2. A branch not existing is the same intent as the branch being deleted, so long as we surface any git errors from `list_branches` early on.
3. Leaving stray branches in floxmeta isn't the worst thing, …
> fix(gc): Allow floxmeta branches to not exist

- assets/activation-scripts/activate.d/generate-fish-startup-commands.bash
- cli/tests/activate.bats
**test: regression test for spaces in PATH**
The 1.3.13 release contains the new path helper that's written in Rust.
There is a bug in how this is called that does not handle spaces in
PATH. This bug wasn't caught in the test suite, so this change adds a
new collection of tests meant to catch this regression in the future.
**fix: spaces in PATH for fish shell**
There are actually two bugs fixed by this change:
- In-place activations for fish shells would use the generation-time
PATH instead of the runtime PATH, meaning that a user's RC-file
config could be removed from PATH.
- PATH that contains a space gets split in the Bash shell that
generates the startup commands for the fish shell. When the fish
shell then calls `flox-activations fix-paths` it sees too many
arguments due to the word …
> fix: spaces in PATH for fish shell

- cli/tests/containerize.bats
These are failing very frequently at the moment, which is slowing down work on other tickets, and isn't helping us understand or fix the underlying problem any quicker. We've prioritised the ticket (https://github.com/flox/flox/issues/2743) for this coming sprint so temporarily disable the tests in the meantime.
N/A
> chore(containerize): Disable tests aarch64-darwin

- cli/flox/src/commands/services/status.rs
- cli/tests/services/wait_for_service_status.sh
Closes #2597 
This formats the output of `flox services status --json` as a JSON array instead of as JSON lines. This is more consistent with JSON output elsewhere in the CLI, per discussion in this comment and elsewhere: https://github.com/flox/flox/issues/2597#issuecomment-2610807555.
- The output of `flox services status --json` is now a JSON array instead of JSON lines
> feat(services): format status JSON output as an array, not JSON lines

- cli/tests/containerize.bats
Check that podman is functioning
and ensure it has created the necessary directories.
Without this, starting multiple podman containers in parallel,
may cause a race between the containers to create the directories.
We started seeing the effect of the race condition frequently
when running the containerize.bats tests, both locally and in CI [^1].
When running `flox containerize` (which by default writes into a registry)
was run on macos, two processes of `podman` are spawned;
1. `podman run ...` which runs `flox containerize` from within a container and writes that to stdout
2. `podman import` which adds the created container to the local runtime.
As part of their initialization both connect via ssh to the "podman machine",
a VM specifically for running containers.
During this connection …
> fix(test): avoid race condition at first parallel run of podman

- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
This adds the `include` section to the manifest. For now users can only add environments via relative path, but remote environments will be added at some point in the future. The syntax looks like this:
```toml
version = 1
[include]
environments = [
{ dir = "../foo", name = "bar" }
]
```
The `dir` field is meant to resemble the `--dir` flag used on the command line. The `name` field is required only for path environments for the following reasons:
- At some point a user will be able to request updates to individual environments. Thus, you need a way to identify this environment. You could use the built-in name of the environment (since every environment has one), but this name isn't guaranteed to be unique throughout the (eventual) dependency graph, and the name itself isn't visible …
> feat: add include section

- .editorconfig
- assets/activation-scripts/activate
- assets/activation-scripts/activate.d/source-profile-d.bash
- assets/activation-scripts/activate.d/start.bash
- assets/activation-scripts/wrapper
- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
- pkgs/flox-activation-scripts/default.nix
The `wrapper` script is derived from `activate` by pruning off all functionality
not required for wrapping flox-built binaries,
e.g. shell hooks, or `profile.*` scripts from the manifest.
Further, wrapping binaries requires neither services (`process-compose`),
nor a watchdog and lifecycle management via `flox-activations`.
`wrapper` is to be executed in place of `activate --turbo (-- | -c)`,
which disables certain activate functionality _at runtime_.
`wrapper` drops those functions and with it related (unused) dependencies for a smaller closure.
* Build the `build_wrapper` output of `flox-activation-scripts`[sic]
with the `wrapper` scripts in place of `activate`.
Since the `wrapper` script drops references to store paths of non-relevant dependencies
during builds and wrapping of …
> refactor: replace `activate --turbo` with wrapper script

- buildenv/builder.pl
- cli/flox-rust-sdk/src/providers/buildenv.rs
This patch restores the flox custom error message that existed before the introduction of buildenv.nix:
> ❌ ERROR: 'bar' conflicts with 'foo'. Both packages provide the file 'bin/hello'
It also updates the error and warning handlers respectively to more closely resemble their rust counterparts.
Closes #2619
* fixed regression in error message displayed when attempting to install package conflicts
> fix: restore previous installation package conflict error message

- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
Whenever we merge two manifests that have common keys, we allow the manifest of higher priority to override the field.
The depth of these fields depends on the field in question, and some fields in fact perform a non destructive union.
The absolute knowledge of what is being merged and how is implemented by a few _leaf merge_ functions, in particular: `[optional_]map_union`, and `shallow_merge_options`.
These are called as part of intermediate merge functions, e.g. `deep_merge_optional_containerize_config`  and `ManifestMergeStrategy::*`.
This PR changes the _leaf merge functions to produce warnings when a field is overridden.
The warnings are associated with a `KeyPath` that identifies the conflicting field which is provided to the leaf merge functions by their respective callers.
The …
> feat(merge): produce and propagate warnings

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/tests/lang-node.bats
- test_data/config.toml
- test_data/generated/init/nodejs_20.json
- test_data/generated/init/nodejs_gt_20.json
- test_data/generated/search/nodejs_all.json
- test_data/input_data/init/node/nodejs_20/package-lock.json
- test_data/input_data/init/node/nodejs_20/package.json
- test_data/input_data/init/node/nodejs_20/src/index.js
- test_data/input_data/init/node/nodejs_gt_20/package-lock.json
- test_data/input_data/init/node/nodejs_gt_20/package.json
- test_data/input_data/init/node/nodejs_gt_20/src/index.js
We recently fixed the versions reported by catalog server, which allows us to install Node.js packages by proper semver versions. The tricky part is that Node.js major versions are separate packages. This change makes it such that a user that has a version requirement in their `package.json` will get the correct `nodejs_*` package installed that corresponds to their version requirement.
This is accomplished by doing parallel resolutions against a list of hardcoded attribute paths for all currently available Node.js versions in the catalog. This means that we'll have to add attribute paths to this list as they become available, but that's a problem for later.
Since the current spinner was only designed for a single catalog request at a time, you temporarily see multiple spinners (one for …
> fix: install correct nodejs package

- cli/flox-rust-sdk/proptest-regressions/models/manifest/typed.txt
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
This adds an optional "compose" section to the lockfile. When this section is present it indicates that the lockfile's manifest was the result of merging other manifests.
An alternative to making this section optional would be to make the `compose.manifest` field optional. But that means we have a `compose` section in the lockfile even when we haven't done composition.
N/A
> feat: add composition to lockfile

- flake.nix
- pkgs/nix/default.nix
This just adds a space and forces nix package to be rebuilt.
This change is needed as an aftermath of recent incident (incident-10).
N/A
> fix: New hash is needed for nix package

- pkgs/flox-cli-tests/default.nix
The flox package applies versioning to the wrapped flox-cli package, which always uses the version in FLOX_VERSION.
For macOS containerize tests, we use the version to construct a flakeref for the flox to run inside the proxy container. For feature branches, we need to test the feature branch, so we need the version to include a commit SHA.
NA
> test: use flox package instead of flox-cli

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
[refactor: inline lock_with_catalog_client](https://github.com/flox/flox/commit/236c19f4722218aaca131b5b2eed32a74bdf451f)
The function is only used once, and inlining it allows skipping an
unnecessary read of the lockfile from disk.
[feat: split out merge_manifest function](https://github.com/flox/flox/commit/e259bd71a7fa0f316eecbc282fbfeeaf64af1b59)
We'll refer to fetching and merging includes as merging, resolving
packages in the merged manifest as resolving, and merging + resolving as
locking. Split out `merge_manifest` and `resolve_manifest` functions
accordingly.
Unit tests could be re-written to be slightly more targeted and call
`resolve_manifest` rather than `lock_manifest`, but it doesn't seem
worth the effort.
Implement the very simplest case where has a manifest has no …
> Prep patches for merging includes

- cli/flox/src/main.rs
- cli/tests/version.bats
I noticed that `flox --version` and the `containerize` tests were still incorrect for me when the devShell is running from within an interactive activation:
% env -i /run/current-system/sw/bin/flox --version
1.3.14-g8fa0811
% ./cli/target/debug/flox --version
1.3.14-g8fa0811
% env -i ./cli/target/debug/flox --version
1.3.15-g2c0ae4c3
We can't easily test the wrapper script from the integration tests so they attempt to exercise the same combination of code paths. Failure from before this change:
version.bats
✓ version: accepts runtime version from wrapper derivation [917]
✗ version: doesn't propagate runtime version into activations [1147]
tags: version
(from function `assert_output' in file /nix/store/yf08fkff6pbr4lya678aprc0nwsddxgn-bats-with-libraries-1.11.1/share/bats/bats-assert/src/as …
> fix(activate): Don't propagate FLOX_VERSION

- cli/tests/containerize.bats
Fix these failing tests on the release branch by always testing the flake from `main` within the proxy container:
- https://github.com/flox/flox/actions/runs/13594323337/job/38007994931
This is a temporary solution while I attempt to untangle the correct `flox --version` used by both locally built and Nix built binaries from `flox-cli-tests` out of:
- https://github.com/flox/flox/pull/2769
This can be merged back to `main` from `release-1.3.16` (@stahnma @mkenigs is that the direction you were going to document?)
N/A
> test(containerize): Use main for proxy flake

- cli/tests/setup_suite.bash
All of the zsh activation tests that use a nested activation fail for me when `just integ-tests` is run from an existing zsh activation because `FLOX_SAVE_ZSH_PS1` leaks in and affects the known prompt for `expect`:
not ok 1 zsh: repeat activation in .zshrc doesn't break aliases in 12206ms
…
#
This is another case where we shouldn't be exporting environment variables that aren't documented for public use. I did try using the `restore_saved_vars` trick to see if it would help here but it didn't solve this or my other Zsh prompt bug:
- https://github.com/flox/flox/issues/2728
The solution to that ticket, in addition to flox/flox#2629 and flox/flox#2767, might be to search and replace our indicator if it's found in the existing prompt rather than attempting to carry the original prompt …
> test(suite): Unset FLOX_SAVE_*

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/raw.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox/doc/doc-compose/manifest.toml.md
- cli/flox/doc/flox-activate.md
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/services/mod.rs
- cli/tests/activate-mode.bats
- cli/tests/activate.bats
- mkContainer/mkContainer.nix
This provides a default for the environment which still defaults to
`dev` if not specified and can still be overridden by `flox activate -m`
The `manifest.toml` docs have been copied and slightly modified from:
- https://flox.dev/docs/concepts/activation/#development-vs-runtime-mode
The `activate` docs have been slimmed down with a reference to
`manifest.toml` so that we don't have to repeat all of the same
information; some of which already varied between the three places they
were specified. I plan to change the concepts do to link back to
`manifest.toml` docs as well.
The new `[activate]` section of the manifest has been added before
`[options]` and not included in the manifest template to reflect that
most users won't need to set it and it's not a first-class feature that
we need to …
> feat(activate): Add activate.mode to manifest

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/manifest/raw.rs
- cli/flox/src/commands/mod.rs
Puts the `[include]` section in the manifest template when the feature flag is enabled.
A second commit refactors the manifest template into helper functions to make it easier to read.
The manifest template now looks like this with the feature flag enabled (feel free to bikeshed the `... include other environments to merge with this one` language):
```toml
##
##
##
version = 1
[install]
[vars]
[hook]
[profile]
[services]
[include]
[options]
systems = [
"aarch64-darwin",
"aarch64-linux",
"x86_64-darwin",
"x86_64-linux",
]
```
N/A
> feat: add include section to manifest template

- cli/flox/doc/doc-build/flox-publish.md
- cli/flox/doc/doc-build/manifest.toml.md
Initial pass on publish man page.  
This is distinct from the floxdocs and reference architecture documentation where ever that should live.  I didn't want to spend too much time on it since we are in the process of changing much of this and I'm not sure what we have now will go into anyone's hands.
I'm happy to leave on a branch, do a bit of clean up, merge as is, or collaborate with someone based on feedback.
> docs: add docs for publish command

- cli/flox/doc/doc-compose/flox-list.md
- cli/flox/doc/doc-compose/manifest.toml.md
- cli/flox/src/commands/list.rs
- cli/flox/src/utils/message.rs
- cli/tests/list.bats
Update `flox list --config` to print the merged manifest with a notice
when using composition.
We now lock early, which we didn't previously for `list -c`, in order to
detect composition and for a more consistent experience between composed
and non-composed environments.
We have to re-serialize merged manifests from `typed::Manifest` which
means that we lose comments and add some defaults that the user may not
have specified. We'll improve on this in later commits and tickets.
N/A
> feat(compose): Add support to list --config

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/tests/list.bats
When fetching included path environments, error if the environment has not been locked or has changes in the manifest not reflected in the serialized form of the manifest in the lockfile:
```
❌ ERROR: failed to fetch environment 'name': cannot include environment since its manifest and lockfile are out of sync
```
For managed environments, error if the environment is out of sync with floxmeta:
```
❌ ERROR: failed to fetch environment 'name': cannot include environment since it has changes not yet synced to a generation.
To resolve this issue, run either
* 'flox edit -d /path/to/name --sync' to commit your local changes to a new generation
* 'flox edit -d /path/to/name --reset' to discard your local changes and reset to the latest generation
```
I'm not sure if formatting the error with a …
> feat(compose): error for modified environments

- pkgs/t3/default.nix
We've had some intermittent failures from the t3 tests due to output ordering on faster machines.
Prevent these from blocking the installation of Flox as a flake by disabling `doCheck` for the package, as previously agreed in this thread:
- https://flox-dev.slack.com/archives/C05P6A5J6U8/p1739292017829209
The t3 repo runs these same tests in CI so we'll still get feedback when we make changes to t3 itself, which is the time that we're most likely to make breaking changes and be in a position to fix them.
Make the installation of Flox from a flake more reliable.
> chore(pkgs): Disable doCheck for t3

- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/tests/list.bats
⚠️ Split from and based on #2813 to make it easier to review
So that they don't get rendered as empty tables when `flox list -c`
serializes a merged manifest that didn't explicitly specify values. They
are still kept if they were explicitly set though, per the additional
test. The remaining options are deferred to 2812.
N/A
> chore(manifest): Make hook and profile optional

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/utils/logging.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/upgrade.rs
[fix: use lockfile to detect changes for edit](https://github.com/flox/flox/commit/4afa51d834ead251a7ece964be51e6506ba55da3)
Currently, if `flox edit` modifies `[include]` in a way that leads to a
change in e.g. hook.on-activate for the merged manifest, we don't print
the warning that a user may need to reactivate.
Fix this by using the manifest in the lockfile rather than the user
manifest.
This also refactors EditResult to only have two variants, Unchanged and
Changed. Upcoming changes will require warning when `[include]` is
modified, which isn't mutually exclusive with ReActivateRequired and
Success, so the enum would start to become a truth table. Using a method
EditResult::reactivate_required will be simpler.
[test: factor out …
> feat: message after `[include]` is modified

- cli/Cargo.lock
- cli/flox/Cargo.toml
- cli/flox/doc/flox-config.md
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
We had a Sentry report for a failed update check against the path `by-env/nixos-24.05/LATEST_VERSION` which looks like someone set the `installer_channel` config option to represent a Nix channel:
- https://flox-dev.sentry.io/issues/6421529049/?alert_rule_id=15667377&alert_type=issue&environment=stable&notification_uuid=cb2bb2c3-3b62-4c88-b17a-fb67d0426310&project=4506548241825792&referrer=slack
Prevent this from happening by restricting and documenting the values that can be provided. If you try to set an incorrect value imperatively:
% flox config --set installer_channel nixos-24.05
❌ ERROR: unknown variant `nixos-24.05`, expected one of `stable`, `nightly`, `qa`
If you set an incorrect value declaratively, as that user has:
% flox list
❌ ERROR: Could not parse config: unknown variant …
> fix(installer_channel): Document and restrict vals

- cli/flox/doc/doc-build/flox-build.md
- cli/flox/doc/doc-build/flox-publish.md
- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-config.md
- cli/flox/doc/flox-update.md
- cli/flox/doc/flox.md
I noticed some incorrect uses when editing `flox-config` in another PR and filtered the remaining offenders with:
rg "[^./'\`]flox" cli/flox/doc
N/A
> docs: Flox uppercase as noun

- pkgs/pre-commit-check/default.nix
I wasn't able to merge a branch that contained a revert commit:
- https://github.com/flox/flox/actions/runs/13948656774/job/39042042563#step:9:84
- https://github.com/flox/flox/pull/2769/commits/737558e4cf35ad0b01a94ea9a8379d09efed6760
Adding `-x` to this script revealed that it was double quoting the args:
+ ALLOWED_PREFIXES_FLAG=
+ ALLOWED_PREFIXES=("Revert")
+ '[' 1 = 1 ']'
+ ALLOWED_PREFIXES_FLAG='--allowed-prefixes "Revert"'
+ /nix/store/cpwhg2mjgbpyq1ll286kxr2s55mncs81-python3.12-commitizen-4.0.0/bin/cz check --allowed-prefixes '"Revert"' --rev-range 7907112422299d8eb310ee20c86c50994896201b..737558e4cf35ad0b01a94ea9a8379d09efed6760
It now looks like this, when tested with some additional values:
+ ALLOWED_PREFIXES_FLAG=
+ ALLOWED_PREFIXES=("Revert" "something else" "another thing …
> fix(ci): Allow revert commits in merge queue

- assets/environment-interpreter/wrapper/wrapper
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
**follow up to #2734 and #2729**
The late consensus was that variables defined in the manifest shall be
scoped to the manifest only and not baked into binaries.
Because variables are _set_ in the wrapper,
which sits between the executing environment and the binary,
these variables cannot be reset.
> feat: drop manifest variables from build_executable_wrapper

- cli/tests/containerize.bats
- mkContainer/mkContainer.nix
Follow-up from 2178ba3e for the documented environment variables that are now passed as args and can be derived for containers. We're not passing `--env-project` because there is no source project in the rendered container.
`/tmp` now exists in containers built by `flox containerize`.
`FLOX_ENV*` changes roll into other ticket.
> fix(containerize): Set FLOX_ENV_{DESC,CACHE}

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
Improve the performance of `manifest_without_install_or_include()`
`lock_manifest_noop_if_locked_without_install_section` has been consistently taking more than 60 seconds for me.
The issue seems to be the `prop_filter()` calls in `manifest_without_install_or_include()`. I assume that many manifests are being generated and then rejected. Instead of using prop_filter, create a valid manifest by construction.
This massively improves the speed of
`lock_manifest_noop_if_locked_without_install_section`, so increase the number of cases we're running.
NA
> test: improve proptest generator performance

- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/tests/activate.bats
- cli/tests/compose.bats
- cli/tests/list.bats
- cli/tests/setup_suite.bash
**test(integ): Default to FLOX_FEATURES_COMPOSE=true**
Run all integration tests with the composition feature flag enabled so
that we get early feedback in preparation for turning it on for
everywhere when the feature is launched.
Ideally it would be nice to run a matrix of the tests with and without
the feature flag but it's complicated to configure and expensive to run,
so it doesn't seem worth it.
It's worth noting that the feature flags for composition and services
affect manifest parsing in various places and we mostly switch on the
presence of includes rather than the flag, unlike pkgdb vs catalog which
took completely different setups and codepaths.
This change highlights an issue with `flox list` which will be fixed in
a subsequent commit.
**fix(compose): include.environments …
> fix(compose): include.environments serde default and test with FLOX_FEATURES_COMPOSE=true

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
[refactor: don't re-fetch includes for flox upgrade](https://github.com/flox/flox/commit/1b2c0435bc707fb2559fd71a19fe1bdc780d3bf5)
Currently upgrading all packages is implemented by completely removing the seed
lockfile. This will force all includes to be re-fetched.
Instead, only unlock packages when performing an upgrade.
[feat: add zebra() to Environment trait](https://github.com/flox/flox/commit/0557f55822401bb564f18d75dcac4dc100e0851f)
We haven't yet decided what to call the operation that re-fetched an
included environment, so I'm calling that zebra in this commit.
Add zebra() to Environment trait and implement it in CoreEnvironment and
Lockfile.
zebra() re-fetches all included environments or if specified, a list of
included environments.
I added some tests, but I plan to …
> feat: add zebra() to Environment trait

- .github/CONTRIBUTORS.csv
- buildenv/buildenv.nix
**fix: Force the use of coreutils/cp to copy static manifest chunks**
I just add `command` before `cp --no-preserve...` in the `createManifestChunks` section in buildenv/buildenv.nix
Since I updated the [nix package](https://archlinux.org/packages/extra/x86_64/nix/) in Arch Linux from 2.24.11-10 to 2.26.3-1 the process to update the manifest breaks with the following error:
```
$ flox edit
❌ ERROR: Failed to build environment:
Failed to constructed environment: these 2 derivations will be built:
/nix/store/q8ibksg63fx49qz541by1mm9k79c1zlk-manifest.drv
/nix/store/mf2lsq6dbllqdh4w79k8fi16wrl6dhng-environment.drv
building '/nix/store/q8ibksg63fx49qz541by1mm9k79c1zlk-manifest.drv'...
manifest> + export 'PATH=/nix/store/b1wvkjx96i3s7wblz38ya0zr8i93zbc5-coreutils-9.5/bin:/path-not-set' …
```
> fix: Force the use of coreutils/cp to copy static manifest chunks

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/utils/message.rs
- cli/tests/activate.bats
- cli/tests/list.bats
Best reviewed commit-by-commit.
I've matched the locations of the existing "integration" tests in BATS
and Rust because both commands use a different pattern and I still can't
decide which I prefer.
This surfaces the name `Current manifest` which isn't ideal but we don't
currently have a way for the `ComposesiteManifest` to know the name of
the environment that it came from.
N/A
> feat(compose): Print overrides for edit, list, and activate

- cli/tests/activate.bats
- cli/tests/services.bats
Block this test on the activation having started (which in turn blocks on `process-compose` starting) before attempting to poll for the running. This pattern is copied from tests in `activate.bats`.
To workaround these failures on the x86_64-darwin remote builder:
not ok 472 activate services: shows warning when services already running in 2105ms
#
#
Recent examples:
- https://github.com/flox/flox/actions/runs/13639271677/job/38125290933
- https://github.com/flox/flox/actions/runs/13944603552/job/39028991616
- https://github.com/flox/flox/actions/runs/13657894699/job/38182980609
- https://github.com/flox/flox/actions/runs/13636847423/job/38117625355
What's particularly strange about the failures is that it only completed one or two polls of loop (with 0.1s delay) within the 1s timeout. …
> test(services): Add activate_finished fifo

- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/utils/message.rs
- cli/tests/activate.bats
- cli/tests/list.bats
List the notices about overridden fields in the order that the environments were included and the composing environment last.
Changes the unit test to use real environments because it depends more heavily on the implementation of the `Compose` object; specifically the naming of the environments in `Compose.include` vs `Compose.warnings`.
Follow-up from:
- https://github.com/flox/flox/pull/2837#discussion_r2010346244
- https://github.com/flox/flox/pull/2837#discussion_r2010348329
N/A
> feat(compose): Order override notices by env

- cli/flox/doc/flox-push.md
- cli/flox/src/commands/push.rs
Accept `flox push --owner <>` or `flox push --org <>` with the same effect.
> feat(push): alias `--org` to `--owner`

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/delete.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/include.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/flox/src/commands/services/status.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/commands/upgrade.rs
- cli/flox/src/utils/metrics.rs
- cli/tests/compose.bats
- cli/tests/upgrade.bats
See commit messages for first few commits. Primary change is:
[feat: flox include upgrade](https://github.com/flox/flox/commit/61da141790c13af7d199818ead4cbf5a2b3b8766)
Add command `flox include upgrade`.
This exposes functionality already implemented on the Environment trait.
Help text for the new command:
```
Upgrade environments included in an environment
Usage: flox include upgrade [-d=<path> | -r=<owner>/<name>] [<included
environment>]...
Get the latest contents of included environments and merge them with the
composing environment.
The included environments to upgrade can be specified by name, or if none are
specified, all included environments will be upgraded.
Available positional items:
<included environment>  Included environments to upgrade
Available options:
-d, --dir=<path> …
```
> feat: flox include upgrade

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/push.rs
- cli/flox/src/utils/errors.rs
- cli/tests/push.bats
Local includes be it by absolute or relative path are unlikely to impossible to reproduce when pulling the environment on another machine.
This PR checks the current manifest whether for local includes and bails the push command if that is the case.
> chore: check that pushed  environments do not refer to local includes

- cli/flox/src/commands/list.rs
- cli/tests/list.bats
Implements a `toml_edit::visit_mut::VisitMut` visitor, that changes the layout of the printed to align closer to our preferred style (section table headers with dotted subtables).
The default serializer provided by the `toml` crate renders all tables as implicit non-dotted tables, e.g.:
```toml
version = 1
[install.curl]
pkg-path = "curl"
[install.hello]
pkg-path = "hello"
[options.allow]
licenses = []
[options.semver]
[services.sleep1]
command = "sleep 1"
[services.sleep2]
command = "sleep 2"
```
In our documentation we generally prefer non-implicit tables at the root/document level with dotted subtables.
```toml
version = 1
[include]
environments = [
{ dir = "some empty environment" }
]
[install]
curl.pkg-path = "curl"
hello.pkg-path = "hello"
[services]
sleep1.command = "sleep 1" …
```
> style(list): render composed manifest with tables and sections

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/tests/list.bats
- test_data/generated/envs/build-noop/manifest.lock
- test_data/generated/envs/build-runtime-all-toplevel.json
- test_data/generated/envs/build-runtime-packages-not-found.json
- test_data/generated/envs/build-runtime-packages-not-toplevel.json
- test_data/generated/envs/build-runtime-packages-only-hello.json
- test_data/generated/envs/go_gcc/manifest.lock
- test_data/generated/envs/hello-unfree-lock.json
- test_data/generated/envs/hello/manifest.lock
- test_data/generated/envs/hello/manifest.toml
- test_data/generated/envs/hello_and_htop_for_no_system/manifest.lock
- test_data/generated/envs/hello_as_greeting/manifest.lock
- test_data/generated/envs/influxdb2/manifest.lock
- test_data/generated/envs/kitchen_sink/manifest.lock
- test_data/generated/envs/krb5_prereqs/manifest.lock
- test_data/generated/envs/pip/manifest.lock
- test_data/generated/envs/publish-simple/manifest.lock
- test_data/generated/envs/tabula-lock.json
- test_data/generated/envs/vim-vim-full-conflict-resolved.json
- test_data/generated/envs/vim-vim-full-conflict.json
- test_data/generated/search/java_suggestions.json
**refactor: make allow.licenses optional**
This change makes `allow.licenses` optional so that its merge semantics
are clearer. This field is a `Vec`, which means that it defaults to
empty. At merge time it was unclear whether an empty `Vec` was present
as a default vs. explicitly set by the user, so we've made this more
explicit by making the field optional.
Since this field is optional, it will no longer be included in the
lockfile by default. This means that the test data needed to be
regenerated.
**refactor: add SkipSerializing trait**
This doesn't do much, it just adds a standardized way of writing down
these methods so that it doesn't seem like each `skip_serializing`
method is a one-off.
**feat: skip serializing options.{allow,semver}**
This changes omits `options.allow` and …
> refactor: skip serializing optional fields

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/doc/doc-build/flox-publish.md
- cli/flox/src/commands/publish.rs
- cli/flox/src/config/mod.rs
**feat: create catalog and retrieve ingress uri**
This adds a method to retrieve the ingress URI for a catalog, and
implements the method that idempotently creates a catalog at the same
time since this endoint is also the one that responds with the ingress
uri.
**refactor: remove store_url from config**
This argument will only be used in the future for testing, so it doesn't
need to be persisted in user config. This change also uses the ingress
uri from the catalog response instead of the CLI argument.
**refactor: rename signing key option**
The signing key required during publishing is the *private* key, not the
public key. Renaming this option makes that clearer to the user.
**refactor: rename the no-store option, make public**
This option is renamed to `--metadata-only` and allows a …
> feat: use ingress URI from catalog response

- cli/flox-rust-sdk/src/providers/publish.rs
**fix: show build output during publish**
This change passes the build output through to stdout/stderr during
publish to match the behavior during the build as well. The previous
behavior was going through tracing::info, which I suspect was not being
passed through.
N/A
> feat: show build output during publish

- cli/flox-rust-sdk/src/providers/buildenv.rs
If a user publishes a package with metadata only, and another user tries to install the package, it will attempt to build the package from source. This hits the code path that in the future will attempt to build the package from source. That's not supported today, so previously we would panic. Now we show an error message.
N/A
> fix: don't panic trying to install package

- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox/src/commands/publish.rs
If there's only one build in the manifest, you can now just type `flox publish` without a publish target. If you have 0 or >1 build in your manifest and don't specify a publish target, it is an error.
N/A
> feat: detect default publish target

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/check_for_upgrades.rs
- cli/flox/src/commands/containerize/mod.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/utils/message.rs
Review suggestion from https://github.com/flox/flox/pull/2837#discussion_r2010454197
Adds a `LockResult` enum which indicates whether an environment was
newly locked or an existing lock was used, matching the pattern of
`EditResult` and `UpgradeResult`.
It prevents callers like `activate` needing to `lockfile_up_to_date()` -
which I'll move off the `Environment` trait in a subsequent commit -
before calling `lock()` or `ensure_locked()`.
Into (via From) is provided for accessing the inner `Lockfile` if the
caller doesn't care about the operation. I wasn't sure whether to call
this `to_inner()`, `lockfile()`, or provide it on a struct, but settled
on this.
I'm not currently making any attempt to refactor `ensure_locked()` in
relation to the (slightly out of date) comments because it …
> refactor: lock() and ensure_locked() -> LockResult

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox-rust-sdk/src/models/manifest/mod.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-test-utils/src/manifests.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/utils/message.rs
- cli/tests/install.bats
**chore: add logging to composition operations**
**feat: push resolve responses by name**
This change makes it easier to populate the mock catalog client by
allowing you to push a response by name rather than path.
**chore: ensure install targets composing env**
This doesn't actually change any behavior. Instead, it adds a test to
ensure that when attempting to install a package that's already present
in an included environment, the package is installed to the composing
environment and an override warning is shown about the new override
N/A
> chore: ensure install targets composing env

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-managed.bats
- cli/tests/install.bats
- cli/tests/uninstall.bats
An imperative uninstall command on a composed environment only operates
on the composing environment's manifest rather than the merged
manifest (which is essentially a read-only view) or the included
environments (which are also read-only locks).
So return an error if you attempt to uninstall a package that is only
provided by an included environment.
Also print a notice if you uninstall a package from the composing
environment but the package is still provided by an include, which could
be surprising to the user if we said it was removed but it's still
visible.
Only the highest priority include is returned, rather than listing all
of the possible matches, for user-facing simplicity and to match how we
handle warnings for overridden manifest fields. This could result in
whack-a-mole where …
> feat(compose): Add errors and notices to uninstall

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-test-utils/src/proptest.rs
[test: don't drop proptest cases with izip](https://github.com/flox/flox/commit/8db6a33250d6c5ac77d0e3dbc952d71d0c233c61)
Instead of generating vectors and sets of potentially different sizes
and then zipping them together in a way that truncates extra cases, make
sure all vectors and sets are of the same length.
[test: fix proptest flakey test](https://github.com/flox/flox/commit/b3a10c854ec1849ff3fe343687bb3b63380ba825)
Use lowercase directory names in proptest helper function to avoid
directory collisions on macOS.
Previously, it was possible for two directory names to be generated that
had different casing but were otherwise equivalent, e.g. dir and DIR.
macOS is case insenstive, so this could cause test failures like
https://github.com/flox/flox/actions/runs/14041842973/job/3931362949 …
> test: fix proptest flakey test

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/doc/manifest.toml.md
Add a test/comment/documentation for the behavior that an empty list of licenses allows any license
NA - just documented existing behavior
> fix: clarify behavior of empty licenses list

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/install.rs
It's a common operation to get the lockfile if one already exists. This method has already existed on CoreEnvironment and this change simply exposes it on the Environment trait. The new method is used in the `flox install` command to check the composition override warnings before and after an installation.
N/A
> refactor: add existing_lockfile method

- cli/flox-rust-sdk/src/models/manifest/raw.rs
Previously when you run a `flox init` that does auto setup, it would add the package to the manifest in "inline table" form e.g.:
```toml
hello = { pkg-path = "hello" }
```
This change fixes it to use the dotted form that we use elsewhere.
Packages installed by auto-setup will now use the same formatting in the manifest as packages installed via `flox install`.
> fix: consistent formatting for auto-setup pkgs

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox/src/utils/errors.rs
- cli/tests/uninstall.bats
Follow-up from the review of https://github.com/flox/flox/pull/2883
Moves `get_install_ids` onto `Manifest` in parallel with
`Manifest.install`.
The errors `PackageNotFound` and `MultiplePackagesMatch` have been moved
further down into `ManifestError` to match. These are distinct from
`PkgOrGroupNotFound` because we only handle package names for
`uninstall` and `get_install_ids`, unlike `upgrade`. I've changed the
user facing message in order to match `upgrade` and because we don't
know that the operation is `uninstall` this far down.
Moves `get_includes_for_packages` and `get_include_for_package` onto
`Compose` in parallel with `Compose.include`.
The error `PackageOnlyIncluded` has been grouped in `UninstallError`
which is then wrapped by `CoreEnvironmentError` in the same way as …
> refactor: Move uninstall package helpers

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/publish.rs
[test: support mock responses for get_ingress_uri](https://github.com/flox/flox/commit/60b1ebd1ee502f0683b1288d396a24a02a2c48b5)
Move the implementation of get_ingress_uri to ClientTrait since it
should be identical for both CatalogClient and MockClient.
Add a helper function to push responses that can be used by
create_catalog/get_ingress_uri
[refactor: consolidate merge_cache_options logic](https://github.com/flox/flox/commit/71e40940cb617ecd8a7aa302ade3a035365323d2)
Consolidate logic for handling cache options instead of splitting it
between publish() and merge_cache_options().
This is more readable, allows unit testing all related logic at the same
time, and skips an unnecessary request to the catalog server when
--store-url is passed.
A test case was added to very that the error for …
> Prep patches for https://github.com/flox/flox/issues/2879

- cli/flox/doc/doc-build/manifest.toml.md
- cli/flox/doc/doc-compose/manifest.toml.md
- cli/flox/doc/manifest.toml.md
`abs-path` is a relic of pkgdb
Minor doc cleanup
> docs: drop stale reference to abs-path

- .github/workflows/ci.yml
- pkgs/flox-cli-tests/default.nix
So that it behaves the same locally as in CI. It's the second time this week I've modified a test that runs successfully locally and then fails in CI because the configuration is different, for example:
- https://github.com/flox/flox/actions/runs/14218087982/job/39839312599
N/A
> test: Move RUST_BACKTRACE to flox-cli-tests

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/show.rs
- cli/flox/src/utils/errors.rs
Instead of `Debug` representations of status header and contents, only render status and details using their `Display` format:
/// known server errors
❌ ERROR: catalog error: 422 Unprocessable Entity: something bad
❌ ERROR: catalog error: 404 Not Found
/// Special handling for 404 `flox show`
❌ ERROR: no packages matched this pkg-path: 'foo'
> style: make catalog connection errors less noisy

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/tests/edit.bats
**fix(edit): Ensure lock for noop edits**
Change the behaviour of `flox edit` so that it locks and builds an
environment when there are no changes to the manifest and it's not
already locked.
The primary motivation for this is so that we can provide a single
command for users to run in the error message when a composed
environment has unlocked includes. The alternatives are much more janky,
such as:
- `flox edit` with a whitespace change
- `flox activate -- true`
I think it also provides a more consistent experience and better
feedback loop because if you're editing an unlocked environment then
you'll want to know that it builds rather than deferring to the next
time it's activated.
For this reason I think it's also better irrespective of whether we
choose to implement `flox edit --sync` …
> fix(edit): Ensure lock for noop edits and improve include locking error

- .github/scripts/remote-execute-integration-tests.sh
- .github/workflows/ci.yml
- Justfile
- cli/.config/nextest.toml
We'd like to monitor the flakiness and performance of our unit tests and
integration tests. I believe BuildKite's test suites offering brings what we
need. It can show us the test reliability, how long each test takes, and some
other interesting metrics.
BuildKite integrates well with their own CI (duh), but it also accepts JUnit XML
files to be uploaded and stored. Both Rust with nextest and bats support
generating JUnit files that BuildKite understands. So, this will be our
preferred way of uploading, since we're not planning on moving CI systems.
N/A
> feat(ci): upload test reports to BuildKite

- .github/scripts/remote-execute-integration-tests.sh
- .github/workflows/ci.yml
Apparently, BuildKite allows us to set custom tags and filter on them. So, I thought It'd be a good idea to at least include the architecture the suite targeted, and the Nix falkeref and attribute. E.g.
-F "tags[architecture]=$MATRIX_SYSTEM" \
-F "tags[nix_flakeref]=github:flox/flox/$GITHUB_SHA" \
-F "tags[nix_attribute]=packages.$MATRIX_SYSTEM.flox-cli-tests" \
These tags will then be visible in BuildKite, allowing us to reconstruct the original command that was run to execute the tests. In hopes to reproduce an error if we encounter one.
Ref: https://buildkite.com/docs/test-engine/importing-junit-xml
N/A
> Add more context to BuildKite uploads

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/doc/doc-build/flox-publish.md
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/upload.rs
See this thread and linked notes for context on this change: https://flox-dev.slack.com/archives/C07GRNPFNJE/p1743702577025429?thread_ts=1743439226.018539&cid=C07GRNPFNJE
[refactor: determine ingress_uri in publish provider](https://github.com/flox/flox/pull/2926/commits/f193b8f693ff3c16e1983c0aaf9068cea8980f45)
It's been decided that the publish provider should communicate with the
catalog about where to publish a package, which includes determining the
store type (which could be meta-only in the near future) and the
ingress_uri.
Move the logic in the CLI and `merge_cache_options` into
`PublishProvider::publish` and `determine_cache`.
This meant that cache was removed from the `PublishProvider` struct.
This makes sense, since PublishProvider is now responsible for
determining if a cache …
> refactor: determine ingress_uri in publish provider

- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
**refactor: rename GitProvider::get_origin**
I've renamed this method to make it clear that it's not retrieving a
remote named "origin". Furthermore, this method gets information about
the remote that the current branch is tracking, so the new name feels
more comprehensive and more accurate.
**feat: heuristics for publishing git remote**
Previously we required that the build repository be tracking a remote
branch, where the build repository and the remote repsository were both
on the latest revision. This is restrictive, and causes frustration when
running the `flox publish` command.
This change loosens those restrictions by additionally allowing the
build repository be on a revision that is present on a remote. When
multiple remotes are present we apply the following heuristics to choose …
> feat: heuristics for publishing git remote

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/edit.rs
* Upon successful edits, record a `subcommand_metric` containing whether includes changed during the edit.
* Upon activation, record whether the activated environment performs composition.
> chore: add composition breadcrumb metrics

- .github/scripts/remote-execute-integration-tests.sh
Apparently, XML files can only contain a certain set of characters, of which some control characters are not included. We appear to have one (or multiple, I honestly don't know) of these control characters in the output of our CLI and bats test suite. Bats doesn't seem to clear out these characters, so we'll just do it in an extra step.
Ref: https://www.w3.org/TR/REC-xml/#charsets
N/A
> fix(ci): Remove control characters from XML test report before uploading

- cli/flox/src/commands/include.rs
```
❯ flox include upgrade
✅ Upgraded 'demo' with latest changes to:
- 'included'
ℹ️ The following manifest fields were overridden during merging:
- This environment set:
- install.hello
```
> fix: print overridden fields on `include upgrade`

- pkgs/flox-interpreter/default.nix
Use smaller package, should cut out ~100MB of closure. Also should consider calling this in the Rust directly.
N/A
> fix: use smaller package to provide setsid

- cli/flox/src/commands/search.rs
- cli/tests/search.bats
Fixes #2051, as requested.
Unfortunately, `bpaf` doesn't give much to flexibility of error messages, lest you implement your own parser. The path of least resistance here, though, was just to mark the string as optional, and then bail if it is not provided with our desired error message.
Added better search error message if the search term is not provided.
> chore: improve search error message

- assets/environment-interpreter/activate/activate.d/generate-bash-startup-commands.bash
- cli/tests/activate.bats
In-place activation with Bash 3 currently errors with:
```
Error: Broken pipe (os error 32)
```
This is caused by using `source <(...)`, because Bash 3 does not support process substitution with source. See:
https://lists.gnu.org/archive/html/bug-bash/2006-01/msg00018.html
Fix this by using `eval` instead of `source`
Fixed the error `Error: Broken pipe (os error 32)` for `eval "$(flox activate)"` when using Bash 3, which ships with macOS
> fix: in-place activation for Bash 3

- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/message.rs
- cli/tests/activate.bats
- cli/tests/include.bats
- cli/tests/list.bats
- cli/tests/uninstall.bats
- cli/tests/usage.bats
[fix: deny unknown fields in [include]](https://github.com/flox/flox/commit/876856adffb45590b5b7403b4d291a15a916a10b)
We should error if environments gets mistyped or if name in an include
descriptor gets mistyped.
[feat: improve error for IncludeDescriptor](https://github.com/flox/flox/commit/e2c79d05b172caee76ed82a48207877a606ed9c8)
For an invalid IncludeDescriptor, error with:
```
❌ ERROR: Failed to parse manifest:
Must specify included environment as { dir = <dir>, [name = <name>] }
```
Instead of:
```
❌ ERROR: Failed to parse manifest:
Expected either a local or remote include descriptor.
```
[feat: improve include help](https://github.com/flox/flox/pull/2959/commits/b09c410bbd83805ac6ba53bcb6d01876f7499004)
- Show help when `flox include` is run without any arguments
- Add include …
> Composition messaging tweaks

- cli/flox/src/commands/check_for_upgrades.rs
- cli/tests/activate.bats
- cli/tests/setup_suite.bash
* Allow skipping upgrade checks in tests to avoid some of the race conditions mentioned in #2903
* Add a specific test for upgrade checks on activation
(testing infrastructure)
> test: avoid upgrade check race condition in bats tests 

- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox/doc/manifest.toml.md
- cli/tests/include.bats
Tests are relatively light because most of the supporting work for this
was already done, so I've focused on the fetcher and the happy path for
`flox include upgrade`.
Similarly not much of the documentation needed updating because the
behaviour as described is the same for remote environments. I haven't
duplicated the `manifest.toml` descriptor docs because `name` is in both
and is the most wordy.
Follow-ups that don't need to be in-scope for initial release:
- https://github.com/flox/flox/issues/2948
- https://github.com/flox/flox/issues/2949
I considered using `env.lockfile().manifest` instead of `env.manifest()`
in the new `fetch_remote()` and existing `fetch_local()` but it doesn't
seem right that these could possibly lock if there's a race condition
between checking the lockfile is …
> feat(compose): Support includes of remote envs

- cli/flox/src/commands/services/mod.rs
~ℹ️ I've not raised this against the RC branch whilst we're still deciding on the release. We can cherry-pick it in, if necessary.~
@mkenigs note: we decided to release 1.4.0 so I changed the base branch
So that services are found from the merged manifest.
Before:
% flox services status -d ~/demo/composed
❌ ERROR: Environment does not have any services defined.
After:
% flox services status -d ~/demo/composed
NAME       STATUS       PID
hello      Stopped
Not adding an explicit test for composition with services because it requires a lot of boilerplate and we're unlikely to regress this particular case.
I'm going to look into (or ticket if I run out of time) ways to prevent us from using the unlocked typed manifest, independent from us making a decision about changing the user facing …
> fix(compose): Use lockfile for services

- .github/scripts/remote-execute-integration-tests.sh
- .github/workflows/ci.yml
Apparently we hit the monthly limit of test suite execution uploads. Doesn't make sense to fail the whole pipeline for this.
N/A
> fix(ci): allow buildkite uploads to fail

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
So that we stop accidentally using the unlocked and unmerged manifest
which prevents other features from working with composition.
This is best reviewed commit-by-commit.
This branch (unfortunately, currently) depends on:
- https://github.com/flox/flox/pull/2962 (not reviewed)
- https://github.com/flox/flox/pull/2964 (merged only to RC branch)
N/A
> refactor(env): Remove Environment::manifest()

- cli/flox-rust-sdk/src/models/manifest/typed.rs
Remote environments can now be included but the error message was never updated
> fix: update error with remote environments

- cli/Cargo.lock
- cli/catalog-api-v1/Cargo.toml
- cli/catalog-api-v1/build.rs
- cli/catalog-api-v1/openapi.json
- cli/catalog-api-v1/src/client.rs
- cli/catalog-api-v1/src/lib.rs
- cli/catalog-api-v1/src/mock.rs
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
This is blocked on serverside changes
See this thread and linked notes for context on this change: https://flox-dev.slack.com/archives/C07GRNPFNJE/p1743702577025429?thread_ts=1743439226.018539&cid=C07GRNPFNJE
See commits for more detail. Most significant change:
We've decided that the `/publish` endpoint should be used as a required
step in the publish process. We want to error if a catalog has an
unconfigured store, and we want to use the `/publish` endpoint to get
info required to carry out the publish. For now we need `ingress_uri`,
but we'll likely need `egress_uri` soon as well.
Catalogs are created implicitly server sided when they're needed, so we
can drop `create_catalog` in our client. And we can drop
`get_ingress_uri` in our client in favor of a method named `publish`
since that …
> feat: use /publish endpoint as intended

- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox/src/commands/gc.rs
This change actually runs the `nix store gc` command to remove stale store paths. I wanted to display some kind of meaningful progress to the user without overwhelming them with the full output of the command, so I'm collecting and parsing logs in order to know when GC has reached certain "stages" e.g. liveness checking, deletion, etc.
The `flox gc` command will now free up significantly more disk space when it's run.
> feat(gc): prune store paths

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/commands/pull.rs
- cli/tests/pull.bats
Previously if you ran a `flox pull --copy` you would not get the `.flox/.gitignore` file that you get if you run `flox init`. This meant that logs from services and the watchdog would not be ignored in environments created via `flox pull --copy`. Now we generate that file and the logs are ignored.
Environments created via `flox pull --copy` will now ignore the correct files in the `.flox` directory.
> feat: create .flox/.gitignore for for pull --copy

- pkgs/rust-internal-deps/default.nix
Includes the same reference and narHash for performance.
Replace a "path:" reference with a remote "github:" reference.
Now from 608MB down to 320MB 
Closure size of flox and the flox installation has been reduce by nearly half.
> feat: remove Nixpkgs source from closure

- cli/flox-rust-sdk/src/providers/catalog.rs
We were specifying `nixpkgs` as the search catalog but the service was not actually using that parameter and always search all catalogs.  Now we have implemented that on the service side, but are designating the base catalog `base` (not `nixpkgs`).  There is a workaround in the service to accommodate older CLI versions but we want to remove that code in the future.
This change removes specifying the catalog on the search call, allowing the service to determine the default behavior with the new handling of the catalog parameter.  The actual behavior should not change at all.
> fix: allow default catalogs for search

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/publish.rs
Our normal MockClient should panic by default. It's confusing to have two different mock clients that do the same thing.
It was also making it harder for me to tell where catalog types were being used throughout the codebase.
Fix cases where MockClient wasn't panicking when it should be.
NA
> test: drop PanickingClient

- pkgs/flox-buildenv/default.nix
- pkgs/flox-buildenv/flox-perl.nix
A recent packaging regression caused the size of the perl closure to balloon to more than 1GB on Darwin, but even without such bugs the size of perl is much larger than it needs to be.
This patch introduces the new `flox-perl` package which is a build of perl customized as follows:
- reduce the size of the build itself
- disable shared perl library so that perl remains a single executable
- added `"-Doptimize='-Os'"` Configure option to optimize for size
- disable building of man pages
- disable building of pod files
- disable building of unnecessary extensions
- reduce the size of the installed package
- implemented [perl] code to identify modules loaded when invoking `builder.pl`
- used that file listing to drive a `tar` copy of only the necessary files and remove all others
- remove …
> feat: minimal perl for use with builder.pl

- .github/workflows/ci.yml
Check closure size in CI
https://github.com/flox/flox/actions/runs/14578433318/job/40889621855#step:5:343
```
/nix/store/j65z0bhyzwpf3wl8isp2hkfdrikvc8fc-flox-1.4.0-g6d5d7d9
-> .#packages.x86_64-linux.flox is too large: 336151704
Error: Process completed with exit code 1.
```
Will need to merge a few PRs before this check will pass.
The distribution of flox has been cut in size by more than half, resulting in faster installs, downloads, and overall happiness.
> ci: check closure size in CI

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/upload.rs
**feat: upload nar info with publish metadata**
We now format the raw JSON NAR info into the format expected by the
catalog server and include it as part of the upload process.
**feat: query nar info from catalog after upload**
Now after uploading artifacts to the Catalog Store we query the NAR info
from the egress URI so that we can later massage it (coming in a later
commit) and upload it to the Catalog.
**refactor: abstract over catalog store type**
The existing publish provider and publish command in several places
assume and/or hardcode a `nix copy` Catalog Store. I've refactored the
provider to use a generic `ClientSideCatalogStoreConfig` type instead
that internally handles the details of publishing to particular store
types.
**refactor: remove --store-url option**
This `flox …
> feat: publish narinfo with publish metadata

- assets/environment-interpreter/common/etc/profile.d/0500_python.sh
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
Previously the Python etc/profile.d script would refer to the location of the `pip.ini` file (necessary to enforce a virtual environment) via a path relative to `$FLOX_ENV`. This doesn't work in builds because the relative path is in the Nix store e.g. `/nix/pip.ini`.
This change refactors the `/etc/profile.d` script and the build script to set and use the `$FLOX_ENV_PROJECT` variable instead of a relative path.
I tested this interactively but didn't create a test for it because it didn't seem worth it. To test it I created an environment with a simple Python project created via Claude. In the build logs you can see that it correctly creates binary wheels from the project.
N/A
> fix: correctly set pip.ini path in builds

- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/mod.rs
- cli/tests/environment-remote.bats
Check for trust when running `flox activate` against a composed
environment that includes remote environments.
This mimics the behaviour of `flox activate -r` for a non-composed
environment and reduces (or shifts responsibility for) the risk of
running arbitrary hooks from external sources by requiring the user to
review and accept them first.
It's also easier to implement it at `activate` rather than when the
remotes are fetched and merged because that happens deep within the SDK
for several callpaths and we don't have an easy way to surface that
messaging in the CLI.
This check has to be done after locking because, although we have the
names of the remotes from the unlocked manifest, we don't have the
manifest contents of the remotes. This means that the environment will
still be built …
> feat(compose): Implement trust for remote includes

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
Our goal is to avoid garbage collection of store paths between realisation
and the eventual nix build producing a flox environment path.
To that end we are going to create gc-roots for all paths going into the environment build.
Since all realisation steps are going to produce gc-roots,
the base paths for gc roots is ubiquitously needed.
In order to avoid passing paths as arguments around, we can use the ambient `BuildEnvNix` instance
to hold a basepath and provide further functionality to format prefixes.
[feat: add function to create gc_roots. i.e. link store paths](https://github.com/flox/flox/commit/5f12026da87e8b4fd2f740c5016a09ccd5b067d7)
Essentially runs `nix build <store path> --out-link <prefix>`.
To avoid accidental building or substitution of this command,
we also pass …
> feat: set (temp) gc roots during environment builds

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/src/utils/errors.rs
This is meant to address an issue we've seen in CI where a hardcoded temporary directory used to store GC roots during a build is owned by the wrong user.
N/A
> fix: don't hardcode gc roots tempdir

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/upload.rs
**feat(publish): FloxHub auth on nix-copy to ingress**
Pass a FloxHub token on `nix copy` calls to known FloxHub authenticated
store hostnames. These hostnames are currently hardcoded whilst we
figure out how we will provide multi-tenancy.
I've provided a helper function and then passed the file into the
publisher, rather than passing the token in, so that we don't have to
thread `flox.temp_dir` all the way through and it has symmetry with the
existing signing key argument.
It isn't wrapped in an `Option<>` because it's subject to change (as
above), may cause mistakes if it's sometimes not passed, and has no
effect for non-FloxHub store URIs.
Support for reading narinfo from the egress URI with auth will follow in
a separate commit.
**feat(publish): FloxHub auth on narinfo from egress** …
> feat(publish): FloxHub auth on remote stores

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
Previously, the default version for manifest builds was `unknown`. While
technically valid, this leads to the string `unknown` appearing in
places like `flox show` where a version number is reasonably expected.
This changes the default to 0.0.0 which, while still being relatively
meaningless, at least looks and feels like a version number.
> feat: Use a proper version number (0.0.0) as default for manifest builds

- cli/flox/src/commands/general.rs
- cli/tests/environment-remote.bats
Allow TOML keys such as `trusted_environments.foo/bar` to be parsed without requiring any additional quoting from the user.
This fixes a regression that I introduced in 841d6b47 (not currently in a release version) where I accidentally dropped the quoting from some uses of the key, which prevented trust choices from being saved:
% flox activate -r nicklewis/example
⚠️  The environment nicklewis/example is not trusted.
flox environments do not run in a sandbox.
Activation hooks can run arbitrary code on your machine.
Thus, environments need to be trusted to be activated.
> Do you trust the environment nicklewis/example? Trust, save choice
❌ ERROR: Could not write token to config: Could not parse key: TOML parse error at line 1, column 31
|
1 | trusted_environments.nicklewis/example
| …
> fix(config): Parse unquoted TOML keys

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/providers/auth.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/commands/upload.rs
- cli/flox/src/utils/errors.rs
**feat: use auth provider in publish**
This simply replaces the existing calls to `write_floxhub_netrc` with
calls to the auth provider.
**feat: use auth provider in buildenv**
The tricky part in buildenv is that we don't know which stores need auth
beforehand aside from two hardcoded cases:
- `https://cache.nixos.org`
- `daemon`
I don't *really* understand the second one, but Tom claims that it's a
valid value, so I've hardcoded that as well (some of our tests use it,
but without comments on those tests it's hard to tell if those are just
test values or something real).
The existing logic does a pre-build check to make sure that all of the
store paths required to build the environment are substitutable.
Different store paths may be on different stores, so we iterate over
the store paths …
> feat: add authentication for publisher

- cli/flox-rust-sdk/src/models/lockfile.rs
We try to avoid using `includes`
Spinner wording change so probably NA
> fix: align spinner vocab with guidelines

- cli/flox-rust-sdk/src/providers/auth.rs
- pkgs/nix/default.nix
- pkgs/nix/patches/seekable_http.patch
Support PUT operations that are redirected. Currently they are broken because the http implementation in Nix didn't/couldn't rewind the data.
The patch is merged upstream at: https://github.com/NixOS/nix/pull/13121 , available in 2.28
Also adds localhost for sending netrc auth, useful for testing. 
N/A
> fix: seekable http

- cli/flox/doc/manifest.toml.md
Add the [include] section to the high-level description of the manifest.toml man page
N/A
> Add [include] section to description

- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
When running `flox list -r` we create a remote environment in a temporary directory, or pull the latest updates to it if it already exists. In the past the `.flox/run` path was a symlink to what is now the `dev` mode environment. That was changed with v1.3.3, and now that path is a directory that contains the `*.dev` and `*.run` symlinks. This command attempts to migrate from the old path to the new path, but failed to do so because of a misunderstanding of the `Path::exists` method.
The `Path::exists` method traverses symlinks to determine whether the real file exists. On my system the `.flox/run` symlink was dangling, so `Path::exists` returned false even though the symlink itself existed. This caused the `create_dir_all` function to fail to create the new `.flox/run` directory. We now …
> fix: unable to create gc-roots directory

- assets/environment-interpreter/activate/activate.d/start.bash
- cli/flox-rust-sdk/src/providers/build.rs
- test_data/config.toml
- test_data/generated/envs/gcc_boost.json
- test_data/generated/envs/gcc_boost/manifest.lock
- test_data/generated/envs/gcc_boost/manifest.toml
- test_data/generated/init/go.json
- test_data/generated/init/node_npm.json
- test_data/generated/init/nodejs_20.json
- test_data/generated/init/nodejs_gt_20.json
- test_data/generated/init/python_poetry.json
- test_data/generated/init/python_pyproject_pip.json
- test_data/generated/init/python_requests.json
- test_data/generated/init/python_requirements.json
- test_data/generated/init/yarn_1x.json
- test_data/generated/init/yarn_berry.json
- test_data/generated/resolve/node_suggestions.json
- test_data/generated/resolve/package_suggestions.json
- test_data/generated/search/ello_all.json
- test_data/generated/search/exactly_ten.json
- test_data/generated/search/hello.json
- test_data/generated/search/java_suggestions.json
- test_data/generated/search/nodejs_all.json
- test_data/generated/search/python.json
- test_data/input_data/envs/gcc_boost/manifest.toml
Test building a C++ program that uses an `#include` of a library
provided by Flox.
Tests correspond to the issue described in
https://github.com/flox/flox/issues/2992,
but the reproducer in that issue was technically not a valid reproducer
since in the example given, boost is actually needed at both buildtime
and runtime.
quotes-app-cpp has since been changed accordingly in
https://github.com/flox/flox-manifest-build-examples/pull/6
This commit adds two tests: one that requires boost just at build time,
and one that requires boost at both build time and runtime.
The test that only requires boost at build time fails prior to
https://github.com/flox/flox/commit/5a8e106b30e86ed0e5d8e668f860157e7e81d3d0.
The other one does not, because adding boost to runtime-packages means
that the include …
> test: C++ includes work for manifest builds

- pkgs/pre-commit-check/default.nix
Previously this would show failures as:
% pre-commit run -a --hook-stage push
clang-format.............................................................Passed
clippy...................................................................Passed
nixfmt-rfc-style.........................................................Passed
rustfmt..................................................................Failed
- hook id: rustfmt
- files were modified by this hook
Now it shows the actual change:
% pre-commit run -a --hook-stage push
clang-format.............................................................Passed
clippy...................................................................Passed
nixfmt-rfc-style.........................................................Passed …
> fix(pre-commit): Show rustfmt errors

- cli/flox/src/commands/activate.rs
Error instead of panicking if running the activation script fails.
We received a Sentry error with:
```
failed to run activation script: Os { code: 10, kind: Uncategorized, message: "No child processes" }
```
This is likely due to process exhaustion on the host running Flox. We don't need to report that via Sentry and instead should just bubble up the error.
NA
> fix: error instead of panic on failure to run process

- cli/flox-rust-sdk/src/providers/auth.rs
- cli/flox-rust-sdk/src/providers/buildenv.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/upload.rs
Use catalog provided auth in buildenv and publisher for Publisher store
type.
We're using convention for auth format, but for now it looks something
like:
{
"aws-s3": {
"envs": {
"AWS_ACCESS_KEY_ID": "XXX",
"AWS_SECRET_ACCESS_KEY": "XXX",
"AWS_SESSION_TOKEN": "XXX"
}
}
}
> Use catalog provided auth

- cli/mk_data/src/generate.rs
Catch errors in all commands of `pre_cmd`, `cmd`, and `post_cmd` scripts
when `ignore_errors` is not set. Previously only the exit code of the
last command was used to detect errors.
This makes `RESPONSE_FILE` manipulation safer because we won't
accidentally end up with an empty file or field if there's a problem
with a `jq` query.
I tested running `just gen-data -f` locally which completed and verified
that we don't have any current errors. I haven't included it in this
commit though because it's very noisy and will conflict with the
`httpmock` work.
N/A
> fix(mk-data): Catch errors in cmds

- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/init/metrics.rs
These two live in parallel with each other:
1. `init_uuid()` and `~/.local/share/flox/uuid`
2. `init_telemetry_uuid()` and `~/.local/share/flox/metrics-uuid`
However the former never appears to have been used since it was added in 2f0768b8 and occasionally causes race conditions when I run the integration tests locally:
✗ flox activate works with requirements.txt and pip [1005]
tags: catalog end2end python python:activate:requirements
(from function `assert_success' in file /nix/store/612z53vfi1py1qf2cii0nzrqcigfgbag-bats-with-libraries-1.11.1/share/bats/bats-assert/src/assert_success.bash, line 42,
in test file lang-python.bats, line 115)
`assert_success' failed
❌ ERROR: failed to parse a UUID
0: std::backtrace_rs::backtrace::libunwind::trace
at …
> chore: Remove unused Flox.uuid

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/manifest/raw.rs
- cli/flox/src/commands/init/mod.rs
Rather than re-implementing toml_edit logic in format_customization, add
a RawManifest::new_minimal method that calls RawManifest helpers. It
also avoids doing unnecessary work by calling insert_packages, which is
designed to operate on a pre-existing manifest.
In hindsight I'm not sure it was worth the effort, added conditionals in
RawManifest, and weird newline handling. But it's probably slightly less likely
that we'll end up with accidentally different behavior between new_documented
and format_customization with this approach.
Closes #2806
> refactor: use RawManifest helpers

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/utils/errors.rs
- cli/tests/init.bats
Addresses #781 , but follows the latter suggestion of putting the file at `.flox/.gitattributes` instead of `.flox/env/.gitattributes`.
- The `flox init` command now creates a `.gitattributes` file in the `.flox` directory.
> chore: add gitattributes when `flox init` runs

- cli/flox-rust-sdk/src/providers/catalog.rs
Make temporary mock filename unique to avoid tests running in parallel conflicting and using the same file.
Generating mocks was flaking with:
```
failed to rename recorded mock file: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
A little println debugging showed two tests running in parallel could add the same timestamp to the temporary file:
```
saved mock file /Users/matthew/.cargo/git/checkouts/httpmock-7a2fab464d0fd253/84956ea/target/httpmock/recordings/httpmock_1747852294.yaml
saved mock file /Users/matthew/.cargo/git/checkouts/httpmock-7a2fab464d0fd253/84956ea/target/httpmock/recordings/httpmock_1747852294.yaml
```
Presumably one test beats the other to renaming the file, and the second fails because the expected file no longer exists.
NA
> test: fix race in httpmock recording

- cli/flox-rust-sdk/src/models/manifest/typed.rs
This anchor no longer exists and we're about to redirect the page in:
- https://github.com/flox/floxdocs/pull/226
There's not much we can do about redirecting that specific anchor because it requires client-side redirects for anchors and they're not currently supported by `mkdocs-redirects` so we'll just have to accept that only newer releases will get the right error message.
N/A, probably not worth mentioning.
> fix(manifest): Correct manifest package desc link

- assets/environment-interpreter/common/etc/profile.d/0800_cuda.sh
- cli/tests/cuda.bats
The CUDA script would fail on the last `find | nawk` command when:
1. `/dev/nvidia0` is present
2. `ldconfig` returns no matching libs
3. `/run/opengl-driver` doesn't exist (ie. not NixOS)
This caused the `find` to fail on a non-existent directory and caused activations to fail because it runs the script with `set -e`.
It's reproduced by not automatically creating the directory for every test in the suite. It's now only created for the two tests that exercise NixOS behaviour. It's fixed by catching the error from `find` and returning an empty result like we did previously for `ldconfig` in 5c3cf9b1.
Failure with the change to the test and not the script:
✗ cuda disabled when nvidia0 device present but libcuba absent [1327]
tags: cuda
(from function `assert_success' in file …
> test(cuda): Catch error from find on non-NixOS

- cli/catalog-api-v1/build.rs
- cli/catalog-api-v1/src/client.rs
- cli/catalog-api-v1/src/lib.rs
- cli/flox-rust-sdk/src/providers/publish.rs
Supersedes https://github.com/flox/flox/pull/3096
So that..
1. We automatically get changes from the upstream schema, such as making `CatalogStoreConfigPublisher.publisher_url` optional. Previously we would have to remember to make those changes manually.
2. We don't have two types of the same name available like we did for `CatalogStoreconfigMetaOnly` or `CatalogStoreConfigPublisher` because we didn't add `settings.with_replacement()` call for them.
This leaves us with an extraneous `store_type` field but I think that's the lesser of evils.
N/A
> refactor(catalog): Don't shadow store_type variant

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
As observed in #3051 and discussed in #3020, our use of disallowedReferences was causing build failures based on otherwise-immaterial references from the log and buildCache outputs. This update replaces our use of that feature with an external check performed after the "successful" build, one advantage of which is that we can now display the exact "why-depends" reason for failing the build, rather than just reporting a failure with no way to examine the failed package to see what went wrong.
Closes #3051
N/A
> fix: stop using disallowedReferences for manifest builds

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
- package-builder/flox-build.mk
- test_data/generated/build/hello/hello.c
- test_data/input_data/build/hello/hello.c
Allow `flox publish` to distinguish between manifest and expression builds.
Determine locked nixpkgs for expression builds
independent from the current catalog page of the `top-level` group.
For that we split the `check_environment_metadata` routine of the publish process into `check_environment_metadata` and `check_package_metadata`, where the latter primarily deals with the differences between manifest and expression builds.
Changes in determining available builds further motivated unifying this for reuse in builds and publishes.
Finally while dynamically resolving the nixpkgs page to publish for
will be addressed separately,
we add support to build nix expressions with arbitrary nixpkgs flakerefs.
> feat: allow publishing of nix expression builds

- assets/environment-interpreter/activate/activate.d/generate-fish-startup-commands.bash
- assets/environment-interpreter/activate/activate.d/generate-tcsh-startup-commands.bash
- cli/Cargo.toml
- cli/flox-activations/src/cli/fix_paths.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/profile_scripts.rs
- cli/tests/activate.bats
**fix(fish): runtime expansion in generated script**
This uses much of the same strategy as for tcsh since fish also doesn't
have `${foo:-}` syntax.
**fix(tcsh): runtime expansion in generated script**
This has a number of changes.
1) Expand variables at runtime rather than temp-rc-file-generation-time.
This prevents environment directories from mysteriously going missing
from PATH, MANPATH, etc.
2) Use if-statements to determine whether FLOX_ENV_DIRS and MANPATH are
unset. Tcsh doesn't have an equivalent of "${foo:-}" as in Bash and
Zsh, so you need to explicitly check first.
3) Rather than expanding FLOX_ENV_DIRS and MANPATH to empty strings,
expand them to the sentinel value "empty". This is necessary because
the empty string just becomes whitespace during one of the parsing
stages and …
> fix: runtime expansion for fish and tcsh

- assets/environment-interpreter/activate/activate
- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/Makefile
- package-builder/build-manifest.nix
- package-builder/env-filter.bash
- package-builder/flox-build.mk
- pkgs/flox-package-builder/default.nix
Update pure manifest build to activate developer environment in build mode as is done in the sandbox off case. Also reorder arguments to exactly match the invocation as found in flox-build.mk.
Closes #3052 
N/A
> fix: activate developer env in build mode for pure builds

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/providers/publish.rs
Partial revert of https://github.com/flox/flox/commit/7b990aa7215e11f2c212459c7da2bca0db682474 which made `EnvironmentPointer::open` public.
The typo of "environment" originally caught my attention and then it
occurred to me that the `unreachable!()` message was inverted because it
would only be triggered when opening a non-path environment.
We can use `open_path()` instead, as already used by `providers::build`,
and then just call trait methods on `Environment` without having to
explicitly convert to `ConcreteEnviroment::Path` or similar.
Track the project path in `CheckedEnvironmentMetadata`, rather than the
`.flox` path and working backwards, to make this easier. This doesn't
lessen our guarantees about what's in the tracked repo because we're
still opening an environment.
N/A
> refactor(publish): Use open_path()

- cli/flox-rust-sdk/src/providers/catalog.rs
The catalog currently provides psude git flakerefs, e.g. `https://github.com/flox/nixpkgs?rev=<rev>`.
`BaseCatalogUrl::as_flake_ref` attemps to turn these urls into valid flake-refs, i.e. `git+<url>`.
However, `git+<url>` results in a full clone of the nixpkgs repo, which can take several minutes depending on I/O.
The fastest alternative would be fetching a tarball via the API, i.e. turning the url into `github:flox/nixpgks`,
or `file+https://github.com/flox/nixpkgs/tarball/<rev>`, or equivalent.
Alternatively, `?shallow=1` can be provided with any `git+<url>` flakeref to avoid full clones.
While possibly slower, it
1. does not require as much url rewriting,
2. uses the same protocol (git), and thus
3. avoids api limits on api.github.com.
> fix: turn catalog git urls into shallow flakerefs

- assets/environment-interpreter/activate/activate.d/generate-fish-startup-commands.bash
- cli/tests/activate.bats
Avoid spaces or other shell-significant characters breaking activation by being misinterpreted at activation time. As mentioned in <https://github.com/flox/flox/issues/1719> this can lead to errors at activation time. This commit adds quoting to the generated fish commands. bash, and tcsh already took care of this quoting, zsh is being initialized differently but does include quoting as well.
> fix(activate): quote arguments in generated fish activation commands

- cli/flox/doc/flox-containerize.md
- cli/flox/src/commands/containerize/mod.rs
- cli/tests/containerize.bats
Allow both `--runtime` and `--file` arguments to be specified rather
than being mutually exclusive, so that macOS users with both `docker`
and `podman` on their PATH can choose which proxy runtime they want to
use, whilst still being able to write to a file outside the proxy.
I'm not convinced that `--file` is actually that useful since we added
the ability to write to runtime registries but it's hard work to get
usage metrics and removing it would be a breaking change.
The new logic is:
1. No args
a. Detect proxy runtime, and
b. Detect output runtime or write to default file
2. --runtime foo
a. Use foo for the proxy and output runtime
3. --file bar
a. Detect proxy runtime and write to file bar
4. --runtime foo --file bar
a. Use foo for the proxy runtime and write to file bar
I considered …
> feat(containerize): Allow --runtime and --file

- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
In order to provide better compatibility with manifest builds,
we need to allow building nix expressions with a compatible set of nixpkgs.
Generally this will the "latest available" set of nixpkgs used when building,
nix expressions can't be expected to be compatible.
Instead we will use the nixpkgs revision referenced by the toplevel group (if available).
This implements the finding of toplevel nixpkgs for dependency expression builds.
I.e. IF there are packages in the toplevel group, make will be called with an additional variable `TOPLEVEL_NIXPKGS_URL`.
I guess if we're building without anything in the toplevel group using whats currently `BUILDTIME_NIXPKGS_URL` is should be good enough.
Publishing _manifest builds_ still requires packages in `toplevel`.
> feat(build): nixpkgs url for dependency expression builds

- package-builder/nef/default.nix
Allow evaluating (and building) unfree and insecure packages. It's the responsibility of the catalog to deny _installation_ downstream. For builds, provide a more user friendly, i.e. permissive experience.
This keeps denying broken and unsupported packages, as building or using those is unlikely
to be resulting in a working build.
> chore: make nef nixpkgs evaluations more permissive

- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox/src/commands/build.rs
- package-builder/flox-build.mk
As in the result link is named after the target name/attrPath (.flox/pkgs/foo/bar.nix -> flox build foo.bar -> ./result-foo.bar). With manifest builds that attrPath becomes the pname (hence probably the var name `$(_pvarname)_result = result-$(_pname))`). Expression builds also link to `$(_pvarname)_result`, irrespective of thweir actual pname (as defined in the nix expression). Thus when we look for `result-(build_output.pname)` after the build, we falsely claim that the build of nix expressions failed.
This commit adds an `out_link` field to the buildOutput json and changes the cli to check that instead of guessing the outlink.
> fix(nef/cli): check the right outLink

- cli/flox/src/commands/publish.rs
This makes the `flox publish` and `flox push` commands symmetric when using the short form of the flag.
N/A
> refactor: replace --catalog flag with --org

- cli/flox-rust-sdk/src/providers/publish.rs
While uploading during publish, we don't need to show the full destination location in the spinner message.  Removed that and confirmed the full upload destination with query parameters are available in debug logs with `-vv`.
> fix(publish): remove upload destination on spinner

- cli/flox-rust-sdk/proptest-regressions/providers/services.txt
- cli/flox-rust-sdk/src/providers/services.rs
- cli/tests/services.bats
You can set environment variables at both the environment level (via the `[vars]` section) or the service level via
`services.<name>.vars.<name>`. Previously the service level variables were not applied. There are two bugs involved.
The first bug is caused by the fact that `process-compose` has an internal templating engine that allows interpolating variables defined in the `vars` section of the config file. These variables are _not_ environment variables, and are only used for templating purposes. However, the manifest uses `vars` as the name of the environment variables section, and so when the service configuration is serialized to YAML we end up translating environment variables to template variables. This explains why it was possible to use template syntax by mistake in the service …
> fix: service-level variables not applied

- cli/flox/doc/manifest.toml.md
This is already linked on the right hand side of the rendered docs but we should list it here as well for consistency.
N/A
> docs(manifest): Add link to build section

- package-builder/flox-build.mk
We make an attempt to detect build dependencies written with the typical Nix syntax in the user's manifest builds. However, the comment in this diff breaks the command being run by the Makefile because the previous line has a line continuation.
Without this fix, the Go pure build example was not able to complete a multi-stage build where the first stage vendors dependencies and the second stage uses the output of that build.
Closes #3250 
N/A
> fix: detect build deps

- assets/environment-interpreter/common/etc/profile.d/0500_python.sh
- cli/flox-activations/src/cli/fix_paths.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/prepend_and_dedup.rs
- cli/flox-activations/src/main.rs
**fix: prepend environment dirs to PYTHONPATH**
Previously we appended environment directories to `PYTHONPATH`, which
is incorrect because in nested activations you'll end up preferring
modules from earlier activations instead of newer activations.
**feat: add generic path fixing command**
We already have functionality for prepending and deduplicating
environment directories as we add them to a `PATH`-like variable. This
change just exposes that functionalty as a generic command that prints
out the modified `PATH`-like variable. This means that it's up to the
caller to properly _set_ a variable to this output and then export it.
This is done on purpose to keep the command generic.
Closes #3225 
Fixes a bug that causes Python modules from outside the environment to be preferred when …
> fix: prepend environment dirs to PYTHONPATH

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/catalog.rs
So that we report the `detail` from any error message where possible such as the recently added permission errors.
There's a discrepancy with us reporting read permissions before write permissions which will be fixed separately in https://github.com/flox/catalog-server/pull/382
Before:
% flox publish -o billlevine
…
Completed build of quotes-app-go-0.0.1 in local mode
❌ ERROR: Failed to publish package: 403 Forbidden
After:
% flox publish -o billlevine -d ~/projects/flox/flox-manifest-build-examples/quotes-app-go
…
Completed build of quotes-app-go-0.0.1 in local mode
❌ ERROR: Failed to publish package: 403 Forbidden: You are not permitted to read this catalog.
The other way to solve this case is to explicitly enumerate a 403 response for each of the endpoints that are doing permission …
> fix(catalog): Attempt to parse unexpected errors

- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
In preparation for 1.5 release.
We aren't using these anywhere else in code or tests, via the struct or
environment variables, so there is nothing else to change. The
`doc-build` directory mentioned in the ticket was already merged in
https://github.com/flox/flox/commit/c9d0d16949e1d5349be14288e6e30c943ee41552.
I've left the feature flag on `upload` because we're not exposing this
to users and perhaps(?) it will be removed in the near future.
N/A by itself.
> feat(build/publish): Remove feature flags

- cli/flox-rust-sdk/src/models/manifest/raw.rs
I've taken the shortest but complete example I can from the concept docs
because we don't want to clutter up everyone's environments with a
really long command.
It's a little odd to have `[build]` and `[build.myproject]` next to each
other when uncommented but it both matches the style of the other
headings and makes the project specific build easier to read.
I've signposted the build and publish commands so that users know what
to do next but there's not much more to say about them like we do for
services beacuse they're pretty self explanatory.
N/A
> feat(template): Add build to manifest template

- cli/mk_data/src/generate.rs
- test_data/config.toml
**fix: skip extra mock regen: build/hello**
This job moves the response file at the end of the job, but the
presence of that response is what's used by default for checking
whether to re-run the job. This change adjusts the job to check
for the presence of the output directory instead.
**fix: skip extra mock regen: ld_floxlib**
This job specifies a path to check to determine when the job should be
re-run, but does not create that path at the end of the job, so it is
always re-run.
**fix: correctly detect mock regen**
Previously we were preferring the presence of the response file when
determining whether to re-run a job and not honoring the
`skip_if_output_exists` field in all cases. Now we use this field to
completely override which path to check when determining whether to
re-run a job. …
> fix: correctly detect need for mock regen

- default.nix
Adds a flake-compat (an older variant that doesn't use fetchTree to ensure Nix 2.18.1 compatibility) for easier usage without flakes.
> feat: add a default.nix for non-flake usage

- pkgs/nix/default.nix
- pkgs/nix/patches/ghsa-g948-229j-48j3-2.28.patch
Apply nixpkgs patch for Nix 2.28 to our build of Nix to fix CVE-46415 and CVE-46416.
I considered pulling in a second nixpkgs flake or overriding Nix src, but just applying the patch seemed the most straightforward since we're already building Nix from source, and we want as minimal of a change as possible since we're cutting a release.
- Apply patch to fix Nix CVE-46415 and CVE-46416
> fix: Nix patch for CVE-46415 and CVE-46416

- cli/flox/src/commands/publish.rs
We've seen the publish command time out while waiting for processing on the Publisher side. The current timeout is 5 minutes, and a recent 1.5GiB closure took 15 minutes to process. Bump this to 30 minutes so that we don't give up before the user does.
N/A
> chore: bump publish timeout

- .github/workflows/build-examples-tests.yml
Upon merges to `main`, start a workflow run of the Manifest Build Examples CI to exercise the merged version of flox against the examples.
> ci: trigger builds if the manifest build examples on push to main

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
Issue #3308 documents the issue of attempting to use a command installed from the manifest in the process of using the `version.command` attribute to set the version string for a build, and finding that the command is not found.
This patch updates the code to always invoke the command string from within an invocation of `$(FLOX_ENV)/activate -c '<string>'`, which brings the full context of the activation into scope for running the command. It also adds an additional check to the existing suite of version checks to exercise this use case.
* Fixed bug to allow use of manifest-installed packages from within the `version.command` manifest build attribute
> fix: invoke `version.command` string from activated environment

- package-builder/flox-build.mk
Currently (manifest) builds that produce any executable in `$out/bin` fail to build with the following error:
```
❌ ERROR: Unexpected dependencies found in package 'quotes_app_cpp':
1. Remove any unneeded references (e.g. debug symbols) from your build.
2. If you're using package groups, move these packages into the 'toplevel' group.
3. If you're using 'runtime-packages', make sure each package is listed both in
'runtime-packages' and in the 'toplevel' group.
1 packages found in /nix/store/6i593wmvszs4c2jmmcz0mi4i9bx7hs5a-quotes-app-cpp-0.0.1
-      not found in /nix/store/qqmf6j5pb999vbdc8w9v8979svx5fxh9-environment-build-quotes-app-cpp
/nix/store/6i593wmvszs4c2jmmcz0mi4i9bx7hs5a-quotes-app-cpp-0.0.1
└───bin/.quotes-app-cpp-wrapped: …
```
> fix: allow build wrapper bash into the closure

- cli/flox/doc/flox-config.md
- cli/flox/src/config/mod.rs
* Redefine the hierarchy of config files loaded by flox;
We now source _at most_ two config files,
1. a system wide config and
2. a user specific config
* Drop the caching of `Config::parse` results, to allow reloads at runtime and decrease complexity.
> refactor: more predictable config loading

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
- pkgs/flox-package-builder/default.nix
Issue #3310 documents problems encountered using `gnutar` and `sed` to serialize and modify directory contents in the process of copying the manifest build output from a temporary directory to `$out`. This approach had the effect of modifying the destination of symbolic links as embedded in the gnutar control stream, which in turn corrupted its own validation checksums.
Fortunately, `cpio` archives do not suffer from this issue and are tolerant of binary substitutions that have the effect of rewriting symlink destinations, and this PR documents the effort to switch from the use of `tar` to `cpio` for copying and modifying manifest build outputs.
Closes #3310.
* Fixed bug triggered by symbolic links in manifest build outputs referring to `$FLOX_ENV`
> fix: use cpio for serializing directory contents

- package-builder/nef/default.nix
- package-builder/nef/lib/extendAttrSet.nix
- package-builder/nef/lib/mkOverlay.nix
* Improve two user facing error messages originating in the NEF library.
* Add breadcrumbs to error traces pointing potentially helping to better pinpoint evaluation errors.
* Improve function documentation for `nef.extendAttrSet`
> chore(nef): improve messages and add error breadcrumbs

- default.nix
Use older variant that doesn't assume flakes.
> fix: use older flake-compat

- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/build.rs
Unlike Nix builds which solely write to stderr, the manifest builder emits lines to both stdout and stderr, which presents the possibility of getting the ordering wrong when printing those lines to the tty. We wrote `t3` specifically to address this issue while at the same time providing color highlighting and timestamping, but then undid all that by again reading and writing each line of output from flox, thereby re-introducing the possibility that lines can come out of order.
This patch updates `FloxBuildMk::{clean,build}` to inherit stdio rather than relaying output and streaming possibly out of order at the CLI level. For the use in tests, or other deliberate use where the output should be suppressed and collected instead, `FloxBuildMk::new_with_buffers`, was added to provide `&mut …
> fix: do not relay stdout/err coming from builder

- cli/flox-activations/src/cli/fix_paths.rs
- cli/flox-activations/src/cli/prepend_and_dedup.rs
Make `--suffix` an optional argument to `flox activations prepend-and-dedup`
An upcoming change will use this subcommand for CMAKE_PREFIX_PATH which doesn't require a suffix.
NA
> feat(flox-activations): make suffix optional

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
Add a new environment trait for generations and expose metadata for managed and remote environments.
Currently this returns `GenerationsError` rather than wrapping it in something like `EnvironmentError`. We might want to change that in the future, but right now it's hard to predict without wiring up all of the functionality.
N/A
> feat(generations): Expose meta w/new env trait

- cli/flox/doc/manifest.toml.md
We already document build.*.version.command and build.*.version.file in man flox-build, but man manifest.toml was overlooked
NA
> docs: dynamic version in man manifest.toml

- pkgs/nix/default.nix
- pkgs/nix/patches/pr_12642_libfetchers_git_shallow_clone_cache.patch
Flox, or more specifically nix expression builds, currently use nix fetchers to fetch shallow git clones of nixpkgs. The git fetcher in Nix < 2.29, was not consistently using the same cache dir for operations on shallow clones, i.e. when computing cache path was determined inconsistently via `getCachePath(<url>, getShallowAttr(input))`, and `getCachePath(<url>, false)`.
The most easily observable effect were "fatal" git messages and Nix warnings, as documented in <https://github.com/flox/flox/issues/3346>. Whether it has further effect on the nixpkgs used, is unclear but possible.
The bug was fixed in Nix >= 2.29 via
<https://github.com/NixOS/nix/pull/12642>. Since the nix version used here is still 2.28.3, backport the patch until our nixpkgs ships with a patched distribution of nix.
Our …
> build: backport fix for shallow clone caches

- pkgs/nix/default.nix
- pkgs/nix/patches/pr_12580_host-in-locked-github-url.2.24.11.patch
Originally introduced in <https://github.com/flox/flox/pull/2789> the patch was merged upstream into master
in February via <https://github.com/NixOS/nix/pull/12580>. Assuming it was available via Nix in nixpkgs in late June, we removed the patch in <https://github.com/flox/flox/pull/3176>, which bumped our nix distribution to v2.28.2.
It turns out that the upstream patch was only released via nix **2.29.0**, thus by removing our patch we regressed that behavior.
This commit reintroduces the patch, while we use nix 2.28.3.
> build: backport fix host attribute in github/gitlab urls

- .github/scripts/remote-execute-integration-tests.sh
- .github/workflows/ci.yml
- codecov.yml
Replace junit report ingress into buildkite via curl, with ingress into CodeCov via their github action.
> feat: Use CodeCov for test analytics

- assets/environment-interpreter/activate/activate.d/zsh
We should use flox-activations profile-scripts to be consistent with all other shells
NA
> refactor: flox-activations profile-scripts for zsh

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/envs.rs
So that it's easier to discover FloxHub functionality. This also
disambiguates the names of remote environments by including their owner.
There's an existing "bug" whereby remote environments that you're
currently or have previously used are listed with their
`~/.cache/flox/remote` directories and they aren't omitted if you
currently have one of them activated due to the way that we cache them
as managed environments.
I'm not attempting to fix that here because I think the fix belongs in
how we model the environments rather than applying fixes to the display
layer.
`flox envs` now shows the FloxHub URLs of remote and managed environments.
> feat(envs): Show URLs for managed and remote

- cli/flox/src/commands/init/mod.rs
- cli/tests/init.bats
So that people can discover the benefits of using FloxHub when creating
new environments. With the exception of environments that are within
existing git repos - detailed in the code comment.
The check is performed early in the `init` command so that traverse
directories to find the git parent doesn't add a noticeable delay
between printing parts of the result message. It shouldn't take long
enough to warrant a spinner though.
The original criteria was to print this notice on the first invocation
of `activate` for an environment and to also exclude temporary
environments (within `$TMPDIR` or name `tmp.*`) but that would have
required adding detection and state tracking to `flox activate` which is
much more sensitive to latency.
We don't need the temporary environment logic in this …
> feat(init): Add push hint when not in git

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/generations/list.rs
- cli/flox/src/commands/generations/mod.rs
- cli/flox/src/commands/mod.rs
Allows to run `flox generations list [<environment>]` to get a listing of all generations of the selected environment.
The generations are currently formatted as
```
* {generation_id}[ (current)]:
Description: {description}
Created: {created}
Last Active: {last_active}
```
> feat: add `generations` category and `generation list` subcommand

- pkgs/nix/default.nix
- pkgs/nix/patches/pr_13340_db_lock_permission_error.patch
I have an upstream PR applying this patch, but it hasn't merged yet, and
even if it does we can apply it in the meantime.
When running as a non-root user using a single-user installation of Nix,
or when the nix daemon crashes, the current error Nix provides doesn't
give much hint for how to solve the issue. The current error for a
`flox install` is:
```
❌ ERROR: Failed to build environment:
Failed to realise 'hello':
error: opening lock file '/nix/var/nix/db/big-lock': Permission denied
```
Prior to our most recent update of Nix, the error included
```
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```
Modify the error to provide some hints at how to solve the problem.
After this patch, the error is:
```
❌ ERROR: Failed to build …
```
> fix: patch Nix for better single user error

- assets/environment-interpreter/activate/activate.d/generate-bash-startup-commands.bash
- assets/environment-interpreter/activate/activate.d/generate-fish-startup-commands.bash
- assets/environment-interpreter/activate/activate.d/generate-tcsh-startup-commands.bash
- assets/environment-interpreter/activate/activate.d/zsh
- cli/flox-activations/src/cli/profile_scripts.rs
- cli/flox-activations/src/shell_gen.rs
- cli/tests/activate.bats
[refactor: use typed Shell for --shell arg](https://github.com/flox/flox/pull/3413/commits/b6f26160060c2508d7080defe2ad00e70e0c1f06)
[b6f2616](https://github.com/flox/flox/pull/3413/commits/b6f26160060c2508d7080defe2ad00e70e0c1f06)
This will error early if an unsupported arg is passed to --shell.
This will make it so upcoming commits that need a Shell object don't
have to add error handling deeper within the logic of flox-activations
profile-scripts
[fix: only run profile scripts once per shell](https://github.com/flox/flox/pull/3413/commits/35a5eec5219b93943e905e60c9c17feda4426998)
[35a5eec](https://github.com/flox/flox/pull/3413/commits/35a5eec5219b93943e905e60c9c17feda4426998)
Use a _FLOX_SOURCED_PROFILE_SCRIPTS shell variable to track when
environment's profile scripts have been run, …
> fix: only run profile scripts once per shell

- cli/flox/src/commands/build.rs
Removing extra "." that resulted in a double ".." in the final comment following a successful build, e.g.:
```
> Completed build of flox-cri-0.1.0 in local mode
>
> ✨ Builds completed successfully.. Output created: ./result-flox-cri
^^
```
N/A
> fix: don't print double ".." upon successful build

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/generations/list.rs
- cli/flox/src/commands/generations/mod.rs
- cli/flox/src/commands/generations/rollback.rs
- cli/flox/src/commands/generations/switch.rs
Allow rollbacks to previous generations (specifically, the generation active before the currently active generation).
Also allow switching to an arbitrary generation via `flox generations switch`.
> feat: add `flox generations {rollback,switch}` commands

- cli/flox-rust-sdk/src/models/manifest/raw.rs
This reverts commit 0ae5c95b4275a6dd347281f5fc8e59fbea1cc095.
We now have a server-side fix in `catalog-server` which prevents badly formed pkg/attr paths from causing errors. They are now treated as literal strings which don't match any known package:
% FLOX_CATALOG_URL=https://api.preview.flox.dev/ nix run github:flox/flox/v1.6.0 -- install -d ~/tmp 'foo.pkg_group = "bar_group"'
❌ ERROR: resolution failed:
Could not find package 'foo.pkg_group = "bar_group"'.
Try 'flox search' with a broader search term.
Implemented in:
- https://github.com/flox/floxhub/pull/303
To be deployed to production in:
- https://github.com/flox/floxhub/pull/305
CLI validation would still be useful if we could do it consistently in `manifest::typed` to handle both imperative and declarative installs, but since …
> Revert "fix(install): Prevent '=' and ' ' in pkg-path"

- buildenv/buildenv.nix
- cli/flox-rust-sdk/src/providers/buildenv.rs
- test_data/manually_generated/buildenv/lockfiles/null_fields/manifest.lock
Don't call `outdentScript` on `null` fields as rendered by older versions of Flox. This doubles up the `getAttr` call but I think that's preferable to more nested conditionals.
I was unable to pull this older environment with Flox versions v1.5.0 and later, but pulls with v1.4.2 and earlier still worked, and so did `activate -r` presumably because it hadn't need to rebuild:
% nix run github:flox/flox/v1.5.0 -- pull dcarley/tailscale
❌ ERROR: Failed to build environment:
Failed to constructed environment: error:
… while calling the 'derivationStrict' builtin
at <nix/derivation-internal.nix>:37:12:
36|
37|   strict = derivationStrict drvAttrs;
|            ^
38|
… while evaluating derivation 'environment'
whose name attribute is located at …
> fix(buildenv): Don't outdent null script fields

- cli/flox-rust-sdk/src/models/environment/generations.rs
This PR adds support for history tracking within the generation metadata file (`medatata.json`).
History is represented as a list of changes that describe the "who, where, when and what" of a change.
Modification of the history are only possible via the new methods on `AllGenerationsMetadata`, which preserve the internal consistency of the metadata.
> feat: add history support to `AllGenerationsMetadata`

- assets/environment-interpreter/activate/activate.d/zsh
- cli/flox-activations/src/cli/fix_fpath.rs
- cli/flox-activations/src/cli/fix_paths.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/prepend_and_dedup.rs
- cli/flox-activations/src/main.rs
**feat: allow appending multiple suffixes to var**
This extends `flox-activations prepend-and-dedup` to allow the
`--suffix` to take multiple values for the situations in which you need
to append multiple suffixes to an environment directory.
> Note: this ended up not being needed since we need to handle fpath/FPATH carefully, but it could still be useful in the future.
**refactor: use flox-activations for zsh fpath**
This change refactors our Zsh init script to use `flox-activations` to
set `fpath`/`FPATH` in a similar way that we use `flox-activations` to
set `PATH`, `MANPATH`, and other `PATH`-like variables.
The main thing to notice here is that since `flox-activations` operates
on colon-separated variables already, we take `FPATH` as an input, but
generate code that sets `fpath`. …
> refactor: use flox-activations for zsh fpath

- cli/flox-rust-sdk/src/models/manifest/raw.rs
The redirect without the trailing slash is broken.
We'll need to fix this for existing manifests that have been generated by `flox init`, but it's not trivial right now, and we can avoid the indirection for newer versions:
- https://github.com/flox/floxdocs/issues/307
We moved the manifest concept to the environments concept for reasons described in the following PR, which I still think make sense:
- https://github.com/flox/floxdocs/pull/226
But if you want to learn more about the manifest then it's probably better that you go to the reference page for that specifically.
N/A
> docs(manifest): Update link in template

- cli/flox-rust-sdk/src/models/environment/generations.rs
Make the error when a generation number can't be parsed slightly more friendly.
Before:
```
> flox generations switch foo
❌ ERROR: couldn't parse `foo`: invalid digit found in string
```
After:
```
> flox generations switch foo
❌ ERROR: couldn't parse `foo`: generations must be referenced by number
```
> fix: make generations switch error more clear

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox/src/commands/generations/history.rs
- cli/flox/src/commands/generations/list.rs
Closes #3500 
* Reserve asterisks for marking the current generation in the `generations list` subcommand (remove from `generations history` entirely)
* Bold the first line of each entry to emphasize the sort order of `generations list` (generation) and `generations history` (date).
* Highlight `(current)` in yellow to visually emphasize what generation is current
* Left-align field values in the `generations list` subcommand (to match the formatting style of `generations history`.
* Ensure the current version has a `Last Active` field (set to `Now`) for consistency with other versions.
* Simplify the v1 migration message to `[metadata migrated]` and move it to the end of the description so it doesn't feel quite so redundant.
https://github.com/user-attachments/assets/64a9ccbc-f510-49e0-ac …
> style: Polish output for generations list and history

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox/doc/flox-generations-list.md
- cli/flox/doc/flox-generations-rollback.md
- cli/flox/doc/flox-generations-switch.md
- cli/flox/src/commands/generations/list.rs
- cli/flox/src/commands/generations/mod.rs
- cli/flox/src/commands/generations/rollback.rs
Use "live" instead of "active" when describing the currently live generation.
Also print "Last Live" in `flox generations list`
Active is overloaded since we have `flox activate`, and "last active"
mean either "last time `flox activate` was run with this generation" or
"last time this generation was the current version of the environment"
Use "live" instead of "current" when referring to generations.
Also print "(live)" instead of "(current)" in `flox generations list`
The word "current" means "most recent" which has an implication about
time.
Because you can switch to an older generation that is not "most recent,"
"current" has some incorrect implications. We avoid the word "latest"
for the same reasons (although with "latest," it's a bit more overt)
Because of it's implications about …
> fix: wording tweaks: {current,active} -> live

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/generations/history.rs
- cli/flox/src/commands/mod.rs
- cli/tests/generations.bats
- cli/tests/push.bats
This will be used by `generations history` to record what command was
used to modify an environment.
update_dummy_env is unused in push.bats
Display the command used to modify an environment in `generations
history`.
This provides a more precise record of how the environment was modified.
Example output:
```
* Date:       2025-08-13 22:55:41 UTC
Author:     author
Host:       host
Generation: 2
Command:    flox install hello
Summary:    installed package 'hello (hello)'
```
NA
> feat: add CLI commands to generations history

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/list.rs
This surfaces the outputs of a package in the `flox list -a` view as shown below.
```
curl:
Description:  Command line tool for transferring files with URL syntax
Package Path: curl
Package Name: curl
Priority:     5
Version:      8.14.1
License:      curl
Unfree:       false
Broken:       false
Outputs:      [ "bin", "dev", "devdoc", "man", "out" ]
ripgrep:
Description:  Utility that combines the usability of The Silver Searcher with the raw speed of grep
Package Path: ripgrep
Package Name: ripgrep
Priority:     5
Version:      14.1.1
License:      [ Unlicense, MIT ]
Unfree:       false
Broken:       false
Outputs:      [ "out" ]
hello:
Description:     Program that produces a familiar, friendly greeting
Locked URL:      github:NixOS/nixpkgs/f962ff8e1bc00582f90509ab8dab04f0bacb6859?narHas …
```
> feat: show package outputs in 'flox list'

- cli/flox-rust-sdk/src/models/environment/generations.rs
435149a1a regressed v1 generations migrations because the old metadata format uses last_active, not last_live.
Restore last_active in the schema for the old metadata format.
NA
> fix: v1 generations migrations

- assets/environment-interpreter/common/etc/profile.d/0800_cuda.sh
- buildenv/buildenv.nix
- buildenv/builder.pl
**fix: follow symlinks in find command**
In the NixOS fallback command for CUDA detection, we crawl the user's
system with a `find` command. On NixOS, however, `/run/opengl-driver`
is a symlink that contains the drivers. Without the `-L` flag, the
drivers are never found on NixOS.
**fix: omit "stubs" output in buildenv.nix**
This is a temporary fix to omit the `stubs` output of packages that
install stub libraries to be used at build time, when other libraries
are needed at run time.
This is a mitigation for an issue caused by our recursive linking:
```
lib-stubs-pkg/
lib/
mylib.so <-- really a stub
stubs/
mylib.so <-- really a stub
lib-pkg/
lib/
otherlib.so
stubs --> lib-stubs-pkg/lib/stubs
FLOX_ENV/
lib/
mylib.so <-- really a stub
otherlib.so
stubs/
...
```
When `lib-stubs-pkg` and …
> fix: omit stub outputs

- cli/flox/src/commands/mod.rs
Allow to run generation commands with both `flox generations` and `flox generation`
> feat(generations): alias as `flox generation`

- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/path_hash.rs
This is an internal command solely for debugging. It prints out a hash of the specified path, or of `$FLOX_ENV` if it's defined. This will be used to figure out which directory in `~/.cache/flox/run` belongs to a specific activation.
N/A
> feat: add hidden path-hash command

- cli/flox/src/commands/services/logs.rs
Allos `flox services logs -f`. Because that's what every tool ever does
We added the overlooked short option `-f` for `--follow`
> fix: allow -f instead of --follow

- cli/flox/doc/flox-services-logs.md
- cli/flox/doc/flox-services-restart.md
- cli/flox/doc/flox-services-start.md
- cli/flox/doc/flox-services-status.md
- cli/flox/doc/flox-services-stop.md
docs: remove double --dir
All our services man pages have `--dir` in them twice, once inline and
once via an include
docs: fix trailing whitespace
NA
> docs: remove double --dir

- package-builder/flox-build.mk
Per https://discourse.flox.dev/t/error-building-with-sandbox/1181,
`git ls-files` doesn't always sort, which will cause `comm` to fail
```
git init
$ touch ABcd Aa aBc ab aaa
$ git add .
$ git ls-files
ABcd
Aa
aBc
aaa
ab
$ git ls-files | sort
Aa
aaa
ab
aBc
ABcd
$ sort --version
sort (GNU coreutils) 9.7
Packaged by https://nixos.org
```
Fixed bug where `flox build` and `flox publish` would fail in certain git repos with 
```
comm: file 1 is not in sorted order
comm: input is not in sorted order
```
> fix: sort before calling comm

- buildenv/builder.pl
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- package-builder/flox-build.mk
Set outputs to install with list context rather than scalar context.
Manifest builds are now published with empty outputs_to_install. This reaches previously unreached code that sets outputs_to_install to all outputs. Currently this leads to an error:
```
❌ ERROR: Can't use string ("1") as an ARRAY ref while "strict refs" in use
```
This is because the current line
```
$package->{"outputs_to_install"} = keys %{$package->{"outputs"}};
```
is making an assignment in scalar context, which sets $package->{"outputs_to_install"} to the number of keys in outputs instead of the actual keys.
NA
> fix: buildenv empty outputs_to_install bug

- cli/flox-rust-sdk/src/models/environment/generations.rs
Suggest that the user upgrades their version Flox if we encounter a
metadata version that is unknown by the current version.
This makes it clearer that the environment has been modified by a newer
version and what they need to do to resolve it, rather than suggesting
that it's been corrupted.
NB: This varies slightly from the original suggestion in the ticket.
I've kept the original error as the first line because it contains the
found version which may be useful when debugging support requests.
Error handling further up the stack will take care of the trailing
newline so it's not included in the assertion string.
Improve error messages for future generations metadata changes.
> fix(generations): Unknown version suggest upgrade

- .github/workflows/ci.yml
**fix(ci): CodeCov from merge queue**
Send test reports to CodeCov when running from the merge queue. It seems
this conditional may have been a mistake because we set it at the same
time as forcing both runs to have the same `branch_name`, so that the
results are collated together, but excluded the merge queue from runs.
Before that change:
- commit: 87b38f1
- merge: https://github.com/flox/flox/actions/runs/16978182037/job/48132841669
- push: https://github.com/flox/flox/actions/runs/16978656531/job/48133848083
After that change, job skipped:
- commit: bdc2728
- merge: https://github.com/flox/flox/actions/runs/16978824316/job/48134381261
- push: https://github.com/flox/flox/actions/runs/16979135480/job/48135251182
**refactor(ci): Unset override_branch**
This defaults to `main` on both …
> fix(ci): CodeCov on merge queue and unset defaults

- assets/environment-interpreter/activate/activate.d/generate-bash-startup-commands.bash
- assets/environment-interpreter/activate/activate.d/zdotdir/.zlogin
- assets/environment-interpreter/activate/activate.d/zdotdir/.zprofile
- assets/environment-interpreter/activate/activate.d/zdotdir/.zshenv
- assets/environment-interpreter/activate/activate.d/zdotdir/.zshrc
- assets/environment-interpreter/activate/activate.d/zsh
- cli/Cargo.lock
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/cli/profile_scripts.rs
- cli/tests/activate.bats
Fix the (newly added) failing test for zsh with the suggestion:
> An alternative would be exporting a variable similar to what we already do with _flox_already_sourcing_bashrc and use that to so that activations in RC files only source profile scripts for FLOX_ENV. Using env variables to communicate between two activations seems error prone, but it’s been working okay for bash
I explored this other suggestion for a while, which would be preferable,
but the recursion and identifying the number of places it *might* break
which we might not have test coverage for broke my head:
> Although for the first half of the proposal, the suggestion is not adding to FLOX_ENV_DIRS until after starting userShell. I don’t think we can do that without a decent amount of re-work, because etc-profiles, which …
> fix(activate): zsh profile script modify PATH

- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- package-builder/flox-build.mk
We were inconsistent in the system used for publish.  This change passes the system actually used for the build back to the CLI in the build outputs, and uses that for publish, eliminating the multiple paths of interpreting the system override command line argument.
Publish for the correct system when using `flox publish --system <override>`
> fix: use built system for publish

- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
Change tempdir cleanup behavior:
On startup, flox creates a main tempdir in `$FLOX_CACHE_HOME/process` for the lifetime of the process.
During normal usage, this directory is deleted after the process terminates.
Before this change, the deletion was skipped _iff_ flox was called with one or more `-v` flags.
However, in environments where flox is always being run with internal logs enabled,
no cleanup ever happens causing tempdirs to pile up.
This change adds a new config options `keep_tempdir`, which has to be set to true to enable the old behavior. without this flag, or the flag set to `false`, tempdirs are now always deleted.
Additionally this change consolidates the cleanup run after successful completion, and upon signals, to avoid unnecessary duplication.
> refactor: always cleanup tempdirs

- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/manifest/typed.rs
Extend the include descriptor for remote environments, with an optional `generation` field:
```
IncludeDescriptor::Remote := {
remote: string (serialization of EnvironmentRef)
name?: string
generation?: number
}
```
If the generation is provided, flox will attempt to retrieve a lockfile for this generation instead of the upstreams "live" generation.
Likewise on `flox include upgrade` the lock for such pinned environments
should remain unchanged.
To allow this, this PR adds a new `lockfile_contents_for_generation` method to the `GenerationsExt` trait (which is implemented for generation supporting environments).
> [!NOTE]
> #2840 mentioned to alternatively fold generation specifiers into `EnvironmentRef`.
> Format and use (e.g. in activate) has not been discussed since,
> so for this i …
> feat: allow pinning included remote environments to generation

- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/restart.rs
- cli/flox/src/commands/services/start.rs
- cli/tests/services.bats
This is a prep patch refactoring some code and adding a skipped test. I'll make the actual fix once I'm not concerned about merge conflicts with contents of _FLOX_ACTIVE_ENVIRONMENTS.
Currently running `activate -m run` followed by `services start` will run a dev mode activation to start services.
Additionally, we have a bug that activations will stop services started by an activation of a different mode.
This means that `flox services start` for a run mode default environment will start a dev mode activation that exits immediately and stops services.
To fix that case, detect the mode of the active environment when running `services start` and run our ephemeral services activation in that mode.
NA
> refactor: prep to respect activation mode

- assets/environment-interpreter/activate/activate.d/attach-command.bash
- assets/environment-interpreter/activate/activate.d/attach-inplace.bash
- assets/environment-interpreter/activate/activate.d/attach-interactive.bash
- assets/environment-interpreter/activate/activate.d/generate-bash-startup-commands.bash
- cli/tests/activate.bats
This change skips loading `~/.bashrc` for in-place activations with the assumption that it has already been sourced by the shell doing the in-place activation. This prevents the following sequence of events that sources `~/.bashrc` twice.
- Add an in-place activation of the default environment to `bashrc`
- Create a new bash shell
- Shell loads `bashrc` (1)
- `bashrc` initiates the in-place activation
- `_flox_sourcing_rc` is unset at this point, so source `bashrc` (2)
- Finish the activation
- Finish the original sourcing of `bashrc`
For reviewers, this required some changes to a couple of tests. Bash only loads `~/.bashrc` when interactive, but our activation code was loading `bashrc` regardless, so some tests that perform a `bash -c <cmd>` no longer load `bashrc` and therefore no …
> fix: skip sourcing ~/.bashrc for in-place

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
We stopped calling a background `nix store delete` for manifest builds (and later NEF builds) to workaround a Nix daemon GC bug:
- 29076c43e96b54df6954029a9771015a3f66b559
But we didn't apply this to manifest builds that use the sandbox, for reasons that are unclear to me. Doing so means that they won't be subject to the same bug and allows us to dramatically speed up the tests by removing serialisation.
Before:
Summary [ 288.125s] 83 tests run: 83 passed (3 slow), 661 skipped
After:
Summary [  69.784s] 83 tests run: 83 passed, 661 skipped
I verified that the tests still failed prior to this change and without serialisation. So we still have the underlying bug.
I've inlined and commented the differences between the two targets into one to make it clear that we're not using the other …
> fix(build): No nix store delete for sandbox clean

- cli/Cargo.lock
- cli/flox/Cargo.toml
- cli/flox/src/commands/generations/history.rs
- cli/flox/src/commands/generations/list.rs
- cli/flox/src/utils/message.rs
The output from `generations list` and `generations history` can get
very long and spam the terminal for older environments that have lots of
generations.
The pager isn't invoked if the output would fit in the terminal, the
terminal isn't interactive, or the `--no-pager` argument is given.
Output has been reversed so that the most recent items appears at the
top of page. This behaviour doesn't change when not using a pager,
partly because we don't have control over when the pager decides to
page, but it's also consistent with how `git log` works.
This library seemed like a good choice and less fiddly than invoking an
external pager. There hasn't been a recent release but it looks pretty
feature complete. There are a few open issues but:
- I can't reproduce any problem with tracing
- text …
> feat(generations): Page output from list+history

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/commands/push.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-managed.bats
* feat: include diverged metadata states in error message
Include generation, timestamp and summary of both the local and remote generation history
if they are detected to diverge during `flox push|pull`.
```
❌ ERROR: The environment has diverged from the remote:
Local:
* yannik installed package 'iputils (iputils)' on Yanniks-NUC
Generation:  4
Timestamp: 2025-10-01 12:25:49 UTC
Remote:
* yannik installed package 'gum (gum)' on Yanniks-MacBook-Pro.local
Generation:  4
Timestamp: 2025-10-01 12:25:15 UTC
This can happen if the environment is modified and pushed from another machine.
To resolve this issue, either
* run 'flox pull --force'
to discard local changes
and reset the environment to the latest upstream version.
* run 'flox push --force'
to overwrite the remote environment with the …
```
> feat: show diverged metadata on `flox push|pull` with diverged history
