- flake.lock
Before
```
❯ nix flake metadata
Resolved URL:  git+file:///Users/rok/dev/flox
Locked URL:    git+file:///Users/rok/dev/flox?ref=refs%2fheads%2fbuild%2fmoving-things-around-part4&rev=6801b1370483dc15505e1e3c8740efe5d8ea4294
Description:   Floxpkgs/Project Template
Path:          /nix/store/bh6wxd70b905nlmyqjvn232wd4xj8777-source
Revision:      6801b1370483dc15505e1e3c8740efe5d8ea4294
Revisions:     457
Last modified: 2023-05-10 14:21:29
Inputs:
├───capacitor: github:flox/capacitor/9d4b9bce0f439e01fe2c2b2a1bfe08592a6204c4
│   ├───nixpkgs: github:flox/nixpkgs/60c1d71f2ba4c80178ec84523c2ca0801522e0a6
│   └───nixpkgs-lib: github:nix-community/nixpkgs.lib/367c0e1086a4eb4502b24d872cea2c7acdd557f4
├───nixpkgs-flox: github:flox/nixpkgs-flox/c3a93944d96c39f79a8704c4c7feba1aaad52727
│ …
```
> build: flake lock bump, to get rid of floxpkgs in flake graph

- flake.lock
- flake.nix
The rename is needed to be compatible with `--override-input` that is happening with in flox CLI.
Originally the input was already called `nixpkgs` but we renamed it to `nixpkgs-flox` forgetting that flox CLI depends on it.
> build: Rename flake input `nixpkgs-flox` to `nixpkgs`

- flox-bash/Makefile
This got missed in the repo merge
> fix: result target should build flox-bash

- .github/scripts/release.sh
- .github/workflows/release.yml
* Harden release script
add set -euxo pipefail to the release ci script to correctly fail early in CI.
* Fixes regarding pushing of "latest" branch.
Since we push a "tag" to a branch we have to "unpeel" the tag
to get to the referenced commit, which is what we push to the branch ref.
unpeeling looks like the following:
given a tag `v0.2.0`, unpeel to commit as `+v0.2.0~0`
* Push to release pr branch to close the PR
There is likely a way to properly show the PR as merged (i've seen it before)
but for now we keep on closing the PR instead.
The new order of closing PR branches should also make error recovery easier.
* Add some documentation to the release script
> fix: pushing tag as "latest" branch

- pkgs/flox-bash/default.nix
- pkgs/flox/default.nix
The rust flox reads the version from cargo.toml, which in turn is updated by commitizen on release
Flox package version changes from `flox-A.B.C-rXXX-U.V.W-rYYY` and `flox-U.V.W-rYYY` to `flox-A.B.C-rXXX` and `flox-bash-A.B.C-rXXX` respectively.
> build: fix flox package versions

- pkgs/flox-bash/default.nix
Following the merge of the flox-bash codebase into flox the build started failing as noted below and we found that performing the `patchShebangs` invocation in a subshell works around the problem.
The stdenv setup hook is throwing the following build error on x86_64-linux:
```
/nix/store/...-stdenv-linux/setup: line 136: pop_var_context: head of shell_variables not a function context
```
N/A
> flox-bash: update build to avoid stdenv setup bug

- pkgs/flox-bash/default.nix
This solution is confirmed to work with a build of flox; the last patch was only tested to build flox-bash.
> build(flox-bash): update build to avoid stdenv setup bug take two

- crates/flox/doc/flox-activate.md
- flox-bash/lib/commands/activate.sh
- flox-bash/tests/integration.bats
- flox-bash/tests/package.bats
- pkgs/flox/default.nix
`FLOX_ENV` is now set properly while each activation script is run, and after activation completes `FLOX_ENV` is set to the path associated with the "target" environment indicated on the CLI.
Currently all activation scripts run with `FLOX_ENV` set to the default environment.
N/A
> flox-bash: fix FLOX_ENV for multiple envs

- flox-bash/lib/commands/environment.sh
The move to bare repositories broke the ability to checkout the floxmain branch, and that in turn broke the logic in `flox destroy` to delete environment branches.
This patch fixes the issue by removing the requirement to check out the "floxmain" branch prior to destroying the environment branch. In previous versions we performed this checkout as a way of guaranteeing we would never attempt to delete the currently-checked-out branch.
Fixed bug which prevented `flox destroy` from fully deleting environment metadata.
> [BUG] repair `flox destroy` ability to fully remove branch metadata

- .github/workflows/release.yml
Include the "latest" branch in the atomic push operation that pushes the version tag and "main" branch. latest must not divert from main anyway, and can be fast-forwarded
We currently do 3 pushes to github
1. for version tag and main
2. for the latest branch (force)
3. for to close the release PR
Since were fast-forwarding anyway, the latest branch can be pushed atomically with main and the version tag
> build: push all release branches in a single atomic operation

- flox-bash/tests/integration.bats
- flox-bash/tests/test_support.bash
Skip AWS test when the necessary variables are unset.
This test always fails.
N/A
> fix: skip aws test

- .github/workflows/ci.yml
This will `flox build` all 3 packages:
- `flox`
- `flox-bash`
- `nix-editore`
`flox` is installed using https://github.com/flox/install-flox-action.
Yes there is no caching and will be slow, but this should kick us to do something about it.
> build: add very basic CI check

- crates/flox/src/utils/init/mod.rs
`gh` introduced support for storing credentials in an encrypted keyring about 3 months ago ([1])
If stored in a keyring the `oauth_token` field in the hosts.yml file will remain empty. We previously relied on that field to be present, drawing only from observations due to the lack of documentation on the schema of `hosts.yml`.
Since reading the hosts.yml file is no reliable source for the user's access token anymore, we should either employ
gh auth token --hostname <host>
or REVISIT THE USE OF `gh` ALTOGETHER.
[1] https://github.com/cli/cli/commit/df83dc2d58f242fc368fa62656d410e5fd820f6e
fixes #44
fixes #22
> fix(gh): allow missing oauth_token

- flake.lock
- flake.nix
- flox-bash/Makefile
- flox-bash/lib/catalog-search.jq
- flox-bash/lib/commands/general.sh
- flox-bash/lib/search.jq
- flox-bash/lib/searchJSON.jq
- flox-bash/tests/package.bats
- flox-bash/tests/semver-search.bats
- flox-bash/tests/test_support.bash
- pkgs/flox-bash/default.nix
- pkgs/semver/default.nix
Extends `flox search` to support semantic version range filtering such as:
```console
$ flox search hello@2;
hello - A program that produces a familiar, friendly greeting
stable.nixpkgs-flox.hello@2.10
stable.nixpkgs-flox.hello@2.12
stable.nixpkgs-flox.hello@2.12.1
staging.nixpkgs-flox.hello@2.10
staging.nixpkgs-flox.hello@2.12
staging.nixpkgs-flox.hello@2.12.1
unstable.nixpkgs-flox.hello@2.10
unstable.nixpkgs-flox.hello@2.12
unstable.nixpkgs-flox.hello@2.12.1
$ flox search 'hello@^2.12';
hello - A program that produces a familiar, friendly greeting
stable.nixpkgs-flox.hello@2.12
stable.nixpkgs-flox.hello@2.12.1
staging.nixpkgs-flox.hello@2.12
staging.nixpkgs-flox.hello@2.12.1
unstable.nixpkgs-flox.hello@2.12
unstable.nixpkgs-flox.hello@2.12.1
```
Users are unable to filter search results …
> feat: Add semver range parsing to `flox search`

- flake.nix
The nixpkgs "follows" statement in flake.nix was breaking flake updates of
the floxpkgs-internal pkgset, and is not necessary when building with flox.
Comment out the "follows" statement to get other updates flowing over the
long weekend and we'll revisit this next week.
N/A
> fix: disable inputs.nixpkgs.follows in flake.nix

- crates/flox-rust-sdk/src/flox.rs
Since we run nix with stderr attached to the user terminal, with the current verbosity levels users face unnecessary amounts of (internal) logs emitted by nix.
In particular resolving package targets is noisy and to the detriment of the user experience.
This PR lowers the default verbosity level for _all_ nix calls by two levels (`nix --quiet --quiet`) which suppresses warnings informing about flake overrides.
This change should be revisited if it turns out we are losing too much information by suppressing certain levels of logging output or we want to approach more fine grained nix output parsing.
> fix(nix): lower verbosity of nix subprocesses

- flox-bash/lib/init.sh
- flox-bash/lib/metadata.sh
- flox-bash/lib/utils.sh
We are no longer checking out branches of the floxmeta repository in situ and are instead performing all manipulations using a bare repository. With that we no longer need to call gitCheckout() from metaGit(), after which that function is no longer used at all.
Also pared an invocation of metaGit() that was never being performed on account of $_cline never being defined in that scope.
Closes #51 
See #51 
Fixed bug preventing `flox export` from working for users who hadn't already been using older versions of flox.
> fix: deprecate gitCheckout()

- crates/flox/doc/flox-activate.md
- crates/flox/src/commands/environment.rs
- flox-bash/.github/workflows/gpg-test.yml
- flox-bash/flox.1.md
- flox-bash/lib/commands/activate.sh
- flox-bash/tests/usage.out
- shells/flox/default.nix
Using `source <(flox activate)` breaks in zsh shells.
flox checks for updates of the current environment and issue an interactive prompt to apply possible updates.
In zsh `<(_)` attempts to read from stdin will block forever:
> The = form is useful as both the /dev/fd and the named pipe implementation of <(...) have drawbacks. [..]
> In the second case, if the programme does not actually open the file,
> the subshell attempting to read from or write to the pipe will
> (in a typical implementation, different operating systems may have different behaviour)
> block for ever and have to be killed explicitly. In both cases,
> the shell actually supplies the information using a pipe,
> so that programmes that expect to lseek (see lseek(2)) on the file will not work. …
> docs: use `eval` to `flox activate` in the current shell

- crates/flox/src/utils/init/mod.rs
- flox-bash/lib/init.sh
- flox-bash/tests/integration.bats
Unify the output during config generation. Skipping before checking nix.conf output.
Differences in bash and rust testing can cause failures.
n/a
> test: unify informative output during config generation

- flox-bash/tests/integration.bats
- flox-bash/tests/multi-env.bats
- flox-bash/tests/package.bats
- flox-bash/tests/semver-search.bats
Separate `flox activate -e foo -e bar` "multi-env" tests to separate file.
This largely acts as a model for separating similar test collections.
These tests currently reside in `integration.bats`.
Failures match existing failures.
No tests are fixed or broken, they are only reorganized.
N/A
> test: separate multi-env tests to separate file

- pkgs/flox-bash/default.nix
- pkgs/flox-src/default.nix
- pkgs/flox/default.nix
filter the source to be less sensitive to test suite iteration. Note that this will still create a distinction between dirty and clean builds due to the revision count injection, but otherwise should make it easier to work on the tests
any change to the repo creates a rebuild
N/A
> fix: sanitize source to minimize rebuild

- flox-bash/lib/commands/development.sh
The placement of --impure within the floxBuild() function meant that it also applied to nix builds happening by way of flox publish invocations. This patch moves the flag to the [1] place where we are calling floxBuild to build flox environments, which do require the use of --impure.
Note that flox build as called from the top-level flox-bash/flox.sh is handled by rust, so that use of the floxBuild() function is not relevant.
Fixed obscure bug affecting the correctness of flox publish when working with impure inputs.
> fix: don't invoke nix build with --impure flag when publishing

- flox-bash/lib/commands/general.sh
The output of `flox channels` was broken with a recent commit, returning only the first in a list of channels.
This patch replaces the use of `read` with `mapfile` to parse all the channels instead of just the first.
The patch also removes a block of utility command fallback assignments not required for the production version that had temporarily been added for testing.
Fixed bug with `flox channels` command returning only the first in a list of channels.
> fix: repair broken `flox channels`

- flox-bash/tests/bads.bats
- flox-bash/tests/integration.bats
Any test cases which failed in CI were disabled ( migrated to a separate file and commented out ) with little or no attempt to reform them.
Any tests that failed as a result of removing aforementioned tests ( in the vast majority of cases because they contain hard coded generation numbers ) were also disabled with little or no attempt to reform them.
This PR will turn CI green.
Any tests that wish to be re-enabled will only do so when they are green in CI.
Rather than complaining about a test being removed - fix it if you feel that it is important.
In the future tests should never:
1. depend on the runtime state of other tests unless they are organized in a dedicated file with a valid explanation inline for why this dirty state requirement is necessary.
2. "Snapshot tests" which hard code …
> fix: disable any test cases that make CI red

- .github/workflows/ci.yml
- flox-bash/lib/commands/activate.sh
- flox-bash/lib/utils.sh
- pkgs/flox-tests/default.nix
- tests/activate.bats
- tests/integration.bats
- tests/progs.bats
Adds support for `dash` shell.
Adds tests for `flox activate` run with `zsh`, `bash`, and `dash`.
TODO: test `bash` v{3,4,5}.x explicitly.
Tests currently adopt whatever the running shell is, in CI this is often `bash`.
Adds support for `dash` shell.
The recommended invocation of `flox activate` and `flox print-dev-env` non-interactively has been changed in order to support shells such as `dash` and `zsh`.
The recommended way to activate environments from a script is now:
```shell
eval "$( flox activate -e <NAME>; )";
eval "$( flox activate -e default; )";
eval "$( flox print-dev-env '.#<NAME>'; )";
eval "$( flox print-dev-env '.#default'; )";
```
> fix: support dash shell, add flox activate tests for dash, bash, and zsh

- pkgs/flox/default.nix
Use rev independent version for deps and rev dependent one for the flox package.
Previously this was mistakenly set the other way around
> fix: set correct version variables

- flox-bash/lib/registry.jq
Sorts generations numerically.
Generations are sort lexicographically so you get `[1, 11, 2]` not `[1, 2, 11]`.
`flox generations` command now sorts results numerically.
> style: sort generations numerically

- flox-bash/lib/metadata.sh
- flox-bash/lib/utils.sh
Call `gh auth login` with a stub `$GIT_CONFIG_GLOBAL` to avoid inadvertently writing user config files.
We do not want the use of flox to modify anything about the user's personal gitconfig, but we recently found that the mere act of invoking `gh auth login` mutate's the user's own global git config ($GIT_CONFIG_GLOBAL =? ~/.config/git/config or ~/.gitconfig):
```
$ cat ~/.config/git/config
[user]
name = ""
email = ""
$ gh auth login
...
$ cat ~/.config/git/config
[user]
name = ""
email = ""
[credential "https://github.com"]
helper = 
helper = !<path to gh> auth git-credential
[credential "https://gist.github.com"]
helper = 
helper = !<path to gh> auth git-credential
```
`gh` does not provide an option to disable this behaviour but obeys to `GIT_CONFIG_GLOBAL`
Work around behaiour of an …
> fix: avoid gh writing to git config files on user's behalf

- crates/flox/doc/flox-activate.md
- flox-bash/lib/templateFloxEnv/pkgs/default/flox.nix
This commit updates the default floxEnv template to enable logic to source the etc/profile file if it exists within the flox environment, and adds instructions for installing the "etc-profiles" package that provides the language-specific modules which drive the process of configuring the environment.
Updated default flox environment template in support of new environment initialization features.
> feat: source floxEnv `etc/profile` upon activation

- flox-bash/flox.sh
- flox-bash/lib/bootstrap.sh
- flox-bash/lib/commands/activate.sh
- flox-bash/lib/utils.sh
* exit if selection required without tty
Let `selectAttrPath` raise an error if more than one option exist but we can't prompt users.
* exit if choosing a package 
Fail `selectAttrPath` if `gum choose` command failed.
This can be either due to an error in gum or (more importantly) an explicit interrupt by the user.
This change was originally motivated by providing better errors for `flox activate`, but since `selectAttrPath` is used by several commands all of them will benefit from it.
> fix(flox-bash): make  `selectAttrPath` more resilient

- .github/workflows/ci.yml
- pkgs/flox/default.nix
Explicitly copy compiled cargo deps to binary cache - a second try at speeding up CI
> ci: cache cargo deps

- tests/develop.bats
- tests/develop/devShell.exp
- tests/develop/develop-fail.exp
- tests/develop/develop.exp
- tests/develop/toplevel-flox-nix.exp
Fetch and eval `flox develop` work-spaces before running `expect`.
More portable form of "find absolute path to my executable": `which foo` -> `command -v foo||which foo||type -P foo`.
Tests fail in a non-deterministic fashion based on cache warmth and network connection speed by timing out `expect` sleeps.
Some tests fail when the user's shell is `zsh` or `dash`.
N/A
> test: avoid non-determinism in develop tests

- crates/flox/doc/flox-edit.md
- crates/flox/src/commands/environment.rs
- flox-bash/lib/commands/environment.sh
- tests/edit.bats
- tests/test-flox.nix
--file allows replacing the environment declaration with the contents of a file, or it reads from stdin if - is passed
> feat: add --file|-f option to flox edit

- pkgs/flox/default.nix
Add `LIBSSH2_SYS_USE_PKG_CONFIG=1` to the `cargoArtifacts` build.
Missing this causes build failure as cargo tries to build libssh from source which involves cloning git submodules into the r/o nix store path.
> fix: enforce using system ssl for rust ssl bindings

- CONTRIBUTING.md
- tests/README.md
Update CONTRIBUTING.md and README.md files with shorter `flox run '.#flox-tests' ...` invocations.
Current docs recommend `flox shell` and are longer/uglier.
N/A
> test: update readme/contributing with shorter flox run invocation

- flox-bash/flox.sh
Invocations of `flox activate` where the invoked command contained an `-e` argument were failing as in the following example:
$ flox activate -e foo -- python -e 'import foo'
ERROR: environment "import foo" cannot contain whitespace
This patch adds logic to stop parsing args at the "--" delimiter as found in argv.
Fixed bug in the parsing of command arguments passed to `flox activate`.
> fix: stop parsing activate args at "--" delimiter

- flox-bash/lib/utils.sh
The trace() function was echoing a string containing an unquoted embedded pprint() invocation, and the resulting string was being globbed to the empty string on account of `shopt -s extglob`. This problem was evident when running `flox --debug --debug` as in the following example (look at the end of the line beginning `trace:`):
$ flox --debug --debug destroy -e foo |& grep "Are you"
+ boolPrompt 'Are you sure?' no
+ trace 'Are you sure?' no
trace:/nix/store/8x517fn3ckdgj4p013hnbyl91wsg9g0f-flox-bash-0.2.3-r532/lib/commands/environment.sh:1365 boolPrompt( 'Are you no )
+ local 'prompt=Are you sure?'
This patch removes a pair of quotes so that the output of pprint() is quoted, thus preventing the glob'ing from removing arguments. With this patch in place the above example shows:
$ flox …
> trace(): remove unnecessary quotes from echo invocation

- flox-bash/lib/commands/environment.sh
- flox-bash/lib/templateFloxEnv/flake.lock
- tests/integration.bats
We made changes to how flox envs substitute binaries in flox/floxpkgs#143.
This PR updates the lockfile of the flake template used to create new environments and CoW modifications to existing environments.
> fix: bump flox env template

- flake.lock
- flox-bash/lib/commands.sh
- flox-bash/lib/commands/development.sh
- flox-bash/lib/commands/environment.sh
Enable parsing and passing of nix flake related options to flox environment-related commands. In particular this facilitates the testing of flox-floxpkgs library changes with:
$ flox install foo --override-input flox-floxpkgs ~/wherever
flox subcommands updated to accept flake-related options for the building of flox environment packages.
> feat: pass nix flake args to environment subcommands

- flox-bash/lib/commands/publish.sh
- flox-bash/lib/utils.sh
Minimal changes were made since I anticipate a lot of work in the near future surrounding publish; but this at least enables non-interactive usage of `flox publish` which is a necessary prerequisite for automated testing.
This change causes `flox publish` to throw an error rather than hang waiting for an interactive prompt in cases where mandatory arguments were omitted, or there is a dirty git tree.
Additionally it is possible to omit certain arguments by passing the empty string; specifically `--upload-to` and `--download-from`.
Minor fixes to fallback variable expansion and the use of `mapfile` instead of `array=( $(...) )` were also made.
Currently prompts prevent the user from publishing without certain optional args.
Additionally if there is a dirty git repo prompts will be launched …
> fix: publish non-interactively

- flox-bash/lib/commands/publish.sh
When publishing from branches other than the default branch, the flakeref url constructed within `floxPublish` will contain a `?rev` pointing to a revision outside the main branch.
In these cases nix requires that a either `?ref=67e0617635fae9779247e9a5d660285bb92afe24` or `?allRefs=1` is specified.
> fix(publish): add `allRefs=true` to all built flakerefs

- flake.lock
- flox-bash/lib/commands/publish.sh
- flox-bash/lib/utils.sh
- pkgs/flox-bash/default.nix
Include builtfilter into flox-bash closure at "compile" time.
This is a temporary effort to get CI publish working while we pursue integrating builtfilter into flox itself.
> build: include builtfilter in flox-bash closure

- pkgs/flox-bash/default.nix
Pull in builtfilter from the shared capacitated context rather than as an independent input.
> fix: pull in builtfilter from the capacitated context

- flox-bash/lib/utils.sh
The recent cleanup broke reporting of pertinent env variables set during nix invocations. This patch repairs that and also fixes an issue relating to the printing of env variable contents containing spaces.
Revise code which iterates over of `${exported_variables["$1"]}`. Add a `pprint()` call to quote the value of environment variables when necessary.
Verbose output (as shown with `flox -v`) no longer displays the pertinent environment variables for `nix` invocations. Invoke `flox -v upgrade` or similar to view a sample `nix build` invocation which should have a number of environment variables displayed, starting with `NIX_REMOTE=`.
N/A
> fix: repair environment variables displayed with `nix` invocations

- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/Cargo.toml
- crates/flox-rust-sdk/src/models/mod.rs
- crates/flox-rust-sdk/src/models/publish.rs
- pkgs/flox/default.nix
Implement scaffolding for the `Publish` command and provides eval time analysis.
`Publish<State>` holds common data required during all phases of the publish,
as well as a typestate that contains phase specific data, ie.e (partial) snapshots.
Additionally we introduce a custom flakeref group; `PublishFlakeRef`s.
A `PublishFlakeRef` is a reference to an upstream git repo.
It is indirectly created by resolving `FlakeRefs` to `git+_` flakerefs if possible.
The current implementation provides trivial conversions for `git+{https,ssh}.
More are being worked on separately as part of the publish efforts.
> feat: init `Publish` structure

- flox-bash/lib/catalog-search.jq
The key returned by nixPkgToCatalogPkg is used as the key in a $_jq -r -s add invocation. Because add overwrites the value for previous keys, this overwrites values for previous stabilities.
Based on comments, this bug was likely just a typo.
> fix(search): don't overwrite stability entries

- Cargo.lock
- Cargo.toml
https://github.com/flox/runix/pull/28 introduced important fixes to the flakeref parser required for publish and improving convenience for users across nix'y commands.
> build(dep): update runix

- flake.lock
- flake.nix
Bump `parser-util` to pull in fixes for Darwin.
`parser-util` fails to build on Darwin systems.
N/A
> chore: bump parser-util v0.1.0 -> v0.1.1

- Cargo.lock
- crates/flox-rust-sdk/src/actions/environment.rs
- crates/flox-rust-sdk/src/actions/package.rs
- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/lib.rs
- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/flox_package.rs
- crates/flox-rust-sdk/src/models/floxmeta/environment.rs
- crates/flox-rust-sdk/src/models/project/environment.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox-types/src/catalog/cache.rs
- crates/flox-types/src/catalog/element.rs
- crates/flox-types/src/catalog/eval.rs
- crates/flox-types/src/catalog/mod.rs
- crates/flox/src/commands/package.rs
- crates/flox/src/utils/mod.rs
runix split Installable into an enum with FlakeAttribute and StorePath.
Refactor all occurrences of Installable to instead be a FlakeAttribute.
Depends on https://github.com/flox/runix/pull/30
> refactor: use FlakeAttribute

- crates/flox-rust-sdk/src/models/publish.rs
Converts `github:<owner>/<repo>` flake refs to `git+https` references as inspired by [`GithubInputScheme::clone`](https://github.com/NixOS/nix/blob/fe1fbdb5a14a059763fcc7434f2cd1e483dc00e6/src/libfetchers/github.cc#L299C6-L299C6).
May eventually support ssh as well as through a toggle.
> feat: convert `github:` references to `git+https`

- flake.lock
Upgrade `parser-util` to `0.1.2`.
We use `parser-util` at `0.1.1`.
N/A
> chore: parser-util 0.1.1 -> 0.1.2

- crates/flox-rust-sdk/src/actions/package.rs
- crates/flox-types/src/stability.rs
- crates/flox/src/commands/general.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/package.rs
- tests/reliability.bats
Do not perform a stability override by default.
Simple commands perform a speculative nixpkgs update, ignoring existing lockfiles and making it difficult to replicate behavior.
Fixes: https://github.com/flox/product/issues/301
Note: stability overrides now require the use of `--stability` instead of always overriding to "stable".
> feat: no stability override by default

- .github/CONTRIBUTORS.csv
- crates/flox/doc/flox-init.md
Fix spelling typo: change "creat" to "create" in the template description. 
Spelling error: "creat"
N/A
> fix: typo in template description

- crates/flox-rust-sdk/src/models/publish.rs
Add a method on `Publish<NixAnalysis>` that can be used to copy binaries to a cache.
* feat: impl copy binaries during publish
* refactor: extract `store_paths` method
> feat: impl copy binaries during publish

- .github/CONTRIBUTORS.csv
- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/Cargo.toml
- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox-types/Cargo.toml
- crates/flox/Cargo.toml
- crates/flox/src/commands/mod.rs
- flake.lock
- pkgs/flox/default.nix
This PR uses the new URL/flake reference parser recently added to `runix`. With this change several flake reference parsing bugs will solve themselves.
This PR also moves all dependencies to the `[workspace.dependencies]` section of the top level `Cargo.toml` as explained in [the Cargo Book](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table). The benefit is that all workspace crates that depend on a crate `FOO` will now receive the same version of `FOO` rather than each workspace crate pinning `FOO` separately (and potentially falling out of date). Another benefit is that you no longer need to bump `FOO` in each workspace crate individually, it only needs to be bump in the top level `Cargo.toml`.
- Dependencies are specified separately in each crate
- Flake …
> feat: use runix's new url parser in flox

- crates/flox-rust-sdk/src/models/publish.rs
Add library function to sign the published package before uploading to binary cache.
Leaves validation of the signing key and package to the nix call.
> feat(publish): sign published package

- pkgs/builtfilter-rs/default.nix
Create a separate store path for the builtfilter package, for faster build times.
The build closure for the builtfilter output includes `self` so builtfilter will be rebuilt with every commit, regardless of changes to its source.
> build: do not include entire repo in build closure of builtfilter-rs

- crates/flox/src/utils/init/mod.rs
- flox-bash/lib/commands/general.sh
- flox-bash/lib/utils.sh
This fixes a few stray messages in the flox search (and other) output.
* We now use `GREP_COLORS` instead of the obsolete `GREP_COLOR`
* Errors about non-existent attribute (caused by searching stabilities that don't exist) are filtered out
* The message about missing `oauth_token` in gh hosts.yml is now at debug level instead of warn, as it doesn't represent a problem and there's nothing the user can do about it (this one affects _every_ flox invocation, not just search)
> fix: cleaner output for flox search

- flox-bash/lib/commands/environment.sh
Removes the printing of builds that occur during install.
Verbose output of the buildEnv wrappers.
N/A
> fix: remove spurious print-build-logs

- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/src/actions/package.rs
- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/flox_package.rs
- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox-types/src/stability.rs
- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/general.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/package.rs
- crates/flox/src/config/mod.rs
- crates/flox/src/main.rs
- tests/integration.bats
- tests/usage.bats
We are regrouping our commands and flox output.
Currently, all commands are defined in match branches of Existing command groups.
This PR moves all command definitions into separate structs and moves their implementation from the `match` branches to an associated `handle` method.
This reshuffling is particularly noisy with git, thus the large diff. Please take into account that this PR **does not change the implementation of any command** beyond adapting variable names.
Done:
> refactor: clean up usage and command definitions

- Justfile
- shells/rust-env/default.nix
This PR adds `just` to the `rust-env` environment and a Justfile for local development. The Justfile has commands for running the test suite and makes it easier to run subsets of the `bats` test suite specifically.
Example:
```
$ just shell-test ./tests/activate.bats
```
Currently if you want to run a specific test file you would have to write out:
```
$ cargo build
$ flox run '.#flox-tests' -- -- --flox target/debug/build ./tests/activate.bats
```
N/A
> chore: add Justfile for development

- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox/doc/flox-delete.md
- crates/flox/doc/flox.md
- crates/flox/src/commands/environment.rs
- flox-bash/flox.sh
- tests/README.md
- tests/environment-delete.bats
- tests/integration.bats
- tests/multi-env.bats
- tests/package.bats
- tests/setup_suite.bash
- tests/test_support.bash
- tests/usage.out
This PR adds a `flox delete` command behind the `FLOX_FEATURES_ENV="rust"` feature flag. The semantics are as follows:
- When `flox delete` is called it will attempt to delete `$PWD/.flox`.
- If `.flox` exists, it will be deleted.
- If `.flox` doesn't exist, an (extremely minimal) error message is printed
This command does not exist currently.
The `destroy` command is renamed to `delete`, but otherwise functions identically (accepts the same flags, etc)
> feat: add feature-flagged 'flox delete'

- flake.lock
- flake.nix
The presence of floco in closure is temporary, so drop the "follows of follows" statement that makes floxpkgs lock updates problematic.
Update `flake.nix` to remove "follows of follows" statement.
It is currently not possible to do a `flox flake update` from a floxpkgs repository referencing the main branch of flox/flox.
N/A
> fix: remove "follows of follows" statement from flake.nix

- crates/flox/src/utils/init/mod.rs
Imports became unused after the change of git config initialization in https://github.com/flox/flox/pull/184
> fix: remove unused imports

- crates/flox-rust-sdk/src/models/environment.rs
Update trait to clarify that interactive operations should be managed by the flox crate
@zmitchell I leave it to you to actually use the updated interface when you work on `edit`
> feat: no interaction in Environment trait

- crates/flox/src/config/mod.rs
This message doesn't represent anything the user needs to be aware of or
take action based on, so it can be logged more quietly.
Fixes #181
> fix: Don't warn about non-existent config when creating it

- flox-bash/lib/metadata.sh
- pkgs/flox-gitforge/default.nix
Automatically rewrite git origin for environments owned by `flox` and `flox-examples`.
Users are currently prompted to migrate the floxmeta repositories for the flox and flox-examples organizations, which they cannot do.
N/A
> Flox floxmeta repos set origin

- Cargo.lock
- crates/flox-rust-sdk/Cargo.toml
- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/flox_package.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/utils/mod.rs
- crates/flox-types/Cargo.toml
- crates/flox/src/commands/environment.rs
- crates/flox/src/utils/display.rs
- crates/flox/src/utils/mod.rs
- tests/environment-install.bats
- create symlink to built environment in .flox/builds/{system}.{name}
- this required some changes to copying directories, as
fs_extra::dir::copy does not support symlinks
- copy catalog.json into the built environment
- print a message to users saying whether a package was installed
- add a test for flox_nix_content_with_new_packages
> feat: next iteration of `flox install`

- crates/flox-rust-sdk/src/models/environment.rs
Rename the target for environment activation symlinks to avoid possible confusion with package build symlinks in future.
Currently environment symlinks are created in the `.flox/builds` directory and this may be a source of confusion when symlinks to package builds are also present.
N/A
> fix: create environment symlinks in `.flox/envs`

- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox/doc/flox-publish.md
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/package.rs
- tests/publish.bats
closes #221 
Also fixes a bug where, cache misses where treated as success, because nix wont error on them, rather issue
```
[
{
"path": "/nix/store/q90yr4zhzbvfwpkfqikn6brvsgyhn9av-builtfilter-rs-0.1.0",
"valid": false
}
]
```
> feat(publish): impl binary cache check retry

- README.md
- doc/release-notes/rl-0.1.2.md
- doc/release-notes/rl-0.1.4.md
- doc/release-notes/rl-0.1.5.md
- doc/release-notes/rl-0.2.5.md
- flox-bash/README.md
- flox-bash/lib/commands/activate.sh
- flox-bash/lib/commands/environment.sh
- flox-bash/lib/metadata.sh
- flox-bash/libexec/flox/darwin-path-fixer.awk
- pkgs/flox/default.nix
This PR should be merged once website/discourse/events.flox.dev domain are ready.
> Initial search/replace of floxdev.com->flox.dev

- flox-bash/lib/commands/environment.sh
- flox-bash/lib/metadata.sh
Remove the following old/redundant schema migration functions after identifying that one of them had been corrupting version links by introducing an extra "system" in the path.
- temporaryAssert007Schema()
- temporaryAssert008Schema()
- temporaryAssert009LinkLayout()
Reproducer for corrupting behavior:
<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~/src/flox]$</b></span> flox pull -e flox/default
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To /home/brantley/.cache/flox/meta/flox
* [new branch]        x86_64-linux.default -&gt; x86_64-linux.default
<span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease …
> fix: remove old temporary migration functions

- flox-bash/lib/commands/environment.sh
This patch fixes a bug that prevented rolling back to generations that weren't already present in the local store by calling syncEnvironment() to render each environment and the associated generation symlinks following each rollback.
Reproducer:
<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> <span style="color:#55FF55"><b>[brantley@clubsoda:~/src/flox]$</b></span> flox pull -e flox/default                                                                                                                                                       
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To /home/brantley/.cache/flox/meta/flox
* [new branch]        x86_64-linux.default -&gt; x86_64-linux.default
<span …
> fix: render environments and generation links with rollback

- flox-bash/lib/utils.sh
Update invocations of `/usr/bin/patch` on Darwin hosts to send all prompts to STDERR to prevent shells from tripping over that output during `flox activate`.
When running `flox activate` on Darwin hosts flox checks to see if patches need to be (re-)applied to `/etc/zshrc{,_Apple_Terminal}`. If the output is being sourced by a shell it can then trip over the prompts sent to STDERR by `/usr/bin/patch`.
Fixed bug patching `/etc/zshrc{,_Apple_Terminal}` files when running `flox activate` from a shell "rc" file.
> bug: shell trips over `patch` output when running `flox activate` on Darwin hosts

- flox-bash/lib/metadata.sh
Replacing the use of $_git with floxmetaGit() in all floxmeta-related functions worked in all cases except when invoked with xargs, which of course cannot invoke a bash function. Reverting this one instance from the previous bulk change.
Closes #243 
See #243 
Fixed bug creating managed environments introduced in  version 0.3.0.
> fix: revert xargs bug introduced with floxmetaGit

- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox/src/commands/environment.rs
When publish creates a new catalog branches it invokes `git checkout --orphan` which keeps the original working tree in the index.
This PR adds a call to `git rm .` to clear the index.
closes #220
> fix(publish): clear files on newly created orphan catalog branches

- flake.lock
- pkgs/flox-gh/flox-gh.patch.v2.32.1
Bumping flake and adding `gh` patch link as required by current stable version. Merging as hotfix in advance of review as required by release.
> fix: stability gh version bump

- pkgs/flox-bash/default.nix
Nix 2.17 has problems rendering environments locked with an old version of flox-floxpkgs which uses builtins.fetchClosure() without specifying "inputAddressed = true". Reverting to nix 2.15 for a release cycle while we work to figure out the best way to address the problem going forward.
Attempts to render a flox environment with nix 2.17 results in the following error:
<pre><span style="color:#5F5FAF"><b>flox </b></span><span style="color:#FFAF87"><b>[flox/prerelease default]</b></span> brantley@Michaels-MBP flox % result/bin/flox pull -e flox/prerelease                   
Everything up-to-date                                                                                                 
<span style="color:#FF55FF"><b>warning:</b></span> input &apos;flox-floxpkgs/etc-profiles&apos; has …
> fix: revert to use of nix 2.15

- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/main.rs
- tests/usage.bats
Version is implemented as a separate check that ensures all remaining args (if any) are valid argument to flox.
> chore: check for `--version` before handling flox arguments

- pkgs/flox-gh/flox-gh.patch.v2.32.1
This patch sets a unique identifier for `flox-gh` tokens in the keyring so that subsequent logins/logouts of `gh` and `flox-gh` won't stomp on each other.
It also reinstates the secure storage feature previously removed during testing.
Further background and discussion of this issue is available in [discourse](https://discourse.flox.dev/t/release-announcement-v0-3-0-august-31-2023/791/5).
Authentication tokens generated by the `flox-gh` tokens are [insecurely] stored in `~/.config/flox/gh/hosts.yml`. With this patch these tokens can be stored securely, for example as implemented in Apple's keyring implementation.
When the keyring service is available, this is the expected output when logging into both of the `gh` and `flox-gh` applications:
```
flox [flox/prerelease default] …
```
> fix: use "flox-gh" identifier in secure keyring

- flox-bash/lib/metadata.sh
Taking inspiration from the example of creating an orphaned branch recently added to the rust codebase.
Clean up orphan branch creation logic by running `git rm -r .` rather than `git ls-files | xargs --no-run-if-empty git rm`. It's a minor change but the latter was recently the source of a bug so figured it was worth fixing.
This is just code cleanup and does not change behavior.
N/A
> fix: tweak logic for creating new orphaned branch

- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/floxmeta/environment.rs
- crates/flox-rust-sdk/src/models/floxmeta/mod.rs
- crates/flox-rust-sdk/src/models/floxmeta/user_meta.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/models/root/reference.rs
- crates/flox-rust-sdk/src/models/root/transaction.rs
- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/package.rs
Remove `GitProvider` generic from `floxmeta` implementation.
We have been referring to the Git command interface in a generic way for the lifetime of the floxmeta abstractions.
Since we never got to implwmwnt more than one implementation, and plan to have smaller usecase focused git wrappers, we need to reduce the complexity generics add to the codebase first.
This PR should also make further refactorings of floxmeta easier as fewer generics need to be considered.
> refactor: ungenerify floxmeta

- flox-bash/lib/commands/publish.sh
- flox-bash/lib/utils.sh
Fix typo in code: `$invoke_git` not `$_invoke_git`.
`flox publish` currently fails with this error:
```
/nix/store/vf55aazry7qqddbj4j6cs5i2z0jqrqb1-flox-bash-0.3.3-r626/lib/commands/publish.sh: line 596: -C: command not found
```
Fixed bug affecting `flox publish`.
> fix: typo, $invoke_git not $_invoke_git

- crates/flox-rust-sdk/src/providers/git.rs
- tests/publish.bats
- tests/setup_suite.bash
Tests need to succeed when the user has not configured their own git `user.{name,email}` settings, so we shouldn't be setting these in our tests either. We should instead set default values for the git operations in which we explicitly require them.
Tests don't detect when flox functionality silently relies upon the user's git `user.{name,email}` having been set.
N/A
> fix: remove user.{name,email} git config from test setup

- crates/flox-rust-sdk/src/models/floxmeta/mod.rs
- crates/flox-rust-sdk/src/models/legacy_environment.rs
- crates/flox-rust-sdk/src/models/legacy_environment_ref.rs
- crates/flox-rust-sdk/src/models/mod.rs
- crates/flox-rust-sdk/src/models/project/environment.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/package.rs
- crates/flox/src/utils/mod.rs
This is was a quick attempt to restore behavior - I only expect we should merge this if we want to get containerize working in the near term. It might not be the most "correct" way to revert the changes, but `flox containerize -e <name>` works again.
c0bdfe19311396c901668737d7401f7312a8001a broke non-feature flagged behavior of pure Rust commands like containerize. This partially restores that behavior - in particular flox containerize of environments in floxmeta works again.
Behavior for project environments was not fully restored; in particular environment() and environment_out_link_dir() were restored simply as unimplemented!().
> fix: non-feature flagged rust command regression

- flox-bash/lib/utils.sh
- pkgs/flox-bash/default.nix
When running activate tests for dash on macOS, ps is not found, so flox falls back to SHELL syntax, which leads to a test failure.
> fix: don't depend on ps in PATH

- crates/flox/src/commands/mod.rs
- crates/flox/src/main.rs
Some internal docs for `--verbose` were leaking into the usage output of flox.
This PR removes an indirection used for the "fake" `--version` flag.
As a reminder; `--version` is handled separately from the main argument handling,
so that it any flox command that contains `--version` will print the version
and abort early in proper POSIX fashion.
That change also dropped the "Version: " prefix in the output of `--version` which 713f45a reverts
> fix: --version flag usage

- crates/flox-rust-sdk/src/models/project/environment.rs
The affected test module is currently ignored in nix builds (and in CI?).
> fix: resolve type errors in (ignored) unit test

- flox-bash/lib/metadata.sh
The temporaryMigrateGitHubTo030Floxdev() function was failing when run with a non-default git_base_url. This patch fixes the bug by ensuring it returns 0 (success) when invoked against a non-default git_base_url.
> fix: return 0 when not using default git_base_url

- flox-bash/lib/commands/activate.sh
- flox-bash/lib/utils.sh
So this was an interesting one. bash can be invoked as sh, which is not currently detected by identifyParentShell.
The first commit uses /proc/$pid/cmdline to determine argv[0] instead of /proc/$pid/exe. That breaks CI, because it correctly detects that bash has been invoked as sh. But then flox doesn't think it can handle sh, so it fails. https://github.com/flox/flox/actions/runs/6343743972/job/17232325528#step:7:367
The second commit changes `activate` to be okay with `sh` - I'm assuming sh should be handled the same as dash, but I'm not actually 100% sure, is that correct?
> fix: detect bash invoked as sh

- pkgs/flox-bash/default.nix
- pkgs/flox-pkgdb/default.nix
- pkgs/flox/default.nix
pkgdb is simply re-exposed in pkgd/flox-pkdb/default.nix which is unnecessary indirection.
> fix: use pkgdb directly as a flake

- crates/flox/src/commands/environment.rs
Clarify error for install and uninstall.
Before:
$ flox install
ERROR: At least one package
After:
$ flox install
ERROR: Must specify at least one package
> fix: {un,}install error

- crates/flox-rust-sdk/src/providers/git.rs
Open a repo, but don't search upwards, instead erroring if a subdirectory of a repo is specified.
We currently only have a discover method which searches upwards.
> feat: git open method

- .github/workflows/ci.yml
This PR has no effect on `flox` itself, it's just adding a larger runner for CI.
N/A
> chore: use larger x86_64-linux runner

- flox-bash/lib/diff-catalogs.jq
The diff-catalogs.jq script was reporting the new package to be upgraded, but not the old package being upgraded. With this patch it now reports both, introducing the new "from-package" and "to-package" keys in the process.
This is an internal change with no user-facing changes.
> feat: report full upgrade details

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/flox_installable.rs
- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/main.rs
- crates/flox/src/utils/init/mod.rs
- tests/activate.bats
- tests/develop.bats
- tests/develop/devShell.exp
- tests/develop/develop-fail.exp
- tests/develop/develop.exp
- tests/develop/toplevel-flox-nix.exp
- tests/edit.bats
- tests/environment-activate.bats
- tests/environment-install.bats
- tests/environment-list.bats
- tests/flox-pushpull.bats
- tests/gpgsign.bats
- tests/integration.bats
- tests/multi-env.bats
- tests/package.bats
- tests/progs.bats
- tests/setup_suite.bash
Add argument parsers for `--dir` and `--remote` and make changes to `Environment` in order to use the trait as a trait object in cases where we don't need/want to know the concrete implementation.
[BREAKING CHANGE]: removing the `-e`/`--environment` flag is backwards incompatible with the legacy flox commands. The bash implemented commands can be recovered using the `--bash-passthru` flag. All Tests that test the legacy behavior have hence been edited to contain this flag in [c299877](https://github.com/flox/flox/pull/272/commits/c299877778b3681b954aa41cc29dd1694ce97377)
* [refactor: make environment trait "object save"](https://github.com/flox/flox/commit/5fe6875f449d2e4ef26b0e20f71a0b3373429727)
In order to create trait objects of the Environment trait, e.g. `Box<dyn Environment>`
the …
> feat!: environment selection with `--dir` and `--remote`

- crates/flox-rust-sdk/src/models/search.rs
- crates/flox/src/commands/channel.rs
- flake.lock
- tests/channels-search.bats
- tests/develop.bats
- tests/publish.bats
This PR cleans up the output of the feature-flagged `flox search` command by:
- Only showing a portion of the package's attribute path
- Deduplicating multiple versions of a package from the same input
- Disambiguating between packages with the same name that come from different inputs.
Given a subscription/input of just `nixpkgs-flox` on `x86_64-linux` a search for the `hello` package displays these results:
```
hello          A program that produces a familiar, friendly greeting
hello-wayland  Hello world Wayland client
gnome.iagno    Computer version of the game Reversi, more popularly called Othello
```
If you then add a `nixpkgs2` input (`github:NixOS/nixpkgs/release-23.05`) and perform the same search you'll see this output:
```
nixpkgs2:hello                                   A …
```
> feat: shorten and disambiguate search output

- crates/flox-rust-sdk/src/models/search.rs
- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/mod.rs
- tests/channels-show.bats
- tests/environment-list.bats
- tests/usage.bats
This adds a bare bones feature-flagged `flox show` command. The output is currently just a list of the search results from the provided package name, but the command is aware of disambiguated packages. Properly formatted output is coming in later PRs.
Closes flox/product#356.
N/A
N/A
> feat: add 'flox show' command

- crates/flox/src/commands/mod.rs
Allows users to drop back to legacy behavior by setting an environment variable
> feat: check `FLOX_BASH_PASSTHRU` in addition to `bash-passthru`

- .github/workflows/ci.yml
Sequence package matrix to avoid redundant builds.
Avoid pushing the entire `nix` store - only push new paths.
Multiple runners may be used to build individual packages which require setup.
Since all targets are dependencies of `flox`, runners which only build earlier dependencies perform redundant work.
For caches we previously cached the entire `nix` store instead of just
newly added paths.
N/A
> perf: sequence CI builds and improve cache push

- pkgs/flox-gh/flox-gh.patch.v2.32.1
Update all mention of "GitHub CLI" in the authentication code of our internal `gh` clone to instead read "flox CLI".
When prompted to log into the "flox CLI" the user is instead prompted to log into the "GitHub CLI".
Updated flox CLI prompts to remove mention of GitHub.
> feat: revise all CLI auth prompts to read "flox"

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/floxmetav2/mod.rs
- crates/flox-rust-sdk/src/models/mod.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox-types/src/version/mod.rs
- crates/flox/src/commands/environment.rs
- tests/environment-delete.bats
- tests/environment-edit.bats
- tests/environment-install.bats
- tests/environment-list.bats
- Add a method EnvironmentPointer::open that reads an env.json and
returns a pointer to either a managed or path environment.
- Use EnvironmentPointer::open in all environment commands, and
depending on the result call PathEnvironment::open or
ManagedEnvironment::open
- Add ManagedEnvironment::open, which locks an environment and ensures
floxmeta has a unique branch for the environment
- Add FloxmetaV2::open, which either opens a user's floxmeta or clones
it (cloning not yet implemented)
- Add another git helper for ManagedEnvironment, commit_on_branch
> feat: ManagedEnvironment::open

- flox-bash/lib/templateFloxEnv/flake.lock
Update the flake lockfile used for environments.
flox/product#486
New environments will now 
* use newer nixpkgs for inline packages
* emit fewer warnings regarding unrelated inputs
> bump: update environment flake lockfile

- Cargo.toml
Fixes a compile time warning issued by cargo, because we crates and workspaces use different versions of the dependency resolver.
This PR explicitly sets the resolver for the cargo workspace to the new version `2`.
> chore: set `workspace.resolver = "2"`

- crates/flox/src/main.rs
- crates/flox/src/utils/init/logger.rs
- tests/publish.bats
Not flushing the logger appears to be causing flaky tests on macOS - likely the error messages expected by some tests are not being printed to stderr before flox exits.
Re-enable tests that were disabled due to this failure.
> fix: flush logger

- tests/publish.bats
One of these tests was flaky in
https://github.com/flox/flox/actions/runs/6586779982/job/17895784262?pr=310#step:15:218
So 2d525e7a7b454b6b9a015d3505d2b28d5b23dd58 may have been premature.
> fix: disable flaky tests

- crates/flox/src/main.rs
- crates/flox/src/utils/init/logger.rs
This reverts commit 2d525e7a7b454b6b9a015d3505d2b28d5b23dd58.
As this commit did not fix flaky tests as first thought, revert it.
> Revert "fix: flush logger (#306)"

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/floxmeta/mod.rs
Resolving some clippy complaints, nothing substantial.
> chore: fix clippy lints in managed_environment tests

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox/src/commands/environment.rs
- tests/environment-delete.bats
- tests/environment-edit.bats
- tests/environment-install.bats
- tests/environment-list.bats
We implemented Environment opening through an intermediate `EnvironmentPointer` in #280 for `ManagedEnvironments`.
This PR implements the required changes to `PathEnvironment` to support `EnvironmentPointer`s.
In the course of the PR some previous APIs were removed (`PathEnvironment::discover`, various `EnvironmentRef` methods) in favor of a future pointer based implementation.
`flox envs` (which was using `PathEnvironment::discover`) refactored to use `EnvironmentPointer::open` in the meantime, before being either removed or `EnvironmentPointer::discover` is implemented.
> refactor: adapt `PathEnvironment` to use `PathPointer`

- crates/flox/src/commands/package.rs
flox publish manually checks whether a `signing-key` is provided as a command line argument or via the config system.
If absent will provide an error that provides a hint which flag/config key to set. `signing-key` was previously called `sign-key` which did not get renamed in all instances.
> fix: hint the correct flag and config when signing key absent

- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/Cargo.toml
- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
This PR implements the `ManagedEnvironment::encode` method and creates symlinks back to the project environment.
Closes flox/product#511
N/A
N/A
> feat: ManagedEnvironment::encode method, reverse links

- .github/workflows/ci.yml
This is a preparation PR to make sure I don't suddenly break CI while I merge next version of `install-flox-action` (https://github.com/flox/install-flox-action/pull/26)
> ci: pin install-flox-action to mitigate any breakage

- crates/flox/src/commands/channel.rs
- tests/channels-search.bats
when displaying flox search {package} results show a line at the bottom about using flox show --> Use `flox show {package}' to see available versions
> feat: hint `flox show` for more info as part of `flox search`

- .envrc
- .github/workflows/ci.yml
- .gitignore
And also:
- run again, since it was removed from CI, `cargo tests`
- we run Cargo tests in parallel to Bats tests
- sneaking in support for direnv (`.envrc` file)
> Switch to new version of install-flox-action 

- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/channel.rs
- tests/channels-show.bats
This properly formats the output of the feature-flagged `flox show` command:
```
$ flox show hello
hello - A program that produces a familiar, friendly greeting
hello - hello@2.12.1
$ flox show hello --all
hello - A program that produces a familiar, friendly greeting
hello - hello@2.12.1, hello@2.12, hello@2.10
```
The current output is a crude list of `name - description` lines.
N/A
> feat: format flox show output

- crates/flox/src/commands/channel.rs
`flox show` was implemented as a replacement to show detailed information about a package and fully available with #327.
> feat: remove `--long` flag from `flox search`

- crates/flox/src/commands/mod.rs
- tests/environment-init.bats
Add
- `run`
- `list`
- `nix`
- `import`
- `export`
- `envs`
to the list of deprecated commands.
(raises a deprecation warning as the command is used)
> fix: amend deprecated commands

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox-rust-sdk/src/models/manifest.rs
- crates/flox/src/commands/environment.rs
- tests/environment-install.bats
This PR edits `manifest.toml` with `flox uninstall`.
Given a `manifest.toml` that looks like
```toml
[install]
foo = {}
bar = {}
```
and the uninstallation command you'll see the following output
```
$ flox uninstall foo bar
🗑️ 'foo' uninstalled from environment
🗑️ 'bar' uninstalled from environment
```
If _any_ of the packages requested for uninstallation is missing from the manifest the whole operation is aborted and the manifest is unchanged. This is to pave the way for transactional operations.
`flox uninstall` removes packages from `manifest.toml`
> feat: edit manifest with 'flox uninstall'

- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/floxmeta/mod.rs
- crates/flox-rust-sdk/src/models/floxmeta/user_meta.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox-rust-sdk/src/models/root/git.rs
- crates/flox-rust-sdk/src/models/root/reference.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/general.rs
- crates/flox/src/commands/mod.rs
Probably not too important to be thorough here - not sure if https://github.com/flox/flox/issues/304 should have even gotten pulled in, but it's quick to close.
Remove async from git provider.
This may have removed some async throughout the codebase as I used some linter assistance, and I fixed a few unrelated clippy warnings.
No user facing changes
> fix: make git provider sync

- crates/flox/src/commands/auth.rs
- crates/flox/src/commands/general.rs
- crates/flox/src/config/mod.rs
Once a token is received through `authenticate`, write the token to the user config file under the key `floxhub_token`.
Reciprocally, remove the key `floxhub_token` to logout from floxhub.
* a token can be set via `flox auth login` (which writes to the user config file), by manually editing any flox config file (how to get the token to put there 🤷🏼) or by setting the `FLOX_FLOXHUB_TOKEN` env variable.
* if a token is present, `login` will replace it (see #357 for a smarter(?) solution)
* if a token is present, `logout` will assume its in the user's config file - this will fail with a message if the token is set via the environment or a higher order config file.
* if no token is present, logout will exit early
> feat: manage `floxhub_token` in config

- pkgs/flox-bash/default.nix
Trim down the locales to a sane default.
Less common locales are no longer included by default.
> fix: use trimmed down Utf8 locales

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox/src/commands/environment.rs
- call activation script for an environment with FLOX_ENV and FLOX_PROMPT_ENVIRONMENTS set
- add activation_path to Environment trait
- remove flake_attribute from Environment trait as it is no longer needed
- don't add tests yet as activation_path depends on build which doesn't
yet work
> feat: call environment activate script

- pkgs/flox-bash/default.nix
Remove patches that are not used. Will continue to upstream multiple-github-tokens and nlohmann tempates.
Patch supporting "flake#.rawAttrPath" syntax is removed. (is available in upstream latest, pending next release).
Patch supporting multiple access tokens per domain removed.
> chore: nix -> 2.15.3 and remove superfluous patches

- assets/mkEnv/build-env.sh
- assets/mkEnv/env-from-lockfile.nix
- assets/templateFloxEnv/dummy_lockfile.json
- checks/pre-commit-check/default.nix
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox/src/commands/environment.rs
- pkgs/flox/default.nix
- tests/channels-search.bats
- tests/channels-show.bats
- tests/environment-activate.bats
- tests/environment-build.bats
- tests/environment-delete.bats
- tests/environment-edit.bats
- tests/environment-init.bats
- tests/environment-install.bats
- tests/environment-list.bats
- tests/setup_suite.bash
This PR builds environments when `flox activate` is called. The environment is built with a new executable called `build-env`, which currently is just a shell script that calls `nix build` on another new file: `env-from-lockfile.nix` .
The `activate` command currently builds a hard-coded lockfile. Generating a lockfile from the manifest is coming in a later PR.
This PR also disables `clippy` as a precommit hook because it's super annoying.
`flox activate` now builds an environment.
> feat: activate builds environments

- flake.lock
Flake lock file updates:
• Updated input 'pkgdb':
'github:flox/pkgdb/5a3d9dd15674852baac08e07c84a59d62ceb7740' (2023-11-02)
→ 'github:flox/pkgdb/aec2f6ece0e5ed6c8f7e9e7e5b798a051d3e3db0' (2023-11-03)
> chore: bump 'pkgdb' flake input

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/floxmetav2/mod.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/environment.rs
- tests/environment-push.bats
Implements `flox push [--dir]` and `flox push [--dir] --owner` in a highly green pathed way.
Maily this is due to missing implementations of `Environment for ManagedEnvironment`. E.g. we have not yet implemented generational `install` et.al.
Thus, we everything this implementation is useful for at the moment is pushing an existing path environment to floxhub, converting it to a managed env in the process.
Pushing of new generation _should_ work but due to the fact that we are not creating new generations yet, I'm unable to test this case.
> feat: green path `flox push`

- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/floxmetav2/mod.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/utils/completion.rs
- tests/environment-pull.bats
- tests/environment-push.bats
Implements `flox pull [--dir]` and `flox pull --remote [--dir]`.
Environment branches are updated using `fast-forward`s and fail if this is not possible.
> feat: `flox pull|push` for managed envs

- CONTRIBUTING.md
- fixes typo `flox develop` -> `nix develop`
- adds _quick start_ to top of `CONTRIBUTING.md`
N/A
> doc: fix typo and add quickstart to CONTRIBUTING.

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox/src/commands/environment.rs
Instead of printing e.g.:
✅ 'python' installed to environment
Print:
✅ 'python' installed to environment name at /some/path
Improve confirmation messages for install/uninstall (idk if this is big enough to mention)
> feat: print environment modified by {un,}install

- pkgs/flox-tests/default.nix
- tests/environment-activate.bats
pkgdb must download and evaulate nixpkgs, which is time intensive. At times this causes expect to time out.
Instead of bumping the timeout, factor out operations that we never want to timeout outside of the expect test. Since expect must have a timeout, the timeout will be easier to set accurately if we move actions that should never timeout outside of expect. This may also make caching easier in the future.
No user facing changes
> fix: warm up pkgdb to avoid timeout

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- Check pkgdb exit code. Currently pkgdb exit status is ignored, and we only detect errors if deserialization of an error succeeds. Although pkgdb makes a best effort to output valid error JSON, this is not always guaranteed, so exit code should be checked.
- Make context_message and caught_message optional, as they are optional in pkgdb
- Rename FailedResolution to LockManifest since users are more likely to understand what locking a manifest means as opposed to resolving a registry
No user facing changes
> fix: improve pkgdb error handling

- assets/mkEnv/env-from-lockfile.nix
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- flake.lock
- tests/environment-activate.bats
- `pkgdb lock` was moved to `pkgdb manifest lock`
- url is now added at {package}.input.url, so don't add it in Rust, and use that field in env-from-lockfile.nix
- Use registry.inputs.nixpkgs.from.rev instead of inserting a hardcoded rev for nixpkgs in Rust
- Hardcode a rev for nixpkgs in tests
- Key nesting was changed from {package}.{system} to {system}.{package}
- package.path was moved to package.attr-path
Flake lock file updates:
• Updated input 'pkgdb':
'github:flox/pkgdb/aec2f6ece0e5ed6c8f7e9e7e5b798a051d3e3db0' (2023-11-03)
→ 'github:flox/pkgdb/27f19d0d51a78527497f3210dcc417c04605d636' (2023-11-08)
No user facing changes
> chore: bump 'pkgdb' flake input and fix breakage

- crates/flox-rust-sdk/src/models/search.rs
- crates/flox/src/commands/search.rs
- crates/flox/src/config/features.rs
- crates/flox/src/config/mod.rs
- tests/package-search.bats
Allows to specify whether how to match packages in Search
set `FLOX_FEATURES_SEARCH_STRATEGY=match` to include matches in the package description (default)
set `FLOX_FEATURES_SEARCH_STRATEGY=match-name` to exclude matches in the package description
closes #384
> feat: add `SearchStrategy` feature flag

- flake.nix
Rooted follows (with the "/") prefix, seems to disable the ability to override a full input tree, ie: the rest of the tree remains as the original, this is very likely not the intended behavior.
```
$ nix eval git+ssh://git@github.com/flox/flox?ref=latest#flox --json
"/nix/store/a149wgp7j6nnipga3km57r7pjc83wpn0-flox-0.3.6-r692"
$ nix eval git+ssh://git@github.com/flox/flox-passthru#flox --json
"/nix/store/a149wgp7j6nnipga3km57r7pjc83wpn0-flox-0.3.6-r692"
```
so far so good, hashes match
```
$ nix eval git+ssh://git@github.com/flox/flox?rev=3863f43de63a622ec01e3d9eab9bcd078d58880f#flox --json
"/nix/store/vpx3jks05c5s1nvhd6whxymca2qck9y6-flox-0.3.7-r732"
$ nix eval git+ssh://git@github.com/flox/flox-passthru#flox --override-input f …
```
> fix: non-root follows

- crates/flox-rust-sdk/src/flox.rs
- crates/flox/src/commands/environment.rs
* make get username async again as blocking as we are still in a tokio runtime
* use bearer authentication on gh api since we don't have a jwt
* set `user-agent: flox cli` as github will resopond with `403 FORBIDDEN` without it
* use `https://api.github.com` as base url
closes #423
> fix: github username api request

- crates/flox-rust-sdk/src/models/floxmetav2/mod.rs
rm semicolon which was being passed along to gitforge, and breaking token validation
N/A
> fix: remove semicolon from opts config flag to fix flox push

- assets/mkEnv/set-prompt.sh
- assets/mkEnv/source-profiles.sh
- bash 3.2 gets confused by a closing parenthesis in a subshell, so add the optional opening parenthesis
- nixpkgs#bash does not have readline, so don't attempt to set a colorized prompt as it gets garbled
> feat(activate): support bash 3.2 and nixpkgs#bash

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
`flox push` was broken and it appeared that `flox push` should replace .flox/env.json with a file that says `{"owner": <owner>, "name": <name>, "version": <number>}`
This PR fixes this issue
> fix: flox push was incorrectly writing env.json to the temp path 

- Cargo.lock
- assets/global_manifest_template.toml
- assets/templateFloxEnv/manifest.toml
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/search.rs
- crates/flox/Cargo.toml
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/search.rs
- crates/flox/src/main.rs
- crates/flox/src/utils/mod.rs
- flake.lock
- pkgs/flox/default.nix
- tests/environment-activate.bats
- tests/package-search.bats
- tests/package-show.bats
Search inputs are no longer collected from channels or hardcoded in searches, but instead they're read from the manifest by `pkgdb` (which itself hardcodes a registry at the moment).
This greatly simplifies the search interface from the Rust side.
N/A
> feat: read registry from manifest

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- tests/activate/activate.exp
The `path` field on environments is used to set FLOX_ENV and then PATH, so it must be absolute, otherwise changing directory will invalidate PATH.
Fixes bug where changing directory invalidates PATH after running `flox activate`
> fix: store absolute paths in environments

- crates/flox/src/config/features.rs
- tests/package-search.bats
Set default search strategy to match-name. The match strategy can still be used by setting FLOX_FEATURES_SEARCH_STRATEGY=match
> feat: set match-name to be default

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/mod.rs
- crates/flox-rust-sdk/src/models/pkgdb_errors.rs
- crates/flox-rust-sdk/src/models/search.rs
This adds a custom std::error::Error implementation for `PkgDbError` such that the JSON we receive from `pkgdb` is printed as if it we any other encountered on the Rust side.
Example:
```
$ flox search hello
ERROR: search encountered an error
Caused by:
0: invalid manifest file
1: unrecognized manifest field `options.doesnt_exist'.
```
Previously the JSON errors received from `pkgdb` would simply be printed in their raw form.
Users will now see friendly error messages when there's an error with their manifest or when an error is encountered during a search.
> feat: format errors from pgkdb

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/search.rs
- crates/flox/src/commands/search.rs
- tests/package-search.bats
- tests/package-show.bats
This adds a couple of tests for `search`/`show` that ensure these commands fall back to the global manifest when outside of a project.
As part of making the tests pass some helper functions were added that aid in discovering a `.flox` directory.
This is the final PR required for closing flox/product#551.
N/A
> test: add integ tests for manifest presence

- crates/flox-rust-sdk/src/models/environment/mod.rs
- flake.lock
- tests/environment-activate.bats
This fixes an activate regression; pkgdb now expects --ga-registry, but
we hadn't started passing it to `pkgdb manifest lock`
Flake lock file updates:
• Updated input 'pkgdb':
'github:flox/pkgdb/8160d50f328e9cc07c89c146bdb56552ce41a6aa' (2023-11-16)
→ 'github:flox/pkgdb/a56042073ebdaac724fdef28c0cb2ea7bac71f1e' (2023-11-19)
> chore: bump 'pkgdb', call lock with --ga-registry

- flake.lock
Pulls changes which make `pkgdb search` use pins from lock-files.
N/A
> chore: bump pkgdb pin

- assets/mkEnv/env-from-lockfile.nix
- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox-rust-sdk/src/models/manifest.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/utils/mod.rs
- flake.lock
- tests/environment-install.bats
Attempt to transactionally build the environment when installing, uninstalling, or activating. This has the added benefit of ensuring that you can't install a package that doesn't exist.
Installing/uninstalling a package now actually builds the environment rather than simply putting the package name in the manifest.
> feat: build envs on install/activate

- flake.nix
Use only callPackage, it [should already be overridable](https://github.com/NixOS/nixpkgs/blob/master/lib/customisation.nix#L192C34-L192C49). 
Quick testing:
```
nix build .#flox-tests .#flox-tests-end2end --json --extra-substituters s3://flox-store | jq .[].drvPath -r | xargs nix-diff --color always | grep -C1 TESTS_DIR
warning: Git tree '/home/tom/flox/flox/main' is dirty
warning: Git tree '/home/tom/flox/flox/main' is dirty
Usage: $0 [--flox <FLOX BINARY>| -F <FLOX BINARY>] \
[--tests <TESTS_DIR>| -T <TESTS_DIR>] \
[--watch | -W] \
--
-[fF]|--flox)         export FLOX_CLI="${2?}"; shift; ;;
-[tT]|--tests)        export TESTS_DIR="${2?}"; shift; ;;
-[wW]|--watch)        WATCH=:; ;;
--
: "${TESTS_DIR:=$PWD/tests}";"${TESTS_DIR:=$PWD/tests/end2end}";
export TESTS_DIR FLOX_CLI;
if [[ …
```
> fix: callPackage has an .override already

- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/src/flox.rs
- crates/flox/Cargo.toml
- crates/flox/src/commands/auth.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- pkgs/flox/default.nix
* refactor manual oauth authentication with [`oauth2` crate](https://crates.io/crates/oauth2)
* read username from auth0
* make auth endpoints configurable in build expression for flox (preferred) or at runtime through environment variables
- FLOX_OAUTH_BASE_URL
FLOX_OAUTH_CLIENT_ID
FLOX_OAUTH_AUTH_URL
FLOX_OAUTH_TOKEN_URL
FLOX_OAUTH_DEVICE_AUTH_URL
> refactor: switch to auth0 for authentication

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
`fs::rename` requires both source and destination paths to be on the same file system. Since the project may be on any mount point on the system, it can not be guaranteed that restoring the .flox copy under transaction by renaming will succeed.
This change will finish the transaction by _copying_ back the modified .flox rather than trying to rename it.
> fix: replace transaction .flox by copying

- pkgs/flox/default.nix
This does mean some overrides will not work, but makes it far easier and reproducible to grab the original closure available to callPackage.
- stores some values in passthru needed during installation
- prepares for flox-bash removal https://github.com/flox/flox/issues/336
N/A
> feat: expose original closure

- env-builder/src/buildenv.cc
- env-builder/tests/build-env.bats
Read `nix-support/propagated-build-inputs` and add paths to environment.
This will also recursively do the same with already postponed paths.
closes flox/product#565
> feat: recursively include propagatedBuildinputs paths

- crates/flox-rust-sdk/src/models/search.rs
- debug!() the exact command run.
- Add skip_serializing_none so it's easier to read the debugged command.
> feat: improve search command debugging

- crates/flox/src/commands/auth.rs
Previously, we were requesting a token that could only be used with the
Auth0 userinfo endpoint. We now explicitly specify the flox hub audience
so the token will be accepted by flox hub.
> fix: Add audience to token request

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox/src/commands/auth.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- tests/environment-delete.bats
- tests/environment-install.bats
- tests/install/last-activated.exp
- Keep track of activated environments in FLOX_ACTIVE_ENVIRONMENTS.
- For environment commands, use the last activated environment when not in a directory that contains a .flox.
- Use the parent path of the .flox directory for confirmation messages printed to users.
This is part of https://github.com/flox/flox/issues/359, but it doesn't use last activated environment for search or show, and it doesn't implement handling for when there's an activated environment and a .flox in current directory.
> feat: use last activated environment

- tests/end2end/python.exp
The theory is that expect is sending commands to the shell before the prompt is ready, and then the shell sits there waiting for a command, then times out.
Wait for a prompt. Note that the full prompt will be different on a per machine and SHELL basis.
Hoping to fix the flakey test.
N/A
> ci: make end2end python test wait for prompts

- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/models/environment/path_environment.rs
- crates/flox-rust-sdk/src/models/environment/remote_environment.rs
- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/search.rs
- crates/flox/src/utils/metrics.rs
- tests/package-search.bats
- tests/show/prompt-which-environment.exp
Previously, search/show searched upwards for a .flox, while environment commands did not. Environment commands used the last activated environment, but search/show did not. Instead, all commands (except activate) should both search up and use the last activated environment.
- Introduces `UninitializedEnvironment` to represent an environment with a valid env.json but that may not be fully initialized. This can be used, for example, to prompt users to pick between environments without the slowdown of having to initialize both of them first.
- `find_dot_flox` now returns an `UninitializedEnvironment`.
- `detect_environment` now uses `find_dot_flox` to search upwards.
- `manifest_and_lockfile` was moved to the flox crate, and it uses `detect_environment` to check for the last activated …
> feat: make environment detection consistent

- tests/end2end/python.exp
Juggle the python timeout tests. Possible that when the builder is under load this takes a bit of time. Better would be to run this via the same scheduler as builds so there is a limited concurrency.
N/A
> ci: extend timeout for python in case under load

- tests/end2end/python.bats
This skips the flaky test that is failing in CI. It can be enabled at a later date when it's confirmed to be working.
> test: disable flaky test

- Justfile
Previously we had no automated to audit the crates for license compatability. This adds a simplistic instruction to do that in the Justfile.
`just license`
None.
> chore: Add ability to dump licenses for all crates

- crates/flox-rust-sdk/src/models/environment/mod.rs
- crates/flox-rust-sdk/src/providers/git.rs
- crates/flox/src/commands/mod.rs
- tests/environment-install.bats
- tests/install/prompt-which-environment-git.exp
- tests/package-search.bats
Instead of searching up for flox environments all the way to `/`, only search up if in a git repo, and only search up to the top of the git repo.
Additionally, change prompt wording when an environment is detected in a git repo but it is not in the current directory:
```
? Do you want to search for packages using the flox environment detected in git repo or the current active flox environment?
> flox environment detected in git repo [name at path]
current active flox environment [name at path]
[↑↓ to move, enter to select, type to filter]
```
> feat: detect environments in git repos

- tests/end2end/python.exp
Expect is accepting lines with prompts in them. Make the regex less greedy.
N/A
> ci: protect against multiline expect accepting prompts

- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/search.rs
- tests/environment-init.bats
- tests/package-search.bats
* corrects `flox` and `flox init` CLI output which had messages that were referencing CLI commands with double quotes and variable replacement that didn't match [standards](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)
* flips the order of the `flox activate` hint to more naturally follow progression
N/A
> fix: init and flox CLI syntax fixes 

- cli/flox/src/commands/mod.rs
--unspecified was accidentally added to help messages:
```
Usage: flox install [-s=SYSTEM] [-d=<path> | -r=<owner/name> | --unspecified] PACKAGES...
```
This restores the expected help message:
```
Usage: flox install [-s=SYSTEM] [-d=<path> | -r=<owner/name>] PACKAGES...
```
> fix: remove --unspecified from help

- Justfile
- cli/flox-rust-sdk/src/models/search.rs
The path to the `pkgdb` binary is provided via an environment variable at either build time or runtime. The environment variable for providing the path at runtime did not have the same name as what was used to provide the path at build time (`PKGDB` vs. `PKGDB_BIN`).
Also, the Justfile was never calling the integration test suite, so that command has been added and included in the `test-all` target.
N/A
> fix: provide pkgdb via correct env var

- pkgs/flox-cli/default.nix
fixes #591
I don't know if there are subtle dependencies on these variables being set to `""`.
Maybe we can set proper defaults in the (devShell) shellHook already as well (`!ci`) so we don't need to set tehm manually (to always the same path) in dev.
> fix: unset `*_BIN` vars if unavailable

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
* Move all `EnvironmentError2` errors produced by _core_ environment operations (env transactions, locking, building, etc) into `core_environment::CoreEnvironmentError`
* Remove other unused error variants of `EnvironmentError2`
* Group remaining variants and add `todo:`s for future refactoring
> refactor: cleanup `EnvironmentError2`

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/search.rs
- cli/tests/environment-managed.bats
* refactor: track environment (`.flox`) path in guaranteed canonicalized form
* create unique out_paths for each instance of a managed environment
* amend `Environment::{manifest_path,lockfile_path,manifest_contents}` to
- take a `&Flox` reference to create tempdirs in a tracked location
- return `Result`s as managed environment has to materialize the repo to the file system first
* add a test proving search still works in managed environments
> feat: support `search` and `activate` in managed environments

- Justfile
The license target broke after the cli portions of the repo were moved under
/cli. This simply updates the justfile to popd into cli directory.
N/A
> fix: Update `license` target in justfile to work

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/environment.rs
* replace `unwrap`s for better error types
* further mixing error types in `managed_environments` module
* refactor `flox push` to check divergence through "sync branch" rather than `FETCH_HEAD`
> chore: improve error handling in `managed_environment` module

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-managed.bats
* feat: support flox delete for managed environments 
* deletes path specific branch
* deletes respective .flox directory
* improve `delete` command output
* migrate `PathEnvironment` to `CanonicalPath`
> feat: support `flox delete` for managed environments

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/src/commands/environment.rs
This makes the contents diff nicely when committed to a project repo.
Closes #629.
N/A
> feat: Pretty-print manifest.lock contents

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/main.rs
- cli/tests/environment-managed.bats
- cli/tests/test_support.bash
* fix: link built environments to `out_path`
* test: move `floxhub_setup` to `test_support.bash`
* test: add an integration tests that tests activate works with managed environments
` * added a single test that checks for setting the PATH
* the built environment is equivalent to the one produced by `PathEnvironments`
* Possibly more generic (and complete) testing of environment operations
may be implemented with flox/product#462
> test: validate that activate works on managed environments

- flake.nix
- shells/default/default.nix
* add `shfmt` too to the dev shell
* add `shfmt` pre-commit hook
* add `shellcheck` pre-commit hook but keep it off until we have time to fix the loads of complaints it has
> ci: check formatting of shell files

- .gitignore
- Justfile
- assets/templateFloxEnv/manifest.toml
- cli/Cargo.toml
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/general.rs
- cli/tests/environment-activate.bats
- cli/tests/environment-edit.bats
- cli/tests/environment-install.bats
- cli/tests/setup_suite.bash
- flake.nix
- pkgdb/.gitignore
- pkgdb/Makefile
- pkgdb/include/flox/core/util.hh
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/include/flox/resolver/descriptor.hh
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/resolver/environment.cc
- pkgdb/src/resolver/manifest-raw.cc
- pkgdb/src/util.cc
- pkgdb/tests/environment.cc
- tests/python.bats
This PR has a number of changes, only some of which are related to the title:
- Calling `flox install foo` will create an entry in the manifest `foo.path = "foo"`, which allows users to install packages like `rubyPackages.rails` via `flox install` rather than needing to manually edit the manifest.
- Infers the install ID from `flox install foo` and provides a flag for manually specifying the install ID at the CLI.
- Fixes a bug that would automatically set the descriptor `name` if one wasn't provided, which prevented installing packages that provided their own install ID that differed from the package name.
- Refactors the Justfile to make it a little bit more sane
- Adds a suite of logging functions that mirror those found in the Rust side of `flox` so that it's easy to turn on logging …
> feat: install packages via path instead of name

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox/Cargo.toml
- cli/flox/src/commands/search.rs
- cli/flox/src/utils/dialog.rs
A take on flox/flox#526 that implements the spinning on the cli layer by running expected long running functions on a worker thread and showing a spinner after a given timeout
If we end up needing more granular spinners from within the library, we can either inject a spinner through our context/flox instance or use something like [tracing-indicatif](https://crates.io/crates/tracing-indicatif)
> feat: show spinners for long running operations

- Justfile
- pkgdb/src/nix-state.cc
Changes the TTL on downloaded tarballs, namely `nixpkgs`, to be fresh for 24 hours rather than 1 hour. This prevents the global registry from being invalidated every hour and should result in fewer package database rebuilds.
Users should have to rebuild the search index much less often.
> feat: refresh global registry every 24 hours

- cli/flox/src/commands/environment.rs
- cli/tests/environment-activate.bats
A very preliminary implementation of `flox activate --`
Instead of opening an interactive shell with `exec shell`,
its passing down the run arguments to the shell as `shell -i -c <run args>`.
Being interactive it does all the initializations of the flox environment which are tied to the rc files.
> feat(activate): run command interactively if provided

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/environment.rs
The `Environment` trait started off as async when it was calling `async` runix functions.
We have since transitioned to a more classical sync approach.
Since we're not using any async components in any implementation, this removes `async` coloring .
> chore: remove defunct `async` on `Environment` methods

- CONTRIBUTING.md
- Justfile
- cli/tests/package-search.bats
- cli/tests/package-show.bats
- pkgdb/src/search/command.cc
- pkgdb/src/search/params.cc
- pkgdb/src/util.cc
Properly handles search terms containing `.` (e.g. nested packages) by populating `PkgQueryArgs.relPath` when the search term is a relative path. Previously these search terms were populating the `PkgQueryArgs.partial{Name}Match` fields, and returning no results for packages in the `python3*Packages` and `rubyPackages` package sets.
Addresses #653, #596
Users should be able to search for nested packages again.
> fix: searches handle terms containing dots

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/upgrade.bats
- pkgdb/include/flox/resolver/command.hh
- pkgdb/include/flox/resolver/descriptor.hh
- pkgdb/include/flox/resolver/environment.hh
- pkgdb/include/flox/resolver/manifest.hh
- pkgdb/include/flox/resolver/mixins.hh
- pkgdb/src/resolver/command.cc
- pkgdb/src/resolver/environment.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/src/resolver/manifest.cc
- pkgdb/src/resolver/mixins.cc
- pkgdb/tests/environment.cc
`flox upgrade` tries to resolve packages in a newer input. Upgrades can
be specified using iid or group name. "toplevel" is introduced as the
group name for packages without a group. `upgrade` will fail if an iid
for a package that is part of a group with other packages is specified.
Code notes:
- In pkgdb, groups are now stored as an unordered_map instead of a
vector using group name as key, since "toplevel" can be used as the
key for the toplevel group.
- A bug in `tryResolveGroup` was fixed where packages that should have
been upgraded were being resolved in the old input.
> feat: flox upgrade

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/environment.rs
- cli/tests/activate/envVar.exp
- cli/tests/activate/hello.exp
- cli/tests/activate/hook.exp
- cli/tests/activate/remote-hello.exp
- cli/tests/edit/re-activate.exp
- cli/tests/install/last-activated.exp
- cli/tests/install/prompt-which-environment-git.exp
- cli/tests/install/prompt-which-environment.exp
- tests/python.exp
Adds spinners to 
- `activate` (replacing current messaging)
- `install`
- `uninstall`
- `edit`
- `pull` is implemented as part of #655
> feat: implement building notification of activate as a spinner

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- pkgdb/src/buildenv/command.cc
- pkgdb/src/main.cc
Fixes a bunch of minor mistakes around `pkgdb` error handling.
- The Rust invocation of `pkgdb buildenv` doesn't correctly handle errors, because it expects them on stderr instead of stdout.
- `pkgdb buildenv` doesn't print JSON as expected for a pkgdb subcommand.
- `category_message` is `Optional` in `PkgDbError` but it is required in C++.
- `PkgDbError` doesn't deny unknown fields.
- Nix errors and errors without a wrapper in `pkgdb` are printed with the wrong JSON schema.
> fix: buildenv error handling

- cli/flox/src/commands/environment.rs
- cli/tests/environment-list.bats
* add `--config` flag: show the raw manifest
* add `--name-only` (default): show package names
both flags are mutually exclusive
> feat: add flox `list {--config,--name-only}` options

- cli/tests/environment-activate.bats
- pkgdb/src/buildenv/realise.cc
Variables set in the manifest are now also available in the activation hook script
fixes flox/flox#614
> fix: evaluate `vars` before running the `hook` script

- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
containerize is not yet implemented so it should not be visible in help
> fix: hide containerize from help

- pkgdb/Makefile
- pkgdb/tests/buildenv.bats
- Remove `test-data` target from `Makefile`.
- Create resources previously produced by `test-data` in the `setup_file` hook of the relevant `bats` tests.
- Use plain paths in `buildenv.bats` invocations of `pkgdb buildenv`.
- Add single test that checks inline JSON parsing for `pkgdb buildenv`.
- fix: Use consistent `--ga-registry` revision in `pkgdb/tests/buildenv.bats`.
> fix: generate test data in setup

- assets/templateFloxEnv/manifest.toml
- cli/tests/environment-activate.bats
- cli/tests/environment-edit.bats
> chore: add `vars` to manifest template

- pkgdb/Makefile
- pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh
- pkgdb/src/buildenv/realise.cc
- pkgs/flox-pkgdb/default.nix
Use `substituteAll` to inject absolute paths to binaries used in `profile.d` scripts.
fixes #676
> fix: substitute native dependencies intprofile.d scripts

- pkgdb/Makefile
Had an extra `nix` command after `$(NIX)`.
> fix: nix command invocation in Makefile

- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/pkgdb/write.cc
These were originally exposed because `PkgDb` initially had mixins which required direct access to those routines; but since those are no longer necessary we can reduce clutter in `flox/pkgdb/write.hh`.
Since that header is already massive this is worthwhile.
> refactor: make PkgDb::init() helpers static

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/floxmeta/mod.rs
- cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
- cli/flox-rust-sdk/src/providers/git.rs
* Add another error detection for failed authentication with git remotes (i.e. floxhub)
* Improve error reporting
closes #686
(cherry picked from commit 784b61704d028231d0d75a6eaa1e11850d85148c)
> fix(git): test catching `push` authentication errors

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/mod.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-types/src/catalog/mod.rs
- cli/flox-types/src/catalog/source.rs
- cli/flox/src/commands/environment.rs
- cli/tests/update.bats
- pkgdb/src/pkgdb/scrape.cc
- pkgdb/src/resolver/command.cc
- pkgdb/tests/ga-registry.bats
- Add a pkgdb scrape call for each updated input.
- Don't allow both --global and environment flags, i.e change: [-d=<path> | -r=<owner/name>] [--global] to [(-d=<path> | -r=<owner/name>) | --global]
- Move generation of messages to print to the user to Rust instead of C++, and make messages consistent with CLI guidelines.
> feat: scrape database in update and some polish

- pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh
> fix: use `command -v` to check for availability of python3, pip

- cli/flox-rust-sdk/src/models/environment/mod.rs
Observed that error messages were being printed twice, e.g.:
```
Michaels-MacBook-Pro% echo broken > /tmp/debug/.flox/env.json         
Michaels-MacBook-Pro% ~/src/flox/result/bin/flox install foo
ERROR: invalid .flox directory at /private/tmp/debug/.flox: Failed parsing contents of env.json file: Failed parsing contents of env.json file: expected value at line 1 column 1
Michaels-MacBook-Pro% ~/src/flox/result/bin/flox install foo
```
Discussed with Yannik who noted that the error was being printed both in the error description string and also by way of the error handler automatically appending it as well. The suggested fix is to stop including the "source" error message as part of the error description string.
N/A
> fix: eliminate double-printing of error messages

- pkgdb/src/resolver/lockfile.cc
- pkgdb/src/resolver/mixins.cc
- pkgdb/tests/lockfile.bats
- Fixes a parse error when processing lockfiles with `null` entries
for skipped `packages.<SYSTEM>.*` resolutions.
- Adds a test case covering this.
N/A
> fix: handle 'null' packages in lockfile

- cli/flox/src/utils/init/metrics.rs
- cli/flox/src/utils/metrics.rs
Extra fields are folded into to the submitted json blob.
closes #727
> feat: extend `subcommand_metrics` to allow passing extra fields

- Justfile
- pkgdb/Makefile
- pkgdb/include/flox/core/types.hh
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/include/flox/pkgdb/read.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/pkgdb/read.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/tests/search.bats
- pkgs/flox-pkgdb/default.nix
Adds simple database locking so that more than one search process launched shortly after one another don't step on each other.
Note that this isn't bulletproof and you'll notice in the tests that the processes aren't launched at exactly the same time. Instead, the processes are launched with a slight delay between them. This is good enough because the processes will *most likely* never be launched at **exactly** the same time in any real use case.
N/A
> feat: add database locking

- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/colors.rs
- cli/tests/environment-activate.bats
- pkgdb/src/buildenv/realise.cc
Print a short activation script that can be `eval`ed in a bashrc, if stdout is not a terminal and no command is provided.
The activation script simply exports the same variables we set for `exec` activations and sources the `activate` script for the active shell.
Activation script example:
```bash
export FLOX_ENV=/Users/yannik/.cache/flox/run/ysndr/aarch64-darwin.cli.fe47112ff9e1e0f6c10c29addea59a77d3da46c3063e54a0425d0e442695a4f8
export FLOX_PROMPT_ENVIRONMENTS=ysndr/cli
export FLOX_ACTIVE_ENVIRONMENTS='[{"type":"dot-flox","path":"/Volumes/Projects/Flox/flox/flox/cli","pointer":{"owner":"ysndr","name":"cli","floxhub_url":"https://saas-dev-main.floxdev.com/","version":1}}]'
export FLOX_PROMPT_COLOR_1=61
export FLOX_PROMPT_COLOR_2=216
export FLOX_SOURCED_FROM_SHELL_RC=1
source …
```
> fix: print activation script for use in rc files

- pkgdb/src/buildenv/assets/etc/profile.d/0100_common-paths.sh
1) If MANPATH begins with a colon, it is appended to the default list; 
2) if it ends with a colon, it is prepended to the default list; 
3) or if it contains two adjacent colons, the standard search path is inserted between the colons. 
4) If none of these conditions are met, it overrides the standard search path.
We're making use of rule 2) here
fixes #684
> fix: set MANPATH with respect to the existing and default manpath

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/utils/mod.rs
Do not build to provide `activation_path` if the manifest (or pointer lockfile) was not updated after the `out_link` was set.
This should guarantee quicker (second) activations unless the out_link is modified externally
> fix: skip build if modified after `outlink` was modified

- cli/flox-rust-sdk/src/providers/git.rs
* disable config by setting `GIT_CONFIG_{GLOBAL,SYSTEM}=/dev/null`
> fix: avoid user config leaking into git tests

- cli/flox/src/commands/auth.rs
- cli/flox/src/utils/dialog.rs
- cli/flox/src/utils/mod.rs
- cli/flox/src/utils/openers.rs
- cli/tests/auth.bats
- cli/tests/auth/loginPrompt.exp
Listen for `[enter]` events and open the token url with either `xdg-open` or `open` 
on linux or mac respectively.
closes #719
> feat(auth): enable opening auth page using `[enter]`

- .github/workflows/ci.yml
use main branch of install action, this should have the effect of trimming down our post-install-action to be faster (and smaller in terms of taking less space)
N/A
> fix: use main branch of install-flox-action

- assets/templateFloxEnv/manifest.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-init.bats
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
Adds the `options.systems` field during init populated with the current system. 
`m4` is used to inject the system into the template instead of `toml_edit` because `toml_edit` injects the `options` table between the `hook` table and the commented out script below it, so a user that uncomments the script hook will encounter an error.
Users that create an environment will now explicitly have their sytem type added to the manifest.
> feat: inject current system during init

- pkgdb/include/flox/pkgdb/read.hh
Increases the database retry timeout  from 100s to 250s so that slow CI operations don't spuriously fail.
N/A
> fix: increase busy wait timeout

- pkgdb/src/main.cc
Run `pkgdb` without catching exceptions by setting `PKGDB_NO_CATCH` to something non-empty and non-`"0"`. This is only useful for debugging as exception-catching machinery clutters backtraces.
N/A
> feat: allow running without catching

- cli/flox/src/utils/init/logger.rs
- cli/flox/src/utils/init/metrics.rs
- cli/flox/src/utils/metrics.rs
The telemetry sending used to happen in an async context on a separate thread.
Events were sent to the telemetry thread using mpsc and handled concurrently with the main thread.
Both threads were using a handle to the same global `tokio` runtime.
When the execution of the main thread completes, the async runtime is dropped.
Any task still on the runtime is aborted.
As telemetry buffering **and transfer** used the same runtime on a parallel thread,
we observed frequent aborts of the telemetry transfer (https://github.com/flox/flox/issues/432).
This PR drops the concurrent telemetry thread in favour of immediate writes to the metrics buffer
and _occasional_ transfer.
* writing on the main thread _will_ incur a small amount of time,
we hope the delay will be non-noticeable in practice
* …
> fix: remove async telemetry event handling

- pkgdb/src/nix-state.cc
Now that pkgdb databases are explicitly generated with `flox update`, we can use the shorter default Nix tarballTtl without triggering random slowdowns.
> feat: don't set tarballTtl to 24 hours

- cli/tests/activate/envVar.exp
- cli/tests/activate/hello.exp
- cli/tests/activate/hook.exp
- cli/tests/activate/rc.exp
- cli/tests/activate/remote-hello.exp
- cli/tests/edit/re-activate.exp
- cli/tests/environment-managed.bats
- cli/tests/environment-pull.bats
- cli/tests/environment-push.bats
- cli/tests/install/last-activated.exp
- cli/tests/install/prompt-which-environment-git.exp
- cli/tests/install/prompt-which-environment.exp
- cli/tests/setup_suite.bash
- cli/tests/show/prompt-which-environment.exp
Support running existing bats/expect tests with no isolation.
can be run via something like:
```
FLOX_BIN=flox \
NIX_BIN=nix \
TESTS_DIR=$PWD/cli/tests \
SHELL=bash \ PKGDB_BIN=/nix/store/zggaya81gm8m7y8bkjjrx7fxjynmaxaz-flox-pkgdb-0.1.0/bin/pkgdb \
__FT_RAN_HOME_SETUP=real \
bats cli/tests
```
Intention is to allow running and using existing bats/expect tests in a non-isolated fashion, in VMs, containers, etc.
Requires: jq, expect, bats-with-libraries (TODO)
N/A
> test: support runnning raw tests on a host

- pkgdb/Makefile
- pkgdb/include/flox/buildenv/buildenv.hh
- pkgdb/include/flox/buildenv/command.hh
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/assets/mkContainer.nix
- pkgdb/src/buildenv/buildenv.cc
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/buildenv.bats
- pkgs/flox-pkgdb/default.nix
Build a container builder using `dockerTools.streamLayeredImage`
- builds the environment 
- if `--container` provided calls vendored `mkContainer.nix` script with 
(1) a `nixpkgs` flake,
(2) the storePath of the built environment
(3) the host system
- `mkContainer.nix` creates a container builder that contains 
(1) the environment
(2) `bashInteractive`
(3) `coreutils`
> feat(pkgdb): add `buildenv --containerize` command

- cli/tests/environment-containerize.bats
Stderr output from podman regarding UID/GUID is likely a testism and not necessary at the moment.
N/A
> ci: split podman output, ignore uid/guid warnings

- .editorconfig
This causes a warning in neovim:
invalid value for option trim_trailing_whitespace: true;
> fix: stray semicolon in editorconfig

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/environment.rs
- pkgs/flox-cli/default.nix
Remove additional context from `flox push` error messages
before:
```
ERROR: Could not push new environment: ❌  You do not have permission to write to ghudgins/cli
```
after:
```
ERROR: ❌  You do not have permission to write to ghudgins/cli
```
> fix: do not add extra context to converted errors

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/tests/environment-list.bats
Detect missing packages for the current system in the lockfile
and omit them when listing.
Future changes could change the `list` output to include these packages
with a note that they are _not_ installed for the current system.
closes flox/flox#761
> fix: filter packages not installed for the current system

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/tests/environment-edit.bats
* core environment: detect if the literal content of **manifest.toml** is unchanged
and return `EditResult::Unchanged` immediately
* `Environment` implementors: skip `link`ing/creating a generation/pushing
if edit resulted in EditResult::Unchanged
closes #751
> feat(edit): skip building/linking if manifest is unchanged

- cli/flox-rust-sdk/src/models/search.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/config/features.rs
- cli/tests/package-search.bats
- pkgdb/include/flox/pkgdb/pkg-query.hh
- pkgdb/include/flox/search/params.hh
- pkgdb/src/pkgdb/pkg-query.cc
- pkgdb/src/search/command.cc
- pkgdb/src/search/params.cc
The current match-name and match search strategies will find exact matches for relPath (e.g. python310Packages.requests), but they will not return partial matches (e.g. Packages.requests).
Instead:
- Change the match-name and match strategies to no longer return results when an exact relPath is provided. Only match against pname, attrName, and in the case of match, description.
- Add a match-name-or-rel-path search strategy that returns partial matches against relPath. Make this the default search strategy.
> feat: allow partial relPath matches

- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/utils/didyoumean.rs
- cli/flox/src/utils/mod.rs
- cli/flox/src/utils/search.rs
- cli/tests/environment-install.bats
* Add a `DidYouMean` mechanism that matches terms with known package names
and searches the top 3 packages using `pkgdb search`.
* Handle `120` ("resolution failure") errors emitted by `pkgdb manifest lock` during `install`.
* print suggestions iff **one** package was provided to install.
> feat: integrate suggestions into `flox install`

- cli/flox-rust-sdk/src/models/container_builder.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-containerize.bats
- pkgdb/src/search/command.cc
- pkgdb/src/search/params.cc
* test: add `-q` to all `podman run` calls
* test: remove `\r` filtering (removing `--tty` flag from `podman run` earlier made this unnecessary)
* test: clear podman cache in `file_teardown`
improves caching of container layers and speeds up all tests reusing the same layers (~2x)
* style: add more messaging to containerize
* docs: document `ContainerBuilder`
* test: add tests for `ContainerBuilder`
> fix: improve containerize tests and touch up command implementation

- cli/flox/src/utils/init/mod.rs
Previously the message had a suffix that said " - weird". It's not ideal to
tell a user that their freshly installed flox has a weird setup if they've done
nothing. So, let's just take out the word weird.
N/A
> fix: remove "weird" from our debug message

- cli/flox-rust-sdk/src/flox.rs
> fix: print "Updating nix.conf:" to `debug` channel

- Justfile
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/openers.rs
- cli/tests/environment-managed.bats
- cli/tests/environment-push.bats
- cli/tests/environment-remote.bats
implements https://github.com/flox/flox/issues/825
> feat: add build check to ManagedEnvironment::{push,push_new}

- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/utils/didyoumean.rs
- cli/flox/src/utils/search.rs
- cli/tests/package-search.bats
Implementation of #804
currently it's using the "maximalist" alternate design since that allowed for the most code reuse currently..
Current example output:
```
$ flox search make
gnustep.make                             A build manager for GNUstep
chickenPackages_5.chickenEggs.make       The PLT 'make' macro
vimPlugins.nvim-treesitter-parsers.make  <no description provided>
alpine-make-vm-image                     Make customized Alpine Linux disk image for virtual machines
automake                                 GNU standard-compliant makefile generator
automake116x                             GNU standard-compliant makefile generator
automake115x                             GNU standard-compliant makefile generator
automake111x                             GNU standard-compliant …
```
> feat: append search of curated terms if possible

- pkgdb/src/pkgdb/input.cc
The timeouts while waiting for a database scrape were different while waiting to create a read/write connection vs. a read-only connection. The read-only timeout was roughly 20 seconds, whereas the read/write timeout is a little over 4 minutes. This PR makes the read-only timeout the same as the read/write timeout (~4 minutes).
N/A
> fix: match r and r/w db timeouts

- cli/flox/src/utils/search.rs
Apply format to a `String` rather than passing it on to the `DisplayItem` formatter.
fixes #876
> fix: column formatting of search results

- cli/flox/src/commands/environment.rs
- cli/tests/environment-activate.bats
- pkgdb/src/buildenv/assets/etc/profile.d/0100_common-paths.sh
In non-interactive, non-executing mode (i.e. when used as `eval "$(flox activate)"` allow activating an already active environment.
When spawning interactive subhells regularly (e.g. with `tmux`), users observe errors reading "Environment <env> already active". #812 
This PR adds a check after detecting double activation and permits activation.
[fix: do not fail if run non-interactive (with eval)](https://github.com/flox/flox/commit/0963d94d674ce44c891d1433fac66aec14524e0b) implements this by simply returning early, printing _nothing_.
The following commits add a mitigation to the effects of the `path_helper` on macos machines.
The `path_helper`'s intent is to construct a valid `PATH` by _appending_ default system paths.
Unfortunately, contrary to that intent, the elements of `$PATH` end …
> fix: handle `path_helper` and activate non-interactively without error

- pkgdb/include/flox/resolver/manifest.hh
- pkgdb/src/resolver/environment.cc
- pkgdb/tests/environment.cc
Currently we lock all unlocked inputs and then afterwards merge in locked inputs from the lockfile. Instead, only lock inputs that aren't present in the lockfile.
> fix: don't re-lock already locked inputs

- cli/flox/src/utils/dialog.rs
Some find it confusing that flox prompts when stdout is piped
> fix: don't prompt unless stdout is a tty

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/tests/environment-remote.bats
* feat: store remote-envs persistently and centrally
store a single copy for each remote env in `$FLOX_CACHE_DIR/remote/<owner>/<name>`
* fix: reduce unnecessary rebuilds of remote and managed environments
Pulling a managed environment _always_ causes a rebuild even if no changes were pulled.
That is because each pull would (re) write the generation lockfile at `.flox/env.lock`.
Since rebuilding depends on the mtime of that file, we rebuilt unnecessarily often.
The solution for now is to skip writing the file iff
(1) the file exists
(2) the contents are unchanged
* feat: protect active environment state until push succeded 
The inner managed environment of a remote environment is first updated, _and then_ pushed.
If the push fails $FLOX_ENV will point to the updated but unpushed out_link …
> feat: store remote-envs persistently and centrally

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/errors.rs
- cli/flox/src/utils/mod.rs
- cli/tests/environment-containerize.bats
* Adds methods to map internal library errors (`EnvironmentError2, ManagedEnvironmentError, RemoteEnvrionmentError, etc..`) to user facing error messages
* If the head of the "error chain" is a known type,
we print the rich error and omit the rest of the chain.
> feat: rich error messages for environment operations

- assets/etc/flox.toml
- cli/flox/src/config/mod.rs
- pkgs/flox-cli/default.nix
- Drop unneeded config file. Set package defaults in Rust rather than reading defaults from a RO config file in the nix store.
- Drop unused config fields
> fix: drop `flox config` cruft

- pkgdb/src/buildenv/realise.cc
- pkgdb/src/command.cc
- pkgdb/src/eval.cc
- pkgdb/src/flake-package.cc
- pkgdb/src/parse/command.cc
- pkgdb/src/pkgdb/gc.cc
- pkgdb/src/pkgdb/get.cc
- pkgdb/src/pkgdb/pkg-query.cc
- pkgdb/src/pkgdb/read.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/src/raw-package.cc
- pkgdb/src/registry.cc
- pkgdb/src/resolver/command.cc
- pkgdb/src/resolver/descriptor.cc
- pkgdb/src/resolver/environment.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/src/resolver/manifest-raw.cc
- pkgdb/src/resolver/mixins.cc
- pkgdb/src/search/command.cc
- pkgdb/src/util.cc
- pkgdb/tests/groups.bats
- pkgdb/tests/search.bats
Aligning pkgdb outputs with style guide, i.e. single quotes around code words as discussed in https://github.com/flox/product/issues/596
Left  `` `...' `` in place where they were used in comments
> chore: replace backticks for single ticks in outputs

- cli/flox-rust-sdk/src/models/environment_ref.rs
- cli/flox/src/commands/environment.rs
Adds an error handling layer above parsing environment names so that a more informative error message can be shown to the user.
```
$ flox init --name foo/bar
ERROR: Name 'foo/bar' is invalid. Environment names may not contain ' ' or '/'.
```
N/A
> fix: better env name error message

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox/Cargo.toml
- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/colors.rs
- cli/flox/src/utils/errors.rs
- cli/flox/src/utils/init/logger.rs
- cli/flox/src/utils/logger.rs
* remove bold errors
* remove indentation of following log lines
* add timestamp, file, and line number in `--debug` mode
This still uses `log` for both "logging" and "communicating" for now as the change to this is less invasive then either formally splitting `tracing` for logging from `log` (or custom wrappers) for logging.
This reduced scope was discussed in #849
> style: lighter post processing of user facing output

- cli/flox/src/commands/mod.rs
Allows to use flox in non-interactive settings without explicitly providing a `-d` flag to every command,
when there is _also_ an active environment.
> fix: use nearest found environment by default if unable to prompt

- Justfile
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox/src/config/mod.rs
Fix broken unit tests
Remove popd in Justfile commands.
The popd sets exit code to 0, and it isn't necessary because the pushd
only applies to the current line anyways
> chore: fix exit code in Justfile and broken tests

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/utils/errors.rs
> fix: return an error early if specified path does not contain `.flox`

- cli/flox/src/commands/search.rs
fixes https://github.com/flox/flox/issues/891
> fix: add empty line after `flox show` hint for better visibility

- cli/flox/src/commands/environment.rs
We now create a tempfile named manifest.<random>.toml rather than simply
<random>, which allows the text editor to properly detect the kind of
file and enable syntax highlighting.
> feat: Add .toml extension to temp manifest created for editing

- pkgdb/include/flox/core/util.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/util.cc
Using macros allows avoiding allocating strings that won't actually be logged.
From my perspective, this sacrifices some maintainability for performance, so I'm not convinced we should do it this way.
> perf: make logging functions macros

- pkgs/flox-cli/default.nix
This updates the base URL and client id to use the production values.
> chore: Use production Auth0 tenant

- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/general.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
Remove duplicate descriptions from `flox` help text.
Previously the help looked like this:
```
> flox show --help
Show details about a single package
Usage: flox show [--all] <search-term>
Show detailed package information
```
The second description above has been removed.
Closes #922
N/A
> fix: remove duplicate descriptions

- pkgdb/tests/buildenv.bats
This gets rid of the seemingly random `ls` output that appears early in `pkgdb` test runs.
> fix: remove spurious `ls` invocation from `pkgdb` tests

- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/general.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/message.rs
- cli/flox/src/utils/mod.rs
- cli/flox/src/utils/search.rs
- cli/tests/edit/re-activate.exp
- cli/tests/environment-containerize.bats
- cli/tests/environment-edit.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/package-search.bats
> **tl;dr:** 
>
> This PR should make the messaging across `flox` more consistent
> If we provide _messages_ to users (success, error, warning, creation, update,...)
> We can do so through the new `message` module introduced here.
> Lifting this responsibility from the logging subsystem,
> which can now be used for its intended purpose, logging --
> optional semi user facing (structured) messages.
We are currently using a mix of `println!`, `eprintln!`, `log::info!`, `log::error!`
to display _messages_ to users on the CLI.
* `println!` => processable output.
* `log::error!` => error messages, prefixed with `ERROR:`
* `eprintln!` and `log::info` => other user facing messages without or limited processing
Using `log` for user output is suboptimal since `log` will do double duty
for logging …
> feat: add messaging functions

- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-pull.bats
- cli/tests/pull/answerPrompt.exp
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/core/exceptions.hh
- pkgdb/src/buildenv/realise.cc
- tests/cross-system.bats
Catch specific eval and build errors of packages during the build of an environment.
Eval errors thrown by nixpkgs' metadata checks regarding the supported system
are caught early and reported as a distinct error.
Other eval errors (such as missing attrpaths, python version assertions, etc.)
are caught generically.
Build errors, e.g. for unfree software that is not cached are similarly caught
and reported as a separate category.
> feat: handle package build and eval failures

- cli/flox-rust-sdk/src/models/container_builder.rs
Resolve issues with rust unit tests in `models::container_builder::tests::*`.
The container builder tests spuriously failed with `Text file busy`:
```
thread 'models::container_builder::tests::test_writes_output_to_writer' panicked at flox-rust-sdk/src/models/container_builder.rs:81:54:
called `Result::unwrap()` on an `Err` value: CallContainerBuilder(Os { code: 26, kind: ExecutableFileBusy, message: "Text file busy" })
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::result::unwrap_failed
3: core::result::Result<T,E>::unwrap
at /build/rustc-1.73.0-src/library/core/src/result.rs:1077:23
4: flox_rust_sdk::models::container_builder::tests::test_writes_output_to_writer
at ./src/models/container_builder.rs:81:9
5: …
```
> fix: rust unit test "Text file busy"

- cli/tests/environment-activate.bats
- pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh
The profile.d script managing the python setup used to detect _any_ `python3` available on the `$PATH` which summons an xcode wizard on macos.
This PR changes the profile.d script to look for `python3` within `$FLOX_ENV/bin` explicitly.
fixes #877
> fix(activate): only detect python in `$FLOX_ENV`

- assets/templateFloxEnv/manifest.toml
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/commands/environment.rs
- cli/tests/container/manifest.toml
- cli/tests/edit/manifest.toml
- cli/tests/environment-edit.bats
- cli/tests/environment-install.bats
- cli/tests/environment-list.bats
- cli/tests/environment-pull.bats
- cli/tests/ld-floxlib/manifest.toml
- pkgdb/docs/manifests.md
- pkgdb/include/flox/resolver/descriptor.hh
- pkgdb/src/raw-package.cc
- pkgdb/src/resolver/descriptor.cc
- pkgdb/src/resolver/environment.cc
- pkgdb/tests/data/manifest/ga0.toml
- pkgdb/tests/data/manifest/ga0.yaml
- pkgdb/tests/data/manifest/manifest0.toml
- pkgdb/tests/data/manifest/manifest0.yaml
- pkgdb/tests/data/manifest/post-ga0.toml
- pkgdb/tests/descriptor.bats
- pkgdb/tests/environment.cc
- pkgdb/tests/lockfile.bats
- pkgdb/tests/manifest.cc
Renames the manifest descriptor field `path` to `pkg-path`.
All environments on FloxHub will need to be edited and pushed again.
> refactor: path -> pkg-path

- cli/flox/doc/flox-install.md
- cli/flox/doc/flox-search.md
- cli/flox/doc/include/package-names.md
Rename `path` -> `pkg-path` in the man pages.
Note: this will need to be rebased once the outstanding man pages PR is merged.
> docs: path -> pkg-path in man pages

- cli/flox/src/commands/mod.rs
Seems like we added two bpaf `command` annotations, the second of which overrode the first.
This PR merges both into one annotation, meaning we now have both footer and header, as well as hiding the command from `flox --help`.
closes #1010
> fix: hide duplicate `upgrade` from help

- pkgs/flox-manpages/default.nix
- pkgs/flox-manpages/pandoc-filters/filter-links.lua
We experienced issues with pandoc's link handling [1]. For a short term mitigation this PR adds a small lua filter that strips all links from documents before they are compiled to roff and inserts them as plain underlined text.
In addition it refactors the compilation to be less inline'y.
[1]: https://github.com/jgm/pandoc/issues/9458
> build: strip links from manpages

- cli/flox/doc/flox-config.md
- cli/flox/src/config/mod.rs
- cli/tests/setup_suite.bash
- pkgs/flox-gh/default.nix
- tests/setup_suite.bash
* Sets `config_dir` config value as a constant,
thus making resolution consistent.
If explicitly provided in a config file, the value will be ignored.
* Read `config_dir` value from `FLOX_CONFIG_DIR` rather than `FLOX_COFIG_HOME`
> chore: rename `FLOX_COFIG_HOME` -> `FLOX_CONFIG_DIR`

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- pkgdb/build-aux/changed-sources.sh
Restores GitHub Action from original `pkgdb` repository which runs
`clang-tidy` ( a lint checker ) and converts it output into GitHub suggestions.
This PR also causes existing CI workflows to cancel in progress runs if another
PR for the same _ref_ is pushed.
This should hopefully reduce CI spend.
> ci: add pkgdb lint check

- cli/flox/doc/manifest.toml.md
Fixes the header depth for the "Package names" section of the `manifest.toml.md` man page. The include has a `##` header, which breaks the outline of this particular man page.
N/A
> docs: fix header depth in manifest page

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-delete.bats
For `flox install pkg1 pkg2` in a directory without an environment, print:
```
❌ ERROR: Did not find an environment in the current directory.
Create an environment with 'flox init' or install to an environment found elsewhere with 'flox install pkg1 pkg2 --dir <PATH>'
```
For `flox install pkg1 pkg2 -d /tmp` when there's no environment in `/tmp`, print:
```
❌ ERROR: Did not find an environment in '/tmp'
Create an environment with 'flox init --dir /tmp'
```
For `flox uninstall pkg1 pkg2` in a directory without an environment, print:
```
❌ ERROR: Did not find an environment in the current directory.
Create an environment with 'flox init' or uninstall packages from an environment found elsewhere with 'flox uninstall pkg1 pkg2 --dir <path>'
```
For `flox uninstall pkg1 pkg2 -d /tmp` when …
> feat: handle env not found in install/uninstall

- cli/flox/doc/flox-containerize.md
- cli/flox/doc/flox-delete.md
- cli/flox/doc/flox-edit.md
- cli/flox/doc/include/experimental-warning.md
- cli/flox/src/commands/mod.rs
Small fixes to the manpages
* docs(containerize): fill out manpage sections
* docs(containerize): add experimental command warning
* docs(edit): remove duplicate `-f` option
* docs(delete): remove `-r` option
* docs(delete): add crossref to `flox-init(1)`
> docs: manpage touch ups

- cli/tests/setup_suite.bash
When setting up the test suite, we used to _copy_ the user's nix and flox config into the otherwise isolated managed test suite.
The commentary on the containing function suggests that _caches_ are copied for efficiency.
In the absence of compelling reason to impurely use user config files in the test suite, this removes the section that copies flox and nix config dirs and replaces it with `mkdir -p`.
> fix: do not copy user config into test suite

- cli/flox/doc/flox-auth.md
- cli/flox/src/commands/auth.rs
Provides a `flox auth status` command that tells you whether you're logged in to FloxHub or not.
Largely based on the hidden `user` subcommand which got renamed and documented in this PR.
> feat: expose flox auth status

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-pull.bats
`ManagedEnvironment::pull` will return `PullResult::UpToDate`
if both the project specific branch and it's upstream counterpart
are pointing at the same revision.
> feat: detect same commit on project and sync branch

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/tests/environment-activate.bats
When no explicit environment is provided using `-r` or `-d`
**and** the current the current active env is called `default`
**and** an environment is found in the parents of the current dir,
**then** perform flox operations _on the detected env_
**and** do not ask the user to chose.
In presence of another environment, a default environment can now only be modified by addressing it explicitly using `-d/-r`.
closes https://github.com/flox/flox/issues/833
> feat: do not prompt if current active environment's name is `default`

- pkgdb/include/flox/flox-flake.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/flox-flake.cc
- pkgdb/src/registry.cc
Add wrappers around `lockFlake` and `getFlake` to ensure downloads of flakes occur in child processes.
N/A
> fix: add helpers for lockFlake and getFlake

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-list.bats
* Make `PackageInfo.version` an `Optional<String>`
* Write missing version as `N/A` in `flox list` impls
* Add a test to catch regressions
fixes #https://github.com/flox/flox/issues/1039
> fix: tolerate missing version field in packages of locked manifest

- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/metrics.rs
Records a telemetry message with the extra field `failed_packages`: "p1,...,pN"`, where `p1,...,pN` is a comma separated list of the packages supplied to the cli.
closes #950
> feat: record which packages caused a failed install attempt

- cli/tests/ld-floxlib.bats
- cli/tests/ld-floxlib/get-glibc-version.c
- cli/tests/ld-floxlib/test-load-library-last.sh
- pkgdb/Makefile
- pkgdb/src/ld-floxlib.c
- pkgs/flox-pkgdb/default.nix
- Revert skipping ld-floxlib test. The test appears to have been failing because bats was backgrounding a `flox activate -- ...` command. At the time `flox activate` invoked `bash -i -c`. If a background process tries to read from stdin it is sent SIGTTIN. We've since merged https://github.com/flox/flox/pull/889 which no longer invokes `bash` with `-i`, so it's no longer attempting to read from stdin
- Build ld-floxlib for default make target. Without this change, ld-floxlib is not built by `just integ-tests`
- Update `ld-floxlib.c` to "pin" GLIBC symbol versions to the minimum available (varies by architecture type) so as to maximise compatibility with older versions of GLIBC.
- Update `ld-floxlib.c` to replace the use of `stat()` with `open()`, which is a) a function symbol in glibc …
> fix: ld-floxlib compatiblity, re-enable test

- .github/workflows/lint.yml
This one was hard to catch in a PR because it only runs on `main`.
Fixes crash on `lint` workflow when run by trigger.
> fix: typo in workflow

- pkgdb/include/flox/core/util.hh
- pkgdb/include/flox/flox-flake.hh
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/registry.cc
- pkgdb/src/util.cc
- pkgdb/tests/pkgdb.cc
- pkgdb/tests/util.cc
- pkgs/flox/default.nix
Use available memory and observed heuristics to adjust the scraping page size.  This will allow scraping to work down to around 1.5G at the cost of 200% performance impact, but also reduce scrape time by ~15% if ~4G or more is available.
Dynamically optimize memory / performance trade-off during scraping
> feat: use available memory to improve scrape perfomance

- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/flox-flake.cc
- pkgdb/src/pkgdb/write.cc
- split apart the `scrape` function to address linting warnings
- parse the subtree type using the `subtree_type` enum and pass that around.  Since that is static for all children, it can be parsed once and the `enum` checked for various logic.  This also eliminates implied bools being passed around.
- general refactoring of code to limit passing complex values, and unnecessary code execution.
N/A
> fix: code clean up and performance fixes

- pkgdb/src/util.cc
On mac, since we are unable to find a decent method of estimating _available_ memory, use 75% of physical RAM for now.  Currently on mac, it seems it's almost always using the bare minimum page size casing a 2x time penalty.
- Addresses flake scraping performance on MacOS.
> fix: scrape performance on mac

- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-rust-sdk/src/models/search.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/logger.rs
- pkgdb/src/main.cc
Sets an environment variable in `flox` to indicate to `pkgdb` which verbosity level to use. Also redirects `pkgdb` stderr through the `flox` logging machinery.
For calls to `pkgdb search` the stdout and stderr output is streamed using background threads and a channel to preserve the order of stdout/stderr while `pkgdb` prints search results to stdout. Preserving this order is essential for debugging. For all other calls to `pkgdb` we can take a simpler approach: streaming stderr and then collecting the data on stdout.
Users passing at least two `-v` flags will now see more output.
> feat: stream pkgdb stdout/stderr in order

- cli/tests/environment-managed.bats
- cli/tests/environment-pull.bats
- cli/tests/environment-push.bats
- cli/tests/environment-remote.bats
Diverse test files were setting up isolated home dirs for _all_ contained tests
using `home_setup test`.
While this provides better isolation between tests
it also increases the test runtime as caches have to be regenerated for every test.
By sharing a common home_dir between all (most) tests,
we can speed up the affected test files by approx. 25%.
In total that should accumulate to 1 tot 2  minutes total time saved per run of the test suite.
> test: share common home (caches, etc) between tests

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/fetchers/wrapped-nixpkgs-input.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/fetchers/wrapped-nixpkgs-input.cc
- pkgdb/tests/buildenv.bats
- pkgdb/tests/data/buildenv/lockfiles/unfree-allowed/manifest.toml
- pkgdb/tests/data/buildenv/lockfiles/unfree/manifest.toml
Convert `github:nixos/nixpkgs` references, locked in manifest lockfiles, to `flox-nixpkgs:v0` references.
NOTABLE BEHAVIOUR:
* registries can only be references to upstream nixpkgs using the `github:` scheme
* unfree (and broken) packages are denied by default and cause a `PackageEvalFailure` unless `options.allow.{unfree,broken}` is set to `true` in the manifest.
> feat: use custom fetcher to wrap nixpkgs of locked packages

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox/src/commands/environment.rs
- pkgdb/include/flox/buildenv/command.hh
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/core/exceptions.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/.gitignore
- pkgdb/tests/buildenv.bats
- pkgdb/tests/realise.cc
This PR is a dramatic speedup to all operations that build environments (install, pull, etc). This is accomplished via two major changes. It's recommended to review this by each commit since the two major changes are each isolated to their commits.
The first major change is reusing temporary builds of environments. During transactions a copy of the environment is built in a temporary directory so as to not modify the existing environment until we know the new one builds successfully. The result of the build is a Nix store path for the newly built environment. Previously this store path was discarded. After building the temporary copy, the environment is built again from scratch so that it can create the GC root in the correct location. Now this store path is retained and passed to `pkgdb …
> feat: substantial speedup of all build operations

- pkgdb/Makefile
- pkgdb/include/flox/core/util.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/pkgdb/rules.json.hh
- pkgdb/src/pkgdb/scrape.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/src/util.cc
- pkgdb/tests/pkgdb.cc
Add allow/disallow recurse/no-recurse rules for scraping.  This PR should not change the scope of what is scraped.  Those changes (additional rules) will be added as separate PRs.  Notes from the original PR have been carried over.
- Adds the ability to provide `pkgdb` scrape creation rules.
- Rules can be edited in a hard coded `pkgdb/src/pkgdb/rules.json.hh`.
Notable limitations:
- Cannot nest `allow*` under `disallowRecursive` ( docs in `rules.json.hh` reflect this limitation ).
+ `applyRules()` - supports nesting `allow*` under `disallowRecursive`.
+ `scrape()` - implementation may prevent this from working.
- Hard coded rules file - previous PR allowed for a command line argument to define the rules file, however, it's not clear when or if that will be needed and had several `FIXME`s …
> feat: use rules for scraping.

- cli/flox-rust-sdk/src/flox.rs
- tests/cross-system.bats
The domain names for the preview instance were changed from
hub-dev.flox.dev to hub.preview.flox.dev
and
api-dev.flox.dev to api.preview.flox.dev
> fix: hub-dev -> hub.preview

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox/Cargo.toml
- cli/flox/src/commands/init.rs
- pkgdb/tests/search.bats
Implement nodejs init hooks, but only run them if _FLOX_NODE_HOOK is set, since the npm and yarn hooks are not yet implemented.
- Look for nodejs version in .nvmrc
- Look for nodejs version in the engines.node field of packages.json
Depending on whether a version is found and whether Flox can provide it, offer to install nodejs.
If offering to install nodejs, look for package-lock.json and yarn.lock, and depending on which are present, offer to add a hook.
> feat: add nodejs init hooks

- cli/flox/src/commands/environment.rs
Adds spinning messages to more potentially long-running tasks.
> style: add missing spinners to `flox {update,upgrade,push}`

- pkgdb/include/flox/flox-flake.hh
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/fetchers/wrapped-nixpkgs-input.cc
- pkgdb/src/flox-flake.cc
- pkgdb/src/pkgdb/input.cc
- pkgdb/tests/realise.cc
- Fix forked child exits during scraping to use `_exit()`
- Remove `flox::lockFlake()` and wrapper to fork for downloads, no longer needed.
N/A
> fix: use native nix::flake::lockFlake in fetcher

- cli/flox/doc/flox-activate.md
- cli/flox/src/commands/mod.rs
- cli/tests/environment-remote.bats
Automatically trust remote environments owned by "flox"
> feat: trust official flox environments by default

- pkgdb/Makefile
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/include/flox/pkgdb/read.hh
- pkgdb/include/flox/pkgdb/scrape-rules.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/pkgdb/read.cc
- pkgdb/src/pkgdb/schemas.hh
- pkgdb/src/pkgdb/scrape-rules.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/tests/data/search/params-local.json
- pkgdb/tests/migrate.bats
- pkgdb/tests/pkgdb.cc
- New Db schema to store scraping meta data
- Include a hash of the rules used to scrape in the Db
- When opening the Db, if the hash for the rules is different, invalidate the Db so it will be re-created
- New schema for the package Db will cause existing databases to be re-created.
> feat: invalidate database when scraping rules change

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-rust-sdk/src/models/search.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/tests/environment-install.bats
- cli/tests/package-show.bats
- cli/tests/update.bats
- cli/tests/upgrade.bats
- pkgdb/include/flox/search/params.hh
- pkgdb/src/search/command.cc
- pkgdb/src/search/params.cc
Depending on which of package.json, package-lock.json, and yarn.lock are
present, check for a compatible version of yarn.
yarn hardcodes nixpkgs#nodejs as the node it uses, so make sure
nixpkgs#nodejs is compatible with engines.node before offering to
install yarn.
If constraints are not satisfied, fall back to just installing nodejs.
At this point, don't check engines.npm, because nixpkgs only contains
one version of npm, but it contains more versions of npm bundled in with
the several different versions of nodejs it contains.
The node init hook is left feature flagged with _FLOX_NODE_HOOK.
> feat: install yarn in node `flox init` hook

- cli/tests/install/prompt-which-environment-git.exp
- cli/tests/install/prompt-which-environment.exp
The expect tests were only waiting until they _saw the spinner_ before issuing `cd 2` and expecting an echo of `cd 2` from the shell.
However, since the spinner continuously updates the terminal, the output got mangled: https://github.com/flox/flox/actions/runs/8193738916/job/22408165476?pr=1133#step:6:375
```
cd here ^, the respective 2 is yonder to the right ------------------------------------------------------ ^
```
> fix(expect): wait for final activation output

- cli/tests/auth.bats
- cli/tests/environment-activate.bats
- cli/tests/environment-edit.bats
- cli/tests/environment-install.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-pull.bats
- cli/tests/environment-remote.bats
- cli/tests/package-show.bats
- tests/python.bats
Makes the output from failed `expect` tests less verbose so that it's easier to identify the cause of the test failure.
N/A
> chore: less verbose output from expect

- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/colors.rs
- cli/flox/src/utils/dialog.rs
- pkgdb/src/buildenv/assets/mkContainer.nix
- pkgdb/src/buildenv/assets/set-prompt.bash.sh
- pkgdb/src/buildenv/assets/set-prompt.zsh.sh
Uses new brand colors for the flox prompt and dialogs and explicitly support `NO_COLOR` for prompts
> style: use new brand colors for prompts and dialogs

- pkgs/flox-cli/default.nix
Uses the new custom domain for auth0.
> feat(auth): Use the custom auth0 domain

- pkgdb/src/buildenv/assets/set-prompt.bash.sh
Fixes flipped logic introduced in #1151
> fix: `NO_COLOR` support for bash prompts

- cli/flox/src/commands/mod.rs
- pkgdb/build-aux/iwyu
- Add `-V` as short argument for `--version`
- `-V` is short for `--version`
> fix: add -V short for --version

- cli/Cargo.lock
- cli/flox/Cargo.toml
- cli/flox/src/commands/environment.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/mod.rs
- doc/release-notes/rl-1.0.1.md
follow up on https://github.com/flox/flox/pull/1153, which mitigated this for pkgdb but not git
This PR is setting nix related env vars globally for the entire process at startup, as well explicitly for activated environments.
> fix: set default nix vars process wide

- cli/flox/src/commands/environment.rs
Small tweak to offer an additional suggestion when a user encounters 'environment exists' (in FloxHub) error. 
N/A
> fix: improve already exists error message suggestion

- .github/workflows/ci.yml
- cli/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- cli/flox/src/utils/completion.rs
- cli/tests/environment-push.bats
- pkgs/flox-tests/default.nix
- tests/cross-system.bats
* Validate `floxhub_token` on startup
* Warn if token is expired, or otherwise invalid
* Try unset token from user conf file, if validation failed.
May fail if the token is set by a global conf file or env var. Failures to unset from the user conf are _ignored_, but trying to use the token later will trigger a login flow regardless.
* Ensure present token for all modifying remote commands
> feat: handle expired tokens

- README.md
changing from
https://floxcommunitygroup.slack.com
to
https://go.flox.dev/slack
> Update README.md to fix slack link

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox/Cargo.toml
- cli/flox/doc/flox-activate.md
- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/openers.rs
- cli/tests/environment-activate.bats
- cli/tests/environment-edit.bats
- cli/tests/environment-init.bats
- cli/tests/environment-install.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/package-show.bats
- tests/python.bats
We currently rely on `$SHELL` for our detection of the executing shell.
However, sub shells do not reliably reset this variable.
When `flox activate --print-script` is `eval`'ed in a sub shell
-- e.g. a direnv issued bash -- an incompatible script may produced.
SHELL=zsh bash -c 'eval "$(flox activate --print-script)"'
.../activate/zsh:13: setopt: command not found
.../activate/zsh:14: setopt: command not found
This PR implements detection of the parent shell by determining
and inspecting the exe path of the parent process.
If determining the parent process fails,o r the process is an unsupported shell,
we fall back to the existing `$SHELL` detection.
Both methods are overridden by an explicit `FLOX_SHELL` variable.
> fix: implement parent shell detection by process id

- .github/workflows/ci.yml
fail earlier in cases of a hard-lock, we had cases of jobs running for many hours
N/A
> ci: include time limits below the default 6 hours

- flake.lock
With the v1.0.1 we forgot to bump the `flox-latest` input and for this reason we were getting `v1.0.0-...` version.
> build: update flox-latest flake input

- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/init/logger.rs
Wrapping the `Filtered` layer in a `reload::Layer` caused the filter
to be applied globally.
The reload was exposing the filtering of the wrapped layer and applied it globally.
I am personally _not_ convinced this is _expected_ behaviour.
Making only the filter reloadable seems to both simplify the reload handle type
and fix the unwanted propagation of the filter to the global context.
Ordering of the log layer is still significant for unknown reasons:
Filtered layer must come first.
This appears to be the only way to avoid logs of the `flox_command` trace
which is processed by the `log_layer` irrepective of the filter applied to it.
My current understanding is, that it because the `metrics_layer` (at least) is
registering `Interest` for the event and that somehow bypasses the filter?!
> fix: wrap the filter directly in the reload layer

- cli/flox/Cargo.toml
- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/general.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/init/logger.rs
Adds tracing instrumentation to individual commands so that they can be picked up by Sentry. The only command not covered by instrumentation is `activate`, which needs special handling because we call `exec` in this command. That will come later once we have a solution.
N/A
> feat: add tracing instrumentation

- README.md
as we are trying to move over to slack instead
> Update README.md to remove old discord link

- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/mod.rs
- cli/tests/environment-init.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
- cli/tests/install/last-activated.exp
- cli/tests/install/prompt-which-environment-git.exp
- cli/tests/install/prompt-which-environment.exp
Shortens environment descriptions so that they no longer include absolute paths. This also adds single quotes in specific places so that it's always clear when a word is the name of the environment.
**Previous output**
Install
**New output**
Delete
Install
Init
Environment names will now always appear as `<owner>/<name>` or simply `<name>` instead of `<name> at <path>` so that CLI output is less verbose.
> feat: shorten environment descriptions

- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/init/metrics.rs
- cli/flox/src/utils/metrics.rs
For the most part wraps the existing metrics workflows
but allows for more granular tests of the individual components.
I.e.
* flushing can be tested without a connection to the datalake
* tracing behavior can be tested without setting up tracing globally
* Automatic flushing on drop can be tested as well without global setup.
This change _also_ include tests for the MetricsBuffer that buffers metrics on disk.
The design is heavily inspired by the sentry library.
> refactor: testable metrics abstractions

- .github/workflows/ci.yml
- Justfile
- cli/tests/environment-activate.bats
- cli/tests/environment-containerize.bats
- cli/tests/environment-delete.bats
- cli/tests/environment-edit.bats
- cli/tests/environment-init.bats
- cli/tests/environment-install.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-pull.bats
- cli/tests/environment-push.bats
- cli/tests/environment-remote.bats
- cli/tests/ld-floxlib.bats
- cli/tests/package-search.bats
- cli/tests/package-show.bats
- cli/tests/setup_suite.bash
- cli/tests/test_support.bash
- cli/tests/update.bats
- cli/tests/upgrade.bats
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/pkgdb/read.cc
- pkgdb/src/pkgdb/scrape.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/tests/scrape.bats
- pkgdb/tests/search.bats
By default integration tests reuse the same home directory, including config, cache and data directories to improve test performance (mainly reusing nix and pkgdb caches).
However, when run in parallel multiple processes started at the same time contest:
* the global manifest and lockfile 
+ created by multiple processes
+ deleted by some but assumed present by others
+ updated, upgraded, reset
* pkgdb package databases
+ attempted to be created by multiple processes (possibly a bug related to db locking)
* floxmeta clones for managed environments
+ same _owner_ and project name being reused
+ environments are created/deleted/edited concurrently -> git errors, and just plain data corruption
* local ephemeral environments by `--remote` commands.
+ git concurrency
This PR introduces a new …
> test: isolate flox config and caches

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
Currently integration tests cover catching pkgdb build errors when a
manifest does not support the current system, or a package does not
support the current system. These cases will be faster and more targeted
if unit tested instead of integration tested.
Dropping integration tests will be done in a followup PR.
Writing these tests revealed there's currently no easy way to avoid a pkgdb scrape in a unit test and use an isolated flox instance, so the following changes were made as well:
- Add a test_helpers module with flox_instance_with_global_lock that
ensures pkgdb scrape has been run and then adds a global lock to the
flox instance being created.
- Move flox_instance to the test_helpers module
- Drop FLOX_INSTANCE in favor of flox_instance_with_global_lock. Using a
single FLOX_INSTANCE …
> test: unit test incompatible environments

- pkgs/flox-cli-tests/default.nix
- pkgs/flox-tests/default.nix
nix-serve was used in publish tests which have been dropped
> chore: drop unused dependency nix-serve

- cli/flox/src/main.rs
- cli/flox/src/utils/metrics.rs
Uses our metrics UUID as the Sentry user ID and attaches it to all metrics.
N/A
> feat: add sentry user id to metrics

- CONTRIBUTING.md
- Add a note about running CI on external forks
- Move information more relevant for first time contributions to the top
> docs(CONTRIBUTING): add note about CI, reorganize

- .github/CONTRIBUTORS.csv
- cli/flox/src/commands/environment.rs
- cli/tests/environment-pull.bats
When using `flox pull --force` while in an environment, it fails to overwrite the environment. This commit allows overwriting it by checking if the `force` flag is set.
Closes #1205 
Allow overwriting the environment when pulling with `--force`, i.e. `flox pull --force`.
> fix: allow `flox pull` to overwrite environment with `--force` flag

- .github/ISSUE_TEMPLATE/bug-report.md
This avoids users that create bug reports to fixup the bold formatting each time themselves.
N/A
> fix: Correct bold formatting in bug template

- .github/CONTRIBUTORS.csv
- cli/flox/src/main.rs
Make it easier for third parties to parse the version output.
Resolves #1256.
> chore(cli): Omit the "Version: " prefix when printing the version

- cli/Cargo.lock
- cli/flox/Cargo.toml
- cli/flox/src/utils/search.rs
#1250 added the `console` crate to bolden search terms.
Including `console` for styling is redundant considering that `crossterm::Stylize` supports the same features _and_ is used elsewhere in the code base already.
> refactor: remove dependency on `console` in favor of using `crossterm`

- pkgdb/tests/setup_suite.bash
Without this patch tests fail as follows on systems where the 'nix-command' experimental feature has not been configured as a system-wide default:
```
✗ setup_suite []
TESTS_DIR: /Users/brantley/src/flox/pkgdb/tests
PKGDB_BIN: /Users/brantley/src/flox/pkgdb/bin/pkgdb
(from function `nix_system_setup' in file tests/setup_suite.bash, line 73,
from function `env_setup' in file tests/setup_suite.bash, line 127,
from function `common_suite_setup' in file tests/setup_suite.bash, line 140,
from function `setup_suite' in test file tests/setup_suite.bash, line 144)
`setup_suite() { common_suite_setup; }' failed
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
bats warning: Executed 1 instead of expected 168 tests
168 tests, 1 …
```
> fix: enable nix-command experimental-feature for test

- cli/flox/src/commands/edit.rs
> fix: unhandled `unwrap` in `flox edit`

- .github/dependabot.yml
- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/floxmeta.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/config/mod.rs
- cli/flox/src/utils/dialog.rs
* build: move dev dependency declarations to workspace
* build: update outdated dependency declarations
* build: update crates packages to latest semver versions
* ci: configure dependabot for the cli/rust workspace
Updating `inquire` broke some particular expect/prompt tests.
I reverted that commit and would propose fixing this in a separate issue.
I also kept `reqwest` at `0.11` despite their recent bump to `0.12` because `progenitor` will depend on `0.11` by default. We'll add progenitor soon to generate a rest client -- We will investigate bumping `reqwest` within that context.
> build: update cargo managed dependencies

- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
Init customizations now use profile.common, but this was never updated in format_customization
> fix: use profile.common in format_customization

- cli/tests/activate.bats
- pkgdb/src/buildenv/realise.cc
This PR fixes a bug that causes activation failures when the path to a project contains spaces.
**Root cause**
Our activation script sources the scripts stored in `$FLOX_ENV/etc/profile.d`, and previously it did so like this:
```bash
declare -a _prof_scripts;
_prof_scripts=( $(
echo "$FLOX_ENV/etc/profile.d"/*.sh;
) );
for p in "${_prof_scripts[@]}"; do . "$p"; done
unset _prof_scripts;
```
This creates an array, and then populates it with the output of a globbed `echo` command. The output of this echo command is a space-delimited string of paths. An array in both Bash and Zsh is constructed from a string containing space-delimited fields. This presents a problem when the paths themselves contain spaces, as those internal spaces appear the same as delimiters.
Thus, the path `foo bar` …
> fix: handle project paths that contain spaces

- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-config.md
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- pkgdb/src/buildenv/assets/set-prompt.bash.sh
- pkgdb/src/buildenv/assets/set-prompt.zsh.sh
Adds a new config option `shell_prompt` with the possible values `show-all`, `hide-all` and `hide-default`.
`flox activate` respects this config and will **disable** the prompt modifications if the value is `hide-all`.
With `hide-default` it filters out all `default` environments, entirely disabling the prompt if all active envs were filtered.
> feat(activate): allow activation without prompt

- cli/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/init/sentry.rs
- cli/flox/src/utils/metrics.rs
- cli/flox/src/utils/mod.rs
Check for a new flox version on downloads.flox.dev, and if one is available, print a notification to the user.
Only print this notification once every 24 hours.
The notification is printed after command output, and the network call to check for a new version will timeout after 2 seconds.
```
flox version 1.0.2
Usage: flox OPTIONS (init|activate|search|install|...) [--help]
Use `flox --help` for full list of commands and more information
First time? Create an environment with `flox init`
🚀  Flox has a new version available. 1.0.2 -> 1.0.3
Get the latest at https://flox.dev/docs/install-flox/
```
If a command fails, the notification will be printed before the error message:
```
🚀  Flox has a new version available. 1.0.2 -> 1.0.3
Get the latest at https://flox.dev/docs/install-flox/
❌ ERROR: …
```
> feat: notify when new CLI version is available

- pkgdb/src/ld-floxlib.c
The code to parse multiple FLOX_ENV lib directories was mutating the FLOX_ENV_LIB_DIRS environment and consequently breaking its ability to locate libraries in all but the first library on the list.
This patch updates the code to first make a copy of the environment variable, then split that new string into tokens as it populates a new array of pointers. To make the code as efficient as possible the string and array data are maintained in static fixed-length buffers, so we correspondingly make best efforts not to overflow those buffers in the process.
- fixed bug affecting ability to load dynamic shared libraries from layered environment activations
> fix: multiple FLOX_ENV_LIB_DIRS support for ld-floxlib.so

- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
This PR changes the `InitHook` trait by dropping `should_run` check and implementing a type-checker friendly design by allowing trait objects to be instantiated with `None` if they are not intended to run.  
The position of the `flox` argument in many methods is also corrected to be the first argument.
This change could be considered outside of the scope of this PR, and would drop it / move it to a different PR if requested.
Fixes #1266.
N/A
> refactor: reimplement `InitHook` trait to avoid invalid states caused by `should_run`

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/completion.rs
- cli/flox/src/utils/init/catalog_client.rs
- cli/flox/src/utils/init/mod.rs
- Dispatching methods to clients manually tends to fragment the individual client implementations
between wrapping enum and client.
This refactor moves the client impls into a dedicated trait,
but exposes a unified interface through the `Client` enum.
- Move initialization logic up into `flox`
I think the constructors/types should be mostly pure when possible.
Selecting the right client based on an impure variable can be done by the caller instead.
Besides, the mock client likely needs additional initialization 
based on e.g. prepared responses,
that might look different in runtime/integration tests than it will in unit tests.
> [review] feat: add resolve shim and catalog feature flag

- cli/flox/doc/flox-push.md
- cli/flox/src/commands/push.rs
fixes a duplicated word in the help for `flox push`
N/A
> fix: fix typo in flox push

- cli/flox-rust-sdk/src/models/environment/mod.rs
Currently we would likely have a hash collision if someone had sqrt(2^(4 bits per hex character * 5 hex characters)) = 1024 environments.
Admittedly that's not super likely, but using 8 characters instead is still pretty legible, and it raises 1024 to 65536.
> fix: use longer hash for environment registry

- cli/tests/setup_suite.bash
- tests/setup_suite.bash
I was unable to run the integration tests on MacOS because of this error:
% just integ-tests
make: Entering directory '/Users/dcarley/projects/flox/flox/pkgdb'
mkdir -p tests;
Generating tests/.gitignore
make: Leaving directory '/Users/dcarley/projects/flox/flox/pkgdb'
~/projects/flox/flox/cli ~/projects/flox/flox
flox-cli-tests: Running test suite with:
FLOX_BIN:                 /Users/dcarley/projects/flox/flox/cli/target/debug/flox
PKGDB_BIN:                /Users/dcarley/projects/flox/flox/pkgdb/bin/pkgdb
NIX_BIN:                  /nix/store/wf28dxas0i3m27r4az6ppcs4z9syi2yv-nix-2.17.1/bin/nix
LD_FLOXLIB:               /Users/dcarley/projects/flox/flox/pkgdb/lib/ld-floxlib.so
PROJECT_TESTS_DIR:        /Users/dcarley/projects/flox/flox/cli/tests
bats …
> fix(tests): Create new SSH_AUTH_SOCK in std path

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox/Cargo.toml
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/features.rs
- cli/flox/src/utils/completion.rs
- cli/flox/src/utils/init/catalog_client.rs
- cli/flox/src/utils/init/mod.rs
- Add a wrapper client around the autogenerated client. This client can be used throughout flox-rust-sdk. It uses redefined types that are very similar to the autogenerated types, but there are some slight differences (currently just system and stability). These redefined types can be used throughout flox-rust-sdk, but they'll give us a single place to manage changes.
- Add a feature flag to use the catalog, and add an optional catalog_client to the Flox struct dependant on the feature flag
- Add an environment variable to control whether the actual catalog client is used or a mock client, which is left unimplemented!()
> feat: add resolve shim and catalog feature flag

- cli/flox/src/commands/pull.rs
- cli/tests/pull.bats
* Add missing spinners when pulling new environments that require the current system to be added to the manifest (https://github.com/flox/flox/issue/1301) Rebuilding of the modified environment was not covered by any spinner.
* Change messages when pulling results in a broken environment. Previous messages always implied that the environment was ready to be activated even when we knew it was broken.
* Refactor pulling existing environments to match the structure of pulling new environments. Mainly moving messaging inwards.
Co-Authored-By: dan.carley@gmail.com
> refactor: spinners and messaging during `flox pull`

- cli/flox-rust-sdk/src/data/canonical_path.rs
- cli/flox-rust-sdk/src/data/mod.rs
- cli/flox-rust-sdk/src/data/version.rs
- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment_ref.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/doc/flox-envs.md
- cli/flox/src/commands/envs.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/errors.rs
This PR adds an environment registry and `flox envs` command.
Flox commands has so far been mostly stateless, i.e. the fact that an environment exists at a given path is "forgotten" as soon as the command completes.
`flox envs` is supposed to list both active and _available/inactive_ environments (that are represented by .flox directories).
To avoid _scanning_ for `.flox` directories, we use the env registry introduced in #1312.
In addition, the `flox envs` supports filtering the output to only active environments as well as formatting its output as JSON.
> feat: add `flox envs` command

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/update.rs
- cli/flox/src/utils/didyoumean.rs
- cli/flox/src/utils/errors.rs
- cli/flox/src/utils/search.rs
* refactor: split `LockedManifest` into pkgdb and catalog variants
* implement `LockedManifestCatalog`
+ include catalog compatible manifest
+ include locked groups, with name, system and selected page 
(based on LockedGroups of the catalog service but with only one page)
* feat: impl `LockedManifestCatalog::list_packages`
> feat: add catalog compatible lockfile representation

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/search.rs
- cli/tests/catalog_responses/hello_search.json
- cli/tests/search.bats
Uses the mock client to supply search responses from data stored on disk when `FLOX_FEATURES_USE_CATALOG=true` and `_FLOX_USE_CATALOG_MOCK="<path to data>"`.
N/A
> feat: mock search using client

- cli/flox-rust-sdk/src/models/manifest.rs
Derives the `proptest::Arbitrary` trait for the new manifest types. It's likely that the generated data will need to be tuned to ensure it makes sense (invariants upheld, etc) and that test case generation isn't too slow. For performance concerns, see the tweaks made to how data is generated for the registry.
N/A
> feat: add proptest for manifest

- flake.nix
- pkgs/nix/default.nix
Tweaks the flake to allow compiling debug symbols for Nix on Linux by uncommenting a line.
N/A
> chore: debug symbols for nix

- cli/flox-rust-sdk/src/data/canonical_path.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/commands/envs.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/commands/push.rs
- cli/flox/src/commands/uninstall.rs
Avoids managing both directories _containing_ a `.flox` and full paths to `.flox` directories.
Managed- and PathEnvironments, tracked full paths, while `DotFlox` ironically tracked only the parent directory.
This refactor changes `DotFlox::open` to require an existing, canonicalized `.flox` directory
and adds `DotFlox::open_in` which will eagerly assert the existence of a nested `.flox` diorectory.
`EnvironmentPointer:open` now similarly requires a guarantee that the `.flox` path exists.
> refactor: store full paths to .flox directories

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/realise.cc
Refactoring a few calls in buildenv to limit scope within that functionality.  This is in preparation for the new lockfile schema.  I'd like to get this in as a small PR first.
> feat: support loading new lockfile schema

- .github/workflows/nix-managed-lints.yml
Adds an action that runs "pre-commit" lints on the current PR.
pre-pommit only runs tests if relevant files.
This came up in a [comment](https://github.com/flox/flox/pull/1371#discussion_r1580874973) on #1371.
> ci: run nix-managed lints on PRs

- cli/tests/upgrade.bats
- pkgdb/src/resolver/command.cc
To make it clearer, in cases where the package doesn't belong to an explicit package group, that `toplevel` has a special meaning as the default group:
- https://flox.dev/docs/reference/command-reference/manifest.toml/#package-descriptors
My first interpretation of the error was that `toplevel` was an example rather than a reserved word.
Reformatting was applied automatically by `clang-format` to satisfy the pre-commit hook.
N/A
> docs(pkgdb): Quote package group in upgrade error

- .github/workflows/nix-managed-lints.yml
- cli/Cargo.lock
- cli/catalog-api-v1/build.rs
- cli/catalog-api-v1/src/client.rs
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/utils/errors.rs
Implement locking of "v1" Manifests to "v1" lockfiles.
* construct arguments for `catalog::Client::resolve` from a manifest and optional "seed" lockfile
* (naively) implement deconstruction of {resolved groups ｘ pages ｘ packages} into a flat list of locked packages.
* Add logic in `CoreEnvironment` to dispatch locking to either pkgdb or the catalog based on the manifest found
* Handle error case where the catalog feature is disabled i.e. no client is set on `Flox`
> feat: locking using the catalog client

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/resolver/lockfile.hh
- pkgdb/include/flox/resolver/manifest-raw.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/src/resolver/manifest-raw.cc
- pkgdb/tests/lockfile.cc
- Added support for loading v1 lockfiles into the existing data structures without implementing a full schema de-serialization
- Made some assertions about the kind of inputs we'll allow in v1 lockfiles for the time being
- Added a basic unit test for correct parsing of v1 content into existing data structures
This is based on the assumption that `install_id`, `optional`, `priority`, and `system` are present in v1 lockfile schema as per our discussion.  Note that `optional` is not currently used it seems.
> feat: support loading and buildenv for v1 lockfiles

- .github/workflows/lint.yml
Fix two issues that prevented the pkgdb lint workflow being run manually.
The individual commits contain more information about the issues and fixes.
N/A
> Fix manual runs of pkgdb lint workflow

- cli/flox-rust-sdk/src/models/manifest.rs
- pkgdb/include/flox/resolver/manifest-raw.hh
- pkgdb/include/flox/resolver/manifest.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/tests/lockfile.cc
The CLI and pkgdb have a few minor differences in how they treat lockfiles. Fix by:
- Using `allow` consistently (not `allows`)
- Dropping `profile.fish` since it's not present in pkgdb yet
- Using kebab-case
- Using `options.systems` to determine if a manifest.lock supports a system rather than packages. Current catalog locking code doesn't set empty packages for each system.
- Loading options when loading a LockfileRaw from v1 content
> fix: a few lockfile discrepancies

- cli/flox/src/commands/activate.rs
- pkgs/flox-cli/default.nix
PR1299 changed the top-level "activate" path from a directory containing scripts to a script to be invoked, and with that we changed the "zdotdir" from an entirely separate package to instead reside within the "activate.d" directory found in the environment itself.
This was fine for environments rendered with the new activation logic, but obviously broke for old environment renderings which lacked this directory.
This patch updates the build and code to render and use a standalone zdotdir package just as it did previously.
N/A
> fix: repair setting of ZDOTDIR following 1299

- cli/catalog-api-v1/openapi.json
- cli/catalog-api-v1/src/client.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/show.rs
- cli/flox/src/utils/errors.rs
This has a few non-trivial changes:
- CatalogPageInput::packages becomes an Option, which requires throwing an error during resolution if the first page doesn't have packages
- install_id is added in some places where name was incorrectly used, but name is still used in some places
Most changes were trivial:
- Lots of fields were made optional
- `status_code` was dropped from `ErrorResponse`
> chore: bump schema

- doc/release-notes/rl-1.0.4.md
- doc/release-notes/rl-1.0.5.md
Remove two fixes that didn't make it into the 1.0.4 release. Start a new release notes file for the next 1.0.5 (or could a minor instead of patch) release so that we don't forget to include them.
Meta, this is the release notes 😁
> docs: Fix release notes for 1.0.4 and subsequent

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
options.systems is optional for pkgdb, and if it's null, pkgdb defaults to the current system.
The CLI currently passes an empty list, which leads to pkgdb throwing SystemNotSupportedByLockfile.
Instead, make systems an Option in the CLI, and default to the current system for resolution if it is None.
Drop the use of lifetimes in collect_package_groups since that would require figuring out lifetimes for a second source of system strings which seems like too much effort when we could just copy a few strings instead.
> fix(cli): make options.systems optional

- cli/flox/src/commands/activate.rs
Interactive and command activations should respect SHELL over the parent process exe
This commit reverts changes to shell detection from e2202a391bc37451b2bbe408a87b3a6b11da2e56
> fix: revert changes to shell detection

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/doc/manifest.toml.md
There are some minor tweaks to the wording for the `hook` and `profile` sections
I also accidentally committed an error typo but am going to let it merge
> fix: sync activate man page with docs

- pkgs/flox-cli/default.nix
Apparently using bundling rust-analyzer from nixpkgs ran into version incompatibilities with the rust toolchain provided by fenix: #1405.
This PR replaces the nixpkgs package with the one from the fenix toolchain.
> build: use fenix provided rust-analyzer

- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/show.rs
Unit tests no longer include a client by default. Our logic for when to use the client often depends on the presence of the client on the `Flox` struct, so including the client by default could have unintended consequence in tests.
N/A
> test: don't include client by default

- cli/tests/catalog_responses/hello_resolution.json
- pkgdb/include/flox/fetchers/wrapped-nixpkgs-input.hh
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/fetchers/wrapped-nixpkgs-input.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/tests/.gitignore
- pkgdb/tests/flox-nixpkgs.bats
- pkgdb/tests/flox-nixpkgs.cc
- pkgdb/tests/lockfile.cc
We rely on a custom fetcher to allow us to build unfree packages in github:NixOS/nixpkgs. Catalog entries contain URLs of the form https://github.com/flox/nixpkgs, but they should be handled by our fetcher. To support this:
- in v1 lockfiles only, translate https://github.com/flox/nixpkgs into github:flox/nixpkgs
- permit flox as an owner in our fetcher
> feat: allow github:flox/nixpkgs urls in pkgdb

- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
While working on the catalog init hook I discovered that we'll need a common-denominator type for handling information retrieved by either the catalog client or pkgdb. This introduces a new type to handle that, and it's presented as a separate PR to keep the catalog-init PR smaller.
N/A
> refactor: don't default to search result type in node hook

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
* fix: unlock resolve descriptor if manifest was invalidated
Skip resolving with `derivation` if any significant attribute of the manifest descriptor changed (i.e. requested version, pkg-path, group, etc.)
* fix: skip resolution of fully locked groups
Add packages from fully locked groups to the lockfiel without re-resolution.
> fix: skip resolution of fully locked groups, invalidate locks

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/utils/dialog.rs
- tests/catalog.bats
-  Provide tokio to functions called by `spin_with_delay`
The catalog client uses `reqwest` which uses `tokio::time::sleep`. When
the catalog is used in combination with our `spin_with_delay` function,
this causes a panic:
```
there is no reactor running, must be called from the context of a Tokio 1.x runtime
```
Enter the tokio runtime context in the thread spawned by
`spin_with_delay` to avoid the panic.
- Add functional test for catalog install. Note that this is still skipped since we're waiting for changes serverside
> feat: wrap up `install` with catalog

- cli/tests/activate.bats
- pkgdb/src/buildenv/realise.cc
Check and set a guard prior to sourcing .bashrc to prevent in-place activations performed from within the .bashrc file from triggering an infinite loop.
N/A
> fix: avoid infinitely sourcing bashrc

- cli/flox/src/commands/activate.rs
- cli/flox/src/utils/message.rs
- pkgdb/src/buildenv/realise.cc
Running `flox activate` twice was printing:
```
✅ You are now using the environment 'name'.
To stop using this environment, type 'exit'
ERROR: Environment 'name' is already active.
```
Remove the success message from Rust, and only print it in Bash codepaths when the environment is not already active (and an interactive activation is being run).
Also add a ❌ to the error message.
> fix: don't print success before error

- pkgs/flox-cli-tests/default.nix
`flox` was being called with PKGDB_PATH=pkgdb, but since #1299
`pkgdb` is called with an cleared `PATH`.
Unless `flox-cli-tests` are being called with `--pkgdb <abs path to pkgdb>`,
executing pkgdb will fail with a No Such File exception.
> build(flox-cli-tests): export absolute default path to pkgdb

- pkgs/flox-tests/default.nix
This is 54d3ae9e4b1b988174f8710fbea5959628e5c978 but for flox-tests instead of just flox-cli-tests.
`flox-tests` was calling `flox` with `PKGDB_PATH=pkgdb` and expecting `flox` to find `pkgdb` in `PATH`, but since #1299 `pkgdb` is called with a cleared `PATH`.
Unless `flox-tests` are called with `--pkgdb <abs path to pkgdb>`, executing pkgdb will fail with a No Such File exception.
> build(flox-tests): export absolute default path to pkgdb

- doc/release-notes/rl-1.0.5.md
The notes from 1.0.5 say "UNRELEASED" but I believe the release has been completed.
> docs: remove unreleased tag from 1.0.5 release notes

- .github/workflows/ci.yml
* `TARGET` property is now called `FLOX_SRC`
* `git+ssh://` is now needed for `FLOX_SRC` we can use `github:` type of flake input.
> ci: rename TARGET -> FLOX_SRC

- cli/catalog-api-v1/README.md
- shells/default/default.nix
So that we can easily debug interactions with the Catalog API.
This is the least intrusive solution which gives us pretty printed body
content and allows you to see multiple request/response cycles. The
following options were discounted because..
`progenitor` hooks aren't designed for inspecting response bodies:
- https://github.com/flox/flox/compare/main...dcarley/1434-catalog-debug-hooks
Verbose connection logging requires additional copy/paste and string
formatting to get a pretty printed body:
- https://github.com/flox/flox/compare/main...dcarley/1434-catalog-trace-http
TLS key logging to inspect in Wireshark requires messing with the TLS
implementation, including which root CAs are used, and Wireshark doesn't
make the body contents any easier to read anyway:
- …
> chore(catalog): Add mitmproxy instructions

- cli/tests/containerize.bats
This test failed due to an expected number of `stderr` lines containing errors and warnings
- `cannot find UID/GID for user flox-test`
- This is related to how rootless mode works in Podman and it not being able to create additional users or allocate user ids in rootless mode: https://github.com/containers/podman/issues/15611
- `Using rootless single mapping into the namespace`
- Same as above
- `acquiring lock 7 for container <hash>: file exists`
- The podman cache already has this container, which makes sense if the other `podman` test creates the same container 
Ultimately this just skips counting `stderr` lines and instead checks that the last two lines are the ones we expect.
N/A
> test: fix flaky podman test

- cli/catalog-api-v1/README.md
Small fix to 259cec4 because I found that `install` will fail if the package wasn't previously cached in the local store:
❌ ERROR: Failed to build environment.
caught a nix exception: running pkgdb subcommand: error:
… while fetching the input 'flox-nixpkgs:v0/flox/6c0b7a92c30122196a761b440ac0d46d3d9954f1'
… while updating the lock file of flake 'path:/private/tmp/nix-2127-0?lastModified=1716376910&narHash=sha256-71E2zF7xAZivPCPeMiuZzTWk2DGN0Mi9N9aP53zoBro%3D'
… while updating the flake input 'nixpkgs'
… while fetching the input 'github:flox/nixpkgs/6c0b7a92c30122196a761b440ac0d46d3d9954f1'
error: unable to download 'https://github.com/flox/nixpkgs/archive/6c0b7a92c30122196a761b440ac0d46d3d9954f1.tar.gz': SSL peer certificate or SSH remote key was not OK (60)
This didn't come up in my …
> fix(catalog): SSL_CERT_FILE for mitmproxy

- pkgdb/src/buildenv/assets/activate
- pkgdb/src/buildenv/assets/activate.d/bash
- pkgdb/src/buildenv/assets/activate.d/set-prompt.bash
- pkgdb/src/buildenv/assets/etc/profile.d/0100_common-paths.sh
- pkgdb/src/buildenv/assets/etc/profile.d/0500_python.sh
- pkgs/flox-pkgdb/default.nix
PR#1460 introduces the idea of invoking shellcheck for activation scripts but disables all the checks to make it easier to validate the script contents through the refactor. This PR builds upon that effort to fix all the syntax issues and enable the checks.
N/A
> feat: enable shellcheck verification of activation scripts

- cli/tests/activate.bats
The new activate:zdotdir tests added in PR#1467 made the mistake of exercising the ability to find an installed package in the PATH as confirmation that the `zsh` script had run, when of course that doesn't make sense because the PATH configuration happens in the bash activate script that precedes it.
This patch updates the test to reuse the existing `only-once.toml` manifest to confirm both that the `zsh` activation script is invoked to source the `profile.zsh` section of the manifest and that it runs only once. Each test also runs between 100-200ms faster with this change.
N/A
> fix: properly verify execution of zsh activation script

- CONTRIBUTING.md
So that it's clear how to use it and prevent people from trying to render the test fixtures themselves. This will be used by the "set catalog feature flag for integration tests" tickets.
N/A
> chore(contributing): Document catalog dump env var

- cli/flox/src/commands/auth.rs
This skips the step where the user has to copy their activation code and
instead takes them directly to the page where they confirm the code
matches. This is in line with other tools like the Auth0 CLI itself, AWS
CLI, etc.
`flox auth login` no longer requires copying a device code.
> feat: Don't require user to enter their activation code

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/doc-catalog/flox-upgrade.md
- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-edit.md
- cli/flox/doc/flox-install.md
- cli/flox/doc/flox-pull.md
- cli/flox/doc/flox-upgrade.md
- cli/flox/doc/manifest.toml.md
- pkgs/flox-manpages/default.nix
The manifest.toml file is currently being installed as section 1 when it should be installed for section 5 (File formats and conventions).
See `man(1)` for a description of the section numbers and their purpose.
* moved the man page for `manifest.toml` from section 1 to section 5
> fix: move manifest.toml man page to section 5

- cli/flox/doc-catalog/manifest.toml.md
- cli/flox/doc/manifest.toml.md
Update the doc-catalog copy of the manifest man page with catalog
changes:
- `name`, `optional`, and `abs-path` will be dropped
- `semver` was documented but not actually supported.
- `pkg-path` will be required.
- `prefer-pre-releases` will be renamed to `allow-pre-releases`
Also add a note about loosening constraints to solve install failures.
> docs: catalog changes for manifest man page

- cli/tests/activate.bats
It's unclear why this test succeeds most of the time in CI, but as indicated in the comment there's always been a strange interaction with bats and the use of double quotes for this double-flox activation. This version is likely to work better, and will similarly test that the PATH is patched correctly on a second activation.
N/A
> fix: rework test that has proven flaky in CI

- pkgdb/src/buildenv/assets/activate
By default tcsh silently refuses to source a .tcshrc file that the effective user does not own, but this behaviour can be overridden with the `-m` flag as described in tcsh(1):
-m  The shell loads ˜/.tcshrc even if it does not belong to the effective user.
This patch adds this `-m` flag to the two tcsh invocations for which we are setting `$HOME`, and removes the `-v` flag that was accidentally left behind with a previous round of debugging.
N/A
> fix: invoke `tcsh -m` to source flox-provided $HOME/.tcshrc

- cli/tests/activate.bats
- cli/tests/activate/interactive-hello.exp
- cli/tests/environment-managed.bats
- cli/tests/environment-remote.bats
This supersedes https://github.com/flox/flox/pull/1540
**refactor(activate): Rename interactive tests**
Make it clearer that these tests depend on the commands happening in an
interactive activation where we have a TTY. This means that they have to
use `expect` rather than `flox activate -- command`.
**fix(activate): Verbose output from expect failures**
Set `exp_internal` so that we get more feedback from flakey tests when
they fail. Like this one, which almost certainly hit the timeout, but we
can't tell where/why:
- https://github.com/flox/flox/actions/runs/9377878053/job/25820156213#step:6:84
This can also be enabled with `expect -d` but setting it within the
script makes it consistent for all tests that use it. Man page describes
the option as:
exp_internal [-f file] value
causes …
> fix(activate): Verbose output from expect failures

- cli/tests/environment-managed.bats
**test(environment-managed): Copy cases for catalog**
Duplicate the tests that would touch the catalog to run in parallel with
pkgdb test cases. They are modified to pass in a subsequent commit to
make it easier to compare against the originals.
**test(environment-managed): Add catalog mock resps**
For all places where we install a package and expect to resolve from the
catalog server. These are specified inline so that all other commands
default to using the empty response and will blow up if we don't provide
the correct mocks.
**test(environment-managed): Fix manifest version**
Add a `version` when constructing a catalog compatible manifest to fix
this error:
❌ ERROR: unrecognized manifest field: 'version'.
**test(environment-managed): Fix manifest pkg-path**
Add a `pkg-path` when …
> test(environment-managed): Copy cases for catalog

- pkgs/flox-cli/default.nix
Post-install remove reference manually to rust-toolchain. Still not sure why this happens.
N/A
Temporarily Fixes: https://github.com/flox/flox/issues/1526
> fix: temporary fix to remove toolchain reference

- cli/flox/src/main.rs
Avoid panics of `println!` when stdout fd is closed
Attempt to fix #1193
> fix: reset SIGPIPE handler to default

- cli/tests/catalog_responses/resolve/gzip.json
- cli/tests/catalog_responses/resolve/responses_to_generate.json
- cli/tests/pull.bats
- cli/tests/push.bats
Copied all tests although less may suffice as well.
Added `remove_extra_systems` helper to simulate a manifest file that only supports a single system.
> test(pull): test: copy over `pull` tests for catalog

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
In the case where the user has uninstalled and reinstalled Flox, or if
the environment is somehow garbage collected, the symlink to the
environment in .flox/env/run will be broken. Previously, we got an error
in that case. We now treat it as invalidated the same as if the
environment needed a rebuild, and just try to build the environment
again.
> fix: Handle broken symlinks in run/ directory

- cli/flox-rust-sdk/src/models/lockfile.rs
Addresses the remaining test cases from #1529
* When packages are locked for multiple systems,
locking the same package for fewer packages should drop the extra systems
* Adding another system to a package should invalidate the entire group
such that new systems are resolved with the derivation constraints
of already installed systems
> test: drop locked packages for dropped systems

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/utils/errors.rs
An error should be raised if a manifest descriptor tries to lock a system that is not specified in `options.systems` i.e. iff `install.*.systems ⊈ (options.systems ? {default systems..})`.
Fixes a logic regression wrt to pkgdb based locking which required this invariant but implemented it in pkgbd causing it to be overlooked while implementing the rust equivalent.
> fix: require descriptor system enabled in options or default

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/utils/errors.rs
- cli/tests/install.bats
- test_data/config.toml
- test_data/generated/resolve/hello-unfree.json
Unfree, broken, and licenses are already copied from the manifest into
catalog resolution requests. But pkgdb warnings and errors still needed
to be ported to catalog code paths.
- When `options.allow` are changed with a `flox edit`, an error should
be thrown if already installed packages are no longer allowed
- When unfree or broken packages are installed, a warning should be
printed to the user.
Note that with pkgdb, if a package failed to install because it was not
allowed, a helpful error was printed suggesting a modification to
`options.allow`. This is no longer possible since resolution failures do
not currently include enough information to determine if the failure was
due to an `options.allow` setting. The corresponding copied but skipped
integration tests were dropped instead of …
> feat(catalog): support unfree, broken, licenses

- .github/workflows/ci.yml
So that we checkout the same merge commit of a PR that we use to run the `flox-cli-tests` with, which is preferable because it will tell us about failures before we get to the merge queue:
- https://github.com/flox/flox/blob/3338caad08b554fb3757f90ebb1589b753fe12be/.github/workflows/ci.yml#L369
This would have helped me diagnose why the tests failed on my feature branch when mock changes were merged to `main`:
- https://github.com/flox/flox/actions/runs/9479547968/job/26118504738?pr=1560#step:6:367
Despite the checkout using the HEAD of the feature branch:
- https://github.com/flox/flox/actions/runs/9479547968/job/26118504738?pr=1560#step:2:215
This is a partial revert of a previous change but I can't see why those changes would be dependent on using the HEAD of the feature branch or …
> chore(ci): Remove checkout ref and fetch-depth

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/list.rs
- cli/tests/list.bats
* Enable the catalog feature globally for in `list.bats` and disables it for all existing tests.
* Port "'flox list' lists packages of environment in the current dir;" to use the catalog
* Port "'flox list --config' shows manifest content" to use the catalog
* Implement remaining formatting tests as unit tests next to their implementation in `cli/flox`
> test(list): port `list` integration tests to catalog

- Justfile
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/utils/errors.rs
- cli/mk_data/README.md
- cli/tests/upgrade.bats
- test_data/config.toml
- test_data/generated/resolve/old_hello.json
- tests/catalog.bats
This unskips the catalog `flox upgrade` tests, which uncovered some cases that were not covered by existing catalog functionality. Specifically, catalog upgrade now matches `pkgdb` behavior when attempting to upgrade a package that belongs to a group with other packages.
N/A
> feat: handle upgrade errors with catalog

- cli/flox/src/commands/update.rs
Prints an error when a user attempts to use `flox update` with the catalog feature flag enabled.
- `flox update` is now deprecated
> feat: deprecate update with catalog

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/doc-catalog/flox-search.md
- cli/flox/src/commands/search.rs
- cli/tests/search.bats
**feat(search): Strip version specifiers for catalog**
The catalog server won't support searching by version for now. You can
use `flox show` to find the versions for a given package:
- flox/catalog-server#60
The server has been stripping the version specifier server-side.
Implementing this client-side will allow us to remove that, which makes
it clearer, and easier to support versions as a separate parameter in
the future:
- flox/catalog-server#98
The note about version specifiers has been removed from the `--help`
message because we're not able to switch it based on the catalog feature
flag but the existing behaviour will continue to work for pkgdb.
It feels right to implement the logic in the `catalog`, but not as a
method on the client because it doesn't need any state, and then …
> feat(search): Strip version specifiers for catalog

- cli/flox-rust-sdk/src/models/manifest.rs
Mark `TypedManifestCatalog` with `#[serde(deny_unknown_fields)]`.
Previously the handwritten json/toml parsing in pkgdb implemented this
but the behavior regressed when the manifest type was implemented in rust.
> fix(manifest): reject unknown fields in manifest.toml

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
We removed support for wildcard `optional` in favor of more precise handles e.g. `system` and global `options.allow_*` settings.
> chore:  remove `ManifestPackageDescriptor#optional`

- pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
- pkgs/flox-pkgdb/default.nix
add etc-profile for CUDA
FLOX_ENV_ENABLE_CUDA=1 is now a feature flag to set FLOX_ENV_LIB_DIRS to the each directory in `ldconfig -p`.
TODO
- use host-provided ldconfig? or bring one in from glibc package?
> feat: feature flag to point FLOX_ENV_LIB_DIRS as CUDA libraries

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
Manifest operations should be implemented for `TypedManifest` that encompasses both pkgdb and catalog manifests
> chore: remove `Manifest` type alias to PkgdbManifest

- cli/tests/activate.bats
- pkgdb/src/buildenv/assets/activate
- pkgdb/src/buildenv/assets/activate.d/bash
- pkgdb/src/buildenv/assets/activate.d/fish
- pkgdb/src/buildenv/assets/activate.d/tcsh
- pkgdb/src/buildenv/assets/activate.d/tcsh_home/.tcshrc
- pkgdb/src/buildenv/assets/activate.d/zdotdir/.zlogin
- pkgdb/src/buildenv/assets/activate.d/zdotdir/.zprofile
- pkgdb/src/buildenv/assets/activate.d/zdotdir/.zshenv
- pkgdb/src/buildenv/assets/activate.d/zdotdir/.zshrc
- pkgdb/src/buildenv/assets/activate.d/zsh
Running `eval "$(flox activate)"` from within a dotfile has the effect of sourcing the shell-specific flox init script which finishes by cleaning the `_flox_activate_tracelevel` variable from the environment. This is fine in an interactive setting, but when this is happening within an "inner" in-place activation launched from an "outer" interactive one, then this causes problems for the latter.
The fix is to expressly guard against the unsetting of this variable as can happen when sourcing any "dotfile" that may contain an invocation of `eval "$(flox activate)"` or equivalent.
The bug existed for each of the bash, fish, tcsh and zsh shells, and this patch includes fixes and tests for each of them.
* fixed shell errors reported when performing nested activations
> fix: ensure _flox_activate_tracelevel not unset by "inner" activations

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
`flox push` will fetch the latest changes from floxhub prior to pushing to detect diverged branches.
If the environment was removed upstream, the fetch failed. As a result, environments that were deleted before can not be pushed again. With this PR flox will ignore when git is unable to fetch the upstream branch due to it missing and will print a warning instead.
Since this routine is a an internal library detail, its in turn an internal non-user focused warning. Alternatively the warning could be silenced further or implemented as a "precheck" that is called from the frontend crate.
> fix(push): handle deleted environments on floxhub

- cli/Cargo.lock
- cli/flox/Cargo.toml
- cli/flox/src/commands/edit.rs
- cli/flox/src/utils/errors.rs
Shortens user facing message for manifest parsing errors and detects syntax issues in `flox edit`.
> chore: simplify user facing error for manifest parsing issues

- cli/flox/src/commands/search.rs
- cli/flox/src/utils/didyoumean.rs
- cli/tests/search.bats
- test_data/config.toml
- test_data/generated/search/java_suggestions.json
Previously the suggestions were coming from `pkgdb` even when the catalog was enabled. They now use the same path as the original search. New integration tests have been added for both code paths.
We agreed in refinement that it was sufficient to plumb the catalog logic through to `DidYouMean` and refactor later when we removed `pkgdb`. We could group the catalog and pkgdb related arguments in separate types but it doesn't seem worth it if we've removing this code soon.
I considered moving the spinners up one or two levels but I think it makes sense to keep them close to the slow function based on the problems I ran into before with competing spinners at different levels of the codebase.
N/A because it's fixing a bug in something that's not officially released yet.
> fix(search): Search suggestions for catalog

- CONTRIBUTING.md
Add Rust Style Guidelines section and add note about deriving `Clone` and `Debug` for structs. `Clone` and `Debug` are used so widely it's easier to add them up front and avoid times where you add it several layers deep only to find something can't derive `Clone`."
> docs: add Rust style to CONTRIBUTING.md

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
Filter lib dirs in .flox in gitignore. Useful when using flox/lib to have host-provided libs, eg CUDA. 
N/A
> fix: ignore lib directories in .flox

- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/catalog.rs
So that we get version information from the catalog service on release:
- https://github.com/flox/catalog-server/issues/113
To set the user-agent we need to construct our own client. The default timeouts have been cribbed from `catalog::new()`.
Technically it would be better to assert that the header value matches `^flox-cli/\d\.\d` but we can only do that with a custom `matches()` and then we don't get useful output when the test fails, like this:
---- providers::catalog::tests::user_agent_set_on_all_requests stdout ----
thread 'providers::catalog::tests::user_agent_set_on_all_requests' panicked at /Users/dcarley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/httpmock-0.7.0/src/api/mock.rs:543:35:
assertion `left == right` failed: 0 of 1 expected requests matched the mock …
> chore(catalog): Set request user-agent

- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
#1508 marked the command as hidden but its usage entry was added manually, hence removed here.
> chore: hide update command from `--help`

- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-remote.bats
This closes https://github.com/flox/product/issues/656.
This changes the output to `Environment not found in FloxHub` when running `activate -r` on an environment fails in the following cases:
- activating a remote environment that does not exist, by a user that does not exist: foo/bar
- activating a remote environment that does not exist, of another user, the user is valid though
- activating your own environment, that has existed before, but then been deleted from FloxHub and does not exist anymore.
> fix(activate): Improve user output when activating a remote env fails.

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/errors.rs
Previously, we showed a generic failure message when the upstream 
environment was deleted. We now handle that case and show a message 
indicating what's happened and instructing the user how to restore the 
environment.
This also changes the way we handle EnvironmentSelectErrors. We now 
include a check for EnvironmentSelectError in main() alongside the other error
handler, and handle the EnvironmentSelectError::Environment variant the same as
ordinary EnvironmentErrors.
> fix: show a helpful error when a managed environment has been deleted

- cli/flox/src/commands/show.rs
- cli/tests/show.bats
Remove the warning that was added in d27e0d00 so that it will now produce an error:
% flox show --all
❌ ERROR: expected `<pkg-path>`, got `--all`. Pass `--help` for usage information
This has been in two releases (1.0.6 and 1.0.7) and the timing is good to remove it for 1.1.0 as a breaking change.
Removed the deprecated `--all` flag from `flox show` now that it's the default.
> chore(show): Remove deprecated --all argument

- pkgdb/.gitignore
To match the one directory that generate, so that it doesn't ignore new files in:
% git check-ignore -v pkgdb/src/buildenv/assets/activate.d/newfile pkgdb/src/buildenv/assets/etc/profile.d/newfile
pkgdb/.gitignore:2:*.d	pkgdb/src/buildenv/assets/activate.d/newfile
pkgdb/.gitignore:2:*.d	pkgdb/src/buildenv/assets/etc/profile.d/newfile
I noticed this while looking at the CUDA script and my editor failed to find it because many tools like `fd` and `rg` automatically exclude ignored files even if they are tracked.
N/A
> chore(pkgdb): Tighten gitignore for *.d

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/errors.rs
When performing migration of manifest version 0 to version 1, rename
hook.script to hook.on-activate if hook.on-activate doesn't already
exist.
Also add formatter for MigrationError.
MigrationError wraps some errors that should be pretty printed, but the
wrapping causes the formatting function to not be printed. Fix this by
adding a formatting function that calls the formatters for the contained
errors.
Errors were being printed as:
```
❌ ERROR: Upgrade failed.: could not automatically migrate manifest to version 1: unknown field `prefer-pre-releases`, expected `allow-pre-releases`
in `options.semver`
```
But they should be printed as:
```
❌ ERROR: Could not automatically migrate manifest to version 1:
unknown field `prefer-pre-releases`, expected `allow-pre-releases`
Use 'flox edit' to …
```
> feat: migrate hook.script to hook.on-activate

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/tests/upgrade.bats
It's possible for the catalog server to resolve the same package version and derivation from a different page and revision of nixpkgs.
In these cases the packages haven't actually changed and we would tell the user that they haven't been upgraded, however we were still updating the lockfile with the new `page`, `rev`, `rev_count`, and `locked_url`.
Prevent this from happening by returning the existing lockfile. We currently still trigger a build on it though, in part because an existing test expects a noop upgrade to generate a lockfile and the outer function doesn't know whether the lockfile has changed.
A side-effect of this is that the test can't compare the raw lockfile contents because it appears to originally be written out in pretty-print format and then written in compact format, …
> fix(upgrade): Keep lockfile if no pkgs change

- Justfile
- cli/flox/src/utils/openers.rs
- shells/default/default.nix
Replaces the default test runner with `cargo-nextest`, which runs tests in parallel and uses a different scheduling algorithm.
Locally the unit tests went from ~12s to ~4s.
N/A
> test: use cargo-nextest for unit tests

- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/install.rs
- cli/tests/environment-remote.bats
Improved error messages for remote environments, enhancing readability. This update affects the following commands:
* `flox edit --remote` for environments that were previously deleted or never existed
* `flox install --remote` for environments that were previously deleted or never existed
Users will now receive the error message "Environment not found in FloxHub" for all the cases listed above. 
This closes https://github.com/flox/product/issues/727
> feat(edit, install): Impove error messages for remote commands.

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/utils/errors.rs
Adds plumbing commands to realize future behaviour changes of managed environments.
In particular this PR adds methods 
* to create a local copy of the environment stored in the current generation
* reset the local copy 
* and create a new generation from it.
While creation attempts to be as indestructive as possible, only writing files if the `.flox/env` directory does not yet exists, resetting the local copy currently discards any existing files in `.flox/env`.
> feat: managed environment local checkout plumbing

- .github/workflows/ci.yml
- cli/tests/floxhub-cross-systems.bats
This is our slowest job in CI which has been using a MacOS 12 x86 runner. There are newer ARM64 runners available:
- https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
Changing this reduced the job time from 22m52s to 14m53s:
- https://github.com/flox/flox/actions/runs/9647806668/job/26607487916
- https://github.com/flox/flox/actions/runs/9648121868/job/26608534782
The difference in cost appears to be $0.14/min to $0.16/min which should also make it cheaper:
- https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates-for-x64-powered-larger-runners
- https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates-for-arm64-powered-lar …
> chore(ci): Use ARM runner for MacOS

- pkgdb/Makefile
Ensure that any changes to the `buildenv/assets` directory trigger a rebuild of `realise.o`. This prevents some very confusing behaviour whereby the integration tests don't pick up changes to  the `profile.d` scripts.
The original problem is too laborious/tedious to reproduce but here's a demonstration that the rebuilding works correctly:
(2) ~/projects/flox/flox on dcarley/pkgdb-rebuild-assets [$+]
% just build-pkgdb
make: Entering directory '/Users/dcarley/projects/flox/flox/pkgdb'
mkdir -p tests;
Generating tests/.gitignore
make: Leaving directory '/Users/dcarley/projects/flox/flox/pkgdb'
(2) ~/projects/flox/flox on dcarley/pkgdb-rebuild-assets [$+]
% echo >> pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
(2) ~/projects/flox/flox on dcarley/pkgdb-rebuild-assets [$!+]
% just …
> chore(pkgdb): realise.o depend on buildenv/assets

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/doc/manifest.toml.md
- cli/flox/src/commands/activate.rs
- cli/tests/cuda.bats
- cli/tests/cuda/cuda-disabled.sh
- cli/tests/cuda/cuda-enabled.sh
- pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
- pkgdb/src/resolver/manifest-raw.cc
**feat: add options.cuda-detection to manifest**
Instead of the secret feature flag FLOX_FEATURES_ENV_ENABLE_CUDA, add
`options.cuda-detection` to the manifest to control the CUDA activation
script. Default to enabling CUDA if the flag is not set, which is change
in behavior since we currently default to false.
Add a `manifest()` function to the `Environment` trait to simplify
getting a typed manifest for an environment.
**fix(cuda): Stub cuda-detection in pkgdb**
To prevent this error:
-- command failed --
status : 1
output (3 lines):
❌ ERROR: Failed to build environment.
invalid manifest file: unrecognized manifest field 'options.cuda-detection'.
--
I've made it a noop since we're not actually doing anything with the
manifest option within `pkgdb`. The value is checked and an …
> feat: add `options.cuda-detection` to manifest

- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/tests/services.bats
- flake.lock
- flake.nix
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox/default.nix
Adds process-compose to `flake.nix` and `flox` so that we can call it for service commands.
N/A
> feat: bundle process-compose for services

- cli/flox/src/commands/init/mod.rs
- cli/tests/init.bats
After a flox init, include a mention of using flox edit to set env vars and shell hooks. Users have been surprised and excited when they discover this functionality exists, so give a hint about it so they find it.
> feat: mention env vars and hooks after init

- CONTRIBUTING.md
- shells/default/default.nix
So that we can see rendered changes when not using an installer.
Before:
(2) ~/projects/flox/flox on HEAD (353d4213) [$]
% man -w manifest.toml
/run/current-system/sw/share/man/man5/manifest.toml.5
(2) ~/projects/flox/flox on HEAD (353d4213) [$]
% man manifest.toml | tail -n16
installed and appear in search results.  The default is false.
allow.licenses
A whitelist of software licenses to allow in search results in
installs.  Valid entries are SPDX Identifiers
<https://spdx.org/licenses>.
semver.allow-pre-releases
Whether to allow pre-release software for package installations.
The default is false.  Setting this value to true would allow a
package version 4.2.0-pre rather than 4.1.9.
SEE ALSO
flox-init(1), flox-install(1), flox-edit(1)
MANIFEST.TOML(5)
After:
(2) ~/projects/flox/flox on …
> chore(manpages): Make available in devShell

- cli/flox/src/utils/openers.rs
Fix the TODO by only populating the process `exe` data that we need. The unit test would fail if the function is changed in the future to access other data that is no longer populated.
This work was prioritised because we had previously observed this test to be slow:
> just unit-tests test_get_parent_process_exe
...
running 1 test
test utils::openers::tests::test_get_parent_process_exe ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 93 filtered out; finished in 1.70s
However I haven't been able to reproduce it (on an M3 Mac) and this change doesn't appear to have made any appreciable difference to the runtime:
Before:
(2) ~/projects/flox/flox/cli on HEAD (82e818fa) [$]
% nix run 'nixpkgs#hyperfine' -- --runs=100 --warmup=2 'cargo test tests::test_get_parent_process_exe' …
> chore(utils): Narrow down sysinfo data

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
Add `skip_serializing_none` to types for the manifest and lock.
Currently, if a newer version of flox has an optional field, if an environment is locked, the field is put as null in the lockfile. If an older version of flox without that field attempts to edit the environment, it will throw an error, e.g:
```
❌ ERROR: unrecognized manifest field 'options.cuda-detection'
```
Since serializing null doesn't gain us anything, we might as well skip it. It will also make lockfiles slightly smaller.
> fix: skip_serializing_none for manifest and lock

- flake.nix
- pkgdb/Makefile
- pkgdb/src/buildenv/realise.cc
- pkgs/flox-activate/default.nix
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox-pkgdb/default.nix
The activation package was previously assembled at build time from a set of static files (etc-profiles) and other scripts created by pkgdb, then it evolved into a set of static files with package path substitutions performed at Nix build time. This introduced the wrinkle that changes to the flox-activate package could not be picked up without having to exit and re-enter the `nix develop` shell.
This change splits out the flox-activate package as distinct from flox-pkgdb so that the package can be quickly re-rendered with an invocation of `nix build`. It then updates the Makefile, flox-pkgdb and flox-cli builds to use the files from this package.
N/A
> feat: build flox-activate package distinct from flox-pkgdb

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/doc/flox-edit.md
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/uninstall.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-managed.bats
Behavior changing integration of new local env checkout for managed environments
> feat: managed environment local checkout

- cli/flox/src/commands/activate.rs
- pkgs/flox-cli/default.nix
Amend the shell detection for subshells to now determine the shell in the following order:
1. `FLOX_SHELL` environment variable
2. `SHELL` environment variable
3. Parent process shell
4. Default to `bash` bundled with flox as `bashInteractive`
> feat(activate): subshells respect parent shell and fall back to bash

- .github/workflows/ci.yml
- cli/tests/catalog-live.bats
**test(catalog-live): Move env and always run**
Move the environment variable into the tests, rather than sourcing it
from GitHub, so that we always run the tests. This makes the behaviour
of the integration tests consistent across:
- local dev
- `cli-dev` job in CI
- `nix-build-bats-tests` in CI
Previously the latter was the only job to run these which makes it hard
to reason and work on failures.
You could still focus or skip these temporarily if you're working
somewhere without an internet connection.
**test(catalog-live): Relax package description**
The tests have failed in CI because the package description in the
latest catalog scrape has changed from:
A program that produces a familiar, friendly greeting
To:
Program that produces a familiar, friendly greeting
Relax the assertion so …
> test(catalog-live): Fix and always run

- pkgs/flox-cli/default.nix
Removed runtime libraries no longer required by our rust build.
* `zlib, libssh2, libgit2, darwin.apple_sdk.frameworks.Security`: we no longer use the git2 crate
* add `libiconv` on macos which seems to have been provided by libgit2 before
> build: remove unneeded runtime buildInputs

- cli/tests/install.bats
- test_data/config.toml
- test_data/generated/resolve/tabula.json
- test_data/generated/resolve/tabula_allowed.json
This test was skipped because broken packages were not yet available in the catalog. Now that broken packages are available, mock data can be generated and the test can be re-enabled.
> test: re-enable test for broken packages

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/mod.rs
Initially, when calling `maybe_migrate_environment_to_v1_inner` in a managed environment with pending changes,
the migration dialog would show unconditionally.
After accepting the migration, `ManagedEnvironment::migrate_to_v1` would immediatly fail however due to the pending local changes.
To avoid this immediate failure after the dialog a check for local changes was added to `maybe_migrate_environment_to_v1_inner`.
However, since that ran before checking whether a migration was even necessary, it produced the wrong error when local changes were present.
That is it would print
```
Cannot automatically migrate environment:
The environment has changes that are not yet synced to a generation.
Migrate the environment manually by setting 'version = 1'
in the manifest file or reset the local …
```
> fix: only abort migration on local changes if migration was necessary

- cli/flox/src/commands/delete.rs
55ff6afd2c87eb1c729ac06cfb67a995957b34ae shortened the prompt for `flox delete` from:
```
You are about to delete your environment {description}. Are you sure?
```
to
```
Are you sure?
```
This makes sense for cases where the environment is explicitly specified with `-d`, but because we have active environment detection, `flox delete` can delete an environment not in the current directory, and the prompt doesn't give you any signal that's happening:
```
> flox delete
! Are you sure? (y/N)
[Use `-f` to force deletion]
```
When `-d` is not passed, print out a message with the full description.
> fix: print environment description in `delete`

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
Uses the local checkout as source of truth for out-of-band locking and building of containers.
Does not validate the checkout as no modification to the manifest happens.
> fix(managed): use local_checkout in `lock` and `build_container`

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/config/mod.rs
- cli/tests/services/touch_file/check.sh
- cli/tests/setup_suite.bash
- cli/tests/test_support.bash
The current path used may exceed the macOS limit of 104 characters, and it doesn't follow the XDG spec. Instead store the socket in `$XDG_RUNTIME_DIR/flox.path_hash.sock` or `~/.cache/flox/run/flox.path_hash.sock`.
Storing sockets in `flox.cache_dir` required moving the cache directory for tests to `/tmp` so that it wouldn't be too long.
`/tmp` was not used because it might get cleaned up before a long running `flox activate` exits.
ManagedEnvironment::encode was removed since `path_hash` can just be used directly before constructing an environment, and `self.path_hash` can now be used afterwards. Having both `path_hash` and `encode` is confusing.
> fix: use shorter path for sockets

- cli/catalog-api-v1/build.rs
- cli/catalog-api-v1/src/client.rs
- cli/catalog-api-v1/src/error.rs
- cli/catalog-api-v1/src/lib.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- Replace the client generated `MessageType` with an `untagged` type with an `Unknown` variant.
- Add an `UnknownServiceMessage` to the `ResolutionFailure` enum
- Remove the `Option` on the `MessageLevel` field in related structs.  It's required in the API, so it should always be present.
As a follow up, I think the message handling shouldn't be tied explicitly to _failures_ since we can pass warnings and additional explanatory messages.  But that can be a follow up to refactor that when it's needed.
- Improved resolution failure messaging.
> feat: unknown service error types

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/realise.cc
In several places, "package" is used to refer to the `RealisedPackage` for one of a package's outputs. I find referring to a package's packages confusing, so use "outputs" instead in these cases.
Rename `originalPackage` -> `storePathsToInstallIds` since it's only used to look up install ids using store paths, and also change `std::pair<std::string, resolver::LockedPackageRaw>` -> `std::string` since the `LockedPackageRaw` was unused.
> refactor(buildenv): cleanup a few names

- cli/tests/services.bats
This failed on a feature branch:
- https://github.com/flox/flox/actions/runs/9916449301/job/27399123582#step:6:381
- https://github.com/flox/flox/pull/1776
With the following output:
-- command failed --
status : 1
output (4 lines):
Starting process-compose
Waiting for process-compose socket
looking for file
Shutting down process-compose
--
I can't reproduce this locally but think it is a race condition whereby the service hasn't completed by the time we've confirmed the `process-compose` socket is created.
Prevent this from happening moving the file assertion outside of the activation after we've waited for `process-compose` to shutdown. It also gives us clearer output when it fails:
not ok 1 process-compose can run generated config file in 1327ms
N/A
> test(services): Make file test more robust

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/commands/init/go.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/utils/message.rs
- cli/tests/install.bats
This allows a user to `flox install <flakeref>'.  The install ID is inferred in the following way:
- For `github` flake refs, the repository name is used.
- For `https` flake refs where the domain is `github.com`, the repository name is also used.
- For all other URLs the ID is set to `flake`.
Users can now add Nix flakes to their manifest via the `flox install` command.
> feat: allow flakes in install command

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
Originally meant to be included in #1775, this adds a test that ensures
neither client nor flake locker are being used if all catalog descriptors,
or respectively flake installables are already locked.
> test: ensure look is noop if already locked

- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/utils/errors.rs
Print out information about flake installables in flox list.
`list` with no flags and `list -e` print:
```
nix-eval-jobs: github:nix-community/nix-eval-jobs
```
`list -n` prints:
```
nix-eval-jobs
```
`list -a` prints:
```
nix-eval-jobs: (nix-eval-jobs)
Locked URL:      github:nix-community/nix-eval-jobs/c132534bc68eb48479a59a3116ee7ce0f16ce12b
Flake attribute: packages.aarch64-darwin.default
Description:     Hydra's builtin hydra-eval-jobs as a standalone
Priority:        5
Version:         2.23.0
License:         GPL-3.0
Unfree:          false
Broken:          false
```
Code notes:
A `PackageToList` enum was added to wrap either pkgdb/catalog packages or flake packages. A shared format makes sense for pkgdb and catalog packages since they share so much info in common, but flake packages …
> feat: support flake installables for list

- cli/flox/src/commands/list.rs
To be consistent with catalog packages, flake packages should also put Description at the top of the `list -a` output
> fix: move Description to top of `list -a` output

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
Currently when we call pkgdb we set its PATH so it doesn't use user provided binaries. For locking flakes, we do want to use user provided git and ssh, so don't clear PATH for invocations of pkgdb locking flakes.
Tests will be added in a followup.
> fix: allow usage of private flakes

- cli/tests/services.bats
- cli/tests/services/portgrab.sh
- cli/tests/services/redis.toml
- cli/tests/services/wait_and_cleanup.sh
- test_data/config.toml
- test_data/generated/resolve/redis.json
**test(services): Use activate --start-services**
Replace the use of our custom start command now that the
`--start-services` argument has been added to `flox activate`.
This allows us to test our own code more thoroughly and removes the
manual setup that we had to do previously.
**test(services): Redis on standard port**
Test a networked service. We originally deferred this because of port
clashes when running on non-containerised CI systems (Nix builders) but:
a) it's important that we test this most common use case for services
b) workaround for ports will be added in a subsequent commit
I've chosen Redis because it's relatively small and fast to start,
unlike PostgreSQL for example. It currently creates a data dir within
the temporary project environment but that could be disabled …
> test(services): Test network services with Redis

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/doc/services/flox-activate.md
- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
This uses the presence of the socket file to determine when to skip starting services. A warning message is printed to inform the user that they requested to start services as part of the activation and we intentionally did not do what they requested.
In order to make this easy to test I reverted the socket path function to the previous behavior where it would defer to an explicitly set environment variable.
It would be nice to test that `process-compose` is also not started when we show this message, but that seems tricky to test in a cross-platform way (e.g. no access to `/proc` on macOS).
N/A
> feat: skip starting services when already running

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/pkgdb.rs
- cli/flox-rust-sdk/src/providers/flox_cpp_utils.rs
- cli/flox/doc/manifest.toml.md
Building flake installables may require ssh from PATH. Currently PATH is cleared when we call pkgdb buildenv. Instead, append git to PATH for this case.
Also append git to PATH for when we call `pkgdb lock-flake-installable` so we have a fallback.
> fix: support private flake installables

- cli/tests/activate.bats
- cli/tests/activate/hook.exp
**test(activate): Assert on prompt not spinner**
To fix intermittent failures from this test:
- https://github.com/flox/flox/actions/runs/9896583574/job/27339464292#step:6:185
The `zsh` test case didn't get the "Preparing environment" spinner which
may not be outputted if the operation is fast enough. Apply the same fix
that we did for c271f3e by waiting for the shell prompt instead.
**test(activate): Loop over shells for tracelevel**
Make the test easier to read by de-duplicating the common parts.
**test(activate): Consolidate .extra cleanups**
Remove the shell specific `.extra` files in `project_teardown` which is
called by `teardown` after each test, regardless of whether it succeeded
or failed.
Previously a test failure would cause these to leak through to other
tests in the same file …
> test(activate): Fix flakey tracelevel test

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/utils/init/catalog_client.rs
- If running in CI (based on env var `CI` being set), send the `flox-ci` header
- If not opted out of metrics, send the unique id as `flox-device-uuid`.
> feat: add headers to catalog API requests

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/utils/errors.rs
- cli/tests/install.bats
This resolves the issue causing confusing messages when uninstalling packages with a dotted attr_path (e.g., foo.bar). The package name is now correctly parsed, allowing such packages to be uninstalled from the environment.
fixes #1714
> fix(uninstall): Correct package uninstallation with dotted attr_path

- assets/activation-scripts/activate
The `activate` script contains a `process-compose` that should be `$_process_compose` in order to use the `process-compose` from our closure.
N/A
> fix: use Nix-provided process-compose

- .github/workflows/ci.yml
We've had jobs hanging for hours (see e.g.
https://github.com/flox/flox/actions/runs/10067670807/job/27831900822).
Add a timeout of 90 minutes to avoid this.
> test: timeout after 90 min

- pkgdb/.gitignore
- pkgdb/Makefile
This small tweak of the pkgdb/Makefile changes the logic so that the activation-scripts package is only rebuilt when any of its assets or its Nix expression changes, which saves about 4 seconds with each invocation of make in the pkgdb subdirectory when any file in the repository changes.
It also does a small amount of reorganization by putting all of the makefile stanzas pertaining to `realise.o` in the same location.
N/A
> feat: be smarter about detecting when to rebuild activation-scripts

- cli/tests/services.bats
- pkgs/flox-cli-tests/default.nix
process-compose 1.6.1 has a race condition when started with a socket
that it cannot write to. It sometimes leaves running services behind.
Bats will hang forever if a child process doesn't exit because it's
waiting for file descriptor 3 to close. See:
https://bats-core.readthedocs.io/en/stable/writing-tests.html#file-descriptor-3-read-this-if-bats-hangs
Close FD 3 so that tests don't hang forever if the sleep process is left
behind.
A reproducer on aarch64-linux for the race condition is:
$ cat service-config.yaml
processes:
sleep:
command: "sleep infinity"
$ ps -A | grep sleep
$ while ! ps -A | grep sleep; do process-compose up --config service-config.yaml --unix-socket /no-perms; done
24-07-26 20:50:45.882 FTL start UDS http server on /no-perms failed error="listen unix /no-perms: …
> fix: close fd3 in process-compose test

- cli/Cargo.lock
- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/stop.rs
* Allow starting a temporary `process-compose` instance that is killed when the instance is dropped.
*`Read the output of a single process from `process-compose process logs <process> --follow
* compose multiple readers into a single stream
> feat: read logs for services

- cli/flox/src/commands/services/logs.rs
`flox services --help` failed with 
```
thread 'main' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bpaf-0.9.12/src/meta.rs:96:29:
bpaf usage BUG: all positional and command items must be placed in the right most position of the structure or tuple they are in but Flag { name: Long("follow"), shorts: [], env: None, help: Some(Doc { payload: "Follow log output", tokens: [Text { bytes: 17, style: Text }] }) } breaks this rule. See bpaf documentation for `positional` for details.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
because the `--follow` flag was defined after the process list argument.
With this fix the help output for `flox services` now renders as
```
Interact with services
Usage: flox services COMMAND ... …
```
> fix(services-logs): command argument order

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox/doc/flox-uninstall.md
- cli/flox/src/commands/uninstall.rs
Try matching uninstall target against descriptor with version spec.
Approaches the second alternative in [flox/flox#1512](https://github.com/flox/flox/issues/1512):
```
flox init
flox install --id vbox virtualbox@7.0.12
...
flox uninstall vbox                 # works
flox uninstall virtualbox           # works since #1810
flox uninstall virtualbox@7.0.12    # works now with #1834
```
`<version>` has to match the original version specifier exactly; in the example above `virtualbox@7` would not match.
> feat: allow descriptors with versions to uninstall packages

- cli/tests/services.bats
The test `blocking: error message when startup times out` currently uses `ps` to find left behind `sleep` invocations.
`ps` includes a variable amount of whitespace between process name and PID in its output, but currently only a single space is stripped, which can cause the following failure:
```
/tmp/flox-cli-tests-eNqhXo/services.bats: line 306: kill:           2511431
2511432: arguments must be process or job IDs
```
https://github.com/flox/flox/actions/runs/10183811288/job/28170018401?pr=1837#step:6:413
Trim any amount of whitespace instead.
> fix: trim whitespace from sleep PID

- cli/flox-rust-sdk/Cargo.toml
- cli/flox-rust-sdk/src/models/env_registry.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/services/logs.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/stop.rs
- cli/flox/src/utils/errors.rs
- cli/klaus/src/listen.rs
- cli/klaus/src/main.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
- cli/tests/test_support.bash
**refactor(registry): Take reg_path for lock_path**
So that we don't need to construct `Flox` in `klaus` when accessing the
registry. All of the existing callers already have the registry path
when constructing the lock path.
**feat(klaus): Pass in dot_flox_hash for registry**
So that we can access the environment registry without having to
reconstruct information from `Flox` or `.flox`.
**feat(registry): Track activation PIDs**
This will be used by the watchdog `klaus` to track when the last
activation of an environment exits and we should clean up any running
services.
Stale activations are removed when updating the registry on disk to
catch watchdog processes that may have died without cleaning up after
themselves.
The new field needs to use `default` in order to read registry files …
> feat(watchdog): Track activations in registry
