- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox/src/commands/package.rs
The project template will now use mkShell in a default.nix and `flox develop`
See https://github.com/flox/floxpkgs/pull/135
> feat: use mkShell for project template

- .github/workflows/flox-bash-tests.yml
- .github/workflows/gpg-test.yml
Migrate two GitHub Actions tests from `flox-bash` repository.
Currently there is no automated testing.
N/A
> test: move flox-bash GHA tests

- flox-bash/lib/diff-catalogs.jq
flox list --json currently fails with
ERROR: encountered object of type array
when the environment contains a package from a flake.
Instead:
- use publish_element as a marker for whether a package is from a catalog or flake
- change recursion to emit empty rather than error when a flake is encountered
> fix: don't attempt to print upgrades for flakes

- README.md
Closes https://github.com/flox/flox/issues/63
> fix: broken discord link

- .github/workflows/ci.yml
> feat: add caching ci

- crates/flox/doc/flox-rollback.md
> docs: add manpage for `flox rollback`

- .github/workflows/ci.yml
simple caching of all store contents
no caching of build deps of dependencies
N/A
> ci: cache the entire store

- flox-bash/lib/bootstrap.sh
- flox-bash/lib/commands.sh
- flox-bash/lib/commands/activate.sh
- flox-bash/lib/commands/development.sh
- flox-bash/lib/commands/environment.sh
- flox-bash/lib/commands/general.sh
- flox-bash/lib/commands/publish.sh
- flox-bash/lib/init.sh
- flox-bash/lib/metadata.sh
- flox-bash/lib/utils.sh
Fixes all shellcheck issues in `flox-bash/lib/metadata.sh`.
Shellcheck emits over 200 warnings and errors.
N/A
> fix: shellcheck for metadata.sh

- crates/flox/src/commands/package.rs
Currently exposed as a hidden `publish2` subcommand. 
The new publish decidedly takes less/different args than the bash implementation.
To allow for a transition period we expose this command under a different name, while in development.
> feat: add a publish v2 command to the cli

- pkgs/nix-editor/default.nix
Remove IFD from nix-editor derivation, which makes it harder to do eval + build + deployment.
IFD
N/A
> nix editor.remove ifd

- .github/workflows/ci.yml
- pkgs/flox/default.nix
> fix: disable installCheck for flox

- Cargo.lock
- Cargo.toml
- crates/flox-rust-sdk/src/actions/environment.rs
- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox-rust-sdk/src/models/flox_package.rs
- crates/flox-rust-sdk/src/models/floxmeta/environment.rs
- crates/flox-rust-sdk/src/models/project/environment.rs
- crates/flox-rust-sdk/src/models/project/mod.rs
- crates/flox-rust-sdk/src/models/publish.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/package.rs
This PR allows `flox` to resolve indirect flake references to their `git` origins.
This is currently unimplemented for indirect references.
N/A
> feat: resolve indirect references to git

- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox-rust-sdk/src/models/environment_ref.rs
- crates/flox/src/commands/environment.rs
This doesn't rename any of the methods or split them as discussed in https://github.com/flox/flox/pull/202#discussion_r1297501392, but I'm going to hand the baton back to @ysndr
> feat: refactor Environment and make a trait

- .cz.toml
- Cargo.lock
- crates/flox/Cargo.toml
- flake.lock
bump version in preparation for upcoming changes
There will be upcoming changes: https://discourse.floxdev.com/t/upcoming-changes-in-the-flox-cli-0-3-x/787
> chore: bump version

- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox/src/commands/environment.rs
- tests/environment-list.bats
This PR essentially adds the tests from `feature/env2/list` and gives the thumbs up to the feature-flagged `flox list` implementation from #202.
No change
N/A
> feat: add feature-flagged 'flox list' command

- crates/flox-rust-sdk/src/models/environment.rs
- crates/flox/src/commands/environment.rs
- tests/environment-install.bats
- use transaction helpers
- print better output to users
- add some tests
> feat: next iteration of uninstall

- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/general.rs
- crates/flox/src/commands/mod.rs
- flake.lock
- flake.nix
- pkgs/flox-bash/default.nix
- pkgs/flox-pkgdb/default.nix
- pkgs/flox/default.nix
Adds a _very_ rough integration of `pkgdb search` behind the `FLOX_FEATURES_CHANNELS=rust` feature flag.
This is far from a real integration, but it will at least provide a jumping off point.
The actual output formatting needs work ( particularly column alignment ), but I wanted to avoid going down that rabbit hole myself. This should at least get the ball rolling.
NOTE: This PR will not move this ticket to "closed", it should return to the sprint backlog to get _properly_ integrated.
This works:
```shell
$ flox develop '.#flox';
$ cargo build;
$ FLOX_FEATURES_CHANNELS=rust ./target/debug/flox search hello
nixpkgs-flox#legacyPackages.x86_64-linux.unstable.sbclPackages.cl-mw_dot_examples_dot_hello-world: cl-mw.examples.hello-world@20150407-git
...<SNIP>...
```
N/A
> feat: rough integration of 'flox search' using 'pkgdb'

- crates/flox-rust-sdk/src/providers/git.rs
We don't need run_command to be async, so it's just causing pain.
> fix: make git run_command synchronous

- pkgs/flox-gh/default.nix
We're only expecting to carry the `gh` dependency for a few more weeks so we can pin it at version 2.32.1 for that period of time. We do this by committing a modified version of the full Nix expression as found in the previous stable nixpkgs because just overriding the src and vendor checksums does not yield a working build.
> fix: pin upstream gh version at 2.32.1

- tests/publish.bats
This PR skips a test that's flaky on macOS
N/A
> test: skip flaky test on macOS

- crates/flox/doc/flox-show.md
This adds a manpage for the feature-flagged `flox show` command.
Closes flox/product#358
N/A
N/A
> docs: add flox show manpage

- .github/workflows/ci.yml
* duplicate of '.#flox' installable
* removing depth:0 from Checkout step to speed up
> ci: Addressing comments from #320

- doc/release-notes/rl-0.3.6.md
Release flox@0.3.6
flox@0.3.5
N/A
> release: v0.3.6

- Cargo.lock
- pkgs/flox/default.nix
> fix: cargo lock

- crates/flox-rust-sdk/src/providers/git.rs
Allow configuring the git instance using git config pairs (passed to the git cli as `-c <key>=value` and environment variables.
Both should be universally applicable to all git commands.
Thus the configuration can be stored with the command provider and stay valid over its lifetime.
> feat: add `GitCommandOptions`

- crates/flox-rust-sdk/src/flox.rs
- crates/flox-rust-sdk/src/models/environment/managed_environment.rs
- crates/flox-rust-sdk/src/models/floxmetav2/mod.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/utils/completion.rs
* Configure git author data
* Redirect git global and system config files to /dev/null
* Pass floxhub token through `Flox` to floxmeta constructors and configure credential helper
> feat: configure git for floxmeta

- crates/flox/doc/flox-search.md
- crates/flox/doc/flox.md
- crates/flox/src/commands/channel.rs
- crates/flox/src/commands/mod.rs
- flox-bash/flox.1.md
- tests/usage.bats
Missed in e5b29b3baa3e7bc3eaa5e2bbe698eb4be9869e52
> fix: remove a few more mentions of channels

- pkgs/flox/default.nix
continuation of https://github.com/flox/flox/pull/356 (I missed the reference in the flox recipe itself)
> fix: also trim down locales in flox itself

- Justfile
Adds `bump` and `bump-all` commands to the Justfile that automatically updates flake inputs and commits a descriptive message.
N/A
> feat: add bump and bump-all cmds

- crates/flox/src/commands/environment.rs
Displays a message during a build triggered by `flox activate` so that a user has some indication that something is going on and the program isn't stalled.
The message is written to `stderr` and then dismissed when the build is complete.
A progress message is displayed while building an environment as a result of calling `flox activate`.
> feat: display progress message during activate

- crates/flox/src/commands/mod.rs
fixes https://github.com/flox/flox/issues/380
> fix: do not pull in user channels

- crates/flox-rust-sdk/src/models/environment/mod.rs
Useful for debugging https://github.com/flox/flox/actions/runs/6789775563/job/18457726798?pr=401#step:6:134
> feat: debug manifest locking command

- crates/flox-rust-sdk/src/flox.rs
- crates/flox/src/commands/environment.rs
Uses the GitHubClient introduced in #410 to determine the github username associated with the login token we have already stored.
The username is parsed as an EnvironmentOwner so _some_ users with may be unable to use floxhub at all using plain github handles. This is understood to change during the transition to FloxHub users.
closes #418
> feat: resolve owner to push for using github token

- CONTRIBUTING.md
- Justfile
Expands on how to run tagged tests and establishes a set of tags to use.
N/A
> docs: explain how to run tagged tests

- crates/flox/src/utils/mod.rs
> fix: drop dead code

- flake.lock
Pulls updates required to fix `experimental-features` issues.
N/A
> chore: bump pkgdb pin

- Justfile
- flake.nix
- pkgs/flox-tests/default.nix
Running tests locally was broken due to running tests inside of a temporary directory.
> fix: enable running tests locally

- .github/workflows/ci.yml
- flake.nix
uploads to public cache _instead of the private internal cache_
N/A
> ci: upload to flox-store-public

- .github/workflows/ci.yml
Installs a newer Nix to CI.
N/A
> ci: update CI to latest Nix

- pkgdb/src/resolver/environment.cc
The logic to skip resolving an input if it was the same as oldGroupInput was inverted
> fix: logic error, drop try

- crates/flox/src/commands/environment.rs
- crates/flox/src/commands/mod.rs
- crates/flox/src/utils/dialog.rs
- tests/environment-install.bats
- tests/install/prompt-which-environment.exp
For environment commands, prompt for which environment to use when an environment is activated and there is also an environment in the current directory.
> feat: prompt which environment to use

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature.md
Add a version field for flox for bugs.
> Update issue templates

- pkgdb/README.md
Adds high level summary of scraping logic in `pkgdb/README.md`.
N/A
> docs: document scraping logic

- crates/flox/src/commands/mod.rs
- crates/flox/src/commands/search.rs
- crates/flox/src/config/mod.rs
* Add a config field `search_limit`
* pass config to `Search::handle` and replace inline env reading
> feat: use config to set search limit

- Justfile
- cli/tests/develop.bats
- cli/tests/edit.bats
- cli/tests/environment-activate.bats
- cli/tests/environment-edit.bats
- cli/tests/gpgsign.bats
- cli/tests/integration.bats
- cli/tests/multi-env.bats
- cli/tests/package-search.bats
- cli/tests/package.bats
- cli/tests/publish.bats
- cli/tests/reliability.bats
- cli/tests/run.bats
- pkgdb/tests/cli.bats
- pkgdb/tests/ga-registry.bats
- pkgdb/tests/get.bats
- pkgdb/tests/migrate.bats
- pkgdb/tests/pathological.bats
- pkgdb/tests/scrape.bats
- pkgdb/tests/search.bats
- pkgdb/tests/sqlite3.bats
- tests/python.bats
Quotes a few variables that got unquoted in recent changes, and updates the Justfile to the latest test procedures.
N/A
> test: clean up test suite, fix Justfile test commands

- .github/workflows/ci.yml
Attempt building in parallel. CI speedups!
N/A
> ci(pkgdb): attempt parallel

- pkgdb/Makefile
The `ccls` target had a typo.
N/A
> fix: broken ccls target

- cli/flox/src/commands/environment.rs
Updates the info emoji and wording according to AC
> style: update `flox delete` messsages

- cli/flox/src/commands/mod.rs
closes https://github.com/flox/flox/issues/425
> feat: add `flox help` command

- cli/flox/src/commands/environment.rs
- cli/tests/environment-pull.bats
> feat: automatically build environment after `flox pull`

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/tests/environment-managed.bats
closes https://github.com/flox/flox/issues/644
> fix: try find locked rev on project branch if sync branch diverged

- flake.nix
- pkgdb/docs/testing-private-interfaces.cc
- pkgdb/docs/visit.cc
- pkgdb/src/pkgdb/schemas.hh
- pkgdb/src/resolver/lockfile.cc
- pkgdb/tests/environment.cc
- pkgdb/tests/test.hh
* add `clang-format` commit-hook
* ci: change git hooks to run on `push` rather than `commit`
manually run them with 
```
$ pre-commit run --hook-stage manual -a
``` 	
* chore: format c/c++ files
> ci: add `clang-format` commit-hook

- cli/flox/src/commands/mod.rs
- cli/tests/environment-install.bats
- cli/tests/usage.bats
> feat: `flox i` aliases to `install`

- cli/flox-rust-sdk/src/models/environment/mod.rs
> fix: correct misspelling

- cli/tests/environment-activate.bats
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/buildenv.bats
- pkgdb/tests/data/buildenv/lockfiles/vars_escape/manifest.toml
> fix: disable variable substitution in manifest vars

- assets/templateFloxEnv/manifest.toml
* Add header with backlink to docs page
* fix quotes
* Expand docs on `hook` and `vars`
> docs: update manifest template

- .github/actions/common-setup/action.yml
- .github/workflows/ci.yml
> ci: extract common-setup in a composite action with steps that repeat

- .github/workflows/ci.yml
> ci: create an artifact in a CI to be used by shipit

- .github/workflows/ci.yml
Previous path info only reported the size for 1 NAR, not the entire closure.
N/A
> ci: closure size should be recursive

- cli/flox-rust-sdk/src/models/container_builder.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/mod.rs
- cli/flox/src/commands/environment.rs
- cli/tests/container/manifest.toml
- cli/tests/environment-containerize.bats
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
* call `pkgdb buildenv --container` with lockfile of any given environment
* implement `containerize` command with path defaults
> feat: add `containerize` command

- pkgdb/src/pkgdb/input.cc
- pkgdb/tests/search.bats
Makes the parallel database locking test more lenient.
N/A
> test: make parallel test more lenient

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-edit.bats
- cli/tests/environment-push.bats
* feat: add richer error messages to `flox push`
* feat: add `flox edit --name`
> feat: add richer error messages to flox push

- .github/workflows/ci.yml
filter pkgdb test to only run on changes to that subdir
N/A
> ci: limit pkgdb testing to changes in subdir

- pkgdb/tests/search.bats
> chore: format and fix quotes/params in `pkgdb/tests/search.bats`

- .github/workflows/ci.yml
Use smaller machine for sync triggering of other workflows.
N/A
> ci: no need for 8 core to trigger and wait

- cli/flox/src/commands/mod.rs
- cli/tests/environment-remote.bats
- cli/tests/test_support.bash
> feat: automatically trust environments owned by the current login

- cli/flox/src/commands/environment.rs
- cli/tests/activate/envVar.exp
- cli/tests/activate/hello.exp
- cli/tests/activate/hook.exp
- cli/tests/activate/remote-hello.exp
- cli/tests/edit/re-activate.exp
- cli/tests/install/last-activated.exp
- cli/tests/install/prompt-which-environment-git.exp
- cli/tests/install/prompt-which-environment.exp
- tests/python.exp
> feat(interactive-activate): description and exit instructions

- cli/flox/src/commands/mod.rs
> fix: remove left over `dbg`

- cli/flox/src/commands/environment.rs
> chore: format consistently and remove defunct `--system` wrapper

- cli/flox/src/commands/auth.rs
> fix: catch `TokenExpired` response

- README.md
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/tests/environment-edit.bats
- cli/tests/environment-init.bats
- cli/tests/environment-managed.bats
- cli/tests/environment-pull.bats
- cli/tests/environment-remote.bats
Fix typos and align with style guide.
Notes I took while we were creating https://github.com/flox/flox/issues/850
> fix: style nits

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/dialog.rs
- cli/tests/environment-pull.bats
- cli/tests/pull/promptAmendSystem.exp
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/core/exceptions.hh
- pkgdb/src/buildenv/realise.cc
> feat: add system to manifest on pull with `--add-system`

- pkgdb/include/flox/pkgdb/pkg-query.hh
- pkgdb/src/pkgdb/pkg-query.cc
- pkgdb/src/search/command.cc
- pkgdb/tests/pkgdb.cc
- pkgdb/tests/search.bats
> fix: escape special characters in pkg search

- cli/tests/ld-floxlib.bats
skip test that is related to https://github.com/flox/flox/issues/862
N/A
> test: skip ld test as it fails when run on interactive development

- CONTRIBUTING.md
> docs: add C/C++ IDE setup and merge convention to contributing.md

- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
> feat: catch activate errors due to build on incompatible platform

- .github/workflows/ci.yml
- Justfile
- tests/cross-system.bats
Push an environment on one system, and activate it on another system in the next workflow run.
> test: cross system pull

- cli/flox/src/commands/environment.rs
Removes an extra `-d` option in the help for `flox pull`.
Thanks to @ysndr for the patch.
N/A
> fix: remove extra -d option for pull

- Justfile
> ci: remove superfluous --

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/src/commands/environment.rs
- cli/tests/environment-activate.bats
> fix: do not call `<shell> -i` for non-interactive `flox activate --`

- cli/flox/src/commands/environment.rs
- cli/tests/environment-install.bats
* general error message should follow style guide
* hint if no suggestion could be found
closes #893
> style: update error format of install failures

- cli/flox/src/utils/errors.rs
- pkgdb/include/flox/buildenv/buildenv.hh
- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/src/buildenv/buildenv.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/tests/buildenv.bats
> style: improve package conflict error

- cli/flox/src/commands/mod.rs
fixes https://github.com/flox/product/issues/639
> chore: include exit hint in help for `activate`

- cli/flox/src/utils/errors.rs
fixes https://github.com/flox/flox/issues/852
> style: catch toml parsing error and invalid lockfile error

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment_ref.rs
- cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/utils/errors.rs
Improve error message while pulling
closes #851
> feat: rich error when environment not found upstream

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-auth.md
- cli/flox/doc/flox-init.md
- cli/flox/doc/flox-search.md
- cli/flox/doc/flox-show.md
- cli/flox/doc/include/package-names.md
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/tests/environment-activate.bats
- cli/tests/setup_suite.bash
- pkgdb/src/buildenv/assets/mkContainer.nix
- tests/setup_suite.bash
Adds or updates manpages for
- `flox activate`
- `flox auth`
- `flox init`
- `flox search`
- `flox show`
An empty file for `flox update` is also included so that links could be created to it. This file is filled in by another PR.
N/A
> docs: init, search, show, auth, activate manpages

- Justfile
Adds a `just clean` target which runs `cargo clean` and `make clean`.
> feat: add 'just clean' target

- cli/flox/src/commands/environment.rs
> feat: `delete -r` raises an "unsupported" error

- cli/flox/src/commands/environment.rs
> style(list): print a warning if environment is empty

- pkgdb/src/resolver/descriptor.cc
- pkgdb/src/resolver/lockfile.cc
Drop unused code, and add a missing erase for an erase-remove
> fix: address some compiler warnings

- cli/flox/src/commands/auth.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
Renames `path` -> `pkg-path` in help descriptions. Includes some other small fixes.
Note: will need to be rebased once the outstanding manpages PR is merged.
> docs: path -> pkg-path in help

- pkgdb/include/flox/flox-flake.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/include/flox/registry.hh
- pkgdb/src/flox-flake.cc
- pkgdb/src/nix-state.cc
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/src/registry.cc
follow up fixing non-functional nits from memory optimization work.
> style: formatting and doc

- cli/flox/doc/flox-activate.md
- cli/flox/doc/flox-config.md
- cli/flox/doc/flox-containerize.md
- cli/flox/doc/flox-edit.md
- cli/flox/doc/flox.md
- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
Updates the main `flox` man page.
> docs: flox man page

- cli/flox/src/commands/environment.rs
> feat: include docs link in error message

- cli/flox/doc/flox-auth.md
- cli/flox/doc/flox.md
- cli/flox/doc/include/environment-options.md
A few minor tweaks to the documentation.
> docs: couple of corrections

- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-pull.bats
> fix: do not `panic` if remote env is not buildable

- README.md
> fix: link issue in readme

- cli/flox/doc/manifest.toml.md
Rewords part of the description of the `pkg-group` description.
N/A
> docs: tweak pkg-group option description

- pkgs/flox/default.nix
expose calculated version as a nix value
N/A
> fix: expose version in symlinkJoin

- cli/flox/src/utils/init/metrics.rs
closes https://github.com/flox/flox/issues/914
> chore: remove example from metrics notice

- pkgdb/src/buildenv/realise.cc
> style: update the error message for package conflicts

- flake.lock
- pkgs/flox/default.nix
Update lock file for flox-latest. Nix builds then has the expected version.
N/A
> feat: better automatic versions

- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/src/pkgdb/input.cc
Split scraping code into a worker function, refactored for better encapsulation.
N/A
> chore: address linting TODO in scraping code

- cli/flox/src/commands/environment.rs
This just helps with readability in the terminal.
N/A
> chore: add newline after activation msg

- pkgdb/include/flox/core/util.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/src/pkgdb/rules.json.hh
- pkgdb/src/pkgdb/write.cc
- pkgdb/tests/pkgdb.cc
- Code cleanup and simplification
- Add test for unsupported glob in rules
N/A
> chore: address PR comments for rules based scraping

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/floxmetav2/mod.rs
- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/errors.rs
- cli/tests/environment-edit.bats
- cli/tests/environment-push.bats
- tests/cross-system.bats
floxhub -> FloxHub in several comments and error messages
N/A
> fix: FloxHub capitalization

- cli/tests/environment-install.bats
- pkgdb/src/pkgdb/rules.json.hh
- pkgdb/src/pkgdb/write.cc
- pkgdb/tests/search.bats
- add a rule to recurse into `legacyPackages.*.nodePackages`
Additional Node Packages are available.
> feat: scrape under nodePackages (via rules update)

- pkgdb/src/buildenv/realise.cc
- disable command hashing in the flox shell
N/A
> fix: disable cmd hashing in activation scripts

- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/init/node.rs
- cli/flox/src/commands/init/python.rs
- Made some changes I thought were non-controversial
- Added some tests
- test_get_init_customization_with_selected_provider and test_get_init_customization_with_providers are unfinished
- test_poetry_pyproject_unavailable_version and test_pyproject_unavailable_version have legitimate failures that need to be fixed
> fix: some python hook fixes and tests

- doc/release-notes/rl-1.0.0.md
> docs: release notes include 0.9.0 login note

- pkgdb/include/flox/buildenv/realise.hh
- pkgdb/include/flox/core/util.hh
- pkgdb/include/flox/pkgdb/command.hh
- pkgdb/include/flox/pkgdb/input.hh
- pkgdb/include/flox/pkgdb/scrape-rules.hh
- pkgdb/include/flox/pkgdb/write.hh
- pkgdb/include/flox/registry.hh
- pkgdb/include/flox/resolver/command.hh
- pkgdb/include/flox/resolver/environment.hh
- pkgdb/include/flox/resolver/lockfile.hh
- pkgdb/include/flox/resolver/manifest.hh
- pkgdb/include/flox/resolver/primops.hh
- pkgdb/include/versions.hh
- pkgdb/src/buildenv/command.cc
- pkgdb/src/buildenv/realise.cc
- pkgdb/src/main.cc
- pkgdb/src/pkgdb/gc.cc
- pkgdb/src/pkgdb/input.cc
- pkgdb/src/pkgdb/primops.cc
- pkgdb/src/pkgdb/scrape-rules.cc
- pkgdb/src/pkgdb/write.cc
- pkgdb/src/resolver/command.cc
- pkgdb/src/resolver/environment.cc
- pkgdb/src/resolver/lockfile.cc
- pkgdb/src/resolver/manifest.cc
- pkgdb/tests/environment.cc
Addresses various clang-tidy warnings
N/A
> chore: clang-tidy fixes

- README.md
chore: Change flox to Flox in a few spots
> chore: Change flox to Flox in a few spots

- cli/flox/src/commands/init/mod.rs
ensure_global_lockfile() may cause a nixpkgs download, so that should be performed behind the spinner
> fix: spin in init during nixpkgs download

- assets/templateFloxEnv/manifest.toml
We do not currently have a `file` option but still reference it in the manifest template
N/A
> fix: file option in manifest

- .github/CONTRIBUTORS.csv
- README.md
A simple correction in the README, hope to be of help!
N/A
> docs: added a dot and removed an extra space in README

- .github/ISSUE_TEMPLATE/bug-report.md
System and architecture are helpful when debugging issues
> chore: add uname -a to issue template

- README.md
> fix: update install link

- cli/flox/doc/manifest.toml.md
Fix to `manifest.toml.md` docs
N/A
> docs: fix manifest.toml.md docs

- cli/Cargo.lock
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/main.rs
> style: `[--]help` wraps messages at 80 characters wide

- cli/flox/src/commands/environment.rs
- cli/flox/src/commands/mod.rs
Deletes commands that aren't yet implemented.
N/A
> chore: delete unused commands

- .github/workflows/ci.yml
> fix: build for all systems

- doc/release-notes/rl-1.0.3.md
> docs: release notes 1.0.3

- CONTRIBUTING.md
Explain when to add unit, integration, and functional tests.
> docs: describe types of tests in CONTRIBUTING.md

- cli/flox-rust-sdk/src/models/manifest.rs
`RawManifest` is a wrapper around a `toml_edit::DocumentMut`
that allows modifications of the raw manifest document,
while preserving comments and user formatting.
`TypedManifest` represents the Manifest data schema for reading/processing of the manifest.
Writing a `TypedManifest` will drop comments and formatting so this should only be used in cases
where these can safely be severed.
In addition, mark the current `Manifest` type as deprecated, to signal the places that have yet to integrate `TypedManifest`.
> feat: add separate `RawManifest` and `TypedManifest` types

- cli/Cargo.lock
- cli/Cargo.toml
- cli/catalog-api-v1/Cargo.toml
- cli/catalog-api-v1/openapi.json
- cli/catalog-api-v1/src/client.rs
- cli/catalog-api-v1/src/mock.rs
Regenerate code with latest spec changes
> chore: bump openAPI spec

- cli/catalog-api-v1/openapi.json
- cli/catalog-api-v1/src/client.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
The API schema has been changed for outputs and outputs_to_install
> chore: bump schema

- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/commands/show.rs
- cli/tests/catalog_responses/hello_show.json
- cli/tests/search.bats
- cli/tests/show.bats
Uses the mock client for `flox show` when the appropriate environment variables are set and pointing at a mock data file.
N/A
> feat: mock show command

- .github/workflows/ci.yml
Temporarily added token, this fix should allow the correct existing token to be used. 
N/A
> ci: fix name of access token

- cli/catalog-api-v1/build.rs
- cli/flox/src/commands/init/python.rs
- cli/flox/src/utils/metrics.rs
- cli/flox/src/utils/openers.rs
- cli/flox/src/utils/search.rs
- flake.lock
- flake.nix
- pkgs/flox-cli/default.nix
Based on @zmitchell's WIP https://github.com/flox/flox/pull/1369.
I picked that up to continue integration of fenix to bring this over the line due despite PTO
> build: use latest Rust toolchain using fenix

- cli/flox/doc/flox-show.md
This was missed in d27e0d00.
I've included an extra version in the example, even though it depends on catalog features which aren't GA yet, because the risk of it confusing someone seems lesser than the risk of us forgetting to add it later.
N/A
> docs(show): Update output format example

- cli/flox/src/commands/envs.rs
- cli/flox/src/commands/mod.rs
Adds help descriptions for `flox envs -h`.
There's more information in `flox envs -h`.
> docs: add help description for envs command

- cli/flox-rust-sdk/src/providers/catalog.rs
This is a quality of life improvement for saving real response data from commands. Previously, the last response would always overwrite all previous responses in the response file. Now all responses from a given `flox` invocation are recorded in sequence in the mock data file.
N/A
> feat: dump all responses from command

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/upgrade.rs
- cli/tests/catalog_responses/install_curl_hello.json
- cli/tests/catalog_responses/install_hello.json
- cli/tests/catalog_responses/install_old_hello.json
- cli/tests/upgrade.bats
- shells/default/default.nix
Makes copies of `flox upgrade` tests for use with catalog service. All tests are skipped for now due to https://github.com/flox/flox/issues/1485.
Anything not in `upgrade.bats` was added for debugging or to fix a bug in dumping catalog responses.
N/A
> test: make catalog tests for upgrade

- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/tests/init.bats
When using the catalog the manifest now defaults to all systems.
N/A
> feat: default manifest to all systems

- cli/tests/containerize.bats
Copy `flox containerize` tests and run with catalog.
> test: copy containerize tests for catalog

- pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
Fixes to CUDA experimental activation feature.
N/A
> fix: cuda link order

- test_data/README.md
I remembered reading about `GENERATED_DATA` not being re-evaluated but it hadn't initially occurred to me that the file also needed to be staged.
N/A, dev only.
> docs(test_data): Gotcha for changing mocks

- pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
Adds detection for WSL requirements.
N/A (experimental for now)
> feat: support CUDA activation on WSL

- cli/flox-rust-sdk/src/models/manifest.rs
This was partially done in dec0ac79185367542ee62d26df15a9781531a266, but nested fields were missed. It matches pkgdb behavior:
```
> echo '[options]\nallow.blah = true' | FLOX_FEATURES_USE_CATALOG=false flox edit -f -
❌ ERROR: unrecognized manifest field 'options.allow.blah'.
```
> fix: deny_unkown_fields in v1 manifest

- pkgdb/src/buildenv/assets/etc/profile.d/0800_cuda.sh
Include additional locations (eg: /lib64) and additional libraries to symlink (via wildcards).
N/A
> feat(cuda): include additional search location (eg; for Fedora)

- cli/flox/src/config/features.rs
- cli/flox/src/main.rs
- cli/tests/services.bats
Creates the feature flag for service management.
N/A
> feat: add service management feature flag

- cli/flox-rust-sdk/src/providers/catalog.rs
Update the default catalog URL
N/A
> chore: update default catalog url

- cli/tests/upgrade.bats
Ensures that you don't see one line per system when upgrading a package.
N/A
> test: add upgrade test

- cli/flox/src/utils/init/logger.rs
This just provides more data in error reports.
N/A
> feat: enable span attributes on sentry events

- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox/doc/flox-edit.md
- cli/flox/src/commands/edit.rs
- Some of the docs got stale
- Remove an orphaned comment
- Rename a function to make it more obvious what it does
> fix: followup nits for local checkouts

- cli/flox-rust-sdk/src/providers/catalog.rs
We now retrieve up to 1000 results at a time while paging, increased from
only 10. The only cases where we actually use pagination (search --all
and show) retrieve the entire set of results anyway, so smaller pages
don't really reduce the work and substantially increase the latency. For
ordinary search, where we limit the number of results we show, we still
respect that limit and only retrieve the necessary number of rows.
> chore: Increase catalog page size from 10 to 1000

- cli/flox/doc/flox.md
- cli/flox/src/commands/mod.rs
- cli/tests/usage.bats
Alias "l" for list.
New alias "l" for the list command.
> feat(list): short aliases

- Justfile
- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/commands/activate.rs
- cli/klaus/Cargo.toml
- cli/klaus/src/listen.rs
- cli/klaus/src/logger.rs
- cli/klaus/src/main.rs
- cli/klaus/src/sentry.rs
- cli/tests/services.bats
- flake.nix
- pkgs/flox-cli-tests/default.nix
- pkgs/flox-cli/default.nix
- pkgs/flox/default.nix
- pkgs/rust-pkg/default.nix
- shells/default/default.nix
Adds a watchdog executable to be spawned on each activation.
WIP
N/A
> feat(watchdog): add watchdog

- cli/flox/doc/flox-activate.md
> docs: mention FLOX_ENV in the activate manpage

- cli/flox/doc/manifest.toml.md
- pkgdb/docs/manifests.md
> chore(doc): Use friendlier language for allowlist

- .github/CLA.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature.md
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/init/metrics.rs
Replace "flox" with "Flox" in user-visible locations. Most importantly, update the metrics notification that users see upon first invocation.
N/A
> fix: flox -> Flox

- cli/flox/src/main.rs
@ysndr suggested this in https://github.com/flox/flox/pull/1769#issuecomment-2260675622
SIGINT handler now works when metrics client is blocking on DNS.
issue: #1766
> fix: Explicitly drop metrics so runtime SIGINT guard drops last

- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/services/stop.rs
- cli/tests/services.bats
Follow up on #1897.
* Sentence case messages
* ignore stop failures -- print a warning but continue stopping other services
> chore(follow-up): stop and service select messages

- cli/tests/containerize.bats
Remove non-catalog containerize tests.
N/A
> ci: remove tests that are pkgdb-only

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/providers/services.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/main.rs
- cli/tests/environment-remote.bats
- cli/tests/services.bats
- cli/tests/setup_suite.bash
Remove services feature flag and default to true.
> feat: enable services

- .github/workflows/proxy.yml
> ci: proxy build

- assets/activation-scripts/activate
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox/src/commands/activate.rs
- cli/tests/services.bats
So that they are easier for users to find and we can later garbage
collect them from a single directory based on age.
This is best review commit-by-commit.
N/A until release.
> feat(services): Move logs to .flox/log

- cli/flox-rust-sdk/src/models/manifest.rs
- test_data/generated/envs/hello/manifest.toml
Adds service management to manifest template
N/A (covered by others)
> Add service management to manifest template

- cli/flox/src/commands/mod.rs
Previously, `~/.flox/cache/update-notification.json` was written after successfully checking for updates.
This means the file is never written when the CLI is up to date.
Thus periodic checks become unconditional checks executed with every run of flox,
until an update is available.
This PR distinguishes three check results:
1. skipped: the timeout for checking the file hasn't been reached yet, flox is running in a dev build, or cannot prompt to the user
2. refresh: the timeout was reached, but no update was found or no timestamp file was found.
3. update available: the timeout was reached, and an update was found
Case 2 and 3 will now write a new timestamp file to reset the cooldown for update checks.
Case 3 remains the only case that prints the update message.
> fix: always write update check timestamp if it doesn't exist

- Justfile
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/utils/errors.rs
- cli/tests/install.bats
- cli/tests/setup_suite.bash
Drop a few stray references to global manifests, `check_lockfile`, and the catalog feature flag
> Drop catalog feature flag

- cli/flox-watchdog/src/main.rs
Previously, sentry was initialised within a `tracing::instrument` annotated `main` method. However, `tracing` does not seem to register the scope created before its initialisation.
In response this Commit splits the existing `main` method into two phases:
1. parse arguments, setup the logging/tracing guards
2. followed by a call to the command implementation in a `run` method.
The `run` method is annotated with `tracing::instrument(err)` after tracing is initialised. This ensures traces are recorded and errors are attributed to the `watchdog` span.
> fix: sending of watchdog sentry telemetry

- cli/flox-rust-sdk/src/models/manifest.rs
- test_data/generated/envs/hello/manifest.toml
updates a pretty old example of nodejs in the default template that doesn't currently resolve with catalog service (separate issue for that)
n/a
> fix: more recent example in manifest template

- .github/workflows/ci.yml
Add functionality to be able to debug jobs using upterm.
You can do the following to actually advance the action itself, possibly to see it fail and debug it.
```
touch continue
sudo touch /continue
```
Ref: https://github.com/owenthereal/action-upterm/tree/main
N/A
> ci: Add upterm debugging

- package-builder/flox-build.mk
Define variables for accessing full coreutils paths for `mktemp` and `sha256sum` utilities from within `flox-build.mk`.
N/A
> fix: provide fixed paths for remaining coreutils utilties

- package-builder/flox-build.mk
Set fixed paths for accessing 3 further coreutils utilities in `flox-build.mk`.
N/A
> fix: set 3 further coreutils paths in `flox-build.mk`

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox/src/commands/install.rs
- cli/tests/install.bats
- test_data/config.toml
- test_data/generated/resolve/torchvision-bin.json
- First commit adds a test for a case we missed
- Second commit is a pretty straightforward refactor
- Third commit is a bit more opinionated and I can consider dropping it if you don't like the approach @ysndr, but I personally think it makes things more clear
> A few followups to install resolution errors PR

- cli/flox-rust-sdk/src/models/environment/generations.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
These are comments I left myself while I was debugging #2118 and I found them generally useful as someone that isn't super familiar with the push flow for managed environments.
N/A
> docs: add comments for pushing envs

- .github/workflows/ci.yml
Reduce the SSH logging verbosity, to avoid showing the login banner in CI, as this can become perplexing.
N/A
> feat(ci): set SSH LogLevel option to ERROR

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest.rs
Use TypedManifestCatalog::default() instead of using default() for each of its fields.
> style: use default()

- cli/flox-rust-sdk/src/models/env_registry.rs
This is more consistent with the rest of our codebase, and it's also more performant.
Per the docs on serde_json::from_reader:
```
Note that counter to intuition, this function is usually slower than
reading a file completely into memory and then applying from_str or
from_slice on it.
```
> fix: use serde_json::from_str instead of from_reader

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/flox-build.mk
The previous fix to retain the previous build script had the effect of requiring that it always be older than the corresponding build script source file in order to be regenerated, but that doesn't work so well when the source file is coming from the Nix store with a timestamp of 1.
Adding the `FORCE` prerequisite will force the rebuilding of the target in each instance, and we correspondingly ignore that value when iterating through the prerequisites within the shell loop.
Also adding logic to write new version to a separate file so that we can atomically move it into place.
Ref: https://flox-dev.slack.com/archives/C05P6A5J6U8/p1727873559657209
N/A
> fix(build): rebuild with modified command

- Justfile
Have a `format` target for `just` so that I can run `just format` to format _everything_ during development.
N/A
> feat(justfile): add format target

- pkgs/pre-commit-check/default.nix
Check commit messages in CI as well.
> ci: check commit messages in lint CI

- pkgs/flox/default.nix
Reverting https://github.com/flox/flox/pull/2212
> Revert "fix(pkgs/flox): use semver build metadata"

- cli/flox-rust-sdk/src/data/mod.rs
- cli/flox/src/commands/mod.rs
- I think some imports got messed up with a merge or rebase or something
- Using a `let else` is a bit more readable in this case than an `if let else`
> Some review suggestions for 2221

- cli/flox-activations/src/activations.rs
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/mod.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-activations/src/main.rs
Discuss and impl tests for individual commands.
> test: add test helpers for command tests

- assets/activation-scripts/activate
- cli/Cargo.lock
- cli/flox-activations/Cargo.toml
- cli/flox-activations/src/activations.rs
- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-activations/src/cli/start_or_attach.rs
- pkgs/flox-activation-scripts/default.nix
- pkgs/flox-activations/default.nix
See commits:
- fix: circular flox-activations dependency
- fix: use shorter activation id and create dir
> Prep patches for using flox-activations

- cli/tests/activate.bats
Some of our activation tests check multiple behaviors in the same test, and they check that `hook.on-activate` is run multiple times. Since we're about to add support to attach to an existing activation, if a second `flox activate` attaches, it won't run `hook.on-activate` a second time, and the test will fail.
We could wait for the first `flox activate` to get cleaned up, but since in general we prefer more targeted tests, just split the tests up instead.
N/A
> test: split up activation tests

- cli/flox-rust-sdk/src/providers/mod.rs
- cli/flox-rust-sdk/src/providers/publish.rs
> feat: draft publish provider

- cli/flox-activations/src/cli/start_or_attach.rs
- cli/flox-watchdog/src/logger.rs
- cli/flox-watchdog/src/process.rs
- cli/flox/src/commands/init/mod.rs
- cli/flox/src/commands/install.rs
- cli/flox/src/commands/list.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/pull.rs
- cli/flox/src/commands/search.rs
- cli/flox/src/commands/services/mod.rs
- cli/flox/src/commands/show.rs
- cli/flox/src/main.rs
- cli/flox/src/utils/didyoumean.rs
- cli/flox/src/utils/errors.rs
- cli/flox/src/utils/metrics.rs
- cli/flox/src/utils/openers.rs
- cli/flox/src/utils/search.rs
closes #2272.
This simplifies the codebase to improve maintainability and developer productivity.
N/A
> style: simplify statements for readability

- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- test_data/config.toml
- test_data/generated/envs/publish-simple/manifest.lock
- test_data/generated/envs/publish-simple/manifest.toml
Partial functionality preparing for publish.  Gather info from local package build repo and it's lockfile.  Info from the build (outpaths) to come in separate PR.
> feat: collect meta data for publish

- cli/flox-activations/src/cli/attach.rs
- cli/flox-activations/src/cli/set_ready.rs
- cli/flox-watchdog/src/process.rs
- flake.lock
- pkgs/pre-commit-check/default.nix
Enabled by ours truly @mkenigs in
<cachix/git-hooks.nix@9d2422b>
> ci: ensure that #[cfg(test)] is linted

- cli/flox-rust-sdk/src/providers/build.rs
Move some build test functionality to a test_helpers module to make them accessible to other modules that need some build functionality in tests (publish).
> chore: factor out test_helpers from build tests

- buildenv/builder.pl
The previous commit (9ae08258) which disabled outputsToInstall support had the effect of installing all outputs from a given derivation with the same priority, which then introduced the potential for collisions when multiple outputs contained the same paths with differing contents. One example of such a package is the most recent postgresql, as detailed in #2336.
This patch revises the previous commit by installing "outputsToInstall" outputs separately from other outputs, and tweaking their respective priorities so that we don't end up with collisions between any of the "other" outputs that we add by default.
N/A
> fix: install "outputsToInstall" packages with higher priority

- cli/flox-rust-sdk/src/data/flox_version.rs
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-watchdog/src/main.rs
> Review suggestion for #2292

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/publish.rs
- cli/flox/src/utils/init/catalog_client.rs
- pkgdb/src/realisepkgs/realise.cc
- pkgdb/src/realisepkgs/realisepkgs-lockfile.cc
> Implement feature flagged publish command

- pkgdb/include/flox/realisepkgs/realisepkgs-lockfile.hh
- pkgdb/src/realisepkgs/realise.cc
- pkgdb/src/realisepkgs/realisepkgs-lockfile.cc
> feat: skip eval if outpaths already exist

- cli/flox/src/commands/push.rs
> feat: Notify users that envs are public and add a link to settings

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
Updates publish output to suggest how it could be installed.
```
$ floxlocal publish sayhi
✅ Package published successfully.
Use 'flox install billlevine/sayhi' to install it.
```
> feat: add install message after publish

- cli/flox-rust-sdk/src/providers/git.rs
- cli/flox-rust-sdk/src/providers/publish.rs
> fix(publish): use local HEAD for publish rev

- .github/workflows/ci.yml
Refs: 68e1fdf18894964264dcdc15775f47086d214594
> revert: temporarily disable aarch64-darwin builders

- cli/flox-rust-sdk/src/data/flox_version.rs
- cli/flox-rust-sdk/src/flox.rs
- cli/flox-watchdog/src/main.rs
- cli/flox/src/commands/mod.rs
- pkgs/flox/default.nix
Implement missing things from PR #2221
> Don't raise error when compare of version is not possible

- cli/tests/services.bats
Previously the integration tests tagged with `services:logs:follow:combines` expected to see output after 0.5 to 1 seconds
after calling `flox services logs -f`.
It was expected that that is enough
because the flox command was run after we knew,
that the processes have printed output,
by way of waiting for a pipe signal.
In addition, we expect all a tail of the previous output to be printed immediately.
Unfortunately "immediately" appears to take longer than 0.5 to 1 seconds, depending on the test.
To combat this we now increase the timeout to first print, to up to 5 seconds.
Increasing a timeout is not ideal (timeouts in general aren't), however we still need to stop reading logs at some point, as `--follow` will keep stdout open virtually forever. We could remove the timeout altogether …
> test: increase timeout of service log tests that follow

- cli/flox/src/commands/activate.rs
Compute activate_path once instead of x3 for each activation mode. This makes it slightly easier to understand what is shared vs different between different activation modes.
NA
> style: DRY nit in activations.rs

- cli/flox/src/utils/openers.rs
To test our login flow I need to be able to specify the browser, that is being used. The only way to so this now is to change the system default browser (because flox internally uses `open` -- or linux equivalents i available -- which is hard wired to use the system default browser). Which means my default browser gets reset if I run the tests locally. One thing that is quite common with web dev tools, is using the BROWSER environment variable to specify a custom browser.
This commit adds support for browser detection via `BROWSER`, and performs light argument parsing, such that `BROWSER='firefox -P some-profile' can be set to use a specific browser profile for example.
`BROWSER=<your browser>` can be used to explicitly define the browser
opened by `flox auth login`.
> feat: allow overriding opened browser with `BROWSER`

- cli/flox/src/commands/activate-architecture.mmd
Document our activation architecture in its current state
[Rendered](https://github.com/flox/flox/blob/activate-arch/cli/flox/src/commands/activate-architecture.mmd)
NA
> chore: add activation architecture diagram

- cli/flox-rust-sdk/src/providers/build.rs
- package-builder/build-manifest.nix
Only executables in `$out/bin` will be available on the PATH and wrapped correctly. When a build creates files in $out but does not place any files in $out/bin, we want to warn that Flox needs binaries in bin/, so users can correct the build command accordingly.
Now, when '$out/bin' does not contain any executable files, the build will print the following warning:
```
⚠️  WARNING: No executables found in '$out/bin'.
Only executables in '$out/bin' will be available on the PATH.
If your build produces executables, make sure they are copied to '$out/bin'.
- copy a single file with 'mkdir -p $out/bin && cp file $out/bin'
- copy a bin directory with 'mkdir $out && cp -r bin $out'
- copy multiple files with 'mkdir -p $out/bin && cp bin/* $out/bin'
- copy files from an Autotools project with …
```
> feat(build): detect empty $out/bin and executables outside

- cli/flox/src/commands/containerize.rs
When writing to a file, we set the `truncate` argument to allow safe overwrites of existing files.
Previously, `--file -` was translated to `--file /dev/stdout` to unify the stdout special case with files.
However, on some platforms, in particular _inside docker containers_, trying to truncate `/dev/stdout` causes an IO error (Invalid Arguments (22)).
In response we reintroduce special casing of stdout via `std::io::stdout`.
> fix(containerize): stdout handle, instead of `/dev/stdout` as a file

- .helix/ignore
- .helix/languages.toml
- cli/Cargo.lock
- cli/Cargo.toml
- cli/flox-test-utils/Cargo.toml
- cli/flox-test-utils/src/lib.rs
- pkgs/rust-internal-deps/default.nix
Adds the `flox-test-utils` crate with most of the code commented out.
N/A
> feat: add flox-test-utils crate

- cli/flox-core/Cargo.toml
- cli/flox-core/src/activations.rs
- cli/flox-core/src/lib.rs
- cli/flox-core/src/proc_status.rs
- cli/flox-watchdog/src/process.rs
Copies the implementation from `flox-watchdog` behind conditional compilation (on by default)
in `flox-core`, then uses that implementation throughout `flox`.
N/A
> feat: unify process status checking

- assets/activation-scripts/activate.d/zdotdir/README.md
Notes related to zsh on macOS.
N/A.
> chore: zsh notes

- cli/flox-rust-sdk/src/providers/buildenv.rs
- rename a few symbols for "custom package" to "published package" so call out the source rather that differentiate between the _kind_ of package.
- use `todo!` instead of `panic!` to clarify intent
> chore: fix a few follow up publish items

- cli/flox-rust-sdk/src/providers/container_builder.rs
- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
- cli/flox/src/commands/containerize/mod.rs
> Improve containerize debugging, fix `nix` invocation

- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/services/mod.rs
- cli/tests/services.bats
> fix: showing help when services is executed without options

- cli/flox-rust-sdk/src/providers/buildenv.rs
Some context in https://flox-dev.slack.com/archives/C05P6A5J6U8/p1735853289800039
This drops steps from spinners that don't add useful information.
For checking if a package has already been downloaded, don't say the package is being produced or ensured to be present. Although we may skip downloading if the store path is present, in that case the spinner will only flash briefly, and if the user reads it they will understand what happened - the download was fast since it was cached.
Before:
```
⠐ Installing 1 package(s) to environment 'main'...
↳ ⠄ Building environment
↳ ⠄ Producing package 'nodejs'
↳ ⠄ Ensuring packages are present or downloaded
```
After:
```
⠤ Installing 1 package(s) to environment 'main'...
↳ ⠒ Building environment
↳ ⠂ Downloading 'nodejs'
```
Drop the "Producing..." …
> fix: drop redundant "Producing..." spinners

- cli/flox-rust-sdk/src/models/manifest.rs
- cli/flox-rust-sdk/src/providers/build.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/publish.rs
- package-builder/build-manifest.nix
- package-builder/flox-build.mk
Adds `version`, `license`, and `description` fields to `ManifestBuildDescriptor`,
and propagates their values to the derivation metadata.
> feat: add extra build options

- cli/flox/src/commands/services/status.rs
- cli/tests/services.bats
This change makes it no longer an error to call `flox services status` when services have no yet been started. Furthermore, it will report all services as "Stopped".
The actual status reported by `process-compose` in this situation is "Disabled", but we decided against showing that in the original development phase of services because the word "Disabled" sounds like it means something other than "services haven't been started yet."
`flox services status` no longer returns an error if services have yet to be started.
> feat: better messaging about service status

- CONTRIBUTING.md
Makes the instructions explicit for how to run CI for community contributions.
N/A
> docs: update community CI instructions

- cli/flox-rust-sdk/src/flox.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/config/mod.rs
- cli/tests/compose.bats
Adds a feature flag and a test that it's working.
N/A
> feat: add composition feature flag

- cli/flox/src/commands/containerize/macos_containerize_proxy.rs
We've seen the following error when running macOS containerize tests
```
unpacking 'github:flox/flox/9bcabec338c849abcf2e35f1d9b359fcbdb033ff' into the Git cache...
error:
… while fetching the input 'github:flox/flox/main'
error: adding a file to a tree builder: failed to insert entry: invalid object specified - default.nix
```
https://github.com/flox/flox/actions/runs/13163465842/job/36737896328#step:5:470
Although we're not sure, this could be caused by mounting some of the directories Nix uses in ~ inside the container.
The original reason to mount HOME was so that ~/.config/flox/flox.toml
would be respected. Instead of mounting all of HOME, just mount
flox.toml
NA
> fix: only mount flox.toml for macOS containerize 

- cli/flox/src/commands/activate.rs
Don't print the upgrade notification if the environment is already active, which can easily happen if you follow our default environment instructions for Bash or Zsh which do an in-place activation from both an RC and profile file, e.g.
Before:
% bash
bash-5.2$ eval "$(flox activate -d ~/tmp)"
ℹ️  Upgrades are available for packages in 'tmp'.
Use 'flox upgrade' to get the latest.
flox [tmp term] bash-5.2$ eval "$(flox activate -d ~/tmp)"
ℹ️  Upgrades are available for packages in 'tmp'.
Use 'flox upgrade' to get the latest.
flox [tmp term] bash-5.2$
After:
% bash
bash-5.2$ eval "$(flox activate -d ~/tmp)"
ℹ️  Upgrades are available for packages in 'tmp'.
Use 'flox upgrade' to get the latest.
flox [tmp term] bash-5.2$ eval "$(flox activate -d ~/tmp)"
flox [tmp term] bash-5.2$
This …
> fix(activate): Prevent dupe upgrade notifications

- cli/flox-rust-sdk/src/providers/buildenv.rs
We've seen some deserialization failures in CI. Dump the output we failed to deserialize in the error so we have more information when debugging this in the future.
Failure on x86_64-darwin:
```
Failed to deserialize 'nix build' output: missing field `develop` at line 1 column 161
```
https://github.com/flox/flox/actions/runs/13203213900/job/36860174455#step:5:116
Failure on aarch64-darwin:
```
Failed to deserialize 'nix build' output: missing field `runtime` at line 1 column 161
```
https://github.com/flox/flox/actions/runs/13203754812/job/36861976168#step:5:692
NA
> fix: dump output on deserialization failure

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
`CoreEnvironment::lock` unconditionally locks and _writes the result to disk. The side effect of that is that lockfile timestamps (mtime) may change, invalidating some caching e.g. when using manifest builds.
With this commit we will skip writing the lockfile if its contents are the same as the result of the locking operation.
Before:
```
stat --format=%y .flox/env/manifest.lock
2025-02-17 18:25:38.785783409 +0100
❯ flox build
[...]
❯ stat --format=%y .flox/env/manifest.lock
2025-02-17 18:25:50.591135338 +0100
```
After:
```
❯ stat --format=%y .flox/env/manifest.lock
2025-02-17 18:25:50.591135338 +0100
❯ flox build
[..]
❯ stat --format=%y .flox/env/manifest.lock
2025-02-17 18:25:50.591135338 +0100
```
Additionally, use `tempfile::NamedTempFile::persist` to persist the updated contents in …
> fix(core-environment): avoid writing lockfile if contents unchanged

- cli/flox-rust-sdk/src/models/environment/core_environment.rs
In some cases you may encounter a package that was in the old lockfile and isn't in the new lockfile (or isn't present for a certain system). We've encountered this in production, which most likely means that the manifest that was present when initiating the upgrade check was out of sync with its lockfile (i.e. someone edited the manifest through means other than `flox edit`). In those cases we silently ignore the packages (or packages for a certain system) that are no longer present.
Fixes a bug where some users might encounter a panic while running `flox upgrade`.
> fix: prevent panic during upgrade

- cli/flox-rust-sdk/src/models/environment/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/mod.rs
- cli/flox-rust-sdk/src/models/manifest/composite/shallow.rs
- cli/flox/src/commands/activate.rs
- cli/flox/src/commands/check_for_upgrades.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/envs.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/commands/services/mod.rs
> More prep patches for merging includes

- cli/flox-rust-sdk/src/providers/buildenv.rs
take a derivation with two outputs `foo` and `bar`
```
builtins.derivation {
name = "reprod";
system = "aarch64-darwin";
outputs = [
"foo"
"bar"
];
builder = "/bin/sh";
args = [
"-c"
''
echo "a log line"
echo foo > $foo
echo bar > $bar
''
];
}
```
1. nix build --json on a store that has _both or none of_ `/nix/store/...-foo` and `/nix/store/...-bar` produces
```
[{drvPath: foobar.drv, outputs: { foo: /nix/store/...-foo, bar: /nix/store/...-bar }}]
```
2. if either path is missing :
```
sudo nix store delete --ignore-liveness /nix/store/...-bar
```
`nix build --json` will now contain _only_ the "rebuilt" `bar` output (despite of course (re)producing `foo` as well):
```
[{drvPath: foobar.drv, outputs: { bar : /nix/store/...-bar }}]
```
3. on a subsequeneu run the, both `foo` and `bar` will …
> fix(buildenv): retry building environment on partial substitution

- cli/flox/doc/doc-compose/manifest.toml.md
Adds a new docs directory where we can make edits related to the composition project.
Also adds new documentation about the `[include]` section.
N/A
> doc: add include section to manpage

- assets/environment-interpreter/wrapper/wrapper
Fix recently-introduced PATH prepend bug in manifest build wrapper script.
N/A
> fix: "prepend path" logic broken in manifest build wrapper

- cli/flox/src/commands/init/mod.rs
We recently received a Sentry panic with:
```
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```
It happened within the `flox::commands::init::init` trace.
`current_dir()` returns an error if the current directory does not exist, so that seems like a likely cause for the error.
Even if that wasn't the cause, we should add some context in case the error happens again.
Minor bugfix
> fix: remove unwraps in init

- flake.nix
- modules/darwin.nix
- modules/home.nix
- modules/nixos.nix
On the way home from PlanetNix I thought it would be good to have a NixOS/Darwin/HomeManager module to help with installations in Nix ecosystem.
Once this is reviewed & merged I'll open a PR to mention this modules in https://flox.dev/docs/install-flox/#__tabbed_1_7
> feat(nix): NixOS/Darwin/HomeManager modules

- cli/flox/doc/doc-build/flox-publish.md
> docs: typo in flox-publish.md

- cli/flox-rust-sdk/src/flox.rs
- cli/flox-rust-sdk/src/models/environment/managed_environment.rs
- cli/flox-rust-sdk/src/models/environment/path_environment.rs
- cli/flox-rust-sdk/src/models/environment/remote_environment.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
- cli/flox-rust-sdk/src/models/manifest/raw.rs
- cli/flox/src/commands/edit.rs
- cli/flox/src/commands/mod.rs
- cli/flox/src/utils/message.rs
Add a qa feature flag that we can ask people to set permanently
Use it to set features.compose = true
NA - internal use only
> feat: add qa feature flag that controls composition

- cli/flox-rust-sdk/src/models/manifest/raw.rs
This is a temporary fix that installs custom packages to new package groups by default. User packages created without the factory will exist one one page, or very few pages, which causes frequent "constraints too tight" errors.
N/A
> fix: install user packages to pkg-groups

- cli/flox/src/commands/publish.rs
This fixes a bug that still showed an error message when there is a signing key but no ingress URI. This situation now succeeds and skips uploading silently.
N/A
> fix: no mutual exclusion error message

- cli/flox/src/commands/publish.rs
- cli/flox/src/config/mod.rs
> refactor: make config option match cli option

- cli/flox-rust-sdk/src/providers/buildenv.rs
If a user hasn't configured a trusted key that for a package they're trying to install, we now show an error indicating that this is the case. Previously we would show a "building from source" spinner that would eventually fail with an unhelpful error message.
N/A
> feat: specific error message when missing key

- cli/flox/src/commands/list.rs
Add a unit test that a composed environment gets displayed with a root table and dotted subtables, i.e.:
```
version = 1
[services]
sleep1.command = "sleep infinity"
sleep1.is-daemon = true
sleep2.command = "sleep infinity"
sleep2.is-daemon = true
```
I factored out a method that returned a String rather than calling println so we could unit test this. And I removed an unnecessary `mut` while doing so.
NA
> test: unit test we print root table with dotted subtables

- cli/flox-rust-sdk/src/providers/buildenv.rs
* delay start of the "building ..." spinner until after we know that we are actually going to build.
* add a "downloading ..." spinner for attempts to copy custom packages from the catalog provided store.
When installing a package built from a manifest build, the `Building 'package' from source` spinner is started before determining the installable for the (assumed) nixpkgs based package.
If the package is _not_ a nixpkgs package, but defined in a custom catalog, determining the installable however will actually (attempt to) download that package via `nix copy` and return from the whole function early.
While the download happens, the spinner started earlier will falsely state "building from source".
> fix: delay start of "building ..." spinner

- cli/flox/doc/doc-build/flox-build.md
- cli/flox/doc/doc-build/flox-publish.md
> doc: fix feature env var

- cli/flox-rust-sdk/src/providers/upgrade_checks.rs
Prevent non-forwards compatible changes to `upgrade-checks.json`, including the embedded `Lockfile`, from blocking activations:
% flox activate -d ~/demo/composed
❌ ERROR: Failed to parse upgrade information: missing field `warnings` at line 1 column 768
It now prints a debug line that can be seen with `-vvv` and I've observed it recreating the check file after a successful activation:
2025-04-03T09:30:29.543866Z DEBUG flox_rust_sdk::providers::upgrade_checks: discarding existing upgrade information err=Error("missing field `warnings`", line: 1, column: 768) path="/Users/dcarley/demo/composed/.flox/cache/upgrade-checks.json"
We still need to be careful about adding non-optional fields that are nested within optional fields of the `Manifest` and `Lockfile` because they are unlikely to be …
> fix(upgrade-checks): Guard against lockfile compat

- cli/flox-rust-sdk/src/providers/catalog.rs
> refactor: drop stale errors

- .github/scripts/remote-execute-integration-tests.sh
With set -e it's possible the actions exits before it tries to upload the test results to BuildKite. We'd like to know when tests fail, so try uploading when the shell EXITs, instead of only when the test suite succeeds.
N/A
> Trap uploading of test results on EXIT

- .github/CONTRIBUTORS.csv
Adding myself as a signer of the CLA.
N/A
> chore: add mahyar mirrashed to list of contributors

- package-builder/build-manifest.nix
- package-builder/flox-build.mk
> docs: add comments about `flox build` activations

- cli/flox-rust-sdk/src/models/environment/fetcher.rs
- cli/flox-rust-sdk/src/models/lockfile.rs
~~Currently based on #2952 but will change when that's merged.~~
Use the merged manifest from the include's lockfile rather than the user manifest. Besides being more consistent, this also makes it possible to include environments that have already been merged, as demonstrated by the additional test.
I extracted the errors which had to be referenced twice for managed environments because Rust doesn't let you combine conditions like `if let Some(lockfile) && env.has_local_changes()`, an explicit `unwrap` or `expect` within an `if lockfile.is_some()` felt unclear, and we haven't quite settled on how to atomically get an in-sync lockfile for all environment types.
Support including composed environments.
(I'm inclined not to use the word "recursive" because it suggests that we don't …
> feat(compose): Use merged manifests of includes

- cli/flox-rust-sdk/src/providers/publish.rs
Rename one function for clarity and added a few comments.
> chore: cleanup and comments

- assets/environment-interpreter/common/etc/profile.d/0100_common-paths.sh
The runtime loader reserves a static amount of memory for thread local storage (TLS).
When using LD_AUDIT in combination with libraries such as jemalloc that use TLS, the default reservation is exceeded and the program fails to start. Use GLIBC_TUNABLES to increase the reservation.
The default reservation is 512.
Requirements for some programs we've run into the issue with:
On x86_64-linux:
redis-server: 1441
biome: 1417
fd: 1417
On aarch64-linux:
redis-server: 1777
biome: 1553
fd: 1561
See https://sourceware.org/bugzilla/show_bug.cgi?id=31991
Set the reservation to 2500 to give us a little bit of headroom.
Programs such as fd and redis-server should no longer require the workaround `unset LD_AUDIT` to avoid the error `Cannot allocate memory in static TLS block`
> fix: Cannot allocate memory in static TLS block

- cli/flox/doc/manifest.toml.md
Make it clearer why the `is-daemon` option is needed in the manifest docs.
> refactor: daemon service docs

- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/utils/mod.rs
- cli/flox/src/utils/metrics.rs
This will be useful for analyzing usage spikes
NA
> feat: record whether we're in CI for metrics

- cli/flox-rust-sdk/src/providers/buildenv.rs
This addresses a bug we've seen in CI where previously we would create an infinite loop trying to create these GC roots when creating them failed.
> fix: don't infinite loop creating gc roots

- cli/flox-rust-sdk/src/providers/publish.rs
This option is specific to S3 stores and causes a user facing warning if there are any errors when publishing to other store types like HTTPS:
% ft publish --signing-private-key ~/tmp/signing.key
Rendering hello-go build script to /var/folders/8q/spckhr654cv4xrcv0fxsrlvc0000gn/T/nix-shell.HqDmOE/4453a787-hello-go-build.bash
Building hello-go-unknown in local mode
00:00:00.003576 + go build main.go
00:00:00.099458 + mkdir -p /tmp/store_4453a7878a37650e58a20b2e316efe56-hello-go-unknown/bin
00:00:00.101564 + cp main /tmp/store_4453a7878a37650e58a20b2e316efe56-hello-go-unknown/bin/hello-go
this derivation will be built:
/nix/store/69g61y3clvrdnkqfy19fmq60lf1lg5bd-hello-go-unknown.drv
building '/nix/store/69g61y3clvrdnkqfy19fmq60lf1lg5bd-hello-go-unknown.drv'...
hello-go-unknown> signing …
> fix(publish): Restrict ls-compression to S3

- cli/flox-rust-sdk/src/providers/build.rs
Vars are handled by the `--set-vars` argument to the build wrapper activation script. Add a few more test cases not added when `--set-vars` was added.
NA
> test: setting of [vars] for builds

- assets/environment-interpreter/activate/activate
- assets/environment-interpreter/activate/activate.d/attach-command.bash
- assets/environment-interpreter/activate/activate.d/start.bash
- assets/environment-interpreter/wrapper/wrapper
- cli/flox-rust-sdk/src/providers/build.rs
- cli/tests/activate.bats
- package-builder/build-manifest.nix
- package-builder/env-filter.bash
- package-builder/flox-build.mk
- pkgs/flox-package-builder/default.nix
Addressed problems with manifest builds, and particularly those involving C applications. This PR is a WIP.
TODO: update this description
N/A (manifest builds are not a released feature)
> fix: activation-related manifest build problems

- cli/catalog-api-v1/src/lib.rs
- cli/flox-rust-sdk/src/providers/catalog.rs
- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/upload.rs
> feat: add support for publisher store type

- package-builder/flox-build.mk
To address #3017 we've decided to temporarily disable calls to `daemonize nix store delete` when calling `flox build clean`. I've renamed the original target to indicate that it does in fact delete store paths, and created a duplicate target that doesn't delete store paths.
N/A
> fix: temporarily disable delete calls for clean

- cli/flox-rust-sdk/src/providers/buildenv.rs
Fail faster in a few ways:
- If a path needs auth but netrc auth fails, error as soon as we know no location can substitute that path (rather than trying to substitute all other paths before erroring)
- If a path can't be substituted, return false rather than trying to substitute all other paths first
> fix: skip unnecessary work in try_substitute_published_pkg

- cli/catalog-api-v1/openapi.json
- cli/catalog-api-v1/src/client.rs
It appears the autobump PR wasn't opened
> chore: bump catalog client

- cli/flox/src/commands/init/mod.rs
Fixes error "couldn't parse manifest contents: unsupported manifest version" in `flox init` when language detection is active. The issue occurs because the existing `format_customization` function creates an invalid manifest by not including a version field.
This PR adds the necessary version field to the TOML document, ensuring a valid manifest is created even when detecting language customizations like `.nvmrc` files.
This implements @mkenigs "simple fix;" the more elegant fix is probably beyond my ken at the moment (let's see how this one is received.) This fix is tested and working. I haven't tested the Claude-generated unit test b/c I apparently have to install the Rust toolchain's nightly build to do that. I did harden that unit test over several successive (separate) prompting …
> fix: add manifest version in format_customization function

- .github/workflows/ci.yml
- Justfile
- flake.lock
- flake.nix
- shells/default/default.nix
Run unit tests for nef expressions in CI
> ci(nef): run nix unit tests in CI

- cli/flox/src/commands/build.rs
When a flox build name was provided by both the manifest via `build.<name>` _and_ as a nix expression in `.flox/pkgs/<name>{.nix/default.nix}` we previously fell back to the expression build printing a warning in the process. However in other collision situations we anticipate errors being thrown instead, together with directions to mitigate the error.
For the sake of consistency we'll change the behavior here as well.
> fix: return error on build id conflict

- .github/actions/common-setup/action.yml
Ping the proposed server.
- exits on a good ping
- keeps going if it is via DERP
- times out if there is no reply
> ci: ping proposed server until good connection

- test_data/config.toml
> test: better error generation comments

- cli/flox/src/main.rs
Change the warning to debug because it seems alarmist when we don't appear to have any reports in GitHub or Slack of bugs that are caused by `USER` being different from the effective username. It will still be included with `-vv` output though, so we'll see it when asking for debug output in issues.
It's common for `sudo` to be configured to preserve `$HOME` from the calling user but I'm not clear about the conditions where `$USER` would be different from the effective user. Based on this old thread about the original logic in `flox-bash` it seems like this might not be needed anymore:
- https://flox-dev.slack.com/archives/C054SAD6NLD/p1687900692516919
But I think that's best combined with fixing `sudo` behaviour in:
- https://github.com/flox/flox/issues/3025
So I've also added a debug …
> fix(main): Quieten warning about effective UID

- cli/flox-rust-sdk/src/providers/buildenv.rs
The paths iterator can be empty, and we should skip calling Nix when it is. Also tweak a debug! statement to produce something that can be copy-pasted to reproduce.
NA
> fix: skip gc root creation for empty paths

- cli/flox-rust-sdk/src/models/manifest/typed.rs
- cli/flox-rust-sdk/src/providers/build.rs
These options aren't implemented, so we should remove them until they are.
Closes #3242
N/A
> chore: remove unused build options

- cli/flox/doc/flox-build.md
- cli/flox/doc/flox-publish.md
Changes the language in the manpages.
N/A
> chore: artifact -> package

- cli/flox/doc/manifest.toml.md
Missed these references when removing them from the manifest.
N/A
> docs: remove reference to files/systems

- cli/Cargo.lock
Branch to run CI on for external forks
> Community CI

- cli/flox/doc/flox-publish.md
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
> fix: only allow path envs for build and publish

- cli/flox-rust-sdk/src/providers/publish.rs
flox#3236 changed the behavior of `flox publish` to store the build output so that it can be shown when the build fails. However, this means that a user running `flox publish` sees no output during the build which they may not know is happening. This change restores the build output so that users don't get the wrong impression that something is frozen while the build is happening.
As part of this change, since the build output is shown during the build, it is no longer collected and printed in case of an error. Instead, the output is shown during the build and if there is a failure a short message containing the exit status is shown.
N/A
> fix: show build output during publish

- cli/flox-activations/src/cli/start_or_attach.rs
Silence the attach retry warning until retries are exhausted.
Running two `flox activate -- cmd` in a row can lead to one activation trying to attach, the other one exiting, and then the first having to start rather than attach.
The retry warning is causing CI to flake, and it isn't actually helpful to users. See
https://github.com/flox/flox/actions/runs/12714454841/job/35444689929#step:5:352
```
Prior activation of the environment completed before it could be attached to.
Retrying ...
```
Silence the warning since it's not helpful.
I considered holding the lock for the first attach attempt, but special casing the first iteration in wait_for_activation_ready_and_attach_pid seems like it adds more complexity than it's worth to save us 100 milliseconds when we hit a somewhat rare edge case. …
> fix: silence attach retry warning

- cli/flox-rust-sdk/src/models/environment/generations.rs
Implement and test error handling for `set_current_generations` in support of rollbacks.
Doesn't support rolling back to previous (current-1) like the PoC did because there will be different strategies once we address alternative histories.
I considered breaking the test up but it's pretty procedural in nature due to the state required for each step and didn't make it any easier to read.
N/A
> feat(generations): set_current error handling

- cli/flox-rust-sdk/src/providers/build.rs
- test_data/config.toml
- test_data/generated/build/hello-cmake/.flox/.gitignore
- test_data/generated/build/hello-cmake/.flox/env.json
- test_data/generated/build/hello-cmake/.flox/env/manifest.lock
- test_data/generated/build/hello-cmake/.flox/env/manifest.toml
- test_data/generated/build/hello-cmake/CMakeLists.txt
- test_data/generated/build/hello-cmake/HelloTarget/share/hello/HelloTarget.cmake
- test_data/generated/build/hello-cmake/hello.in
- test_data/input_data/build/hello-cmake/.flox/.gitignore
- test_data/input_data/build/hello-cmake/.flox/env.json
- test_data/input_data/build/hello-cmake/.flox/env/manifest.lock
- test_data/input_data/build/hello-cmake/.flox/env/manifest.toml
- test_data/input_data/build/hello-cmake/CMakeLists.txt
- test_data/input_data/build/hello-cmake/HelloTarget/share/hello/HelloTarget.cmake
- test_data/input_data/build/hello-cmake/hello.in
Adding tests as proposed in #3265.
N/A
> chore: add multiple manifest-build-related tests following #3257

- cli/flox-watchdog/src/process.rs
This change makes it such that the watchdog will write its watch list of PIDs back to `activations.json` when it notices that the two are out of sync i.e. when one of the processes has exited.
Flox should consume less CPU in the background.
> fix(watchdog): don't watch old pids

- cli/flox/doc/flox-generations-history.md
- cli/flox/doc/flox-generations-list.md
- cli/flox/doc/flox-generations-rollback.md
- cli/flox/doc/flox-generations-switch.md
- cli/flox/src/commands/generations/mod.rs
Add man pages for `flox generations {list,history,rollback,switch}`
Part of larger generations feature release
> docs: generations man pages

- cli/flox-rust-sdk/src/models/environment/generations.rs
Avoid iterating the history to
1. find the next availabel generation number
2. check if a generation to switch to exists -- we consecutively track all generations `1..=total_genrations`), so a generation is assumed to exist IFF next_generation > total_generations. 
This allows inserts of generations in constatn time and avoids processing the full history for more generation metadata.
> perf: track total generations

- cli/flox/doc/flox-generations-history.md
- cli/flox/src/commands/generations/mod.rs
I think this wording is a little bit more clear.
We never define what "managed changes" are.
NA
> docs: clarify help for history

- cli/flox-rust-sdk/src/providers/publish.rs
- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
> fix: add --nixpkgs-url option to publish

- cli/flox-rust-sdk/src/providers/build.rs
> fix: correct license field names

- cli/flox/src/commands/build.rs
- cli/flox/src/commands/publish.rs
Report when we use NEF and manifest builds for build and publish
NA
> feat: add NEF metric

- cli/flox/src/utils/active_environments.rs
- cli/tests/generations.bats
- cli/tests/services.bats
Review follow-ups from https://github.com/flox/flox/pull/3638
N/A
> test(generations): Review follow-ups

- cli/flox/doc/flox-generations-history.md
- cli/flox/doc/flox-generations-list.md
> docs: document `--no-pager` flag
